### ISSUE TITLE
Alerta 7.2.10  Play notification sounds every time with  Alert Refresh interval 

### ISSUE THREAD

**Issue by judexzhu** [alerta/alerta#1000]
**Issue Summary**
Set `DEFAULT_AUDIO_FILE: "'/audio/alert_high-intensity.ogg'"`

enable "Play Notification Sounds"

![image](https://user-images.githubusercontent.com/17834225/59408022-95194800-8de5-11e9-9aec-2f342272cc90.png)

And then it will play "DingDong" every 5 sec.

If I change the Refresh interval from "5" to "60", then it will play every 1 min

**Environment**
- OS: Linux
- API version: 7.2.10
- Deployment: self-hosted
- For self-hosted, WSGI environment: Kubernetes + Helm

- Database:  Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Keycloak
  Customer views? Yes
  (or provide the `/config` endpoint output)

- web UI version: 7.2.10
- CLI version: 7.2.10

**Expected behavior**
I wish it only plays notification sounds when the new alerts coming in. but not for every refresh interval.

it plays well in Alerta 6

also, I'd like to thank you for the great production and your fantastic work

**Comment by satterly** [comment]
It will only play the sound if there are unacknowledged alerts. If there are no "open" alerts the sound will stop.

**Comment by judexzhu** [comment]
Thank you, Sir, for your quick reply, I understand it better now.
