### ISSUE TITLE
grafana webhook: close alerts when they are not present anymore in evalMatches

### ISSUE THREAD

**Issue by panpann** [alerta/alerta#1002]
Hello, I'm using alerta (deployed with docker) as an interface for grafana alerts, my grafana webhook is configured to send reminders every 15min

I have a use case I wanted to share with you.

Let's say I have a grafana alert **Host - down** and **host1** and **host2** are down (bad things happen)

I will have an alert for host1 and another for host2 in my alerta dashboard.

After some time, host1 is restarted, my **Host - down** alert is triggered only by host2 now.

But in alerta, I will have always 2 alerts until **host2** is up again, because the state of the alert will always be "alerting" and not "ok" as expected [here](https://github.com/alerta/alerta/blob/master/alerta/webhooks/grafana.py#L71) until every matching timeseries in the grafana alert are ok

Here the calls done by grafana in such case (found on alerta logs), to replay the scenario

```bash
# first call, host1 and host2 are down
curl -XPOST "http://127.0.0.1:4444/api/webhooks/grafana?api-key=qu2iuZA8ixT_TqlPxHO-ZRFn_2fMhPX60e26lG2F&environment=Production&service=grafana&timeout=3600" --data '{"evalMatches":[{"value": 0,"metric":"host2"},{"value":0,"metric":"host1"}],"message":"","ruleId":33,"ruleName":"Host - down","ruleUrl":"http://0.0.0.0","state":"alerting","title":"[Alerting] Host down"}' -H "Content-Type: application/json"

# second call only host2 is down, I'm expecting to only have 1 alert in alerta for host2
curl -XPOST "http://127.0.0.1:4444/api/webhooks/grafana?api-key=qu2iuZA8ixT_TqlPxHO-ZRFn_2fMhPX60e26lG2F&environment=Production&service=grafana&timeout=3600" --data '{"evalMatches":[{"value": 0,"metric":"host2"}],"message":"","ruleId":33,"ruleName":"Host - down","ruleUrl":"http://0.0.0.0","state":"alerting","title":"[Alerting] Host down"}' -H "Content-Type: application/json"

# the call when there is no matching timeseries which closes every related alerts
{"evalMatches":[],"message":"","ruleId":33,"ruleName":"Host - down","ruleUrl":"http://test.com","state":"ok","title":"[OK] Host down"}
```

Personally, as alerta stores / displays one alert per timeserie of a grafana alert (which I like so much compared to grafana alerting dashboard), I would expect alerta to take care of updates inside a grafana alert when it is in **alerting** state.

One way I can see is to check if there is opened alerts in the backend based on the **ruleId** and the **metric**, which are not present anymore in the update sent by grafana and to close them

What do you think about it ?

# versions
## python version
Python 3.6.8

## packages versions
```
alerta                   7.2.2   
alerta-amqp              5.4.1   
alerta-cachet            5.0.1   
alerta-enhance           5.3.3   
alerta-forward           5.0.0   
alerta-geoip             5.4.0   
alerta-hipchat           5.3.3   
alerta-influxdb          5.4.3   
alerta-logger            5.3.2   
alerta-logstash          5.3.3   
alerta-mattermost        1.1.3   
alerta-msteams           5.0.0   
alerta-normalise         5.3.1   
alerta-op5               5.0.2   
alerta-opsgenie          5.0.2   
alerta-pagerduty         5.3.1   
alerta-prometheus        5.4.0   
alerta-pubsub            5.2.2   
alerta-pushover          5.3.2   
alerta-rocketchat        5.0.0   
alerta-server            7.2.10  
alerta-slack             5.4.0   
alerta-sns               5.3.1   
alerta-telegram          5.1.1   
alerta-twilio            5.4.0   
alerta-zabbix            5.1.1   
```

# docker labels
```
"Labels": {
    "maintainer": "Nick Satterly <nick.satterly@gmail.com>",
    "org.label-schema.build-date": "2019-06-06T07:44:05Z",
    "org.label-schema.schema-version": "1.0.0-rc.1",
    "org.label-schema.url": "https://alerta.io",
    "org.label-schema.vcs-ref": "44d1d7f",
    "org.label-schema.vcs-url": "https://github.com/alerta/docker-alerta",
    "org.label-schema.version": "7.2.10"
}
```

**Comment by satterly** [comment]
As you are resending the alerts every 15 minutes why don't just you set the timeout on these alerts to 15 minutes ie. `timeout=900`. If they aren't refreshed then they'll be deleted.

**Comment by panpann** [comment]
Yes thank you for your answer, it is simpler :)
I forgot to play with this timeout
