### ISSUE TITLE
Overview Page in Web-UI

### ISSUE THREAD

**Issue by seasurfpete** [alerta/alerta#1003]
**Is your feature request related to a problem? Please describe.**
Uptake of Alerta if that can be classed as a problem

**Describe the solution you'd like**
Our operations dept is so reliant on Nagios/Vagvis as a dashboard/traffic light system that trying to move to alerta is proving problematic due to information overload looking at the landing alerts screen. (nagios alerts here are very spammy) 

It would be nice to see a single page overview of environments/systems in a traffic light form with nice big squares for each (i guess known) environment/system that is green for no alerts, yellow/red with maybe a count of alerts, clicking on these would simply lead to the current landing page with that environment or maybe filter already selected. 

as an extension to this, a configurable option by filters where a tile represents a filter or search would also be amazing. This would mean the operator can have searches for anything represented as a overview button and could mean that different groups could have overview pages of different things. As alerta is a great consolidator of alerts from everywhere this could be very handy.

**Describe alternatives you've considered**
making it myself using the alerta api/flask/python but I'd rather not as the new UI is looking nice.

**Additional context**
If you feel this is a good idea / easy to implement I'm happy to assist.

**Comment by satterly** [comment]
This is already possible with a minimal amount of HTML. Take a look at this example and let me know how you go. https://github.com/alerta/alerta/blob/master/examples/oembed.html

**Comment by seasurfpete** [comment]
Hi Nick,

I've loaded up the file into my ui container (I'm running in docker but have split ui/server into separate containers under k8s) I can't however reference the /oembed at http://ui/oembed, just returning a 404, I can see that the oembed.py is creating a route for oembed, does this need to

**Comment by seasurfpete** [comment]
Hey Nick,  Thanks for this, so I've got it loaded up but the oembed api is responding with 500, 
message | "the match filter must be an expression in an object"
status | "error"

from the example of:
`$('.mobile-alerts').alerta('http://localhost:8080/alerts/count?service=Mobile&status=open', {title:'Mobile Service'});`
I've updated to 
`$('.mobile-alerts').alerta('http://alerta-server/alerts/count?service=abr-repg&status=open' , {title:'abr-repg'});`
this then translates to:
`http://alerta-server/oembed?url=http%3A%2F%2Falerta-server-alerta-pts.apps.pts.origin.foxtel.com.au%2Falerts%2Fcount%3Fservice%3Dabr-repg%26status%3Dopen&title=abr-repg`
in the request from the browser, this is returning the 500 error. Looking at the code its failing in the try section at line 30 (oembed.py) but not sure if its the urlparse or the query= line

running manually to the API server the original query as /alerts/count?service=abr-repg works fine and returns ok,
running via /oembed?without title returns 400 as expected. 

any thoughts? I'm trying to get alerta running in pycharm so i can debug but setup is a little slow.

thanks

**Comment by seasurfpete** [comment]
I did manage to grab the mongo log command when the sock_info command ran
`2019-06-19T15:56:59.241+1000 D COMMAND  [conn14] assertion while executing command 'aggregate' on database 'monitoring' with arguments '{ aggregate: "alerts", pipeline: [ { $match: ""status"=%(status)s" }, { $project: { severity: 1 } }, { $group: { _id: "$severity", count: { $sum: 1 } } } ], cursor: {}, lsid: { id: UUID("133765be-4d09-4fc2-82fa-ac1334c2c434") }, $db: "monitoring", $readPreference: { mode: "primaryPreferred" } }': Location15959: the match filter must be an expression in an object
2019-06-19T15:56:59.241+1000 I COMMAND  [conn14] command monitoring.alerts command: aggregate { aggregate: "alerts", pipeline: [ { $match: ""status"=%(status)s" }, { $project: { severity: 1 } }, { $group: { _id: "$severity", count: { $sum: 1 } } } ], cursor: {}, lsid: { id: UUID("133765be-4d09-4fc2-82fa-ac1334c2c434") }, $db: "monitoring", $readPreference: { mode: "primaryPreferred" } } numYields:0 ok:0 errMsg:"the match filter must be an expression in an object" errName:Location15959 errCode:15959 reslen:140 locks:{ Global: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } protocol:op_msg 0ms
`

**Comment by satterly** [comment]
Please test and confirm fix #1004 works for you. Thanks.

**Comment by satterly** [comment]
@seasurfpete FYI, I've recently added an status panel made up of "alert status indicators" which provide what you want, I think. See https://github.com/alerta/alerta-webui/pull/203
