### ISSUE TITLE
alerta.exceptions - RateLimit not working as expected 

### ISSUE THREAD

**Issue by Chandants** [alerta/alerta#1007]
**Issue Summary**
I have enabled flapping plugin. It is working as expected but the line raise RateLimit  in pre_receive function is not getting executed or I don't see any RateLimit message printed in the logs. 

**Please find the code and the output below.**

```
import logging
from alerta.exceptions import RateLimit
from alerta.plugins import PluginBase

LOG = logging.getLogger('alerta.plugins.transient')

FLAPPING_COUNT = 2
FLAPPING_WINDOW = 120  # seconds

class TransientAlert(PluginBase):
    def pre_receive(self, alert):
        LOG.info("Detecting transient alerts...")
        if alert.is_flapping(window=FLAPPING_WINDOW, count=FLAPPING_COUNT):
            LOG.info("============== INSIDE IF LOOP =============")
            alert.severity = 'indeterminate'
            alert.attributes['flapping'] = True
            LOG.info(" ============= FLAPPING TRUE ============")
            # uncomment following line to stop alerts from being processed
            raise RateLimit("Flapping alert received more than %s times in %s seconds" % (FLAPPING_COUNT, FLAPPING_WINDOW))
        else:
            alert.attributes['flapping'] = False
       return alert
    def post_receive(self, alert):
        return
    def status_change(self, alert, status, text):
        return
```

**Output/Logs**:
```
2019-06-25 06:31:42,988 - alerta.plugins.transient[52]: INFO - Detecting transient alerts... [in ./alerta_transient.py:15]
2019-06-25 06:31:42,999 - alerta.plugins.transient[52]: INFO - ============== INSIDE IF LOOP ============= [in ./alerta_transient.py:17]
2019-06-25 06:31:42,999 - alerta.plugins.transient[52]: INFO -  ============= FLAPPING TRUE ============ [in ./alerta_transient.py:20]
[2019-06-25 06:31:43,042: INFO/ForkPoolWorker-3] Task alerta.webhooks.tasks.zenoss[f46a072d-05ce-4cc4-b29d-48f5cb50a73f] succeeded in 1.6668471280136146s: None
```

**Environment**
- OS:Linux
- API version:  6.8.1
- Deployment:  Docker
- For self-hosted, WSGI environment:eg. nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? No
  Auth provider? No
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: eg. 6.8.1

**To Reproduce**
1. included alerta_transient.py file for flapping.
2. setup.py for flapping
3. Installed the flapping plugin
4. triggered event with alternate severity changes and the code executed as expected , except the raise RateLimit line

**Expected behavior**
RateLimit message should appear in the logs as below,
Flapping alert received more than %s times in %s seconds

@satterly

**Comment by satterly** [comment]
The `RateLimit` exception is returned as a message in the HTTP response.

```
$ alerta send -E Development -S Foo -r r1 -e e1 -s normal
ERROR: Flapping alert received more than 2 times in 120 seconds
```
