### ISSUE TITLE
Security: Authorization in OIDC and SAML not working as expected

### ISSUE THREAD

**Issue by maglo** [alerta/alerta#1009]
**Issue Summary**
If using `ALLOWED_OIDC_ROLES` as described in documentation in https://docs.alerta.io/en/latest/authentication.html#keycloak-oauth2, authorization (granting access based on the requirement to have the roles) does not work.

The user is allowed access even though the roles specified are not in the token.

**Environment**
- OS: Linux 
- API version: 7.2.10
- Deployment: Docker

- Database: MongoDB

- Server config:
```
{"actions":[],"alarm_model":{"colors":{"severity":{"cleared":"#00CC00","critical":"red","debug":"#9D006D","indeterminate":"lightblue","informational":"#00CC00","major":"orange","minor":"yellow","normal":"#00CC00","ok":"#00CC00","security":"blue","trace":"#7554BF","unknown":"silver","warning":"dodgerblue"},"text":"black"},"defaults":{"normal_severity":"normal","previous_severity":"indeterminate","status":"open"},"name":"Alerta 7.2.10","severity":{"cleared":7,"critical":1,"debug":8,"indeterminate":5,"informational":6,"major":2,"minor":3,"normal":7,"ok":7,"security":0,"trace":9,"unknown":10,"warning":4},"status":{"ack":"C","assign":"B","blackout":"E","closed":"F","expired":"G","open":"A","shelved":"D","unknown":"H"}},"audio":{"new":null},"auth_required":true,"azure_tenant":null,"client_id":"alerta","colors":{"severity":{"cleared":"#00CC00","critical":"red","debug":"#9D006D","indeterminate":"lightblue","informational":"#00CC00","major":"orange","minor":"yellow","normal":"#00CC00","ok":"#00CC00","security":"blue","trace":"#7554BF","unknown":"silver","warning":"dodgerblue"},"text":"black"},"columns":["severity","status","lastReceiveTime","timeoutLeft","duplicateCount","customer","environment","service","resource","event","value"],"customer_views":false,"dates":{"longDate":"d/M/yyyy h:mm:ss.sss a","mediumDate":"EEE d MMM HH:mm","shortTime":"HH:mm"},"debug":false,"email_verification":false,"endpoint":"https://10.51.0.33/alerts/api","github_url":"https://github.com","gitlab_url":"https://gitlab.com","keycloak_realm":"bls","keycloak_url":"https://10.51.0.33:8443","oidc_auth_url":null,"pingfederate_url":null,"provider":"keycloak","refresh_interval":5000,"severity":{"cleared":7,"critical":1,"debug":8,"indeterminate":5,"informational":6,"major":2,"minor":3,"normal":7,"ok":7,"security":0,"trace":9,"unknown":10,"warning":4},"signup_enabled":false,"site_logo_url":"","sort_by":"lastReceiveTime","tracking_id":null}
```
- web UI version: 7.2.10
- CLI version: 7.2.10

**To Reproduce**
1. Deploy
2. Set config `ALLOWED_KEYCLOAK_ROLES` or `ALLOWED_OIDC_ROLES`
3. Configure Keycloak as desribed in documentation. 
4. Create a user w/o required roles
5. Try to login with that user
6. Fail by succeeding to log on, even though user is not specified in `ALLOWED_OIDC_ROLES`

**Expected behavior**
`Error: User test3 is not authorized`

**Additional context**
The problem is related to faulty logic in `auth/oidc.py`

https://github.com/alerta/alerta/blob/v7.2.10/alerta/auth/oidc.py#L135

The authorisation succeeds erroneously if one of the tests `not_authorized` returns `false`.

Correct behaviour should be to only succeed if *both* tests return false.

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
Fixed by #1010
