### ISSUE TITLE
Support custom Certification Authorities

### ISSUE THREAD

**Issue by maglo** [alerta/alerta#1011]
**Is your feature request related to a problem? Please describe.**
When using an on-prem authentication provider, such as Keycloak, with a self-issued CA, an error message is displayed when logging on.

`certificate not trusted`

**Describe the solution you'd like**
It is possible to work around this by setting the enrivonment variable `REQUESTS_CA_BUNDLE` to a path with the issuing CA root cetfiticate:
`REQUESTS_CA_BUNDLE: /pki/ca.pem`

It could either be described in the documentation, or perhaps solved in code. I run in a Docker container so for me it was easy setting the environment variable in there and getting things working. However, this might not be straight forward for everyone.

**Comment by satterly** [comment]
That is the suggested approach. It should be better documented. Thanks for raising.

**Comment by satterly** [comment]
Fixed by alerta/alerta-docs@e8d523871e19287c4aca2101cd4cdaf2e02662f0
