### ISSUE TITLE
Make redirect_uri pretty for Keycloak when publishing under sub path

### ISSUE THREAD

**Issue by maglo** [alerta/alerta#1012]
**Is your feature request related to a problem? Please describe.**
When using an on-prem Keycloak authentication provider, and publishing Alerta under a sub path, `/alerts/api` in my case, the redirect_uri sent to Keycloak is set to the root of the site, instead of to the correct sub path.

F.ex if Alerta is published under `https://10.51.0.33/alerts/alerts`. I would like to configure the valid redirect_uri in Keycloak to `https://10.51.0.33/alerts/*`. However, the redirect_uri provided by Alerta is `https://10.51.0.33/`. 

This works (if you allow that redirect_uri in Keycloak), but it is not pretty as the root site is flashed to the user in the logon popup. Also, it would be nice from a security pow to have the redirect_uri "correct".

**Describe the solution you'd like**
When constructing the redirect_uri here: https://github.com/alerta/alerta/blob/master/alerta/auth/oidc.py#L74, it would be nice if the base path was considered.

**Describe alternatives you've considered**

**Additional context**
I am running with `BASE_URL: /alerts/api` in a Docker container and with an nginx proxy with the following configuration:

```
set $upstream_alerta http://alerta_web:8080;
location /alerts/ {


    # Add headers indicating proxy status
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;

    # After successful validation of project token, proxy to backend
    proxy_pass $upstream_alerta;
  }
```

**Comment by satterly** [comment]
Thanks. Good suggestion. Is this something you think you could fix yourself? If not, I'll add it to the backlog.

**Comment by satterly** [comment]
>  I would like to configure the valid redirect_uri in Keycloak to https://10.51.0.33/alerts/*. However, the redirect_uri provided by Alerta is https://10.51.0.33/.

That's not correct. The redirect URL is set in Keycloak by you. If you want to use the correct URL for your scenario that includes a subpath then you can.
