### ISSUE TITLE
Add support for Keycloak session revocation

### ISSUE THREAD

**Issue by maglo** [alerta/alerta#1013]
**Is your feature request related to a problem? Please describe.**
When using Alerta with an on-prem Keycloak, when a user clicks Log Out, he/she is presented with a `You have been logged out` message.

Clicking LOG IN again will log you on again with the same credentials, without being prompted for username / password.

It is possible in Keycloak to revoke a users session by calling a revocation-url.

https://www.keycloak.org/docs/4.8/securing_apps/index.html#logout-endpoint

**Describe the solution you'd like**
Add an optional support for revocation of the Keycloak session when the user clicks the Log Out link.

This would truly log the user out, so that he/she can rest assured that he/she is truly logged out of the realm and that no unauthorized user who gains access to the desktop / browser can access services on the users behalf!

**Describe alternatives you've considered**

**Additional context**

**Comment by satterly** [comment]
Yes, this is good suggestion. When external auth providers were first added Google was the first and logging people out of their email when they logged out of Alerta was not what the user expected. However, it should be optionally supported for other auth providers. I'll add it to the backlog.

**Comment by burakksglu** [comment]
Is there any progress on this request?

**Comment by satterly** [comment]
I've had a quick look at this and it looks like `vueAuth` supports a `logoutUrl` option and optional request parameters. It would be straight-forward to add support for the `logoutUrl` which looks like it does a simple `POST` to the URL.

However, if Keycloak requires a user-specific URL and/or request body that would be trickier.

Can you provide an example logout URL and request body (if any)? Thanks.

**Comment by burakksglu** [comment]
Ok since I'm not able to reach my development environment right now, I created another test realm in keycloak  and got this for you:

`"end_session_endpoint": "http://keycloakhost:keycloakport/auth/realms/{realm}/protocol/openid-connect/logout",`

 If you need anything more let me know. Also for further development needs, all these urls are under:

`http://keycloakhost:keycloakport/auth/realms/{realm}/.well-known/openid-configuration`

**Comment by satterly** [comment]
If I understand the spec correctly web UI should request that the API send an "end session" request to the OIDC server with the original `id_token` supplied by the OIDC when that user logged in. However the Alerta API does not persist the `id_token` returned by Keycloak. Once it has verified that the user is authenticated it discards this token. Does that sound right? How else would Keycloak know which user was logging out?

So, if the origin `id_token` is required it could either be persisted in the database or embedded in the token returned by the Alerta API to the web client. However, this would make this token very big.

Let me know what you think. Thanks.

**Comment by burakksglu** [comment]
Do we really need token to call logout url? 

Grafana works fine, please see below: 

Pull request:

[https://github.com/grafana/grafana/pull/12077](url)

Documentation about this:

[https://grafana.com/docs/grafana/latest/auth/overview/](url)

Also there is an another use case:

[https://blog.sqreen.com/authentication-best-practices-vue/](url)

**Comment by satterly** [comment]
I've managed to get it working for Azure OIDC which used the browser cookies to determine which user to logout, but it failed with Okta which seems to want you to provide the original `id_token`. I've yet to test this with Keycloak.

<img width="1333" alt="Screenshot 2020-01-11 at 10 21 14" src="https://user-images.githubusercontent.com/615057/72202162-abab7e80-345c-11ea-8f9d-76fd4ae6ced6.png">

<img width="1140" alt="Screenshot 2020-01-11 at 10 21 35" src="https://user-images.githubusercontent.com/615057/72202163-ae0dd880-345c-11ea-965f-19dda8266180.png">

**Comment by satterly** [comment]
Tested this with Keycloak now and it mostly works. The user session in Keycloak is revoked on logout from Alerta web UI but the browser is not redirected back to the "post_logout_redirect_url" so the user is just presented with a blank page. Not ideal but good enough for now.
