### ISSUE TITLE
Closing alarm does not set severity to normal

### ISSUE THREAD

**Issue by cisco92** [alerta/alerta#1014]
**Issue Summary**
Trying to close and alarm with curl request does not set severity to normal, it stays in Major.

**Environment**
- OS: Windows & Linux
- API version: 7.2.2
- Deployment: Docker

- Database: MongoDB

- Server config:
  Auth enabled? No & Yes
  Auth provider? Basic
  Customer views? None?

- web UI version: 7.2.11
- CLI version: 7.2.2

**To Reproduce**
Sending a curl request to create an alarm as this:
{
      "environment": "Production",
      "event": "ApplicationError",
      "group": "NTS",
      "origin": "HOST",
      "resource": "NTS",
      "service": [
        "NTS"
      ],
      "severity": "major",
      "text": "Application is down."
}

And to close it:
{
      "status": "closed"
}

But severity is still major.

**Expected behavior**
Severity set to normal.

**Comment by satterly** [comment]
Oh. You shouldn't close the alert unless that is all you want to do. If you want the severity to change to "normal" and the status to "closed" just send the same alert but with severity "normal".
