### ISSUE TITLE
Env Variable to increase the number of Alerts in a page

### ISSUE THREAD

**Issue by pkvel01** [alerta/alerta#1018]
Deployment: [self-hosted]

For self-hosted, WSGI environment: [nginx/uwsgi}

Database: MongoDB

Server config:
Auth enabled? No
Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
Customer views? Yes/No
(or provide the /config endpoint output)

alerta 7.2.11
alerta client 7.2.2
requests 2.22.0
click 7.0

Login to Alerta it displays 20 Alerts on a page by default , can we increase the number to 50 Alerts ?

**Comment by satterly** [comment]
It's in the settings page of the web UI. Alert Summary Settings -> Rows per page.

**Comment by pkvel01** [comment]
i dont see setting options in the web UI 


API | Build | Date | Revision
-- | -- | -- | --
Alerta API 7.2.11 | PROD | 2019-06-18T21:31:27Z | 703cfd48df6776f9a9032f57fcb554e6fcbd5156

**Comment by satterly** [comment]
Are you logged in?

**Comment by pkvel01** [comment]
![image](https://user-images.githubusercontent.com/42444858/60361432-ff5bec00-9992-11e9-8118-f28998659d5d.png)

Yes

**Comment by satterly** [comment]
That's version 6 of the web UI which does not support user-defined settings.

**Comment by pkvel01** [comment]
can you share latest version for the web UI ?

**Comment by satterly** [comment]
The latest version (v7) is here ... https://github.com/alerta/alerta-webui

**Comment by pkvel01** [comment]
thanks
