### ISSUE TITLE
Need help to make a text clickable in webhook/prometheus.py 

### ISSUE THREAD

**Issue by pkvel01** [alerta/alerta#1021]
Deployment: [self-hosted]

For self-hosted, WSGI environment: [nginx/uwsgi}

Database: MongoDB

Server config:
Auth enabled? No
Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
Customer views? Yes/No
(or provide the /config endpoint output)

alerta 7.2.11
alerta client 7.2.2
requests 2.22.0
click 7.0

prometheus.py

def parse_prometheus(alert: JSON, external_url: str) -> Alert:
    status = alert.get('status', 'firing')

    # Allow labels and annotations to use python string formats that refer to
    # other labels eg. runbook = 'https://internal.myorg.net/wiki/alerts/{app}/{alertname}'
    # See https://github.com/prometheus/prometheus/issues/2818

    labels = {}
    for k, v in alert['labels'].items():
        try:
            labels[k] = v.format(**alert['labels'])
        except Exception:
            labels[k] = v

    annotations = {}
    for k, v in alert['annotations'].items():
        try:
            annotations[k] = v.format(**labels)
        except Exception:
            annotations[k] = v

    starts_at = parse_date(alert['startsAt'])
    if alert['endsAt'] != '0001-01-01T00:00:00Z':
        ends_at = parse_date(alert['endsAt'])
    else:
        ends_at = None  # type: ignore

    if status == 'firing':
        severity = labels.pop('severity', 'warning')
        create_time = starts_at
    elif status == 'resolved':
        severity = 'normal'
        create_time = ends_at
    else:
        severity = 'unknown'
        create_time = ends_at or starts_at

    # labels
    resource = labels.pop('exported_instance', None) or labels.pop('instance', 'n/a')
    event = labels.pop('event', None) or labels.pop('alertname')
    environment = labels.pop('environment', 'Production')
    customer = labels.pop('customer', None)
    correlate = labels.pop('correlate').split(',') if 'correlate' in labels else None
    service = labels.pop('service', '').split(',')
    group = labels.pop('group', None) or labels.pop('job', 'Prometheus')
    origin = 'prometheus/' + labels.pop('monitor', '-')
    tags = ['{}={}'.format(k, v) for k, v in labels.items()]  # any labels left over are used for tags

    try:
        timeout = int(labels.pop('timeout', 0)) or None
    except ValueError:
        timeout = None

    value = annotations.pop('value', None)
    summary = annotations.pop('summary', None)
    description = annotations.pop('description', None)
    text = description or summary or '{}: {} is {}'.format(severity.upper(), resource, event)

    if external_url:
        annotations['externalUrl'] = external_url  # needed as raw URL for bi-directional integration
    if 'generatorURL' in alert:
        annotations['moreInfo'] = '<a href="{}" target="_blank">Prometheus Graph</a>'.format(alert['generatorURL'])

Added the below code to show the playbook clickable but it still shows as text 

/***    if 'PlayBook' in alert:
        annotations['PlayBook'] = '<a href="{}" target="_blank">PlayBook</a>'.format(alert['PlayBook'])
    if PlayBook:
        annotations['PlayBook'] = '<a href="{}" target="_blank">PlayBook</a>'  ****/
    attributes = annotations  # any annotations left over are used for attributes

Alert data from the gui

{
  "annotations": {
    "PlayBook": "http://github.home.xx.net/NOC/PlayBooks/wiki/exporter_down",

**Comment by pkvel01** [comment]
Can some one please help ?

**Comment by satterly** [comment]
Can you format the code in the description better? I can't tell what is code and what is not. Thanks.

**Comment by pkvel01** [comment]
Added Lines 64-67 to make playbook url clickable but it still shows as text.

`def parse_prometheus(alert: JSON, external_url: str) -> Alert:

    status = alert.get('status', 'firing')

    # Allow labels and annotations to use python string formats that refer to
    # other labels eg. runbook = 'https://internal.myorg.net/wiki/alerts/{app}/{alertname}'
    # See https://github.com/prometheus/prometheus/issues/2818

    labels = {}
    for k, v in alert['labels'].items():
        try:
            labels[k] = v.format(**alert['labels'])
        except Exception:
            labels[k] = v

    annotations = {}
    for k, v in alert['annotations'].items():
        try:
            annotations[k] = v.format(**labels)
        except Exception:
            annotations[k] = v

    starts_at = parse_date(alert['startsAt'])
    if alert['endsAt'] != '0001-01-01T00:00:00Z':
        ends_at = parse_date(alert['endsAt'])
    else:
        ends_at = None  # type: ignore

    if status == 'firing':
        severity = labels.pop('severity', 'warning')
        create_time = starts_at
    elif status == 'resolved':
        severity = 'normal'
        create_time = ends_at
    else:
        severity = 'unknown'
        create_time = ends_at or starts_at

    # labels
    resource = labels.pop('exported_instance', None) or labels.pop('instance', 'n/a')
    event = labels.pop('event', None) or labels.pop('alertname')
    environment = labels.pop('environment', 'Production')
    customer = labels.pop('customer', None)
    correlate = labels.pop('correlate').split(',') if 'correlate' in labels else None
    service = labels.pop('service', '').split(',')
    group = labels.pop('group', None) or labels.pop('job', 'Prometheus')
    origin = 'prometheus/' + labels.pop('monitor', '-')
    tags = ['{}={}'.format(k, v) for k, v in labels.items()]  # any labels left over are used for tags

    try:
        timeout = int(labels.pop('timeout', 0)) or None
    except ValueError:
        timeout = None

    value = annotations.pop('value', None)
    summary = annotations.pop('summary', None)
    description = annotations.pop('description', None)
    text = description or summary or '{}: {} is {}'.format(severity.upper(), resource, event)

    if external_url:
        annotations['externalUrl'] = external_url  # needed as raw URL for bi-directional integration
    if 'generatorURL' in alert:
        annotations['moreInfo'] = '<a href="{}" target="_blank">Prometheus Graph</a>'.format(alert['generatorURL'])
	if 'PlayBook' in alert:
        annotations['PlayBook'] = '<a href="{}" target="_blank">PlayBook</a>'.format(alert['PlayBook'])
    if PlayBook:
        annotations['PlayBook'] = '<a href="{}" target="_blank">PlayBook</a>'
    attributes = annotations  # any annotations left over are used for attributes`

**Comment by pkvel01** [comment]
I closed the ticket by mistake,

**Comment by satterly** [comment]
You need to use triple backticks around your code not just one backtick for code blocks. ie. ```

**Comment by satterly** [comment]
What's different about this code and the `prometheus.py` webhook code in master branch??

**Comment by pkvel01** [comment]
Added the below mentioned lines .

    if 'PlayBook' in alert:
        annotations['PlayBook'] = '<a href="{}" target="_blank">PlayBook</a>'.format(alert['PlayBook'])
    if PlayBook:
        annotations['PlayBook'] = '<a href="{}" target="_blank">PlayBook</a>'




Raw Data(Alert) from Alertmanager
 "rawData" : { "status" : "firing", "labels" : { "alertname" : "exporter_down", "dc" : "sv", "env" : "prod", "instance" : "ftp02.xxx-ftp.xx:9100", "job" : "ftp-assist-ftp", "promhost" : "monitor-prom04.sv1", "servic e" : "ASSIST", "severity" : "critical", "type" : "ftp" }, "annotations" : { "PlayBook" : "http://github.home.xx-xx/NOC/PlayBooks/wiki/exporter_down", "description" : "ftp02.assist-ftp.xx:9100 of job ftp-xx-ftp has  been unreachable for more than 5 minutes.", "summary" : "Instance ftp02.xx-ftp.xxx:9100 unreachable", "url_dashboard" : "http://prom-alertman01.private.xxx/d/biX6ShJik/system_metrics-sv1?orgId=1&var-job=ftp- assist-ftp&var-node=ftp02.assist-ftp.sv1.xxx&var-port=9100" }, "startsAt" : "2019-06-28T15:15:01.076450545-07:00", "endsAt" : "0001-01-01T00:00:00Z", "generatorURL" : "http://monitor-prom04.privatexx:9090/graph?g0. expr=up+%3D%3D+0&g0.tab=1" }, "customer" : null, "duplicateCount" : 197, "repeat" : true, "previousSeverity" : "indeterminate", "trendIndication" : "moreSevere", "receiveTime" : ISODate("2019-07-01T18:56:53.110Z"), "lastReceiveId" : "eb 8cef5c-6d86-4dea-9093-a64e8bbf65c3", "lastReceiveTime" : ISODate("2019-07-01T20:11:06.802Z"), "updateTime" : ISODate("2019-07-01T18:56:53.110Z"),

**Comment by satterly** [comment]
Both of the links in this alert (text and attribute) work for me ... 
```
$ alerta send -E Development -S Web -r web02 -e node_down -t 'test1 <a href="https://google.com">click me</a>' -s major -A foo=' this is a foo <a href="https://google.com">click me</a>'
117de620-baf2-4a73-bdd5-83f58021d991 (indeterminate -> major)
```

**Comment by satterly** [comment]
I would guess the link doesn't work for you because "Playbook" does not exist as an attribute on "alert". I don't understand where "Playbook" is being set.

**Comment by pkvel01** [comment]
from the alerts (raw data) i see this  "annotations" : { "PlayBook" : "http://github.home.xx-xx/NOC/PlayBooks/wiki/exporter_down",

**Comment by pkvel01** [comment]
This is how its on the details page of the alert.
![image](https://user-images.githubusercontent.com/42444858/60551300-c8157400-9cdf-11e9-8b0b-74d87e15894e.png)

**Comment by satterly** [comment]
Try this ...
```
    if 'PlayBook' in annotations:
        annotations['PlayBook'] = '<a href="{}" target="_blank">PlayBook</a>'.format(annotations.pop('PlayBook'))
```

**Comment by pkvel01** [comment]
Removed the existing code(the one i added for playbook)  in prometheus.py and add the line as you shared . Restart the alerta server and client process but still it shows as text . i see only More info option as clickable. 

Just to let you know i m looking at the Alerta details screen page.

**Comment by satterly** [comment]
A link inside an attribute will be clickable if surrounded by `<a href=""></a>` HTML tags. See ...

<img width="540" alt="Screenshot 2019-07-03 at 10 37 49" src="https://user-images.githubusercontent.com/615057/60576923-a3bca480-9d7e-11e9-8977-d51794666d8a.png">

If it isn't working for you then it's a problem with your code.

**Comment by pkvel01** [comment]
ok thanks
