### ISSUE TITLE
Unable to search alerts by tag

### ISSUE THREAD

**Issue by grjones** [alerta/alerta#1025]
**Issue Summary**
I am trying to search alerts by tag using the following url and params:
`/api/environments?q=tag:asdf&sort-by=lastReceiveTime&status=open&status=unknown`

The API returns a 500 error and the response is:
```
{
  "code": 500, 
  "errors": [
    "Traceback (most recent call last):\n  File \"/var/task/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/var/task/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/var/task/flask_cors/decorator.py\", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File \"/var/task/alerta/auth/decorators.py\", line 74, in wrapped\n    return f(*args, **kwargs)\n  File \"/var/task/alerta/models/metrics.py\", line 259, in wrapped\n    response = f(*args, **kwargs)\n  File \"/var/task/alerta/utils/response.py\", line 19, in decorated\n    return func(*args, **kwargs)\n  File \"/var/task/alerta/views/alerts.py\", line 562, in get_environments\n    environments = Alert.get_environments(query)\n  File \"/var/task/alerta/models/alert.py\", line 533, in get_environments\n    return db.get_environments(query)\n  File \"/var/task/alerta/database/backends/postgres/base.py\", line 577, in get_environments\n    result = self._fetchall(select, query.vars, limit=topn)\n  File \"/var/task/alerta/database/backends/postgres/base.py\", line 1297, in _fetchall\n    cursor.execute(query, vars)\n  File \"/var/task/psycopg2/extras.py\", line 313, in execute\n    return super(NamedTupleCursor, self).execute(query, vars)\npsycopg2.ProgrammingError: column \"tag\" does not exist\nLINE 3:             WHERE \"tag\" ILIKE '%asdf%'\n                          ^\nHINT:  Perhaps you meant to reference the column \"alerts.tags\".\n\n"
  ], 
  "message": "column \"tag\" does not exist\nLINE 3:             WHERE \"tag\" ILIKE '%asdf%'\n                          ^\nHINT:  Perhaps you meant to reference the column \"alerts.tags\".\n", 
  "status": "error"
}
```

**Environment**
- OS: Linux
- API version: 7.2.7
- Deployment: Docker
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: [eg. MongoDB, Postgres]
Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? Yes

- web UI version: Not using
- CLI version: Not using

**To Reproduce**
Run this curl statement:
`curl 'https://YOUR_HOSTNAME/api/environments?q=tag:asdf&sort-by=lastReceiveTime&status=open&status=unknown' -H 'Authorization: Key YOUR_KEY'`

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
Alerts should be returned that have the search tag.  Additionally, tag ranges may need to be supported, since it seems this was intended to be possible in PR https://github.com/alerta/alerta/pull/712

**Screenshots**
None needed.

**Comment by satterly** [comment]
It's `tags` not `tag`. Try this tag query in the [web UI](https://beta.alerta.io/alerts?q=tags%3Alinux#status:open,ack;dateRange:,;sb:default;sd:1;asi:0) or this for [the API](https://alerta-api.herokuapp.com/alerts?q=tags:linux&api-key=demo-key) directly.

**Comment by grjones** [comment]
Thank you for the quick reply.  That did it!

**Comment by satterly** [comment]
Not sure if you've seen this but the query string syntax is documented here ... https://docs.alerta.io/en/latest/api/query-syntax.html

**Comment by grjones** [comment]
Yep, I did, but it doesn't look like tag searching is mentioned there. 😄
