### ISSUE TITLE
Error http 500 when submitting an alert in command line

### ISSUE THREAD

**Issue by rpelissi** [alerta/alerta#1026]
**Issue Summary**
When creating an alert in command line I receive the error message:
ERROR: Severity is not one of fatal, critical, warning, ok, indeterminate, unknown
using
/opt/alerta/bin/alerta --debug send -r net01 -e down -s warning -E Production -S Network -t 'net01 is down.'

**Environment**
- OS: Linux
- API version:  7.2.11
- Deployment: self-hosted
- For self-hosted, nginx/uwsgi,

- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider?  Basic
  Customer views? No
  (or provide the `/config` endpoint output)

  |  
-- | --
actions | []
alarm_model |  
colors |  
severity |  
critical | "red"
fatal | "blue"
indeterminate | "lightblue"
ok | "#00CC00"
unknown | "silver"
warning | "#1E90FF"
defaults |  
normal_severity | "normal"
previous_severity | "indeterminate"
status | "open"
name | "Alerta 7.2.11"
severity |  
critical | 1
fatal | 0
indeterminate | 5
ok | 5
unknown | 9
warning | 4
status |  
ack | "C"
assign | "B"
blackout | "E"
closed | "F"
expired | "G"
open | "A"
shelved | "D"
unknown | "H"
audio |  
new | null
auth_required | true
azure_tenant | null
client_id | null
colors |  
severity |  
critical | "red"
fatal | "blue"
indeterminate | "lightblue"
ok | "#00CC00"
unknown | "silver"
warning | "#1E90FF"
columns |  
0 | "severity"
1 | "status"
2 | "lastReceiveTime"
3 | "timeoutLeft"
4 | "duplicateCount"
5 | "customer"
6 | "environment"
7 | "service"
8 | "resource"
9 | "event"
10 | "value"
customer_views | false
dates |  
longDate | "d/M/yyyy h:mm:ss.sss a"
mediumDate | "EEE d MMM HH:mm"
shortTime | "HH:mm"
debug | true
email_verification | false
endpoint | "http://192.168.2.100:8081/api"
github_url | "https://github.com"
gitlab_url | "https://gitlab.com"
keycloak_realm | null
keycloak_url | null
oidc_auth_url | null
provider | "basic"
refresh_interval | 5000
severity |  
critical | 1
fatal | 0
indeterminate | 5
ok | 5
unknown | 9
warning | 4
signup_enabled | true
site_logo_url | ""
sort_by | "lastReceiveTime"
tracking_id | null

- web UI version: none
- CLI version: 7.2.11 (I guess)

**To Reproduce**
1. Install alerta following the official doc
2. Activate auth
3. in a shell do:
/opt/alerta/bin/alerta login
username
password
/opt/alerta/bin/alerta --debug send -r net01 -e down -s warning -E Production -S Network -t 'net01 is down.'

4. See error (include command output)
send: b'POST /api/alert HTTP/1.1\r\nHost: localhost:8081\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nUser-Agent: python-requests/2.20.1\r\nContent-Type: application/json\r\nX-Request-ID: fa127629-5b78-49bc-ac58-243c4bf9cea9\r\nContent-Length: 341\r\nAuthorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyb21haW4ucGVsaXNzaWVyQGdtYWlsLmNvbSIsInR5cCI6IkJlYXJlciIsImV4cCI6MTU2NDI2OTQ0NSwibmJmIjoxNTYzMDU5ODQ1LCJyb2xlcyI6WyJ1c2VyIl0sIm5hbWUiOiJyb21haW4ucGVsaXNzaWVyIiwic2NvcGUiOiJyZWFkIHdyaXRlIiwiZW1haWwiOiJyb21haW4ucGVsaXNzaWVyQGdtYWlsLmNvbSIsInByb3ZpZGVyIjoiYmFzaWMiLCJzdWIiOiI2MTcxZjg4Mi0wYzEzLTRhNGUtYmJjZS0zZjIzNGNjZjA1M2QiLCJpYXQiOjE1NjMwNTk4NDUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9hcGkvIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXBpLyIsImp0aSI6IjZlYzJhNmMwLWQ2MmUtNGE1MC05NjhkLWYwMjhkMzk5OTkwYSJ9.v4WTtXwer9J7a9TIQKuf2XrD5kmtC1NDSrchq9UmJ28\r\n\r\n'
send: b'{"createTime": "2019-07-13T23:17:27.738Z", "timeout": null, "resource": "net01", "severity": "warning", "environment": "Production", "text": "net01 is down.", "attributes": {}, "rawData": null, "type": null, "tags": [], "service": ["Network"], "group": null, "origin": null, "correlate": [], "value": null, "customer": null, "event": "down"}'
reply: 'HTTP/1.1 500 INTERNAL SERVER ERROR\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: Access-Control-Allow-Origin header: Vary header: X-Request-ID
body: {
  "code": 500,
  "errors": null,
  "message": "Severity is not one of fatal, critical, warning, ok, indeterminate, unknown",
  "requestId": "fa127629-5b78-49bc-ac58-243c4bf9cea9",
  "status": "error"
}

ERROR: Severity is not one of fatal, critical, warning, ok, indeterminate, unknown
For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Screenshots**

**Additional context**

Here is the config:
SECRET_KEY='8&hKxlnh*T%CJFPU7ZBn^yte7RJANxxx'
PLUGINS=['reject','rocketchat']
ALLOWED_ENVIRONMENTS=['Production', 'Development', 'Code']
AUTH_REQUIRED = True

DEBUG = True
BASE_URL = '/api'
USE_PROXYFIX = False
LOG_HANDLERS = ['console', 'file']
LOG_FILE = '/var/log/alertad.log'
LOG_MAX_BYTES = 5*1024*1024  # 5 MB
LOG_BACKUP_COUNT = 2
LOG_FORMAT = 'verbose'

SEVERITY_MAP = {
    'fatal': 0,
    'critical': 1,
    'warning': 4,
    'indeterminate': 5,
    'ok': 5,
    'unknown': 9
}

COLOR_MAP = {
    'severity': {
        'fatal': 'blue',
        'critical': 'red',
        'warning': '#1E90FF',
        'indeterminate': 'lightblue',
        'ok': '#00CC00',
        'unknown': 'silver'
    }
}

#PLUGINS = ['rocketchat']
ROCKETCHAT_WEBHOOK_URL = 'https://192.168.2.100/hooks/qQap62ztfgawHaZfo/9kFozx8Xkec7gMPEfPrjsH6GB4gQRcGq3Kg56MP5kcucixxx'
#ROCKETCHAT_CHANNEL = ''  # if empty then uses channel from incoming webhook configuration

#ICON_EMOJI = '' # default :rocket:
#ALERTA_USERNAME = '' # default alerta
ALERTA_USERNAME = 'rocket.cat' # default alerta
DASHBOARD_URL = 'http://192.168.2.100:8081'

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
What happens if you remove `SEVERITY_MAP` from the server config and restart Alerta API?

**Comment by rpelissi** [comment]
Hi,
I have tried to comment out the SEVERITY_MAP from the config but same thing happen.
I have updated to the 7.30 version and deleted the mongo db "monitoring". Strange thing is that it works once, then the issue appear again.

**Comment by rpelissi** [comment]
Hi,
Ok, don't really know why but I made a second test by removing any new SEVERITY_MAP and COLOR_MAP settings and now it works with this test:
root@pdrnode002:~# alerta send --resource webserver01 --event down --environment Production --service Website01 --severity critical --text "Web server 01 is down." --value ERROR
fda6b264-20c0-4a97-89a3-596d1370f5fe (normal -> critical)

**Comment by satterly** [comment]
It could be that `DEFAULT_NORMAL_SEVERITY` of "normal" is causing an exception because normal isn't included in list of severities. It would be interesting to know if setting `DEFAULT_NORMAL_SEVERITY='ok'` fixed the issue.

**Comment by satterly** [comment]
My guess was right. `DEFAULT_NORMAL_SEVERITY` must be set to 'ok'. See #1031
