### ISSUE TITLE
Question about correlated alerts and service+history and severity

### ISSUE THREAD

**Issue by jjh74** [alerta/alerta#1027]
Hi,

I'm trying to correlate all alerts on same host(resource) into one alert: so for example if I'm sending these alerts:
```
alerta send -E Production -r host300 -e service -S TEST -s warning -A a=1 -A b=2
alerta send -E Production -r host300 -e service -S TEST2 -s major -A c=3
alerta send -E Production -r host300 -e service -S TEST3 -s minor -A d=4
alerta send -E Production -r host300 -e service -S TEST -s ok -A e=5
```
These all are correlated(-e service) into one alert. Couple of questions:
- Is it possible to save previous service into history entries ?
- Since service is an array could new services be pushed into service, for example after `-S TEST3 -s minor`  --> `service = [ 'TEST3', 'TEST2', 'TEST' ]` (perhaps a config option, because for others overwriting service makes more sense (https://github.com/alerta/alerta/pull/953)).
- could `-S TEST -s ok` just remove 'TEST' from service array (and possibly reset status=ok only if service has only 'TEST' service left).
- severity: Is it possible to keep the most severe severity ? So `-S TEST3 -s minor` would still keep severity "major" ?
- Is it possible to have correlated count column in UI (just like duplicated(Dupl.) column) ?
 
Does this make any sense ? Or is there an existing way to achieve something similar  (when multiple  services on one host/resource create alerts within few minutes -> only show one alert(hopefully listing all affected services) in alerta UI (and send out alerts once (or if severity increases))

**Comment by satterly** [comment]
You are asking for complex correlation which is not supported by Alerta "out of the box". You would need to integrate Alerta with an additional tool that provided this functionality. See http://docs.alerta.io/en/latest/server.html#simple-correlation

**Comment by jjh74** [comment]
Thanks (I was on holiday / away from computer for few days), I think I get the complex correlation now. I don't think I'll need full complex corralation flexibility, for my use case simple correlation and adding different services to service array should be enough (and saving service to history if service changes).
