### ISSUE TITLE
How to configue history and data retention in Alerta with PostgreSQL

### ISSUE THREAD

**Issue by yoelbar** [alerta/alerta#1032]
Hi,
We are working with Alerta and PostgreSQL. I have few questions regarding retention of old events:
1. Where can I define the history period for keeping closed alerts?
2. Does Alerta have a way to move old closed alerts (let's say after one month) to a different table in Postgres?
3. We have a daily batch process that need to retrieve all alerts from the last 6 months. What would be the best approach to do so? Using the search API, or maybe direct access to PostgreSQL...?

Many thanks,
Yoel.

**Comment by madan** [comment]
@yoelbar 

> 1. Where can I define the history period for keeping closed alerts?
By default their is no configured retention period set in alerta, which means alerts are available in database as long as you don't delete them. But as part of alerta setup its hughly recommended to setup the housekeeping script that deletes alerts that are closed and older than 2 hours. If you haven't set this up yet, you are running a instance that stores alerts forever and gets slower each day.

Documentation is clear on this.
https://docs.alerta.io/en/latest/deployment.html?highlight=retention#house-keeping

> 2. Does Alerta have a way to move old closed alerts (let's say after one month) to a different table in Postgres?
Unaware of alerta doing this out of the box, plugin eco-system is targeting needs like this. See if you can repurpose the forward plugin to do this.

https://github.com/alerta/alerta-contrib/tree/master/plugins/forward

> 3. We have a daily batch process that need to retrieve all alerts from the last 6 months. What would be the best approach to do so? Using the search API, or maybe direct access to PostgreSQL...?
My personal opinion is it depends on the amount of alerts you have, if its in millions I would recommend you directly access the DB, if in hundreds then should be OK to go with APIs as you don't have to do much of heavy lifting to get this done.

**Comment by satterly** [comment]
> 2. Does Alerta have a way to move old closed alerts (let's say after one month) to a different table in Postgres?

As @yoelbar says, use a plugin to achieve this. There isn't one for this particular request however there are many examples. See also https://github.com/alerta/alerta-contrib/tree/master/plugins/influxdb and https://github.com/alerta/alerta-contrib/tree/master/plugins/logstash

> 3. We have a daily batch process that need to retrieve all alerts from the last 6 months. What would be the best approach to do so? Using the search API, or maybe direct access to PostgreSQL...?

I wouldn't keep 6 months of alerts in the Alerta database. I would export them to an external database (mentioned above) and query that database.
