### ISSUE TITLE
Alerta logging only in json format 

### ISSUE THREAD

**Issue by rdxsuper** [alerta/alerta#1037]
**Issue Summary**
Regardless of the configuration in /etc/alertad.conf, alerta logs in json format only. And setting http methods also has not effect. Constant 'GET' method logs in /var/log/messages due to 'auto update'. 

**Environment**
- OS: 
  CentOS - 7
  Kernel -3.10.0-862.11.6.el7.x86_64

- API version: [eg. 6.8.1]
  Alerta API 7.2.2

- Deployment: [eg. Docker, Heroku, AWS, GCloud, self-hosted]
  Openstack (self-hosted)

- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]
Installed in python virtualenv under /opt/alerta
Python: Python 3.6.8
nginx/uwsgi
 nginx: 1.12.2-3 and related modules
 uwsgi: 2.0.17.1-2.el7.x86_64

- Database: [eg. MongoDB, Postgres]
Postgresql-10

- Server config:
We have plugins that do stuff in pre-receive, post-receive and status change.

Below is alertad.conf:
SEVERITY_MAP = {
    'security': 0,
    'critical': 1,
    'major': 2,
    'minor': 3,
    'warning': 4,
    'indeterminate': 5,
    'informational': 6,
    'normal': 7,
    'ok': 7,
    'cleared': 7,
    'debug': 8,
    'trace': 9,
    'unknown': 10
}
ALARM_MODEL = 'ALERTA'
BASE_URL = '/api'
PLUGINS=['blackout', 'customtimeout', 'teams', 'oracletrap','iop','slack']
ALLOWED_ENVIRONMENTS=[***********************]
CUSTOM_TIMEOUT = 21600
EMAIL_PORT = '25' # default="25"
EMAIL_FROM = '***********************'
EMAIL_SEND_DUPLICATES = 'True'
SLACK_WEBHOOK_URL = ''
SLACK_ATTACHMENTS = True
ICON_EMOJI = ':red_alert:' # default :rocket:
SLACK_SEND_DUPLICATES = 'True'
SLACK_ALT_URL = {***********************}
NOTIFICATION_BLACKOUT = True
BLACKOUT_ACCEPT=['normal','ok','cleared']
AWS_API_GATEWAY = '***************'
ALERT_TIMEOUT = 2400
ALERTMANAGER_API_URL = '******************'
ALERTMANAGER_SILENCE_DAYS = 1

BASE_URL = '/api'
USE_PROXYFIX = True
LOG_HANDLERS = ['file']
LOG_FILE = '/var/log/alerta/alertad.log'
LOG_MAX_BYTES = 5*1024*1024  # 5 MB
LOG_BACKUP_COUNT = 2
LOG_FORMAT = ['verbose']
LOG_METHODS = ['POST', 'PUT', 'DELETE']

#### SSO related entries
PINGFEDERATE_TOKEN_ALGORITHM='****'
AUTH_REQUIRED = True
PINGFEDERATE_OPENID_PAYLOAD_USERNAME='*******************'
PINGFEDERATE_OPENID_PAYLOAD_EMAIL='************'
PINGFEDERATE_OPENID_PAYLOAD_GROUP=['**************']
CUSTOMER_VIEWS = False
ADMIN_USERS = [*********************]
DEBUG = False
DATABASE_NAME = '****************'
SECRET_KEY = "**********************************"
DASHBOARD_URL = "*************************"
PINGFEDERATE_PUBKEY_LOCATION = "****************"
PINGFEDERATE_OPENID_ACCESS_TOKEN_URL = "*****************************"
OAUTH2_CLIENT_SECRET = "******************************"
DATABASE_URL = "*********************************"

  Auth enabled? Yes/No
  Yes

  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Pingfederate, LDAP

  Customer views? Yes/No
  (or provide the `/config` endpoint output)
  No

- web UI version: [eg. 6.8.1] ---> not sure 
  requests 2.22.0
  click 7.0

- CLI version: [eg. 6.8.1]
   alerta client 7.2.2

**To Reproduce**

I use terraform and ansible to build and provision alerta. Every rebuild gives the same result
Install plugins that have pre-receive, post-receive and status changef . I did not do anything more than that.

1. Created virtualenv under /opt/alerta
2. Created a dir for plugins /opt/alerta/plugins
3. Updated pip to 19.2.1
pip 19.2.1 from /opt/alerta/lib64/python3.6/site-packages/pip (python 3.6)
4. Installed packages nginx, snmptrap, etc..
5. Pip install 
      alerta-server==7.2.2
      alerta==7.2.2
      uwsgi
      asn1crypto
      cryptography
      psycopg2
      wheel
6. Various steps that just copy and install required files in respective locations

**Comment by rdxsuper** [comment]
I found this in /opt/alerta/lib/python3.6/site-packages/alerta/utils/logging.py

```
                    'file': {
                        'class': 'logging.handlers.RotatingFileHandler',
                        'formatter': 'json', <----- Is this correct?
                        'filters': ['requests'],
                        'filename': log_file,
                        'maxBytes': app.config['LOG_MAX_BYTES'],
                        'backupCount': app.config['LOG_BACKUP_COUNT']
```

**Comment by satterly** [comment]
What happens if you change that to ... `'formatter': log_format,` ?

**Comment by rdxsuper** [comment]
I encountered an error when I tried to compile it. 
```
[root@alerta-as-01 utils]# python3 -m compileall logging.py
Could not import runpy module
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test #15386 via -m
  File "/usr/lib64/python3.6/importlib/__init__.py", line 57, in <module>
    import types
  File "/usr/lib64/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/usr/lib64/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
ImportError: cannot import name 'namedtuple'
```

**Comment by satterly** [comment]
I can't think why I hardcoded logfile format to 'json'. There may have been a reason at the time. Anyway, I've modified it to allow configurable log format as requested.
