### ISSUE TITLE
Alerta with Postgres: bench-marking on number of alerts to keep history

### ISSUE THREAD

**Issue by yoelbar** [alerta/alerta#1048]
Hi,
We have a requirement to keep 6 months of history of alerts. Our daily volume of alerts is few thousands. Let's assume that in 6 months we expect to have around 1 million of alerts.
Can Alerta+Postgres handle such volume? 
I know that we shouldn't keep such long history but still I wouldn't expect that 1 M of alerts will have much impact.
Many thanks.

**Comment by satterly** [comment]
I wouldn't recommend it. Forwarding alerts to a database designed for long term data retention and analysis is the recommended solution. Something like the ELK stack or Splunk.

You haven't said why you need 6 months and what you are going to do with them. And what if someone deletes an alert from the web UI or using the CLI. You've lost your history.

**Comment by yoelbar** [comment]
We need it for AI. We plan to build models of Root Cause Analysis by analyzing historical data.
And as its for this specific use case, and since were not talking about high volumes, our first option if possible is to keep using Postgres for that rather than on-boarding a new component to our system.

**Comment by satterly** [comment]
That sounds like a reasonable use case. However, I would suggest taking a dump and doing your RCA on an offline copy, or at the very least, a read replica that will not impact the performance of the production database. Good luck and let me know how this goes. Sounds very interesting. 👍
