### ISSUE TITLE
Unable to update blackout start / end time / duration via the API

### ISSUE THREAD

**Issue by mirceaulinic** [alerta/alerta#1053]
**Issue Summary**

I am trying to update the end time / extend duration of an existing blackout, using the API. The API client library has a method named [`update_blackout`](https://github.com/alerta/python-alerta-client/blob/master/alertaclient/api.py#L174) which makes me think we should be able to update blackouts. I believe this might be a core issue, as the python-alerta-client library only executes an HTTP requests and passes the arguments along - please let me know otherwise, and I shall open the issue elsewhere.

**Environment**

- OS: Linux (``Linux 236c37095522 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 GNU/Linux``)
- API version: 6.5.0
- Deployment:  Docker
- Database: Postgres

- Server config:
  Auth enabled? No
  Customer views? No

`/config` endpoint output:

```json
{
  "actions": [], 
  "alarm_model": {
    "name": "Alerta 6.7.5"
  }, 
  "audio": {
    "new": null
  }, 
  "auth_required": false, 
  "azure_tenant": null, 
  "colors": {
    "highlight": "skyblue ", 
    "severity": {
      "cleared": "#00CC00", 
      "critical": "red", 
      "debug": "#9D006D", 
      "indeterminate": "lightblue", 
      "informational": "#00CC00", 
      "major": "orange", 
      "minor": "yellow", 
      "normal": "#00CC00", 
      "ok": "#00CC00", 
      "security": "blue", 
      "trace": "#7554BF", 
      "unknown": "silver", 
      "warning": "dodgerblue"
    }, 
    "text": "black"
  }, 
  "columns": [
    "severity", 
    "status", 
    "lastReceiveTime", 
    "duplicateCount", 
    "customer", 
    "environment", 
    "service", 
    "resource", 
    "event", 
    "value", 
    "text"
  ], 
  "customer_views": false, 
  "dates": {
    "longDate": "d/M/yyyy h:mm:ss.sss a", 
    "mediumDate": "EEE d MMM HH:mm", 
    "shortTime": "HH:mm"
  }, 
  "email_verification": false, 
  "endpoint": "http://localhost",
  "gitlab_url": "https://gitlab.com", 
  "keycloak_realm": null, 
  "keycloak_url": null, 
  "pingfederate_url": null, 
  "provider": "basic", 
  "refresh_interval": 5000, 
  "severity": {
    "cleared": 5, 
    "critical": 1, 
    "debug": 7, 
    "indeterminate": 5, 
    "informational": 6, 
    "major": 2, 
    "minor": 3, 
    "normal": 5, 
    "ok": 5, 
    "security": 0, 
    "trace": 8, 
    "unknown": 9, 
    "warning": 4
  }, 
  "signup_enabled": true, 
  "site_logo_url": "", 
  "sort_by": "lastReceiveTime", 
  "tracking_id": null
}
```

In a separate environment, I've also tried with the latest version, though I'm using the above as a reference as that's the version I'm considering "stable" for our environment (not that the others wouldn't be, but haven't tested them thoroughly). The behaviour for this particular issue seems to be the same in the latest version as well.

**To Reproduce**

1. Add a blackout - either from the GUI or via the API.
2. Using a simple Python client, execute the following request to update the blackout time:

```python
>>> import alertaclient.api
>>> client = Client(endpoint='http://alerta-web:80/api')
>>> b = client.get_blackouts()
>>> client.update_blackout(b[0].id, {'start_time': '2019-08-08T13:05:00.000', 'end_time': '2019-08-08T16:05:00.000', 'priority':2, 'environment': 'Production', 'resource': 'junos::config', 'remaining': 6600})
>>> 
>>> client.http.put('/blackout/%s' % b[0].id, {'end_time': '2020-10-07T16:45:00.000', 'start_time': '2019-08-07T15:46:00.000', 'environment': 'Production'})
{'status': 'ok'}
>>> client.http.put('/blackout/%s' % b[0].id, {'duration': 50000})
{'status': 'ok'}
```

(tried various ways and field combinations).

The blackout I was trying to update, didn't change its duration or end time.

**Expected behavior**

I would expect the blackout time properties to be updated.

**Additional context**

I've started the app in debug mode, and it looks like the start / end time / duration are simply ignored, and the query only attempts to update the environment, resource, or customer fields:

```
alerta-server_1  | ****************************************
alerta-server_1  | 
alerta-server_1  |             UPDATE blackouts
alerta-server_1  |             SET
alerta-server_1  |         environment='Production', resource='junos::config', customer=NULL, 
alerta-server_1  |             "user"=COALESCE(NULL, "user")
alerta-server_1  |             WHERE id='3fb9dec5-81c2-4cae-b368-0bf0fd23e003'
alerta-server_1  |             RETURNING *
alerta-server_1  |         
alerta-server_1  | ****************************************
```

**Comment by mirceaulinic** [comment]
I think I've found the culprit, the field name is `endTime` instead of `end_time` I was using. My confusion was due to the field name returned by the API when querying to return the existing blackouts etc.

Leaving this here, maybe it'll help someone in the future. Relevant code: https://github.com/alerta/alerta/blob/57930a44a9c47dc6768bedf995aa758ecc8d5791/alerta/models/blackout.py#L206-L207

/note-to-self: dig more into the code before opening an issue. Sigh.

**Comment by satterly** [comment]
The API should not return "end_time". That would surprise me.

**Comment by mirceaulinic** [comment]
Well noted, @satterly :smile:  - it's the objects from the API client I was looking at, e.g.,

```python
>>> b = client.get_blackouts()
>>> b[0]
Blackout(id='3fb9dec5-81c2-4cae-b368-0bf0fd23e003', priority=2, status='active', environment='Production', resource='junos::config', start_time=datetime.datetime(2019, 8, 8, 12, 9), end_time=datetime.datetime(2019, 10, 8, 16, 5), remaining=5280499)
```

**Comment by satterly** [comment]
I see. Might add this as an example to avoid future confusion. Thanks.
