### ISSUE TITLE
Alerta - LDAP configuration issue using python3-ldap dependency

### ISSUE THREAD

**Issue by Yu6936** [alerta/alerta#1065]
**Issue Summary**
I am trying to configure LDAP for user authentication for Alerta 7.  I am following these instructions:  https://buildmedia.readthedocs.org/media/pdf/alerta/latest/alerta.pdf
My Alerta server is setup in an python3.6 environment so I have pip install python3-ldap instead of python-ldap for python2. After setting up the /etc/alertad.conf using the LDAP directive and restarting the Nginx/Uwsgi services; uwsgi unable to start with python exception error indicating that I need to install python-ldap dependency (see below).  

**Environment**
- OS: [ CentOS Linux release 7.6.1810 (Core)]
- Deployment: [self-hosted - Ovirt 4.2 virtual machine]
- For self-hosted, WSGI environment: [nginx 1.12.2 /uwsgi]
- Database: [eg. MongoDB 4.0.12]

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? Yes

alerta 7.3.2
alerta client 7.3.0
requests 2.22.0
click 7.0
**To Reproduce**
1. Configure /etc/alertad.conf ldap directive:

AUTH_REQUIRED = True
AUTH_PROVIDER = 'ldap'

LDAP_URL = 'ldaps://example.com'
LDAP_DOMAINS = {
'example.com': 'uid=%s,ou=people,dc=example,dc=com'
}
LDAP_DOMAINS_BASEDN = {
'example.com': 'dc=example,dc=com'
}
LDAP_DOMAINS_GROUP = {
'example.com': '(&(memberUid={username})(objectClass=posixGroup))'
}

2. Issue command "systemctl restart nginx uwsgi"

3. tail  -f /var/log/messages: Look at the error: Must "raise RuntimeError('Must install python-ldap to use LDAP authentication module')"
=====================
Aug 14 11:24:29 hostname alertad[130691]: Traceback (most recent call last):
Aug 14 11:24:29 hostname alertad[130691]:  File "/opt/alerta/lib/python3.6/site-packages/alerta/auth/__init__.py", line 21, in init_auth
Aug 14 11:24:29 hostname alertad[130691]:    import ldap  # noqa
Aug 14 11:24:29 hostname alertad[130691]: ModuleNotFoundError: No module named 'ldap'
Aug 14 11:24:29 hostname alertad[130691]: #012During handling of the above exception, another exception occurred:
Aug 14 11:24:29 hostname alertad[130691]: Traceback (most recent call last):
Aug 14 11:24:29 hostname alertad[130691]:  File "wsgi.py", line 1, in <module>
Aug 14 11:24:29 hostname alertad[130691]:    from alerta import app
Aug 14 11:24:29 hostname alertad[130691]:  File "/opt/alerta/lib/python3.6/site-packages/alerta/__init__.py", line 29, in <module>
Aug 14 11:24:29 hostname alertad[130691]:    app = create_app()
Aug 14 11:24:29 hostname alertad[130691]:  File "/opt/alerta/lib/python3.6/site-packages/alerta/app.py", line 82, in create_app
Aug 14 11:24:29 hostname alertad[130691]:    init_auth(app)
Aug 14 11:24:29 hostname alertad[130691]:  File "/opt/alerta/lib/python3.6/site-packages/alerta/auth/__init__.py", line 24, in init_auth
Aug 14 11:24:29 hostname alertad[130691]:    raise RuntimeError('Must install python-ldap to use LDAP authentication module')
Aug 14 11:24:29 hostname alertad[130691]: RuntimeError: Must install python-ldap to use LDAP authentication module
Aug 14 11:24:29 hostname alertad[130691]: VACUUM: unix socket /var/run/uwsgi/uwsgi.sock removed.
=====================

4.  Installing python3-ldap is successful.
[root@hostname bin]# pip install python3-ldap
Requirement already satisfied: python3-ldap in /usr/local/lib/python3.6/site-packages (0.9.8.4)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.6/site-packages (from python3-ldap) (0.4.6)
[root@hostname bin]#

**Comment by satterly** [comment]
`python-ldap` supports python 3. You should use it instead of `python3-ldap` which is a completely different project.

**Comment by Yu6936** [comment]
Hi Nick,
   
    I've tried pip install python-ldap and getting fatal error.  

Command output
=========================
[root@hostname ~]# /opt/alerta/bin/pip install python-ldap
Collecting python-ldap
  Using cached https://files.pythonhosted.org/packages/ea/93/596f875e003c770447f4b99267820a0c769dd2dc3ae3ed19afe460fcbad0/python-ldap-3.2.0.tar.gz
Requirement already satisfied: pyasn1>=0.3.7 in /opt/alerta/lib/python3.6/site-packages (from python-ldap) (0.4.6)
Requirement already satisfied: pyasn1_modules>=0.1.5 in /opt/alerta/lib/python3.6/site-packages (from python-ldap) (0.2.6)
Building wheels for collected packages: python-ldap
  Building wheel for python-ldap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/alerta/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m6b_pnyv/python-ldap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m6b_pnyv/python-ldap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-behrc01p --python-tag cp36
       cwd: /tmp/pip-install-m6b_pnyv/python-ldap/
  Complete output (81 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  copying Lib/ldapurl.py -> build/lib.linux-x86_64-3.6
  copying Lib/ldif.py -> build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/async.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/syncrepl.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/constants.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/resiter.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/pkginfo.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/cidict.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/functions.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/modlist.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/asyncsearch.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/sasl.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/filter.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/dn.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/compat.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/ldapobject.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/__init__.py -> build/lib.linux-x86_64-3.6/ldap
  copying Lib/ldap/logger.py -> build/lib.linux-x86_64-3.6/ldap
  creating build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/readentry.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/openldap.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/vlv.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/libldap.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/simple.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/sss.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/pwdpolicy.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/deref.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/__init__.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/psearch.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/sessiontrack.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/ppolicy.py -> build/lib.linux-x86_64-3.6/ldap/controls
  copying Lib/ldap/controls/pagedresults.py -> build/lib.linux-x86_64-3.6/ldap/controls
  creating build/lib.linux-x86_64-3.6/ldap/extop
  copying Lib/ldap/extop/dds.py -> build/lib.linux-x86_64-3.6/ldap/extop
  copying Lib/ldap/extop/__init__.py -> build/lib.linux-x86_64-3.6/ldap/extop
  creating build/lib.linux-x86_64-3.6/ldap/schema
  copying Lib/ldap/schema/subentry.py -> build/lib.linux-x86_64-3.6/ldap/schema
  copying Lib/ldap/schema/tokenizer.py -> build/lib.linux-x86_64-3.6/ldap/schema
  copying Lib/ldap/schema/__init__.py -> build/lib.linux-x86_64-3.6/ldap/schema
  copying Lib/ldap/schema/models.py -> build/lib.linux-x86_64-3.6/ldap/schema
  creating build/lib.linux-x86_64-3.6/slapdtest
  copying Lib/slapdtest/__init__.py -> build/lib.linux-x86_64-3.6/slapdtest
  copying Lib/slapdtest/_slapdtest.py -> build/lib.linux-x86_64-3.6/slapdtest
  running egg_info
  writing Lib/python_ldap.egg-info/PKG-INFO
  writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
  writing requirements to Lib/python_ldap.egg-info/requires.txt
  writing top-level names to Lib/python_ldap.egg-info/top_level.txt
  reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'Doc/.build'
  writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/README -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/ca.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/ca.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/client.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/client.key -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/client.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/gencerts.sh -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/gennssdb.sh -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/server.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/server.key -> build/lib.linux-x86_64-3.6/slapdtest/certs
  copying Lib/slapdtest/certs/server.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
  running build_ext
  building '_ldap' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/Modules
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.2.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/include/python3.6m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.6/Modules/LDAPObject.o
  In file included from Modules/LDAPObject.c:8:0:
  Modules/constants.h:7:18: fatal error: lber.h: No such file or directory
   #include "lber.h"
                    ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-ldap
  Running setup.py clean for python-ldap
Failed to build python-ldap
Installing collected packages: python-ldap
  Running setup.py install for python-ldap ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/alerta/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m6b_pnyv/python-ldap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m6b_pnyv/python-ldap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qys75fjm/install-record.txt --single-version-externally-managed --compile --install-headers /opt/alerta/include/site/python3.6/python-ldap
         cwd: /tmp/pip-install-m6b_pnyv/python-ldap/
    Complete output (81 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying Lib/ldapurl.py -> build/lib.linux-x86_64-3.6
    copying Lib/ldif.py -> build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/async.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/syncrepl.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/constants.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/resiter.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/pkginfo.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/cidict.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/functions.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/modlist.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/asyncsearch.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/sasl.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/filter.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/dn.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/compat.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/ldapobject.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/__init__.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/logger.py -> build/lib.linux-x86_64-3.6/ldap
    creating build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/readentry.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/openldap.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/vlv.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/libldap.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/simple.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/sss.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/pwdpolicy.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/deref.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/__init__.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/psearch.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/sessiontrack.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/ppolicy.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/pagedresults.py -> build/lib.linux-x86_64-3.6/ldap/controls
    creating build/lib.linux-x86_64-3.6/ldap/extop
    copying Lib/ldap/extop/dds.py -> build/lib.linux-x86_64-3.6/ldap/extop
    copying Lib/ldap/extop/__init__.py -> build/lib.linux-x86_64-3.6/ldap/extop
    creating build/lib.linux-x86_64-3.6/ldap/schema
    copying Lib/ldap/schema/subentry.py -> build/lib.linux-x86_64-3.6/ldap/schema
    copying Lib/ldap/schema/tokenizer.py -> build/lib.linux-x86_64-3.6/ldap/schema
    copying Lib/ldap/schema/__init__.py -> build/lib.linux-x86_64-3.6/ldap/schema
    copying Lib/ldap/schema/models.py -> build/lib.linux-x86_64-3.6/ldap/schema
    creating build/lib.linux-x86_64-3.6/slapdtest
    copying Lib/slapdtest/__init__.py -> build/lib.linux-x86_64-3.6/slapdtest
    copying Lib/slapdtest/_slapdtest.py -> build/lib.linux-x86_64-3.6/slapdtest
    running egg_info
    writing Lib/python_ldap.egg-info/PKG-INFO
    writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
    writing requirements to Lib/python_ldap.egg-info/requires.txt
    writing top-level names to Lib/python_ldap.egg-info/top_level.txt
    reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'Doc/.build'
    writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/README -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/ca.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/ca.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/client.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/client.key -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/client.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/gencerts.sh -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/gennssdb.sh -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/server.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/server.key -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/server.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
    running build_ext
    building '_ldap' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/Modules
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.2.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/include/python3.6m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.6/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:8:0:
    Modules/constants.h:7:18: fatal error: lber.h: No such file or directory
     #include "lber.h"
                      ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/alerta/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m6b_pnyv/python-ldap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m6b_pnyv/python-ldap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qys75fjm/install-record.txt --single-version-externally-managed --compile --install-headers /opt/alerta/include/site/python3.6/python-ldap Check the logs for full command output.
[root@hostname ~]#
=========================

**Comment by satterly** [comment]
See https://stackoverflow.com/a/4768467

**Comment by Yu6936** [comment]
Thanks Nick,

I've installed  "yum install python-devel openldap-devel" and pip install python-ldap results without errors.  Thanks again. 

[root@hostname ~]# /opt/alerta/bin/pip install python-ldap
Collecting python-ldap
  Using cached https://files.pythonhosted.org/packages/ea/93/596f875e003c770447f4b99267820a0c769dd2dc3ae3ed19afe460fcbad0/python-ldap-3.2.0.tar.gz
Requirement already satisfied: pyasn1>=0.3.7 in /opt/alerta/lib/python3.6/site-packages (from python-ldap) (0.4.6)
Requirement already satisfied: pyasn1_modules>=0.1.5 in /opt/alerta/lib/python3.6/site-packages (from python-ldap) (0.2.6)
Building wheels for collected packages: python-ldap
  Building wheel for python-ldap (setup.py) ... done
  Created wheel for python-ldap: filename=python_ldap-3.2.0-cp36-cp36m-linux_x86_64.whl size=287552 sha256=97355eca619af9d45b4a5fe33a1433410a450c15569ebef8f25f966ef531d517
  Stored in directory: /root/.cache/pip/wheels/48/dd/0b/a06d1baf6575ad4520fc1fcf5bd96b493cd89670fdf6ade224
Successfully built python-ldap
Installing collected packages: python-ldap
Successfully installed python-ldap-3.2.0
[root@hostname ~]# /opt/alerta/bin/pip install python-ldap
Requirement already satisfied: python-ldap in /opt/alerta/lib/python3.6/site-packages (3.2.0)
Requirement already satisfied: pyasn1>=0.3.7 in /opt/alerta/lib/python3.6/site-packages (from python-ldap) (0.4.6)
Requirement already satisfied: pyasn1-modules>=0.1.5 in /opt/alerta/lib/python3.6/site-packages (from python-ldap) (0.2.6)
[root@hostname ~]#
