### ISSUE TITLE
Question: Does Alerta Support connecting to MongoDB with a DNS Seedlist connection string.

### ISSUE THREAD

**Issue by PMDubuc** [alerta/alerta#1069]
We're using Alerta 6.0.1 with MongoDB.  MongoDB supports the DNS Seedlist Connection Format which allows connections to the Mongo cluster without have to specify the list of nodes in the connect string.  When we try doing it this way, we get an error in the Alerta logs saying that it's trying to load a module named "mongodb+srv" which is the connection string prefix for this type of connection.  Does a newer version of Alerta support this type of connection, or is there a way that be done with Alerta 6.0.1?

https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format

**Comment by satterly** [comment]
I've just added support for DNS seedlist connection strings to Alerta. It will be available as 7.4.0 to be released in the next few days.

However, you could try "monkey" patching your version as it's only 2 lines of code...
https://github.com/alerta/alerta/blob/af2d8fb7c9767874ee4b1b6e18592ff458734792/alerta/database/base.py#L21-L22

**Comment by PMDubuc** [comment]
Thanks!
