### ISSUE TITLE
Multi-level OIDC_ROLE_CLAIM and OIDC_GROUP_CLAIM

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#1073]
**Is your feature request related to a problem? Please describe.**
I use Keycloak as OIDC provider and want to use OIDC_GROUP_CLAIM and OIDC_ROLE_CLAIM. But Keycloak reponds with a multi-level claim structure which is currently not possible to use.
```json
{
  "name": "Me",
  "email": "me@example.com",
  "realm_access": {
    "roles": [
      "just_some_generic_roles"
    ]
  },
  "resource_access": {
    "RANDOM_OAUTH2_CLIENT_ID": {
      "roles": [
        "my_role_1",
        "my_role_2"
      ]
    }
  }
}
```

**Describe the solution you'd like**
According to the data above I need something like `resource_access/RANDOM_OAUTH2_CLIENT_ID/roles` as `OIDC_GROUP_CLAIM` and `OIDC_ROLE_CLAIM`.
This leads to `data.get('resource_access').get('RANDOM_OAUTH2_CLIENT_ID').get('roles')` at https://github.com/alerta/alerta/blob/master/alerta/auth/oidc.py#L123.

**Describe alternatives you've considered**
I'm not the supporter of the Keycloak server so it's impossible to have the alternative on the server side.

**Comment by escoand** [comment]
I've found a relatively simple solution for it: https://stackoverflow.com/a/36131992
```python
from functools import reduce
reduce(lambda d, k: d.get(k) if d else None, ['resource_access', 'RANDOM_OAUTH2_CLIENT_ID', 'roles'], data)
# ['my_role_1', 'my_role_2']
```

**Comment by satterly** [comment]
Are you sure your Keycloak server is configured correctly? See test case for expected payload format...
```
        {
          "sub": "4eeaa122-08d8-47bc-b6d0-010481c055c5",
          "email_verified": true,
          "roles": [
            "create-realm",
            "devops",
            "alerta-project",
            "admin"
          ],
          "name": "Nicholas Satterly",
          "preferred_username": "nsatterl",
          "given_name": "Nicholas",
          "family_name": "Satterly",
          "email": "nick@alerta.dev"
        }
```
https://github.com/alerta/alerta/blob/master/tests/test_providers.py#L1241

**Comment by escoand** [comment]
Don't know if this is correct or not. But it's what the server gives me.

**Comment by satterly** [comment]
You need to create a role and group mapper in the keycloak server configuration. For example ...
>Add the following mapper under the Mappers tab:
Name: role memberships
Mapper type: User Realm Role
Multivalued: ON
Token Claim Name: roles
Claim JSON type: String
Add to userinfo: ON

See http://docs.alerta.io/en/latest/authentication.html#keycloak-oauth2

**Comment by escoand** [comment]
As I said I'm not the supporter for the Keycloak server. It's supported by a different department and has hundreds of other users. Sadly, I don't expect too much reaction to such requests.

**Comment by satterly** [comment]
I'm sorry but I can't be expected to rewrite Alerta just because your IT department is slow to respond to work requests.

You could write a proxy to intercept the response and reformat it, or you could just ask you IT department for a minor configuration change to Keycloak.

**Comment by satterly** [comment]
There's the possibility of using `jsonPath` to allow a specific JSON object to be extracted from a payload. https://goessner.net/articles/JsonPath/

This would make the `OIDC_GROUP_CLAIM` and `OIDC_ROLE_CLAIM` settings backwards compatible so for example "roles" would still extract the top-level attribute and for your situation something like "resource_access. RANDOM_OAUTH2_CLIENT_ID.roles" should work for you.

See https://pypi.org/project/jsonpath-ng/

**Comment by escoand** [comment]
Interestingly I can't see any roles in the userinfo response in alerta. The JSON above was generated with [keycloak-gatekeeper](https://github.com/keycloak/keycloak-gatekeeper) (/oauth/token endpoint) and the exact same OIDC client credentials.
Is there some parameter in the userinfo request missing?

**Comment by satterly** [comment]
Did you follow the instructions for creating an OpenID Connect client in Keycloak? As part of that you must create a mapper... See https://github.com/alerta/alerta/issues/785

**Comment by escoand** [comment]
The client configuration in Keycloak can't be the problem as it's the same as for keycloak-gatekeeper.

**Comment by satterly** [comment]
Did you create a mapper for the "roles" attribute, or not?

**Comment by escoand** [comment]
Yes, some kind of. I've a self service form where I can edit the role mapping. What at the end is configured in keycloak is out of sight for me.
But I can see the roles mapped to the token of the same client when debugged with keycloak-gatekeeper. Like the JSON in the initial post.

**Comment by satterly** [comment]
You can find the JWT in any API XHR request. Using the javascript console go to the Network tab and filter on "XHR" requests. Choose Headers and then find the "Authorization" header. The bearer token is the JWT (highlighted in blue below).

<img width="1161" alt="Screenshot 2019-09-10 at 20 50 09" src="https://user-images.githubusercontent.com/615057/64641701-08465080-d40d-11e9-854d-787b529dccf1.png">


Copy and paste the token starting from "ey" into this website to decode the JWT... https://jwt.io and you should get something like this ...

<img width="1150" alt="Screenshot 2019-09-10 at 20 54 06" src="https://user-images.githubusercontent.com/615057/64641779-2744e280-d40d-11e9-9dae-3b4c6a9a57d5.png">

**Comment by satterly** [comment]
Thanks for letting me know about the invalid scopes. #1075
