### ISSUE TITLE
Requests to /management/status redirected to /alerts

### ISSUE THREAD

**Issue by travis-bear** [alerta/alerta#1077]
**Issue Summary**
Doesn't seem to be a way to get data from the /management/status endpoint.  Requests are just redirected to /alerts

**Environment**
- OS: Linux
- API version: 7.3
- Deployment:  Docker
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: MongoDB

- Server config:
  Auth enabled? No
  Auth provider? n/a
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 7.3]
- CLI version: [eg. 7.3]

**To Reproduce**
1. Go to http://alerta.<redacted>.com/management/status

Expected: prometheus metrics as documented at https://docs.alerta.io/en/latest/deployment.html#management-metrics

Actual: redirect to alerts, no metrics available

**Comment by satterly** [comment]
If you're using Docker the API endpoint is at `/api` so in your instance try http://alerta..com/api/management/status

**Comment by travis-bear** [comment]
It works!
