### ISSUE TITLE
Where default LDAP password should be added

### ISSUE THREAD

**Issue by wmariuss** [alerta/alerta#1083]
I have LDAP setup to use credentials before do any query. So i saw in alerta v7.2.4 [code](https://github.com/alerta/alerta/blob/v7.2.4/alerta/auth/basic_ldap.py) there is no way to specify LDAP auth credentials, only for users if they are found.

Should I specify auth credentials on ldap.conf file?

Right now I have issue:

```
=> LDAPError - INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
```

I suppose this is because before do any query in LDAP this can not authenticate to LDAP server.

**Comment by wmariuss** [comment]
I am not talking about users from LDAP, i am talking about LDAP credentials server.

**Comment by satterly** [comment]
User credentials are used to bind to the LDAP server. If they succeed the user is authenticated. It's as simple as that.

**Comment by wmariuss** [comment]
I know. but the LDAP server has default auth credentials enabled, so before bind them, this must be authenticated.

**Comment by satterly** [comment]
You'd need to modify the code then. PR's welcome!

**Comment by wmariuss** [comment]
Ok, I will close the issue for now. 
I will take a look to python-ldap lib how it works and then i will open PR with the changes needed.
Thanks.

**Comment by wmariuss** [comment]
I came with an update for anyone who want to use alerta with LDAP (openldap). Of course there is no issue with 7.2.4 version, it's just using the simple bind with does not need any extra authorization like "ServiceAccount", a layer before doing a query for existing users on the LDAP server.
And to be honest i like this approach, it's simple and easily. All i had to do is:

```
LDAP_URL = "ldaps://x.x.x.x:636"
LDAP_DOMAINS = {
    'domain.net': 'cn=%s,ou=Users,dc=domain,dc=net'
}
```
