### ISSUE TITLE
pip3 install alerta

### ISSUE THREAD

**Issue by binhvcom** [alerta/alerta#1085]
I am using python 3.6
`pip 19.2.3 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)`
Install alerta with this command
`pip3 install alerta-server alerta --user`
But when i am using `alertad run`, i have this error
```
alertad run
alertad: command not found
```
OS: Ubuntu 18.04 (Virtual machine - proxmox)
DB: Postgres version 11
Am i missing something, maybe the config file ?

**Comment by satterly** [comment]
Is the directory where alertad was installed in your path?

**Comment by binhvcom** [comment]
yes, at ~/local/bin, alertad run command not found, but with ./alertad is ok.
- pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
Seem like it go for pymongo, but i already change the config 
```
cat ~/.alertad.conf 
DEBUG=True
DATABASE_URL=postgres://localhost:5432/test
```

**Comment by satterly** [comment]
The default location for server config is `/etc/alertad.conf`. if it is located somewhere else you need to define an environment variable called `ALERTA_SVR_CONF_FILE`

See http://docs.alerta.io/en/latest/configuration.html

**Comment by binhvcom** [comment]
ah, okay, it's work, thanks you so much.
