### ISSUE TITLE
#1079 broke deleting blackouts

### ISSUE THREAD

**Issue by hasso** [alerta/alerta#1089]
**Issue Summary**

#1079 broke deleting blackouts.

**Environment**
- OS: Linux
- API version: 7.4.1
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No

- web UI version: 6.8.1
- CLI version: 7.4.0

**To Reproduce**
1. Update to 7.4.1.
2. Create a blackout.
3. Try to delete created blackout.
4. Nothing happens and an error is logged:
```2019-10-02T09:18:31.152798+00:00 monitor alertad: 2019-10-02 09:18:31,151 alerta.app[33056]: [ERROR] argument of type 'NoneType' is not iterable request_id=a7959d3a-cb7b-4a23-801f-4efe123a610f ip=192.168.1.1#012Traceback (most recent call last):#012  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/opt/alerta/lib64/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function#012    resp = make_response(f(*args, **kwargs))#012  File "/opt/alerta/lib64/python3.6/site-packages/alerta/auth/decorators.py", line 74, in wrapped#012    return f(*args, **kwargs)#012  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/response.py", line 19, in decorated#012    return func(*args, **kwargs)#012  File "/opt/alerta/lib64/python3.6/site-packages/alerta/views/blackouts.py", line 128, in delete_blackout#012    customers=g.customers, scopes=g.scopes, resource_id=blackout.id, type='blackout', request=request)#012  File "/opt/alerta/lib64/python3.6/site-packages/blinker/base.py", line 267, in send#012    for receiver in self.receivers_for(sender)]#012  File "/opt/alerta/lib64/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>#012    for receiver in self.receivers_for(sender)]#012  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/audit.py", line 68, in write_log_response#012    self._log_response(app, 'write', **kwargs)#012  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/audit.py", line 51, in _log_response#012    scopes, resource_id, type, request, **extra))#012  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/audit.py", line 111, in _fmt#012    'data': get_redacted_data(request),#012  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/audit.py", line 86, in get_redacted_data#012    if 'password' in data:#012TypeError: argument of type 'NoneType' is not iterable```

**Expected behavior**
Blackout should be deleted.

**Additional context**
Adding ```AUDIT_LOG_REDACT = False```to the configuration works around the issue.

**Comment by jjh74** [comment]
I think https://github.com/alerta/alerta/pull/1098 fixes deleting blackouts. Can you confirm @hasso ?

**Comment by satterly** [comment]
I'm pretty sure this is now fixed.
