### ISSUE TITLE
Alerts search based on date

### ISSUE THREAD

**Issue by pkvel01** [alerta/alerta#1096]
Alerta Gui should have an option to filter alerts based on date/time like i wanted to see only alerts of 06 Oct ? is this possible?

**Comment by satterly** [comment]
Is this what you mean?

<img width="301" alt="Screenshot 2019-10-10 at 12 07 30" src="https://user-images.githubusercontent.com/615057/66559921-8f92fb00-eb56-11e9-9a80-a2ae1090a74b.png">

It is available from version 7.3.0.

**Comment by pkvel01** [comment]
Yes thanks
