### ISSUE TITLE
Mailer not playing nice with expired alerts

### ISSUE THREAD

**Issue by davtex** [alerta/alerta#1097]
**Issue Summary**
I would expect alerta-mailer to send email when alert is expired or when expired alert is opened

**Environment**
- OS: RHEL6
- API version: 7.2.10
- Deployment: self-hosted
- For self-hosted, WSGI environment: apache/uwsgi

- Database: MongoDB

- Server config:
  Auth enabled? No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? N/A

- web UI version: 7.2.10
- CLI version: 7.2.10

**To Reproduce**
- let alert expire
(no email)
- reopen expired alert
(no email)

**Expected behavior**
Mail is sent in both scenarios.

**Additional context**

Reopening expired alerts:
- if alert is unlucky and auto-clear from Kapacitor does not arrive for some reason, no email is sent out since alert.repeat is true
- I can get around this by adding condition which checks previous alert status in alert history
- main issue that I have

Expiring open alerts:
- no email is sent when alert is expired
- I do not even see AMQP message
- not so important but nice to have

Would it perhaps be possible to also change severity to "OK" when alert is expired? That could fix both problems and would make sense in my setup, where I send alert continuously every X seconds, after which I send OK message. If there are no further alerts and no OK message, I assume alert is OK and OK message got lost.

I have put this in main repo since this is more of a Alerta feaure-request than alerta-contrib bug.

**Comment by satterly** [comment]
The `expired` status is precisely to cover the situation where you expect constant updates to alerts at regular intervals and then if you do not get an OK you assume there is no OK or it got lost, so you expired and clear out the alert.

Changing the severity to OK when an alert expires is an assumption that may make sense in your environment but not in most others. I suggest you create a plugin with a 'post receive' hook to check to see if alerts have been expired and then change the status to OK, if that's what you want.

Thanks for the feedback. Let me know if you need any more help on this.
