### ISSUE TITLE
Is documentation up-to-date for version 7.4?

### ISSUE THREAD

**Issue by PMDubuc** [alerta/alerta#1099]
We're upgrading from Alerta 6.0.1 to 7.4.1  Looking for documentation that covers 7.4, I see that the date seems current but the version still says 6.0?   Does this document and or the documentation on the web site apply to the latest version 7 changes?

Which is the best place to look?
https://buildmedia.readthedocs.org/media/pdf/alerta/latest/alerta.pdf
http://docs.alerta.io/en/latest/

**Comment by satterly** [comment]
The best place to look is the source code ;) The documentation is always out-of-date. I'm working through it now to update where I know it's wrong or someone has told me. It's a big job. Let me know if you have any problems and/or if you spot any documentation errors. Closing this for now.

**Comment by satterly** [comment]
Always refer to https://docs.alerta.io and if it what you need isn't there, it should be.
