### ISSUE TITLE
Event history - update time with seconds

### ISSUE THREAD

**Issue by pavleec** [alerta/alerta#1102]
Hi,

I would be great if alarm history will display the Update Time column with seconds - now it's only in HH:MM format which is a bit unreadable when we receive clear in the same minutte.

![obraz](https://user-images.githubusercontent.com/12551929/66826853-b635a500-ef4d-11e9-8f9b-6bce11360f74.png)

Regars,
PaVliK

**Comment by satterly** [comment]
Change the `DATE_FORMAT_MEDIUM_DATE` to include seconds...

```
DATE_FORMAT_MEDIUM_DATE = 'ddd D MMM HH:mm:ss'  # eg. Tue 9 Oct 09:24:16
```

<img width="1062" alt="Screenshot 2020-01-18 at 23 42 54" src="https://user-images.githubusercontent.com/615057/72671535-5ff46880-3a4c-11ea-8156-a8c1af4fb92f.png">
