### ISSUE TITLE
Alert text field getting overwritten in history

### ISSUE THREAD

**Issue by umangdhaw** [alerta/alerta#1105]
Hi,
We are migrating from a very old version of alerta to the latest version (7.4.1), and noticed that the text field in alert history [gets overwritten](https://github.com/alerta/alerta/blob/2cb00a7b9b7d61e3f41701ce9bde76392371b9fa/alerta/models/alert.py#L341) with values like 'new alert', 'correlated alert', etc. Trying to understand why this is implemented this way? We send custom text from out application as payload and would like to have that available in alert history.

Any help/suggestions would be appreciated. Thanks!

text field on alert details page - 
![Screenshot 2019-10-22 at 11 03 53](https://user-images.githubusercontent.com/40692213/67272294-960d6500-f4bc-11e9-8a67-fdd959709aff.png)

text field on history page - 
![Screenshot 2019-10-22 at 11 08 19](https://user-images.githubusercontent.com/40692213/67272332-a32a5400-f4bc-11e9-8f57-4de3b03d007e.png)

**Comment by satterly** [comment]
This was added/changed to help me (and others) understand the lifecycle of a particular alert. This can get quite complicated with duplicate alerts. For example, if the status has changed the text will say ...
```
                text='duplicate alert (with status change)',
                change_type='status',
```
... and if only the value has changed it will say ...
```
                text='duplicate alert (with value change)',
                change_type='value',
```

Why do you need custom alert descriptions available in the alert history?

**Comment by umangdhaw** [comment]
Our application directly reads the text field from history and displays it on the frontend. With the changes in #1192 I can confirm that the issue is resolved, thanks!
