### ISSUE TITLE
Alerts are not timing out

### ISSUE THREAD

**Issue by moix** [alerta/alerta#1107]
**Issue Summary**
Having a timeout setting of 10 minutes, alerts are not automatically expired 10 mins later after last received time.
In .conf file
```
ALERT_TIMEOUT = 600  # 10 minutes
```
**Environment**
- OS: Linux
- API version: 7.4.0
```
root@monitoring-alerta-server alerta# /home/alertaio/latest/venv/bin/alerta --config-file /etc/alertacli.conf version
alerta 7.4.0
alerta client 7.4.0
requests 2.22.0
click 7.0
```
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? No
/config output
```
{  
   "actions":[  
      "createIssue",
      "updateIssue"
   ],
   "alarm_model":{  
      "colors":{  
         "highlight":"skyblue",
         "severity":{  
            "critical":"red",
            "indeterminate":"lightblue",
            "ok":"green",
            "unknown":"grey",
            "warning":"yellow"
         },
         "text":"black"
      },
      "defaults":{  
         "normal_severity":"normal",
         "previous_severity":"indeterminate",
         "status":"open"
      },
      "name":"Alerta 7.4.0",
      "severity":{  
         "cleared":2,
         "critical":0,
         "indeterminate":5,
         "normal":2,
         "ok":2,
         "unknown":3,
         "warning":1
      },
      "status":{  
         "ack":"C",
         "assign":"B",
         "blackout":"E",
         "closed":"F",
         "expired":"G",
         "open":"A",
         "shelved":"D",
         "unknown":"H"
      }
   },
   "audio":{  
      "new":null
   },
   "auth_required":true,
   "aws_region":"us-east-1",
   "azure_tenant":"common",
   "client_id":null,
   "cognito_domain":null,
   "colors":{  
      "highlight":"skyblue",
      "severity":{  
         "critical":"red",
         "indeterminate":"lightblue",
         "ok":"green",
         "unknown":"grey",
         "warning":"yellow"
      },
      "text":"black"
   },
   "columns":[  
      "severity",
      "status",
      "lastReceiveTime",
      "timeoutLeft",
      "duplicateCount",
      "customer",
      "environment",
      "service",
      "resource",
      "event",
      "value"
   ],
   "customer_views":false,
   "dates":{  
      "longDate":"d/M/yyyy h:mm:ss.sss a",
      "mediumDate":"EEE d MMM HH:mm",
      "shortTime":"HH:mm"
   },
   "debug":true,
   "email_verification":false,
   "endpoint":"http://api.monitoring-alerta.internal:5050/api",
   "github_url":"https://github.com",
   "gitlab_url":"https://gitlab.com",
   "indicators":{  
      "queries":[  
         {  
            "query":[  
               [  
                  "environment",
                  "Production"
               ]
            ],
            "text":"Production"
         },
         {  
            "query":[  
               [  
                  "environment",
                  "Development"
               ]
            ],
            "text":"Development"
         },
         {  
            "query":{  
               "q":"event:Heartbeat"
            },
            "text":"Heartbeats"
         },
         {  
            "query":"group=Misc",
            "text":"Misc."
         }
      ],
      "severity":[  
         "critical",
         "major",
         "minor",
         "warning",
         "indeterminate",
         "informational"
      ]
   },
   "keycloak_realm":null,
   "keycloak_url":null,
   "oidc_auth_url":null,
   "provider":"ldap",
   "refresh_interval":5000,
   "severity":{  
      "cleared":2,
      "critical":0,
      "indeterminate":5,
      "normal":2,
      "ok":2,
      "unknown":3,
      "warning":1
   },
   "signup_enabled":false,
   "site_logo_url":"",
   "sort_by":"lastReceiveTime",
   "tracking_id":null
}
```

- web UI version: 7.4.1
- CLI version: 7.4.0

**To Reproduce**
2. Click on '....' or Run '...'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
I'll expect that alerts are automatically expired and removed from alerta after the next housekeeping task once the timeout period has passed

**Screenshots**
Attached screenshots of alerts with timetout 0 last received 19hours ago

**Additional context**
housekeeping is set as a cronjob running every 5 mins, no errors from it

![Screenshot from 2019-10-24 10-50-37](https://user-images.githubusercontent.com/569132/67470543-3646c380-f64e-11e9-80f7-4eec297be243.png)
![Screenshot from 2019-10-24 11-04-46](https://user-images.githubusercontent.com/569132/67470547-39da4a80-f64e-11e9-8d63-8bcb4c45244b.png)

Thanks!

**Comment by moix** [comment]
They have expired now after 24hours passed so seems the ALERT_TIMEOUT setting in the .conf is not applying, am I setting it correctly?

**Comment by jonhammer** [comment]
Alerta will not housekeep OPEN or ACK'd Alerts. 

Your OPEN alerts should change to expired after the timeout. Not sure why that isn't happening.

I personally modified these lines to expire ACK'd alerts, since I'm not sure why you wouldn't want to (mongo/postgres), by adding "ack" to them:
https://github.com/alerta/alerta/blob/master/alerta/database/backends/mongodb/base.py#L1573
https://github.com/alerta/alerta/blob/master/alerta/database/backends/postgres/base.py#L1222

Also note after the expiry period there is an additional time period (I think two hours is default) that must pass before they will be deleted.

**Comment by moix** [comment]
Hi @jonhammer , yes I know about ack alerts but I was referring to those open with timeout 0.
Checking the code you shared I see a few lines below the query to expire alerts is there (postgres I use):
https://github.com/alerta/alerta/blob/master/alerta/database/backends/postgres/base.py#L1240
Sorry I don't know much about that sql syntax, could be related that timezone is hardcoded to utc? or are all references in database set to utc and should work? my servers are normally in EST

**Comment by satterly** [comment]
Are you saying you set the alert `timeout` attribute to "0"? If so, they won't timeout. `ALERT_TIMEOUT` server configuration is just the default value assigned if none is set in the alert. If you set timeout to "0" then by design those alerts are considered important and should not be subject to housekeeping rules.

**Comment by moix** [comment]
Hi, no I don't set specific timeout for alerts and leave the default one to apply:
ALERT_TIMEOUT = 600  # 10 minutes

Actually if I do a test and send an alert, the timeout is set from 10 mins and decreasing till 00:00 but once it reach that doesn't expire automatically

**Comment by satterly** [comment]
Are you actually running the house keeping script?

**Comment by moix** [comment]
yes it doesn't raise any error. But house keeping script is to clean not open alerts, correct?
Does the expiration happen at the same moment?

I'm doing some tests, can it be related to alerts that were ackd at any point in the history? e.g.:
- alert is received --> open
- user ack it either in alerta web or the ack is received from external source
- the alert keeps open
- the alert ack is removed by same user or differently (or maybe automatically by external source)
- alert timeouts but expire doesn't work?

will update with my findings in case I can reproduce exact case

**Comment by moix** [comment]
sorry for late response on this but needed the time to setup properly and test it in deep. Indeed we were not registering alerts correctly and they were left in wrong status in database.
We have fixed the integration to alerta to trigger proper action to alerts and housekeeping is working as expected.
sorry can be closed now.

**Comment by astir1978** [comment]
Hi,

I have same problem that alerts are not changed from open state to exprred. @moix do you remember what was incorrect with registering alerts?

**Comment by satterly** [comment]
We ask users to not comment on closed/resolved issues. If you have an issue please raise a new bug report and ensure you provide as much information as possible relevant to your particular issue and environment.
