### ISSUE TITLE
Does alerta support query by attributes?

### ISSUE THREAD

**Issue by junhui** [alerta/alerta#1108]
i got 500 error, am i wrong? 

GET /api/alerts?api-key=xxxx&q=attributes.ruleId:160

`
{
"code": 500,
"errors": [
"Traceback (most recent call last):\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/venv/lib/python3.6/site-packages/flask_cors/decorator.py\", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File \"/venv/lib/python3.6/site-packages/alerta/auth/decorators.py\", line 50, in wrapped\n    return f(*args, **kwargs)\n  File \"/venv/lib/python3.6/site-packages/alerta/models/metrics.py\", line 259, in wrapped\n    response = f(*args, **kwargs)\n  File \"/venv/lib/python3.6/site-packages/alerta/utils/response.py\", line 19, in decorated\n    return func(*args, **kwargs)\n  File \"/venv/lib/python3.6/site-packages/alerta/views/alerts.py\", line 310, in search_alerts\n    severity_count = Alert.get_counts_by_severity(query)\n  File \"/venv/lib/python3.6/site-packages/alerta/models/alert.py\", line 504, in get_counts_by_severity\n    return db.get_counts_by_severity(query)\n  File \"/venv/lib/python3.6/site-packages/alerta/database/backends/postgres/base.py\", line 483, in get_counts_by_severity\n    return {s.severity: s.count for s in self._fetchall(select, query.vars)}\n  File \"/venv/lib/python3.6/site-packages/alerta/database/backends/postgres/base.py\", line 1292, in _fetchall\n    cursor.execute(query, vars)\n  File \"/venv/lib/python3.6/site-packages/psycopg2/extras.py\", line 319, in execute\n    return super(NamedTupleCursor, self).execute(query, vars)\npsycopg2.errors.UndefinedColumn: column \"attributes.ruleId\" does not exist\nLINE 3:              WHERE \"attributes.ruleId\" ILIKE '%160%'\n                           ^\n\n"
],
"message": "column \"attributes.ruleId\" does not exist\nLINE 3:              WHERE \"attributes.ruleId\" ILIKE '%160%'\n                           ^\n",
"requestId": "55a804d272385e8b16d20e8cbcfba36c",
"status": "error"
}
`

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by satterly** [comment]
Yes, but use the query API not the query string parser. That is, do this instead...
```
% http ':8080/alerts?attributes.ruleId=160'
```
