### ISSUE TITLE
Improve Prometheus Heartbeat handling (DeadMansSwitch)

### ISSUE THREAD

**Issue by marcofl** [alerta/alerta#1110]
# Problem
Heartbeats, especially in combination with the prometheus and heartbeats plugin could be very powerful as you can easily test the prometheus -> alertmanager -> alerta chain of components. 

Unfortunately in a setup where you have multiple prometheus instances running on multiple kubenretes clusters, spread across all your customers, a few things are missing to actually make this usable:
- [x] Heartbeats don't show meta data like: customer, service, environment, etc. 
- [x] when alertmanager sends the label service with an alert, alerta throws an 400 error and does not handle the alert
- [x]  there is no indicator in the heartbeat WebUI view, that shows expired heartbeats (and you cannot filter on expired heartbeats)
- [x]  no way to map heartbeat tags (labels) to the alerts that are created from the heartbeat when it expires, for example even if there is a customer label in the sent in alert, it's neither shown in the heartbeats list nor is it added to the alert which is created later.

# Solution / Suggestion
- [x]  Have a defined mapping of heartbeat tags to fields of the alert that is created from heartbeats (most importantly: severity, customer, environment, service)
- [x]  pass all other labels from the prometheus alert 1:1 into the heartbeat tags, then when creating the alert from a heartbeat, pass the tags 1:1 into the alert
- [x]  Show similar meta information in heartbeats WebUI view as for normal alerts (customer, environment, service, etc.)

**Comment by satterly** [comment]
Thanks for this. These are all good suggestions and are coupled with real-world use cases. I'll put these enhancements on the backlog. I can't promise I'll get a chance to look at them any time soon but at least you've captured the requirements.  👍

**Comment by satterly** [comment]
An `attributes` field has been added to heartbeats that can be populated with values for `environment`, `service`, `severity` and `group` which will now be used by the `alerta` client script when generating alerts from slow or stale heartbeats.

**Comment by satterly** [comment]
The web UI has been enhanced to show metadata such as `environment`, `service` etc that can now be passed as `attributes` with a heartbeat. Also the heartbeat status has been added to the heartbeats view in the web UI (I'm surprised this wasn't in the original version). And lastly, it is now possible to filter on heartbeat status by using toggle buttons to filter on heartbeats with "OK", "Slow" or "Expired" status. See alerta/alerta-webui#268

**Comment by satterly** [comment]
Prometheus labels that don't match any Alerta attribute are added as tags in the incoming webhook, and when converting alerts to heartbeats the plugin takes any alert tags and makes them heartbeat tags. See https://github.com/alerta/alerta/blob/master/alerta/webhooks/prometheus.py#L52 and https://github.com/alerta/alerta/blob/master/alerta/plugins/heartbeat.py#L22
