### ISSUE TITLE
The -i option of the Alerta 'history' command returns an error

### ISSUE THREAD

**Issue by naureensaba** [alerta/alerta#1119]
ALERTA

The Alerta 'history' command consists of an option '-i', which is basically used to filter out an alert depending on the specified id and provide the history for the same.

But when used the '-i' option with the 'history' command, it always throws an error as follows:

$ alerta history -i 57fb3117
Error: column reference "id" is ambiguous
LINE 5: AND (id LIKE '57fb3117%' OR last_receive_id LIKE '57fb3117%' ...
                     ^

**Comment by satterly** [comment]
Fixed by #1125
