### ISSUE TITLE
Question about custom plugin and untagging

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#1124]
**Issue Summary**
I try to tag and untag within a custom plugin. Tagging is working, but untagging not. Am I doing something wrong?

```python
    def take_action(self, alert, action, text, **kwargs):

        # mark for feedback
        if action == FEEDBACK_ACTION:
            alert.status = FEEDBACK_STATUS
            if FEEDBACK_TAG in alert.tags:
                alert.untag([FEEDBACK_TAG])
                text = FEEDBACK_LOG_REMOVE
            else:
                alert.tag([FEEDBACK_TAG])
                text = FEEDBACK_LOG

        # ...

        return alert, action, text
```

It's going into the right if branch but the untag isn't working.

**Environment**
- OS: Linux
- API version: 7.4.1
- Deployment: Docker

- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? OpenID
  Customer views? Yes

- web UI version: 7.4.1

**Comment by satterly** [comment]
I'm not sure what's wrong with your code. Within an action you can make synchronous calls to the database (ie use `alert.tag()` etc) however I would not encourage it. I would use an attribute instead of a tag and just set `alert.attribute['FEEDBACK'] = True` or `False`.

**Comment by escoand** [comment]
Found a solution but for the problem. Interestingly to remove the tag I need both lines, to add it either are working.

```python
            if FEEDBACK_TAG in alert.tags:
                alert.untag([FEEDBACK_TAG])
                alert.tags.remove(FEEDBACK_TAG)
            else:
                alert.tag([FEEDBACK_TAG])
                alert.tags.append(FEEDBACK_TAG)
```

**Comment by satterly** [comment]
Ok. Thanks for confirming. That seems like a bug. At the very least it's very confusing.

**Comment by escoand** [comment]
The sync methods alone seem not to work because the returned alert object (unchanged) overrides it again afterwards. I tried the same procedure with attributes and there the remove on the dict is enough.

**Comment by escoand** [comment]
@satterly Just tried to remove the synced call to `alert.untag([FEEDBACK_TAG])`. When leaving my `take_action` method the tag is gone. But the response to the client again shows it (version 8.0.0).

**Comment by satterly** [comment]
Now it is enough to use `append()` and `remove()` on the `tags` list and for the API to do the update. For exampe...

```
class TagPlugin(PluginBase):

    def pre_receive(self, alert, **kwargs):
        return alert

    def post_receive(self, alert, **kwargs):
        return alert

    def status_change(self, alert, status, text, **kwargs):
        return alert

    def take_action(self, alert, action, text, **kwargs):

        if action == 'toggle':
            if 'tagged' in alert.tags:
                alert.tags.remove('tagged')
                text = 'remove'
            else:
                alert.tags.append('tagged')
                text = 'add'

        return alert, action, text
```

**Comment by escoand** [comment]
Ok, to you have a planed date for the next release?

**Comment by satterly** [comment]
Either late this week or early next.
