### ISSUE TITLE
API keys without users

### ISSUE THREAD

**Issue by Samgarr** [alerta/alerta#1135]
**Is your feature request related to a problem? Please describe.**
There is no way how to generate API keys before LDAP user is logged in, because API keys are paired with users and this user does not exist before first login.
This issue make provisioning Alerta complicated.

**Describe the solution you'd like**
Separete API keys from users or provide way to create API keys without need to be logged in firstly.

**Describe alternatives you've considered**

**Additional context**
Please let me know if i can provide more context.

**Comment by satterly** [comment]
You don't explain why you want to create an API key for a user who hasn't logged in yet. That would be useful context. Thanks.

**Comment by Samgarr** [comment]
I'm need to use this API key for Prometheus Alertmanger which using webhook to send alerts to Alerta. All this is provisioned by Puppet and must be done without human interaction.

**Comment by satterly** [comment]
There is an admin command that Puppet can use for this already...
```
$ alertad key --help
Usage: alertad key [OPTIONS]

  Create an admin API key.

Options:
  -u, --username TEXT  Admin user
  -K, --key TEXT       API key (default=random UUID)
  --all                Create API keys for all admins
  --help               Show this message and exit.
```
Admin users are those listed in `ADMIN_USERS` server config.

If this doesn't work for your environment we need to understand why before I create another way of doing the same thing.

**Comment by Samgarr** [comment]
Yes, this command working for me without LDAP auth. I'll try this again with another clean installation of Alerta and come back with hopefully more informations.

**Comment by Samgarr** [comment]
Looks like i somehow messed up Alerta config. With clean install i'm able to get api keys for users in `ADMIN_USERS` with command:

`alertad key -u user_name -K tahV3geefieba8moo4fiThoo`

No human interaction needed. Sorry for the noise :)
