### ISSUE TITLE
Allowed domains not working

### ISSUE THREAD

**Issue by gabricar** [alerta/alerta#1141]
this is my setup under alertad.conf

AUTH_REQUIRED = 'true'
AUTH_PROVIDER = 'basic' 
ALLOWED_EMAIL_DOMAINS = 'mydomain.com'

When I tried to sing up a new user as test@mydomain.com I get a 403 response. Not much else in the logs.
I have also tried '@mydomain.com' and get the same result and '*mydomain.com' allows any domains. Please advise if this is a bug or I'm using the wrong format.

Docker logs:
ip=\- [\10/Feb/2020:20:37:18 +0000] "\POST /api/auth/signup HTTP/1.1" \403 \93 "\http://10.3.30.6/signup" "\Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
/web | /api/auth/signup | > POST /api/auth/signup HTTP/1.1

**Comment by satterly** [comment]
`ALLOWED_DOMAINS` is a list. See https://github.com/alerta/alerta/blob/master/alerta/settings.py#L71
