### ISSUE TITLE
Allow "admin" group name to be any user-defined list of groups

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#1146]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

/cc @maneamarius

**Comment by maneamarius** [comment]
We need to be able to give permissions on group-level, not user-level as it seems to be working now.
So that we can set any LDAP group (like 'operations') to have admin permissions in Alerta

**Comment by maneamarius** [comment]
thank you! This is a very useful feature.
