### ISSUE TITLE
To change severity of alerts from Grafana using alert rule tags

### ISSUE THREAD

**Issue by blcak** [alerta/alerta#1155]
**Is your feature request related to a problem? Please describe.**
Alerta receives all alerts from Grafana as major level, the only way to override this was to add severity variable in webhook url, but it is not helping as all alerts will get the same severity level

**Describe the solution you'd like**
Grafana supports alert rule tags which is sent in "alert" dictionary, as "tags" dictionary if we can use this variable then, we can easily define the severity for each alert using rule tags with key as "severity" and value as severity level eg. warning or critical. Can you please help in making this change in grafana webhook? 

This is how we are getting the data in Alerta when we pass the rule tag in Grafana alert.

{*****fullscreen&edit&tab=alert&panelId=8&orgId=1", "state": "alerting", "tags": {"severity": "warning"}, ***}

**Comment by satterly** [comment]
Yes, this is being discussed already. See https://github.com/alerta/alerta/issues/1091#issuecomment-542315583
