### ISSUE TITLE
Missing authorization Bearer token

### ISSUE THREAD

**Issue by EnzoAkira** [alerta/alerta#1163]
@satterly
**Issue Summary**
Accessing to API userinfo get `"message": "Missing authorization Bearer token"`

**Environment**
- OS: `Vagrant alerta-centos7`
- API version: `Alerta API 7.4.4`
- Deployment: `Vagrant`  (Modified to use Postgres 11)
- For self-hosted, WSGI environment: `apache/mod_wsgi`

- Database:  `Postgres`

- Server config:
  Auth enabled? No
  Auth provider? Basic
  Customer views? No

- web UI version: `7.4.4`
- CLI version: `alerta client 7.4.0`

**To Reproduce**
1. Use API (by browser or Postman)
2. Config Header with `Key demo-key`
3. Get 
```json
{
  "code": 401,
  "errors": null,
  "message": "Missing authorization Bearer token",
  "requestId": null,
  "status": "error"
}
```
**Context / Final objective**
I'm creating a plugin for Messagebird. 
1. I intend that a new critical alert arrive and a call is made. To get the number I want search if the users are in a group and get the number from the comment field.

2. When a existing alert change severity (not status) from critical to warning or critical to ok, a sms is send to a specific number with the same logic above.

**Comment by satterly** [comment]
Don't use `/userinfo` use `/user/:userid/attributes`.

**Comment by EnzoAkira** [comment]
> 
> 
> Don't use `/userinfo` use `/user/:userid/attributes`.

Thanks for quick response!
About that! I had test with this but this is what I get:
```json
{
  "code": 405,
  "errors": [
    "The method is not allowed for the requested URL."
  ],
  "message": "405 Method Not Allowed: The method is not allowed for the requested URL.",
  "status": "error"
}
```
Tested on Postman

**Comment by satterly** [comment]
Sorry I should have said... 
Don't use `/userinfo` use `/user/:userid` or `/user/:userid/groups` instead.

**Comment by EnzoAkira** [comment]
Thank you again.

With `/user/:userid/groups` - Worked
```json
{
  "groups": [
    {
      "count": 2,
      "href": "http://localhost/api/group/47e844d7-22c1-44ac-99ee-3ebadc5f3328",
      "id": "47e844d7-22c1-44ac-99ee-3ebadc5f3328",
      "name": "FireMaster",
      "text": ""
    }
  ],
  "status": "ok",
  "total": 1
}
```

With `/user/:userid` - the json message doesn't show any field with groups
```json
{
  "status": "ok",
  "total": 1,
  "user": {
    "attributes": {
      "prefs": {
        "dates": {
          "longDate": "ddd D MMM HH:mm",
          "mediumDate": "YYYY-MM-DD HH:mm:ss.SSS Z",
          "shortTime": "HH:mm:ss"
        },
        "displayDensity": "compact",
        "isDark": true,
        "isMute": true,
        "languagePref": "en",
        "refreshInterval": 2000,
        "rowsPerPage": 50,
        "timezone": "utc"
      }
    },
    "createTime": "2020-02-11T17:57:03.494Z",
    "domain": "XXXX.pt",
    "email": "bcruz@XXXXX.pt",
    "email_verified": true,
    "href": "http://localhost/api/user/4e753141-600b-4f95-bd8e-20ae378ae467",
    "id": "4e753141-600b-4f95-bd8e-20ae378ae467",
    "lastLogin": "2020-02-28T17:30:21.009Z",
    "login": "bcruz",
    "name": "Bruno Cruz",
    "roles": [
      "super admin"
    ],
    "status": "active",
    "text": "+351XXXXXXX",
    "updateTime": "2020-02-14T00:23:18.816Z"
  }
}
```
(some info redacted)

**Comment by satterly** [comment]
Yes users<=>groups is a many-to-many relationship so it has its own endpoint.
