### ISSUE TITLE
Review use of pop-ups during OIDC flow

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#1165]
**Issue Summary**

Most other integrations of Azure AD's OIDC I get redirected and then back. With Alerta's integration it's handled via a pop-up which is blocked by default on modern browsers and iOS Safari.
I can get around it by going to the browser's settings and enable pop-ups though.

**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: [eg. 6.8.1]
- Deployment: [eg. Docker, Heroku, AWS, GCloud, self-hosted]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: [eg. MongoDB, Postgres]

- Server config:
  Auth enabled? Yes/No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
2. Click on '....' or Run '...'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Screenshots**

**Additional context**

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by escoand** [comment]
When the popup was blocked by Firefox and then opened only once without giving permission to open popups automatically, the auth results in a loop and the popup never closes.

**Comment by satterly** [comment]
@escoand what Auth provider are you using?

**Comment by escoand** [comment]
OIDC / Keycloak

**Comment by satterly** [comment]
Pop-ups is the only supported callback method. See https://github.com/sahat/satellizer/issues/656

**Comment by olivluca** [comment]
The use of a pop-up depends on an alerta setting or on the provider (I'm using lemonldap)?
If the former, which setting should I use?

**Comment by olivluca** [comment]
Oh, now I get it, it's because alerta is a single page application and the popup is hardcoded [here](https://github.com/alerta/alerta-webui/blob/b57cfadc4f5c9440aa27192c5bbfe1e5e6104437/src/services/auth.ts#L106).
