### ISSUE TITLE
Add configurable port instead of hardcoding 8080

### ISSUE THREAD

**Issue by decentral1se** [alerta/alerta#1173]
**Is your feature request related to a problem? Please describe.**
I am using dokku.viewdocs.io/dokku to deploy (open source Heroku) (using https://github.com/alerta/docker-alerta) which uses the proxy ports plugin (see https://github.com/dokku/dokku/blob/master/docs/networking/port-management.md) by default which reads the `EXPOSE` definition of the Dockerfile and maps that port to Nginx proxying. Since 8080 is such a common port, this conflicts with other containers. Dokku doesn't easily allow to do the usual `-p 9090:8080` magic where you re-map the port. Hence, I need an application level port configuration.

**Describe the solution you'd like**
Have a configuration option to choose a new port so that I can override the Dockerfile and specify that new port with an `EXPOSE ....` definition.

**Describe alternatives you've considered**
Checked the docs... saw https://github.com/alerta/alerta/issues/178...

**Additional context**
Unsure.

**Comment by satterly** [comment]
This sounds like a fundamental flaw of the tool you are using. I suggest you create your own Dockerfile and expose a port number other than 8080 if you really have to.
