### ISSUE TITLE
Inconsistent behavior when querying by status

### ISSUE THREAD

**Issue by kafeinnet** [alerta/alerta#1207]
**Issue Summary**
If a query contains a filter by status along other filters, it must be in first position.

**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: 6.8.1
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi
- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No

- web UI version: 6.8.1
- CLI version: 6.8.1

**To Reproduce**

Here is the alert currently registered in alerta :
```
$ alerta query 
ID        LAST RECEIVED        SEVERITY    STATUS      DUPL  CUSTOMER    ENVIRONMENT    SERVICE     RESOURCE        GROUP    EVENT    VALUE    DESCRIPTION
--------  -------------------  ----------  --------  ------  ----------  -------------  ----------  --------------  -------  -------  -------  -------------
a248e18b  2020/04/21 14:19:01  warning     ack            0              Preproduction  mail-new-1  internet-bbb-1  Misc     cassé
```

If I query by severity and tags and status, the alert is returned despite its status.
```
$ alerta query -q "severity:(critical warning) AND tags:FSC00075 AND status:open"
ID        LAST RECEIVED        SEVERITY    STATUS      DUPL  CUSTOMER    ENVIRONMENT    SERVICE     RESOURCE        GROUP    EVENT    VALUE    DESCRIPTION
--------  -------------------  ----------  --------  ------  ----------  -------------  ----------  --------------  -------  -------  -------  -------------
a248e18b  2020/04/21 14:19:01  warning     ack            0              Preproduction  mail-new-1  internet-bbb-1  Misc     cassé
```

If I query by status then severity and tags (or tags and status), the alert is not returned.

```
$ alerta query -q "status:open AND severity:(critical warning) AND tags:FSC00075"                
id    lastReceiveTime    severity    status    duplicateCount    customer    environment    service    resource    group    event    value    text
----  -----------------  ----------  --------  ----------------  ----------  -------------  ---------  ----------  -------  -------  -------  ------
$ alerta query -q "status:open AND tags:FSC00075 AND severity:(critical warning)" 
id    lastReceiveTime    severity    status    duplicateCount    customer    environment    service    resource    group    event    value    text
----  -----------------  ----------  --------  ----------------  ----------  -------------  ---------  ----------  -------  -------  -------  ------
```

**Expected behavior**

The query should not have different behavior regarding the position of the terms.

**Comment by kafeinnet** [comment]
I forgot to specify but grouping the terms seems to do the trick.

```
$ alerta query -q '(tags:FSC00075 AND severity:(critical warning)) AND status:open'
id    lastReceiveTime    severity    status    duplicateCount    customer    environment    service    resource    group    event    value    text
----  -----------------  ----------  --------  ----------------  ----------  -------------  ---------  ----------  -------  -------  -------  ------
```

**Comment by satterly** [comment]
This is mentioned in the docs under the "Grouping" sub-section of the Query Parser Syntax page... https://docs.alerta.io/en/latest/api/query-syntax.html#grouping

So,  `A AND B AND C` is not supported but `A AND (B AND C)` or `(A AND B) AND C` should work. See the test here https://github.com/alerta/alerta/blob/master/tests/test_queryparser.py#L157

**Comment by kafeinnet** [comment]
Well, it is mentioned that we can group terms or clauses not that we must.

**Comment by satterly** [comment]
You're right, it is ambiguous. I based this syntax on Lucene query syntax and they are more explicit ... https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Grouping
I will update the docs to say "MUST" and not "CAN".

**Comment by kafeinnet** [comment]
OK, I fix the query on my side. Thanks for the help !

**Comment by satterly** [comment]
Docs updated ... https://docs.alerta.io/en/latest/api/query-syntax.html#grouping
