### ISSUE TITLE
404 errors after upgrade to 7.5.3

### ISSUE THREAD

**Issue by FieldofClay** [alerta/alerta#1215]
**Issue Summary**
I upgraded my instance from 7.5.1 to 7.5.2 and the web UI and python module stopped functioning. The server is reporting 404s on any action. I also tested with 7.5.3 and the error is still there. Rolling back to 7.5.1 works fine.

    127.0.0.1 - - [04/May/2020 19:15:45] "GET /config HTTP/1.0" 404 -
    127.0.0.1 - - [04/May/2020 19:16:19] "GET /config HTTP/1.0" 404 -
    127.0.0.1 - - [04/May/2020 19:18:48] "GET /config HTTP/1.0" 404 -
    127.0.0.1 - - [04/May/2020 19:19:55] "POST /alert HTTP/1.1" 404 -

**Environment**
- OS: Linux
- API version: 7.5.3
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx

- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? Local
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: 7.5.0
- CLI version: 7.5.0

**To Reproduce**
1. Upgrade to 7.5.3

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
Web UI loads, python module creates an alert.

**Additional context**
I am running Arch Linux, so this could also be related to the build process. However it doesn't look like the requirements have changed.

**Comment by satterly** [comment]
Ok, let me know the steps you follow to install. It's almost certainly your wsgi script. It should now be ...

```
from alerta import create_app
app = create_app()
```

**Comment by FieldofClay** [comment]
My wsgi.py is exactly that. I'm running your 7.5.3 which includes #1212. I applied #1214 and that didn't seem to make any difference. 

My standard install process is:
1. Download latest release
2. `python setup.py build`
3. `python setup.py install`

**Comment by satterly** [comment]
instead of running ...

    python setup.py

can you try using...

    pip install .

Using `pip` is far superior to the old method.

**Comment by satterly** [comment]
I've restored a link to the old wsgi file so you could try updating to 7.5.4 and that might fix it.

**Comment by FieldofClay** [comment]
I tried 7.5.4, still no change. I also updated the build process to use `pip install .` and had the exact same result. 

When starting >7.5.1 this is the output:

    May 06 10:37:38 hostname alertad[3289152]:  * Environment: production
    May 06 10:37:38 hostname alertad[3289152]:    WARNING: This is a development server. Do not use it in a production deployment.
    May 06 10:37:38 hostname alertad[3289152]:    Use a production WSGI server instead.
    May 06 10:37:38 hostname alertad[3289152]:  * Debug mode: off
    May 06 10:37:39 hostname alertad[3289152]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
    May 06 10:37:51 hostname alertad[3289152]: 127.0.0.1 - - [06/May/2020 10:37:51] "GET /config HTTP/1.0" 404 -
    May 06 10:39:35 hostname alertad[3289152]: 127.0.0.1 - - [06/May/2020 10:39:35] "GET /config HTTP/1.0" 404 -
    May 06 10:39:53 hostname alertad[3289152]: 127.0.0.1 - - [06/May/2020 10:39:53] "POST /alert HTTP/1.1" 404 -

7.5.1 starts very differently:

    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,475 - alerta.plugins[3301336]: DEBUG - Server plugin 'acked_by' found. [in /usr/lib/python3.8/site-packages/alerta/utils/plugin.py:34]
    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,479 - alerta.plugins[3301336]: DEBUG - Server plugin 'blackout' found. [in /usr/lib/python3.8/site-packages/alerta/utils/plugin.py:34]
    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,480 - alerta.plugins[3301336]: DEBUG - Server plugin 'heartbeat' found. [in /usr/lib/python3.8/site-packages/alerta/utils/plugin.py:34]
    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,481 - alerta.plugins[3301336]: DEBUG - Server plugin 'reject' found. [in /usr/lib/python3.8/site-packages/alerta/utils/plugin.py:34]
    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,482 - alerta.plugins[3301336]: DEBUG - Server plugin 'remote_ip' found. [in /usr/lib/python3.8/site-packages/alerta/utils/plugin.py:34]
    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,484 - alerta.plugins[3301336]: DEBUG - Server plugin 'pushover' found. [in /usr/lib/python3.8/site-packages/alerta/utils/plugin.py:34]
    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,486 - alerta.plugins[3301336]: DEBUG - Server plugin 'gotify' found. [in /usr/lib/python3.8/site-packages/alerta/utils/plugin.py:34]
    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,507 - alerta.plugins[3301336]: INFO -
    May 06 10:45:37 hostname alertad[3301336]:     Add originating IP address of HTTP client as an alert attribute. This information
    May 06 10:45:37 hostname alertad[3301336]:     can be used for debugging, access control, or generating geolocation data.
    May 06 10:45:37 hostname alertad[3301336]:     
    May 06 10:45:37 hostname alertad[3301336]:  [in /usr/lib/python3.8/site-packages/alerta/plugins/__init__.py:17]
    May 06 10:45:37 hostname alertad[3301336]: 2020-05-06 10:45:37,508 - alerta.plugins[3301336]: INFO - Server plugin 'remote_ip' loaded. [in /usr/lib/python3.8/site-packages/alerta/utils/plugin.py:42]
    ...

Full log is on pastebin: [https://pastebin.com/nbJ4uvqW](https://pastebin.com/nbJ4uvqW)

**Comment by satterly** [comment]
What config and commands do you use to run Alerta?

**Comment by FieldofClay** [comment]
I run it with `alertad run`

Config:

    #alertad configuration
    DEBUG = True
    BASE_URL = '/api'
    USE_PROXYFIX = True
    LOG_HANDLERS = ['console', 'file']
    LOG_FILE = '/var/log/alertad/alertad.log'
    LOG_MAX_BYTES = 5*1024*1024  # 5 MB
    LOG_BACKUP_COUNT = 2
    LOG_FORMAT = 'verbose'
    DATABASE_URL = 'mongodb://localhost:27117'
    DATABASE_NAME = 'monitoring'
    CORS_ORIGINS = [
            'http://localhost',
            'http://localhost:8000',
            'http://IPADDR:8000',
            'https://my.domain.name'
    ]
    ALLOWED_ENVIRONMENTS = [ 'Production' ]
    ADMIN_USERS = ['me']
    AUTH_REQUIRED = True 
    SIGNUP_ENABLED = False
    PLUGINS = ['remote_ip', 'reject', 'heartbeat', 'blackout']

**Comment by satterly** [comment]
I've discovered a bug in the `run` command which explains what you are seeing. However you shouldn't run Flask apps like that in production. The `run` command is for development use only. I'll fix the bug but you should look into running Alerta as a WSGI application. See https://docs.alerta.io/en/latest/deployment.html

If you really must run Alerta from the command line you can use `flask run` instead of `alertad run` -- this assumes you have downloaded the source code and run `python setup.py install`.

**Comment by FieldofClay** [comment]
This isn't a production instance, I only use it for testing packages.

`flask run` works fine. Thanks for your help.
