### ISSUE TITLE
Not able to see the logs and alerts 

### ISSUE THREAD

**Issue by ChaitanyaManthena** [alerta/alerta#1222]
Hi Team,
I installed the below version, the process is running but not able to neither alerta logs nor alerts in UI. But created collection in mongodb, the same is working well in alerta server 7.4.5 & aleta 7.4.4. I request you to have a look and let me know if some thing more should i do for the latest version.

alerta            7.5.0
alerta-prometheus 5.4.0
alerta-server     7.5.4

[user@xxxxxxxx alerta]$ sudo /usr/local/bin/python3.7 /usr/local/bin/alertad run --port 8888 --host 0.0.0.0 &
[1] 6819
[user@xxxxxxxx alerta]$  * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0.0:8888/ (Press CTRL+C to quit)

able to listen the port and process running too
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      12303/python3.7

But from browser getting the below error:

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

From Alerta WEB UI getting below error
ERROR: Failed to connect to Alerta API due to missing or invalid config.json file

**Comment by ChaitanyaManthena** [comment]
Hi Team,
I updated the below conf in alertad.conf, still didn't able to generated logs.

DEBUG = True
BASE_URL = '/api'
LOG_HANDLERS = ['file']
LOG_FILE = '/opt/alerta/logs/alerta.log'
LOG_MAX_BYTES = 5*1024*1024  # 5 MB
LOG_BACKUP_COUNT = 2
LOG_FORMAT = 'verbose'

**Comment by ChaitanyaManthena** [comment]
Hi Team,
Is it possible to install older version alerta server 7.4.5 & aleta 7.4.4 and test it out, since those are working as expected in other servers

**Comment by satterly** [comment]
Yes, but you didn't fill in the issue template so I don't know how you installed it in the first place so can't advise on how to upgrade.

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by ChaitanyaManthena** [comment]
Hi Satterly,
Thank you for your quick response, I installed the alerta-server and alerta in past with 7.4.4 which is working fine. when i start the alertad run it created the logs and able to see the alerta ui / alerts. But when i installed alerta yesterday it is newer version 7.5.0  neither generating logs as mentioned in /etc/alertad.conf not viewing the api (localhost:8080/api). 

I request you to check and let me know is there any additional configuration needed to do in latest version or is it possible to install older version 7.4.4 as it is working as expected.

**Comment by satterly** [comment]
You still haven't told me how you installed Alerta. There are literally [dozens of ways people install Alerta](https://docs.alerta.io/en/latest/deployment.html#real-world-examples). Until I know I can't help you.

**Comment by ChaitanyaManthena** [comment]
Hi Satterly,
My apologies, i installed python 3.7 and mogodb. placed config file in /etc/alertad.conf and run the below command. Please let me know if you need more info

sudo /usr/local/bin/python3.7 /usr/local/bin/alertad run --port 8080 --host 0.0.0.0 &

**Comment by ChaitanyaManthena** [comment]
Hi Satterly,
Here is the alertad.conf attaching for reference.

DEBUG = True
SECRET_KEY = 'changeme'
BASE_URL = '/api'
USE_PROXYFIX = False
LOG_HANDLERS = ['file']
LOG_FILE = '/opt/alerta/alertad.log'
LOG_MAX_BYTES = 5*1024*1024  # 5 MB
LOG_BACKUP_COUNT = 2
LOG_FORMAT = 'verbose'
DATABASE_URL = 'mongodb://hostname:27017'
DATABASE_NAME = 'monitoring'
DATABASE_RAISE_ON_ERROR = False

**Comment by satterly** [comment]
How did you deploy the API and web UI? Docker, nginx/wsgi, Apache/wsgi, Heroku, AWS, GCP etc

**Comment by ChaitanyaManthena** [comment]
I deployed by nginx/wsgi

**Comment by satterly** [comment]
So how did you install the Alerta Python package? Pip or git clone? (This would have been quicker and easier if you had just filled in the issue template)

**Comment by ChaitanyaManthena** [comment]
Hi Satterly,
I am really sorry, i installed by pip.

**Comment by ChaitanyaManthena** [comment]
i followed the below and mentioning for reference 
https://devopstales.github.io/home/alerta-on-centos8/

**Comment by satterly** [comment]
So just use pip to install the version you want. Or am I missing something?

**Comment by satterly** [comment]
Why didn't you include that link before? :confused:

**Comment by ChaitanyaManthena** [comment]
May 16 07:31:56 host alertad[17793]: WSGI app 0 (mountpoint='/api') ready in 1 seconds on interpreter 0x199bc60 pid: 17793 (default app)
May 16 07:31:56 host alertad[17793]: *** uWSGI is running in multiple interpreter mode ***
May 16 07:31:56 host alertad[17793]: spawned uWSGI master process (pid: 17793)
May 16 07:31:56 host alertad[17793]: spawned uWSGI worker 1 (pid: 17804, cores: 1)
May 16 07:31:56 host alertad[17793]: spawned uWSGI worker 2 (pid: 17805, cores: 1)
May 16 07:31:56 host alertad[17793]: spawned uWSGI worker 3 (pid: 17806, cores: 1)
May 16 07:31:56 host alertad[17793]: spawned uWSGI worker 4 (pid: 17807, cores: 1)
May 16 07:31:56 host alertad[17793]: spawned uWSGI worker 5 (pid: 17808, cores: 1)

**Comment by satterly** [comment]
So what was the solution? I just spent 3 hours trying to help you with this and now you close the issue without any explanation.

**Comment by ChaitanyaManthena** [comment]
I am still not able to see alerta logs or alerta UI.

**Comment by satterly** [comment]
Why'd you close the issue then? Move this thread to gitter, please.
