### ISSUE TITLE
Errors in WebUI v.7.5.0 with api v.7.5.1 when adding notes to an alert detail

### ISSUE THREAD

**Issue by iv0001** [alerta/alerta#1224]
**Issue Summary**
The steps are the following.
Select an alert, it shows the detailed alert, I click on add note. I confirm with enter and it shows a vuetify handled error (v-alert - '_AppCtxGlobals' object has no attribute 'user' (500) ) and the note is not added.
"

**Environment**
- Docker build from  https://github.com/alerta/docker-alerta  Dockerfile
- API version: [7.5.1]
- web UI version: [7.5.0]
- Database: [MongoDB]
- Server config: Without Config , default
alertad.conf
cat of file.

$ cat alertad.conf 
SECRET_KEY = 'jKYtInU!hpvjSSwK0%*7qEaAIf=(bW$4'

- CLI version: [7.5.1]

**To Reproduce**
1. Go to 'Alert Detail'
2. Click on 'Add Note'
3. Fill Note
4. Press enter
5. See error (include command output)
	red alert console '_AppCtxGlobals' object has no attribute 'user' (500) 

Thanks

**Comment by satterly** [comment]
This was fixed by #1198. I suggest you just upgrade.
