### ISSUE TITLE
Document about Azure AD support

### ISSUE THREAD

**Issue by zhiweiv** [alerta/alerta#1225]
alerta seems support Azure AD, I found PR https://github.com/alerta/alerta/pull/846/files. Is any document about how to configure this in alerta?

It is not in current guide yet: https://docs.alerta.io/en/latest/authentication.html.

**Comment by satterly** [comment]
Fixed by alerta/alerta-docs#2bdb94228de55cf51590c5da118f5e11ba298684

See https://docs.alerta.io/en/latest/configuration.html#azure-active-directory-auth-settings and https://docs.alerta.io/en/latest/authentication.html#azure-active-directory
