### ISSUE TITLE
Report generation in alerta

### ISSUE THREAD

**Issue by bunboy09** [alerta/alerta#1227]
**Issue Summary**
I am unable to pull last 10 days alerts .. i want to list all alerts coming from different sources. it may be any kind of alert. There are no alerts in my view now, all are deleted. But now i want to see the history of alerts. what all alerts did i receive last 10 days.

**Environment**
- OS: Cent OS 7.5
- API version: 7.4.5
- Deployment: Self-Hosted
- For self-hosted, WSGI environment: Nginx

- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? Yes

- web UI version: 7.4.5
- CLI version: 7.4.5

i want to customize the report view and want to change it from offenders, flapping and standing to something that is my company based

**Comment by bunboy09** [comment]
@satterly

**Comment by satterly** [comment]
Export your alert data to something like elasticsearch or a logging service and generate the reports you need for your company from there. See https://github.com/alerta/alerta/pull/744 and https://github.com/alerta/kibana-alerta
