### ISSUE TITLE
Dashboard is visible for non-authenticated users

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [alerta/alerta#1229]
**Issue Summary**
Dashboard is visible even with `AUTH_REQUIRED=true`

**Environment**
- OS: kubernetes
- API version: using image `7.5.5`
- Deployment: GKE / Kubernetes
- For self-hosted, WSGI environment: N/A

- Database: Postgres 12.2

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? Yes

- web UI version: using image `alerta/alerta:7.5.5`
- CLI version: N/A

**To Reproduce**
The dashboard is visible for non-logged in users, despite the following variables being set:

```
AUTH_REQUIRED=true
SIGNUP_ENABLED=false
```

**Expected behavior**
Unauthenticated users should be welcomed with the log in screen.
Instead, the dashboard is visible before and after logging in.

**Screenshots**
![Screenshot 2020-05-28 at 5 43 07 PM](https://user-images.githubusercontent.com/50835081/83157102-e2ccb480-a10b-11ea-9dc7-ee24f00b52c2.png)

**Comment by satterly** [comment]
To enable a setting you must use `True` not `true`. And `SIGNUP_ENABLED` is not a supported environment variable. All of this is explained in the Docker README.
See https://hub.docker.com/repository/docker/alerta/alerta-web

**Comment by pantelis-karamolegkos** [comment]
Thanks!
