### ISSUE TITLE
uwsgi start services showing application" must be a callable object in file wsgi.py

### ISSUE THREAD

**Issue by pkvel01** [alerta/alerta#1235]
**Issue Summary**
Not able to start uwsgi

**Environment**
- OS: Centos7
-Deployment - gcloud
- For self-hosted, WSGI environment: nginx/uwsgi

- Database:  MongoDB

**To Reproduce**
Not able to bring up the service, need help
sudo /usr/local/bin/uwsgi --ini /tools/config/current/alerta/uwsgi.ini
[uWSGI] getting INI configuration from /tools/config/current/alerta/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Thu Jun  4 03:40:49 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 04 June 2020 03:25:24
os: Linux-3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020
nodename: xxx-xxx-xxxx
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /var/tellme/log
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /var/www
your processes number limit is 119917
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/run/alerta/uwsgi.sock fd 3
setgid() to 4242
setuid() to 4242
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8cbda0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
mounting wsgi.py on /api
"application" must be a callable object in file wsgi.py
VACUUM: unix socket /var/run/alerta/uwsgi.sock removed.
[$-east log]$ python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from alerta import app
>>> quit()
[$-east log]$
[$-east log]$ pip3 show uwsgi
Name: uWSGI
Version: 2.0.18
Summary: The uWSGI server
Home-page: https://uwsgi-docs.readthedocs.io/en/latest/
Author: Unbit
Author-email: info@unbit.it
License: GPLv2+
Location: /usr/local/lib/python3.6/site-packages
Requires:
Required-by:

uwsgi.ini

[uwsgi]
chdir = /var/www
mount = /api=wsgi.py
callable = app
manage-script-name = true
master = true
processes = 5

socket = /var/run/alerta/uwsgi.sock
chmod-socket = 666
uid = xxx
gid = xxxxx
vacuum = true
die-on-term = true
chown-socket=xxxx:xxxxx

**Comment by satterly** [comment]
You didn't include your wsgi file. It should look like this https://github.com/alerta/alerta/blob/master/wsgi.py

**Comment by pkvel01** [comment]
cat /var/www/wsgi.py
from alerta import app

**Comment by pkvel01** [comment]
thanks
