### ISSUE TITLE
Error running command

### ISSUE THREAD

**Issue by zylkron** [alerta/alerta#1236]
When I run the command below Im getting error
/opt/alerta/bin/alerta send --resource net01 --event down --severity fatal --environment Code --service Network --text 'net01 is down.'
Error: Failed to get config from http://localhost:81/api/config. Reason: 404 Client Error: Not Found for url: http://localhost:81/api/config

I dont even use port 81.

**Comment by satterly** [comment]
Any reason why you think the issue template doesn't apply to you?

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by zylkron** [comment]
Hi Nick,

Sorry, Im kind of new to github. I registered maybe 2 years ago and went
inactive and recently I set up alerta and faced issue. Im so sorry. Let me
read throughly again. I will channel my question properly now.

Best Regards,

**Comment by zylkron** [comment]
**Issue Summary**
When I run the command below Im getting error
/opt/alerta/bin/alerta send --resource net01 --event down --severity fatal --environment Code --service Network --text 'net01 is down.'
Error: Failed to get config from http://localhost:81/api/config. Reason: 404 Client Error: Not Found for url: http://localhost:81/api/config

**Environment**
- OS: RHEL 7.5
- API version: 3.6.8
- Deployment:  self-hosted
- For self-hosted, WSGI environment: [eg. nginx/uwsgi

- Database: MongoDB

- Server config:
  Auth enabled? No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc - N/A
  Customer views? No


- web UI version: 6.8.1
- CLI version: 6.8.1

I dont know if theres anything more to add in addition to the template but I will provide whatever is required.

Best Regards.

**Comment by satterly** [comment]
Why do you have two different Alerta API endpoints above? 

    ALERTA_ENDPOINT="http://localhost:8000/api"

and

    ALERTA_ENDPOINT="http://localhost:5000"

Your Alerta API endpoint would normally be "http://localhost:8080".

**Comment by zylkron** [comment]
Oh that. my mistake. I fixed it. I used port 8080 for other web
application. Sorry for the late reply.

Best Regards.

**Comment by zylkron** [comment]
Sorry I meant I fixed the endpoint issue but the problem still persists.

Best Regards
