### ISSUE TITLE
Feature request: Map tag values to custom columns

### ISSUE THREAD

**Issue by Hybrid512** [alerta/alerta#1246]
**Is your feature request related to a problem? Please describe.**
We monitor several clusters and centralize their alerts on Alerta.
We use tags to distinguish clusters but you can't sort or filter by tags easily (like clicking on the column header for example)

**Describe the solution you'd like**
Creating custom columns is great but it is too static for our needs, it would be great if we could map tag values to custom columns.
For example, you could define 2 custom columns "cluster" and "region" and map values from the "cluster" tag and "region" tag.

**Describe alternatives you've considered**
Use "unused" alerta attributes to map labels from Prometheus but this is quite a dirty way and very limited since there are not that much "useless" attributes.
Another good option would be to let us declare custom attributes that we could map on Prometheus labels.

Best regards

**Comment by satterly** [comment]
> Creating custom columns is great but it is too static for our needs, it would be great if we could map tag values to custom columns.
For example, you could define 2 custom columns "cluster" and "region" and map values from the "cluster" tag and "region" tag.

Are you talking about "tags" or "attributes"?

**Comment by Hybrid512** [comment]
> Are you talking about "tags" or "attributes"?

I'm talking about tag values.
We can easily add tags to alerts but we would like to map a tag to a custom column.

**Comment by satterly** [comment]
Give me an example of a "tag value".

**Comment by satterly** [comment]
Are you talking about this? https://github.com/alerta/angular-alerta-webui/pull/165

<img width="1182" alt="Screenshot 2020-06-15 at 15 48 08" src="https://user-images.githubusercontent.com/615057/84665008-a11b7680-af1f-11ea-96ce-ad9a384629cb.png">

Where `region` is a custom attribute (not tag!) that has been added to the web UI as a custom column.

**Comment by Hybrid512** [comment]
I was thinking about something like this (don't bother about the visual, this is a quick mockup made with a spreadsheet), hope this is a bit more understandable.

![before](https://user-images.githubusercontent.com/18528623/84665528-3ae32380-af20-11ea-92c3-365a6dd30fc0.png)

![after](https://user-images.githubusercontent.com/18528623/84665524-3a4a8d00-af20-11ea-8471-5456941d5278.png)

**Comment by Hybrid512** [comment]
> Are you talking about this? [alerta/angular-alerta-webui#165](https://github.com/alerta/angular-alerta-webui/pull/165)
> 
> <img alt="Screenshot 2020-06-15 at 15 48 08" width="1182" src="https://user-images.githubusercontent.com/615057/84665008-a11b7680-af1f-11ea-96ce-ad9a384629cb.png">
> 
> Where `region` is a custom attribute (not tag!) that has been added to the web UI as a custom column.

That's an interesting point but how do you define AND map this custom attribute to a custom column ??

**Comment by satterly** [comment]
What you are asking for is already possible.

<img width="695" alt="Screenshot 2020-06-15 at 16 42 36" src="https://user-images.githubusercontent.com/615057/84671170-54d43480-af27-11ea-9ca5-670adae1ea1f.png">

Edit `alertad.conf` server config `COLUMNS` and add `tags` and/or the custom attribute name...

```
COLUMNS = [
    'severity', 'status', 'lastReceiveTime', 'timeoutLeft', 'duplicateCount',
    'customer', 'environment', 'service', 'resource', 'event', 'value', 'text',
    'tags', 'region', 'location', 'datacenter'
]
```

Send an alert with the tags and attributes you want...

    $ alerta send -E Development -S Web -S Core -r net66 -e node_down -s critical -T foo -T baz=quux -A location=Ireland -A region=EU -A datacenter=eu-west-1

**Comment by Hybrid512** [comment]
Agreed but not agreed ...
We tried to do so but as you can see on this screen capture, it doesn't seem to work (see the "cluster" column and "cluster" tag)
And this is not a upper/lower case math issue, they are both written exactly the same between tag name and column name.

![Capture](https://user-images.githubusercontent.com/18528623/84673311-d5943000-af29-11ea-9ea5-33fe50d12511.PNG)

**Comment by satterly** [comment]
You are confusing "tags" and "attributes". In Alerta, there is no such thing as a "tag value" as you call it. You must use an "attribute" if you want it to appear in a custom column in the alert list.

Take another close look at the example `alerta` command above and you'll see I'm sending attributes as `-A location=Ireland`. The tags are sent as `-T foo`. You can convert tags into attributes if you have to using a plugin.

**Comment by Hybrid512** [comment]
Okay, I'm better understanding now.
So we have to deal with attributes and not tags. (or convert tags to attributes as you said).
Do you know a plugin that just do that ?

**Comment by satterly** [comment]
There is no plugin that does this already but it is trivial to write your own. You can find examples here ... https://github.com/alerta/alerta-contrib/tree/master/plugins and a tutorial here ... https://docs.alerta.io/en/latest/gettingstarted/tutorial-3-plugins.html#tutorial-3

The code will look something like ...

```
        for tag in alert.tags:
            try:
                k, v = tag.split('=', 1)
                alert.attributes[k] = v
            except ValueError:
                pass
```
