### ISSUE TITLE
[ERROR] duplicate key value violates unique constraint "constraint_name" when updated to alerta v8.0.1

### ISSUE THREAD

**Issue by arindamchoudhury** [alerta/alerta#1258]
Hi,

I am getting this error:

```bash
2020-06-29 08:46:11,309 flask.app[49]: [ERROR] duplicate key value violates unique constraint "constraint_name"
DETAIL:  Key (customer)=(*************) already exists.
 request_id=96258edd-dadb-465b-82c5-924c4dbf4899 ip=127.0.0.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/alerta_server-8.0.1-py3.8.egg/alerta/views/customers.py", line 26, in create_customer
    customer = customer.create()
  File "/usr/local/lib/python3.8/site-packages/alerta_server-8.0.1-py3.8.egg/alerta/models/customer.py", line 63, in create
    return Customer.from_db(db.create_customer(self))
  File "/usr/local/lib/python3.8/site-packages/alerta_server-8.0.1-py3.8.egg/alerta/database/backends/postgres/base.py", line 1153, in create_customer
    return self._insert(insert, vars(customer))
  File "/usr/local/lib/python3.8/site-packages/alerta_server-8.0.1-py3.8.egg/alerta/database/backends/postgres/base.py", line 1391, in _insert
    cursor.execute(query, vars)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/extras.py", line 319, in execute
    return super(NamedTupleCursor, self).execute(query, vars)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "constraint_name"
DETAIL:  Key (customer)=(*************) already exists.
```

postgres log:

```bash
2020-06-29 08:46:33.342 UTC [23461] ERROR:  duplicate key value violates unique constraint "constraint_name"
2020-06-29 08:46:33.342 UTC [23461] DETAIL:  Key (customer)=(*************) already exists.
2020-06-29 08:46:33.342 UTC [23461] STATEMENT:  
	            INSERT INTO customers (id, match, customer)
	            VALUES ('266f0a59-1103-4259-be20-277941bdfd55', '*************', '*************')
	            RETURNING *
```

customers table schema:
```bash
alerta=# \d+ customers;
                                 Table "public.customers"
  Column  | Type | Collation | Nullable | Default | Storage  | Stats target | Description 
----------+------+-----------+----------+---------+----------+--------------+-------------
 id       | text |           | not null |         | extended |              | 
 match    | text |           | not null |         | extended |              | 
 customer | text |           |          |         | extended |              | 
Indexes:
    "customers_pkey" PRIMARY KEY, btree (id)
    "constraint_name" UNIQUE CONSTRAINT, btree (customer)

alerta=# 

We had problems with duplicate customers, so we added this constraint. 
```

**Comment by satterly** [comment]
I don't understand. You say you are getting an error but don't say where. What were you doing when you go the error? Why did you need to add the constraint? Is the constraint causing the error? What was the problem with duplicate customers? Is it related to this?

**Comment by arindamchoudhury** [comment]
Hi @satterly , sorry for the ambiguity.

the error is in the log of alerta container. All I can see are these logs.

without that constraint we were having duplicate customers.

**Comment by satterly** [comment]
I still don't understand what the issue is. It sounds like you added a table constraint and now are complaining that you see errors in the logs for a violation of that table constraint. Sounds like you should just remove the table constraint. If not, you need to explain better why you added the constraint in the first place.

**Comment by arindamchoudhury** [comment]
we have added this constraint so we dont have duplicate customers with same name.

**Comment by satterly** [comment]
You haven't explained why that's a problem. Why can't you have customers with the same name?

This works perfectly well ...

<img width="524" alt="Screenshot 2020-06-30 at 11 59 58" src="https://user-images.githubusercontent.com/615057/86113260-4fe7b700-bac9-11ea-897b-c2394f19f967.png">

**Comment by arindamchoudhury** [comment]
If we have customers with the same name, we can not create blackout for proper customer.

**Comment by satterly** [comment]
Finally a reason! So why can't you create a blackout for the proper customer? What happens?

Note: I shouldn't have to ask so many questions! You should volunteer this information. How else can I understand what the real issue is? Put yourself in my position and ask yourself what you think you might need to know to help resolve this issue. Thanks.

**Comment by arindamchoudhury** [comment]
I can understand your position.

when we create a alert, we provide customer name, so if we have multiple customer with same name, we dont know which customer the alert belongs to.

When we create a blackout, we can not put specific customer(if we have duplicate customer name) which the alert belongs to.

**Comment by satterly** [comment]
Are you on Gitter Chat?

**Comment by arindamchoudhury** [comment]
yes

**Comment by satterly** [comment]
<img width="533" alt="Screenshot 2020-06-30 at 14 22 21" src="https://user-images.githubusercontent.com/615057/86125913-bbd41a80-badd-11ea-8ca6-d46c28d55fc9.png">

**Comment by arindamchoudhury** [comment]
I made that change in a old alerta version, i will try removing that constraint with the new version.

Thanks a lot.
