### ISSUE TITLE
Alerts are unacked automatically

### ISSUE THREAD

**Issue by hasso** [alerta/alerta#1259]
**Issue Summary**
In our environment apps sending alerts into Alerta have two options:
- Guarantee that they send both open and close alerts themselves and don't care about timeout, but they might set timeout if they send duplicates regularly for fast recovery.
- Send only open alerts (regularly) and set timeout accordingly. Often these systems cant even send closes for alerts because these don't hold the state themselves. It's also common that these systems send duplicates quite fast (every minute for example) in alert situations and set short timeouts (only some minutes) as well.

Timeout is meant to control a time when alerts expire if duplicates aren't received any more.

Since somewhere before 8.0 timeout also started to control automatic unack and unshelve of alerts. In our environment it's not OK even if we'd want to use automatic unack – timeout is controlled by applications sending alerts into Alerta. Even if UI sets timeout to 0 to disable automatic unack, application overwrite it with next duplicate.

**Environment**
- OS: Linux
- API version: 8.0.2
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi
- Database: MongoDB

- web UI version: [eg. 8.0.0]
- CLI version: [eg. 8.0.0]

**Expected behavior**
I see no other option than timeout of controlling expire and timeout controlling unack/unshelve must not be the same fields in the database.

**Comment by satterly** [comment]
The original timeout attribute is now exclusively for alert expiry. A per-status timeout has been added to the status history log to control auto-unack and auto-unshelve which can be set independently or disabled completely. See #1267
