### ISSUE TITLE
Allow synchronization between Alertmanager silences and Alerta blackouts

### ISSUE THREAD

**Issue by Exceptionfault** [alerta/alerta#1266]
**Is your feature request related to a problem? Please describe.**
We're using prometheus and alertmanager in the background and send all active alerts to alerta as our central UI. We also have tons of other notification rules in alertmanager, so we're not making use of alerta notifications. 
Alerts that are ack'ed in alerta create silences in alertmanager by using the alerta-contrib plugin, however they are not visible in alerta for the alerta users. 

The idea is have a view of all silences that are active in alertmanager inside alerta by synchonizing the silences as blackouts.
I know, this is useless from the functionality perspective of blackouts because there will arrive no more alerts from alertmanager matching the blackouts. However it would be great from a user perspective to be able to manage or at least see active blackouts/silences from one place.

**Describe the solution you'd like**
In best cases the housekeeping process running inside docker would be extendend to synchronize active silences from alertmanager to alerta. Therefore alerta calls the `/api/v2/silences` endpoint of alertmanager and creates or updates existing blackouts. As both tools are using uuids, matching shouldn't be a problem.

**Describe alternatives you've considered**
For the beginning we wanted to create a simple external process calling both, the alertmanager api to read silences and the alerta api/blackout to create blackouts. The problem is, that alerta does not allow to set the id of a blackouts manually. When sending something like the following:

```
POST https://<alerta-host>/api/blackout
Content-Type: application/json

{
    "id": "fa2da082-4414-49be-9638-eba2e83d5d3d",
    "environment": "prod",
    "event": "This is a critical event",
    "startTime": "2020-06-23T14:56:30.165Z",
    "endTime": "2020-07-23T14:55:55.490Z",
    "text": "Blackout due to..."
}
```

will create a blackout with a different id:
```
    {
      "createTime": "2020-07-03T06:34:57.196Z",
      "customer": null,
      "duration": 2591965,
      "endTime": "2020-07-23T14:55:55.490Z",
      "environment": "prod",
      "event": "This is a critical event",
      "group": null,
      "href": "/blackout/d7131507-32e7-4c60-9187-5c607e9e48bf",
      "id": "d7131507-32e7-4c60-9187-5c607e9e48bf",
      "priority": 4,
      "remaining": 1758052,
      "resource": null,
      "service": [],
      "startTime": "2020-06-23T14:56:30.165Z",
      "status": "active",
      "tags": [],
      "text": "Blackout due to...",
      "user": null
    }
```
That makes matching in later calls hard to impossible.

**Additional context**
In our case, we're using a single alerta instance for all environments but two prometheus and alertmanagers for production and non-production. That means, synchronization should be possible based on a list of alertmanagers.

**Comment by satterly** [comment]
This was supported for alert id's only. Custom resource ID's are supported for all API resources now. See #1268

**Comment by Exceptionfault** [comment]
Thank you very much for the fast fix! That's great!
