### ISSUE TITLE
severity page unhandled

### ISSUE THREAD

**Issue by KlavsKlavsen** [alerta/alerta#1280]
**Issue Summary**
If I configure severity: page (which is first example on prometheus docs https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/ )

I get this 500 error when alertmanager tries to send an alert to Alerta with that severity:
 alerta.exceptions.ApiError: Severity (page) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown

**Environment**
- OS: docker-alerta running on OpenShift 3.11
- API version: 7.5.1
- Deployment: Docker
- Database: Postgres

**Comment by satterly** [comment]
That is a Prometheus example. `page` is not a valid default Alerta severity.
