### ISSUE TITLE
alerta returns only 50 heartbeats in cli and webui

### ISSUE THREAD

**Issue by 3hedgehogs** [alerta/alerta#1281]
**Issue Summary**
alerta command line tool and webui return only 50 heartbeats from more then 250 in DB

**Environment**
alerta 8.0.3
alerta client 8.0.0
requests 2.24.0
click 7.1.2

- Database: [Postgres]

**Expected behavior**
Return all Hearbeats

**Comment by 3hedgehogs** [comment]
I have found as workaround is to set in .alertad.conf  
`QUERY_LIMIT=100000
DEFAULT_PAGE_SIZE=100000`
But probably api requests and 'alerta heartbeats --alert' have to work and return all heartbeats ?

**Comment by lotooo** [comment]
Same issue here 

```
$ alerta version
alerta 8.0.2
alerta client 8.0.0
requests 2.22.0
click 7.0
```

**Comment by satterly** [comment]
The backend API doesn't support paging for the heartbeats list so for now your only option is to increase the page size so that the returned response contains all the heartbeats. Setting it to 100,000 seems unnecessary. 500 or 1,000 would be more appropriate, I would have thought.
