### ISSUE TITLE
Alerta 8.0.3 performance issue with large number of alerts in MongoDB database

### ISSUE THREAD

**Issue by tuxdevnow** [alerta/alerta#1285]
**Issue Summary**
Alerta GUI is not displaying alerts if number of alerts in the MongoDB database is really big.
In our case, this number is more than 1.2 million.

**Environment**
- OS: Linux
- API version: 8.0.3 (alerta version)
- Deployment: self-hosted on Docker
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: MongoDB replica set

- Server config:
  Auth enabled? Yes
  Auth provider? SAML2
  Customer views? No

- web UI version: 8.0.1
- CLI version: 8.0.0

**To Reproduce**
1. Submit 1+ million alerts to aleta API or load up the alerts collection in MongoDB
2. Login to Web GUI

**Expected behavior**
We should see the first 20 alerts being listed in the UI.

**Additional context**
What we were able to determine is that the problem exists in database/backends/mongodb/base.py in function get_alerts.

We duplicated the observed query from get_alerts in Robo 3T client:
db.getCollection('alerts').aggregate([
  {"$lookup": {"from": "codes", "localField": "severity", "foreignField": "severity", "as": "fromCodes"}},
  {"$replaceRoot": {"newRoot": {"$mergeObjects": [{"$arrayElemAt": ["$fromCodes", 0]}, "$$ROOT"]}}},
  {"$project": {"fromCodes": 0}},
  {"$lookup": {"from": "states", "localField": "status", "foreignField": "status", "as": "fromStates"}},
  {"$replaceRoot": {"newRoot": {"$mergeObjects": [{"$arrayElemAt": ["$fromStates", 0]}, "$$ROOT"]}}},
  {"$project": {"fromStates": 0}},
  {"$match": {"status": {"$in": ["open", "ack"]}}},
  {"$sort": {"lastReceiveTime": -1}},
  {"$skip": 0},
  {"$limit": 20}
])

This results in the error:
Error: command failed: {
	"operationTime" : Timestamp(1596650206, 1),
	"ok" : 0,
	"errmsg" : "operation was interrupted",
	"code" : 237,
	"codeName" : "CursorKilled",
	"$clusterTime" : {
		"clusterTime" : Timestamp(1596650206, 1),
		"signature" : {
			"hash" : BinData(0,"<redacted>"),
			"keyId" : NumberLong("<redacted>")
		}
	}
} : aggregate failed 
Details:
_getErrorWithCode@src/mongo/shell/utils.js:25:13
doassert@src/mongo/shell/assert.js:18:14
_assertCommandWorked@src/mongo/shell/assert.js:534:17
assert.commandWorked@src/mongo/shell/assert.js:618:16
DB.prototype._runAggregate@src/mongo/shell/db.js:260:9
DBCollection.prototype.aggregate@src/mongo/shell/collection.js:1062:12
DBCollection.prototype.aggregate@:1:355
@(shell):1:1

MongoDB logs:
Wed Aug  5 21:14:10.600 I COMMAND  [conn263500] command alerta_dev.states appName: "MongoDB Shell" command: aggregate { aggregate: "alerts", pipeline: [ { $lookup: { from: "codes", localField: "severity", foreignField: "severity", as: "fromCodes" } }, { $replaceRoot: { newRoot: { $mergeObjects: [ { $arrayElemAt: [ "$fromCodes", 0.0 ] }, "$$ROOT" ] } } }, { $project: { fromCodes: 0.0 } }, { $lookup: { from: "states", localField: "status", foreignField: "status", as: "fromStates" } }, { $replaceRoot: { newRoot: { $mergeObjects: [ { $arrayElemAt: [ "$fromStates", 0.0 ] }, "$$ROOT" ] } } }, { $project: { fromStates: 0.0 } }, { $match: { status: { $in: [ "open", "ack" ] } } }, { $sort: { lastReceiveTime: -1.0 } }, { $skip: 0.0 }, { $limit: 20.0 } ], cursor: {}, $readPreference: { mode: "secondaryPreferred" }, $db: "alerta_dev" } planSummary: COLLSCAN keysExamined:0 docsExamined:1253652 hasSortStage:1 cursorExhausted:1 numYields:11975 nreturned:20 reslen:319672 locks:{ Global: { acquireCount: { r: 5030787 } }, Database: { acquireCount: { r: 5030787 } }, Collection: { acquireCount: { r: 5030786 } } } protocol:op_command 320133ms

As a short term "fix," we are currently looking into adding the following to the pipeline to reduce the number of alerts in the alerts collection before join stages of the query:
{"$sort": {"lastReceiveTime": -1}},
{"$limit": 10000}

**Comment by satterly** [comment]
Are you suggesting the sort/limit be done before the severity-from-codes lookup? If so, I can see how that would make more sense from a performance point of view. This assumes that any match filter is not based on severity. I'd need to review this in more detail to be sure about this approach.

However, in the meantime, I would respectfully suggest that 1.2 million alerts in the database is about 1 million too many. My recommendation is to forward alerts to a tool like Kibana/Elasticsearch if you need to store alerts for historical analysis.

See https://github.com/alerta/kibana-alerta

**Comment by satterly** [comment]
Performance should be improved with this PR #1349
