### ISSUE TITLE
Unable to modify/remove alert attribute in status_change using custom plugin

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta#1287]
**Issue Summary**
I noticed on the acked-by plugin that the acked-by alert attribute does not get cleared when an alert gets reopened. This results in an open alert with an acked-by user.

To address this I am trying to clear this attribute in status_change on any alert that changes to 'open' but the attribute is not clearing. I am following the same method as https://github.com/alerta/alerta-contrib/blob/master/plugins/prometheus/alerta_prometheus.py (return alert, etc) but the attribute still will not clear. Any ideas what I might be doing wrong here?

**Environment**
- OS: Oracle Linux 7
- API version: 8.0.3
- Deployment: self
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: mongo

- Server config:
  Auth enabled? Yes
  Auth provider?  LDAP
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: 8.0
- CLI version: [eg. 6.8.1]

**Comment by satterly** [comment]
I've updated the `acked_by` plugin to work as you suggested.
