### ISSUE TITLE
Prometheus Alert Manager Watchdog alert causes ApiError

### ISSUE THREAD

**Issue by andrew-lee-metaswitch** [alerta/alerta#1290]
**Issue Summary**
I have deployed Prometheus (and alermanager) alongside Alerta on Kubernetes, and have got AlertManager sending Alerts to Alerta as per https://github.com/alerta/prometheus-config

One of the Alerts I have set up on Prometheus is the [Watchdog](https://github.com/prometheus-operator/kube-prometheus/blob/eee5e10e72fd557b5db23e1e4684b5708d1d178d/jsonnet/kube-prometheus/alerts/general.libsonnet#L19) which has Severity "none"

This is causing the following error:

```
2020-08-18 04:45:12,013 flask.app[25]: [ERROR] Severity (none) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown request_id=c3ec1bf1-b765-47f3-9eff-683eac4b8a2e ip=10.25.0.17
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/alerta/utils/api.py", line 62, in process_alert
    alert = alert.create()
  File "/venv/lib/python3.7/site-packages/alerta/models/alert.py", line 372, in create
    alert=self
  File "/venv/lib/python3.7/site-packages/alerta/models/alarms/alerta.py", line 134, in transition
    raise ApiError('Severity ({}) is not one of {}'.format(current_severity, ', '.join(valid_severities)), 400)
alerta.exceptions.ApiError: Severity (none) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/alerta/webhooks/custom.py", line 52, in custom
    alert = process_alert(alert)
  File "/venv/lib/python3.7/site-packages/alerta/utils/api.py", line 64, in process_alert
    raise ApiError(str(e))
alerta.exceptions.ApiError: Severity (none) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/venv/lib/python3.7/site-packages/alerta/auth/decorators.py", line 127, in wrapped
    return f(*args, **kwargs)
  File "/venv/lib/python3.7/site-packages/alerta/webhooks/custom.py", line 66, in custom
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: Severity (none) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown
```

**Environment**
- OS: Linux
- API version: Alerta API 7.5.1
- Deployment: Docker /k8s
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]
- Database: Postgres

Beyond [RFC 5674 Alarms in Syslog](https://tools.ietf.org/html/rfc5674.html), there doesn't seem to be any sort of standard for the accept severity types, so that leaves us with a variety of possible ways to fix this:

- We map 'none' (and in fact, all severities not in `SEVERITY_MAP`) to 'unknown' in alerta
- I try and fix https://github.com/prometheus-operator/kube-prometheus/blob/eee5e10e72fd557b5db23e1e4684b5708d1d178d/jsonnet/kube-prometheus/alerts/general.libsonnet#L19 and set the severity to something else, "security", maybe?
- We add 'none to the `SEVERITY_MAP`  https://github.com/alerta/alerta/blob/master/alerta/models/alarms/alerta.py

I am open to your opinions on the best way to go here, but my instinct is that the first fix here seems the cleanest. 

**Expected behavior**
Logs from alertmanager are not full of spam

**Comment by corvus-ch** [comment]
Doing some experiments with OpenShift 4, I found the same issue. However, the _Watchdog_ alert was not the only one having severity not understood by Alerta (high, alert).

Those alert rules are managed by RedHat and there is no (supported) way to change them. On https://docs.openshift.com/container-platform/4.5/monitoring/cluster_monitoring/configuring-the-monitoring-stack.html#maintenance-and-support_configuring-monitoring they explicitly exclude this.

Would it be possible to allow arbitrary severity names within `SEVERITY_MAP`? I tried to do so but then got a parse error.

**Comment by satterly** [comment]
Severity levels are completely customisable already. For example the suggested config for Zabbix integrations is ...
```
SEVERITY_MAP = {
    'Disaster'      : 0,
    'High'          : 1,
    'Average'       : 2,
    'Warning'       : 3,
    'Information'   : 4,
    'OK'            : 5,
    'Not classified': 6,
    'unknown'       : 9
}
DEFAULT_NORMAL_SEVERITY = 'OK'
DEFAULT_PREVIOUS_SEVERITY = 'Not classified'

COLOR_MAP = {
    'severity': {
        'Disaster'      : '#E45959',
        'High'          : '#E97659',
        'Average'       : '#FFA059',
        'Warning'       : '#FFC859',
        'Information'   : '#7499FF',
        'Not classified': '#97AAB3',
        'OK'            : '#59DB8F',
        'unknown'       : '#BA2222'
    }
}
```
This matches not only the severity levels but the Zabbix severity colour scheme.

Having said that, I think having a severity of "none" is a terrible idea. Instead use "indeterminate" or "informational". So my suggestion would be to get "none" fixed at source to something more sensible, add "none" to your list of valid severities using the above config example, or you use a plugin to map "none" to something else.

The problem with mapping missing severity levels to "unknown" or some other severity is that experience has shown people get lazy and just send any old severity, misspell the severity or use the wrong case -- all of which makes correlation and de-duplication based on severity a nightmare.
