### ISSUE TITLE
Question/ new idea: There is a way to update timeout of main alert from duplicates?

### ISSUE THREAD

**Issue by victorarthae** [alerta/alerta#1295]
The question is: can I update the alert timeout with the entry of duplicate alerts?

I know that time is not the alert itself, but the last interaction with it. 

Would it be possible to update the time of this last update (e.g. ack event)?

**Comment by satterly** [comment]
Yes, this happens already. There is an "Ack Timeout" and "Shelve Timeout" option in the web UI settings. This sets the alert timeout to those values when an operator acks or shelves an alert.

And the timeout for an alert is calculated based on the most recently received alert, not the oldest. So if an alert keeps being resent before the timeout window it will never timeout.

You can manage timeouts yourself though, if you want to, using a plugin. See https://docs.alerta.io/en/latest/gettingstarted/tutorial-3-plugins.html#tutorial-3
