### ISSUE TITLE
Correlate multiple alerts

### ISSUE THREAD

**Issue by mmarin11** [alerta/alerta#1300]
Dear Alerta community

We are looking for a way to correlate multiple alarms and only trigger a single action (open ticket when a customer is down). For example, when there is a fiber cut, we receive two alarms, one that is related to the port in the aggregation switch that is down and other alarm for the ICMP of the CPE that is located at the customer location. There are other more complex scenarios where multiple alarms are going to be received at the same time due to a fiber cut and I would like to know if there is a way to analyze the last 100 or so alarms within a period of time and only trigger an action instead of creating of opening 100 independent tickets that have the same root cause, in other words, create a single ticket and add all circuits affected as custom fields to the ticket.

Thank you

**Comment by satterly** [comment]
Hi Thanks for your question. The answer is that there is no easy way to do what you want with Alerta. What you are asking for is "complex correlation" and Alerta was not designed to only implement "simple correlation" (see https://docs.alerta.io/en/latest/server.html#simple-correlation). I suggest you investigate tools specifically designed to implement the correlation you require and then feed the resulting alerts into Alerta. See https://www.google.com/search?q=complex+event+processing
