### ISSUE TITLE
Correlation rules enhancement (add value or text field)

### ISSUE THREAD

**Issue by pavleec** [alerta/alerta#1303]
**Is your feature request related to a problem? Please describe.**
Current implementation of events correlation (based on `resource, environment, event` and `correlate` fields) is not sufficient for  proper handling of network interfaces alerting and flapping based on interface names. 
I've defined basic **LinkDown/LinkUp** events and when two network interfaces are going down it should be possible to correlate them separately based on network interface name and display two separate events in Alerta (instead of single corelated event). Here's simple flow what's happing:

1.**Node1** sends **int1** interface **LinkDown** event - Alerta opens new event with severity set to major:

`alerta send -r node1 -e LinkDown -C LinkUp -v int1 -s major`
`0877e18d-a700-4095-8eb6-0c0a34b6b650 (indeterminate -> major)`

2.**Node1** sends **int2** interface **LinkDown** event - Alerta corelates it as duplicate instead of creating desired separate event

`alerta send -r node1 -e LinkDown -C LinkUp -v int2 -s major`
`0877e18d-a700-4095-8eb6-0c0a34b6b650 (1 duplicates)`

3.**Node1** sends **int1** interface **LinkUp** event - Alerta updates and clears existing event which contains **int2** which is still in down state and should be left displayed with major severity.

`alerta send -r node1 -e LinkUp -C LinkDown -v int2 -s ok`
`0877e18d-a700-4095-8eb6-0c0a34b6b650 (major -> ok)`

**Describe the solution you'd like**
It would be great to have an option/switch in Alerta config which allows `value`  or  `text` fields to be added to correlation rules engine so that unique events will be identified by `environment, resource, event` and `value or text` fields. 

**Describe alternatives you've considered**
The only possible solution to overcome this at the moment is to add interface name to the event  and correlate fields (eg. `LinkDown-int1`) what causes correlation rules to treat them as separate events but in my opinion it's not the best design approach as event names should be more generic. What do you think about this?

**Comment by satterly** [comment]
Adding another alert attribute to the existing list of attributes used for correlation would be a massive undertaking and not the right approach. For this situation I would not modify the `event` but the `resource`. If you set the `resource` for these events as "node1:int2", for example, it would work and make more sense. ie. the node and the interface uniquely identifies the "resource" that the event relates to.
