### ISSUE TITLE
Faster alert list

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#1308]
First, thanks for the hard work and the already good progress in optimizing the complete Alerta performance. The first releases of the "new" webui would be completely unusable with our current >10000 alerts.

**Is your feature request related to a problem? Please describe.**
The users of my Alerta installation always complain it's too slow and every refresh and load takes too long. I can see in the development tools in Firefox that the XHR request takes round about 1 second but it takes 3-4 seconds more until the result is also visible.

**Describe the solution you'd like**
My idea is to load in the alerts list only the needed data, but not history, raw data and so on. In my specific case this would lower the JSON object from 500kb to <15kb for 20 alerts. I have no test to verify this but at least the request would be faster and also the JSON processing should be much faster.
But my gut feeling says also 500kb of JSON should be processed faster and the time is spend somewhere else.

**Describe alternatives you've considered**
Alternative could be to shrink the raw data, but this is not helpful.

**Additional context**

**Comment by satterly** [comment]
Yes, this would work. I'll add it to the backlog. Thanks.
