### ISSUE TITLE
should yaml ,click ,blinker and itsdangerous be listed in requirements.txt

### ISSUE THREAD

**Issue by suliuzh** [alerta/alerta#1316]
**Is your feature request related to a problem? Please describe.**
Hi
As we can see, **yaml ,click ,blinker and itsdangerous**  are used as in source code.  Here I show **blinker** in the following screenshot and others also can be found in other source code files.  And I notice that these dependencies are listed in the _.isort.cfg_ but not in _requirements.txt_.  So if it is a must, I am wondering if  these dependencies should be listed in requirements.txt. If not , why?
![image](https://user-images.githubusercontent.com/27858725/94335883-4828a780-0011-11eb-8395-21174f7e01ef.png)

**Describe the solution you'd like**
**yaml ,click ,blinker and itsdangerous** should be listed as dependencies explicitly.

**Describe alternatives you've considered**

**Additional context**

**Comment by satterly** [comment]
click and itsdangerous are transient dependencies of flask https://github.com/pallets/flask/blob/master/setup.py

yaml is included in the install dependencies (aka PyYAML).

It looks like blinker will silently fail if not available. See https://github.com/pallets/flask/blob/master/src/flask/signals.py#L13 

So, in summary...
yaml => no, already included
blinker => probably
click => no
itsdangerous => no

The alternative is use Pipenv and all this dependency hell just goes away, apparently.
