### ISSUE TITLE
Ability to use /api/[heartbeats|management/housekeeping|webhooks] when OIDC is enabled

### ISSUE THREAD

**Issue by desaintmartin** [alerta/alerta#1322]
**Issue Summary**
When using an OIDC based authentication, it seems ALL paths require OIDC access. In the case of APIs, this becomes hard to implement. For example, it seems not possible to configure Prometheus AlertManager to push to /api/webhooks/prometheus.

Should we have a different settings parameter to setup "internal" /api paths for different authentication ?

**Environment**
- OS: Linux
- API version: 8.0.2
- Deployment: Docker, deployed through Helm Chart

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Gitlab
  Customer views? No

- web UI version: 8.0.2
- CLI version: 8.0.2

**Comment by satterly** [comment]
Just create an API key. See https://docs.alerta.io/en/latest/authentication.html#api-keys
