### ISSUE TITLE
Security issue - DEBUG enabled - logs passwords in clear text to logs

### ISSUE THREAD

**Issue by KlavsKlavsen** [alerta/alerta#1324]
If you enable DEBUG  - it logs password in clear text to logs (and to stdout when running official docker image).

I tested with alerta/alerta-web-8.0.2.

**Comment by satterly** [comment]
Can you include an example log entry? (obviously redact any sensitive info) Thanks.

**Comment by KlavsKlavsen** [comment]
I'll soon need to go around Alerta again - to get AD integration to work with groups-controlled login (as that does not work in 8.0.3 - I could not get it working atleast. I'm probably going to try out the PR thats sitting around for improving that.

In regards to what I did - it was simply that I enabled LDAP - and then enabled DEBUG = True - and when logging in, it put my password in the console output (in kubernetes).

**Comment by satterly** [comment]
You didn't mention you were using LDAP. That was an important detail. I was trying to reproduce the problem using Basic Auth. This is an issue with the 'python-ldap' library, not with Alerta. See https://github.com/alerta/alerta/pull/524#issuecomment-414462891
