### ISSUE TITLE
Grouping alerts based on tags, and tag based silencing

### ISSUE THREAD

**Issue by raags** [alerta/alerta#1338]
**Is your feature request related to a problem? Please describe.**
Right now the labels used in Alerta provide metadata and filtering for alerts. It will be useful to use these to group and deduplicate alerts. For e.g. all alerts for an Instance can come as a single alert. 

Similarily a tag-based silencing is helpful to silence a group of alerts in one go, For e.g. silencing all alerts for a particular team or project.

**Describe alternatives you've considered**
A layer before alerta can potentially do the tag-based grouping and silencing behind the scenes.

**Additional context**
This is very similar to how Prometheus alertmanager works. But alertmanager in't a general alert aggregation service like alerta is.

**Comment by satterly** [comment]
> Right now the labels used in Alerta provide metadata and filtering for alerts. It will be useful to use these to group and deduplicate alerts. For e.g. all alerts for an Instance can come as a single alert.

Using alert tags for deduplication is a significant change and unlikely to be supported in future.

> Similarily a tag-based silencing is helpful to silence a group of alerts in one go, For e.g. silencing all alerts for a particular team or project.

Blackout rules can be defined using tags already. See https://docs.alerta.io/en/latest/gettingstarted/tutorial-5-blackouts.html?highlight=blackout#step-4-blackout-by-tag
