### ISSUE TITLE
How to avoid such a behaviour: Federation doesn't propagate alerts if target cluster was re-created

### ISSUE THREAD

**Issue by mrh666** [alerta/alerta#1340]
Hi there,

I tested Federated alerta: I set up federation in between two clusters of alerta and it works just perfect. After that I destroyed one of the clusters and re-created it from scratch on the same instances with the same ip/name. 
I added API key in the newly re-created cluster and replaced it on source cluster in FWD_DESTINATIONS setting. 

All existent alerts are not propagated, but only new ones does. 
Questions are: 

- is that is proper behaviour or all existent alerts should be propagated anyway?
- if this is a proper behaviour, how can I propagate all existent alerts to the newly created cluster?

**Comment by satterly** [comment]
> is that is proper behaviour or all existent alerts should be propagated anyway?

This is as designed. Alerta is event-driven so can only forward alerts that are new or are resent.

> if this is a proper behaviour, how can I propagate all existent alerts to the newly created cluster?

You should resend alerts at regular intervals if they are still active. Say every 2 hours. Alternatively, write a script that queries the Alerta server with all the alerts and pushes them to the newly re-created Alerta server.
