### ISSUE TITLE
GitLab Auth doesn't work since GitLab 13.5

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#1353]
**Issue Summary**

Using GitLab as our auth provider and since we've updated to GitLab 13.5.x, we get an error message in GitLab when trying to login for Alerta. The error message reads: `The redirect URI included is not valid.`

**Environment**
- OS: Ubuntu 18.04
- API version: 8.0.2
- Deployment: Docker

- Database: Postgres 12

- Server config:
  Auth enabled? Yes
  Auth provider? GitLab
  Customer views? Yes

```
{"actions":["createIssue"],"alarm_model":{"colors":{"severity":{"cleared":"#00CC00","critical":"red","debug":"#9D006D","indeterminate":"lightblue","informational":"#00CC00","major":"orange","minor":"yellow","normal":"#00CC00","ok":"#00CC00","security":"blue","trace":"#7554BF","unknown":"silver","warning":"dodgerblue"},"text":"black"},"defaults":{"normal_severity":"normal","previous_severity":"indeterminate","status":"open"},"name":"Alerta 8.0.2","severity":{"cleared":7,"critical":1,"debug":8,"indeterminate":5,"informational":6,"major":2,"minor":3,"normal":7,"ok":7,"security":0,"trace":9,"unknown":10,"warning":4},"status":{"ack":"C","assign":"B","blackout":"E","closed":"F","expired":"G","open":"A","shelved":"D","unknown":"H"}},"audio":{"new":null},"auth_required":true,"aws_region":"us-east-1","azure_tenant":"common","client_id":"0e0d1f1df40e2cde0ca3989b654b102aaed761f9bf104cfef4e00bc65e059f58","cognito_domain":null,"colors":{"severity":{"cleared":"#00CC00","critical":"red","debug":"#9D006D","indeterminate":"lightblue","informational":"#00CC00","major":"orange","minor":"yellow","normal":"#00CC00","ok":"#00CC00","security":"blue","trace":"#7554BF","unknown":"silver","warning":"dodgerblue"},"text":"black"},"columns":["severity","status","lastReceiveTime","timeoutLeft","duplicateCount","customer","environment","service","resource","event","value","text"],"customer_views":true,"dates":{"longDate":"ddd D MMM, YYYY HH:mm:ss.SSS Z","mediumDate":"ddd D MMM HH:mm","shortTime":"HH:mm"},"debug":false,"email_verification":false,"endpoint":"https://alerta.lakedrops.com/api","filter":{"status":["open","ack"]},"github_url":"https://github.com","gitlab_url":"https://gitlab.lakedrops.com","indicators":{"queries":[{"query":[["environment","Production"]],"text":"Production"},{"query":[["environment","Development"]],"text":"Development"},{"query":{"q":"event:Heartbeat"},"text":"Heartbeats"},{"query":"group=Misc","text":"Misc."}],"severity":["critical","major","minor","warning","indeterminate","informational"]},"keycloak_realm":null,"keycloak_url":null,"oidc_auth_url":"https://gitlab.lakedrops.com/oauth/authorize","provider":"gitlab","refresh_interval":5000,"severity":{"cleared":7,"critical":1,"debug":8,"indeterminate":5,"informational":6,"major":2,"minor":3,"normal":7,"ok":7,"security":0,"trace":9,"unknown":10,"warning":4},"signup_enabled":false,"site_logo_url":"","sort_by":["severity","lastReceiveTime"],"timeouts":{"ack":0,"alert":86400,"heartbeat":86400,"shelve":7200},"tracking_id":null}
```

- web UI version: 8.0.1
- CLI version: 8.0.0

**Additional context**

The redirect URL looks like this:

https://gitlab.example.com/oauth/authorize?response_type=code&client_id=SOMESTRING&redirect_uri=https://alerta.example.com/web&scope=openid&display=popup&state=t0afpfdb3ll

**Comment by satterly** [comment]
You don't actually say what you have configured as your redirect URL in GitLab. Looking at the callback URL it looks like it should be `https://alerta.example.com/web`. Please confirm.

**Comment by jurgenhaas** [comment]
That's interesting, the redirect URL was configured as `https://www.example.com` which has been this way for the last "decade" - well, almost ;-) - and it worked that way. But since 13.5 of GitLab it doesn't anymore and changing it to `https://alerta.example.com/web` fixes the problem. That sounds like GitLab got more rigorous about it recently.

**Comment by satterly** [comment]
Are you running the master branch of Alerta web UI? If so, and you're running Alerta web UI on a subpath, there was a recent fix to include the subpath in the redirect URL. See alerta/alerta-webui#380

**Comment by jurgenhaas** [comment]
You're right, I have my own Dockerfile which uses master branch for web UI, so I'm indeed affected by this change. Thanks for pointing that out @satterly
