### ISSUE TITLE
Scaling out Alerta

### ISSUE THREAD

**Issue by nileshsimaria** [alerta/alerta#1354]
Let say I am scaling out Alerta by starting multiple replicas of Alerta. All of them are behind a gateway. The request will be distributed in a round-robin fashion or based on load, etc. 

Would it work properly? Or do I need to worry about ordering as well based on Environment + event + service and give them to the same worker such that it does not run into the issue of alerts goes out of order for the same Environment + event + service?

Let say my application has produced alerts in the following order
Environment: Production, Event: e1, Resource: r1 and Severity: Major

Immediately it has generated the same alarm with Severity changed from Major to Minor.

Environment: Production, Event: e1, Resource: r1 and Severity: Minor

In the backend, two Alerta workers are processing the alarms. Say instance1 takes care of the first event and instance2 takes care of the second event. But due to load on instance1, it processes the alarm after instance2 has done its job with 2nd alarm. That leads to the incorrect severity of the alarm in the database of Alerta.

Any best practice to take care of scale-out deployments of Alerta to avoid the above-described ordering issue?

**Comment by satterly** [comment]
That ordering issue is extremely unlikely. The first alert shouldn't take more than a few 100 ms to process and so the second would have to be received within that period, and then processed faster than that. I would only suggest that you scale out horizontally with instances of the same size, which is standard practice, anyway.
