### ISSUE TITLE
routing plugin

### ISSUE THREAD

**Issue by MartinDE90** [alerta/alerta#1364]
Hi,

I'm using the docker version of alerta 8.0.2 and I'm trying to create routing plugin  like  described here https://docs.alerta.io/en/latest/gettingstarted/tutorial-3-plugins.html#step-3-route-alerts-to-plugins.

 I have managed to route alerts to telegram and it works fine. But now I want to send only 'critical' and 'ok'. 'OK' should be send only if the previous severity state was 'critical'. I am trying to do this with previousSeverity (previous_severity) attribute but it doesn't work.

I read that the routing plugin is run twice. The first time, it doesn't know the attributes, but the second time it should. My observations show that the plugin is run only once

routing.py:
```
def rules(alert, plugins):
    print("Duplicate count is")
    print(alert.duplicate_count)
    print("Previous severity is")
    print(alert.previous_severity)
```

logs:
```
2020-11-03 15:53:39,049 DEBG 'uwsgi' stdout output:
Duplicate count is
None
Previous severity is
None
```

Thanks!

**Comment by satterly** [comment]
> I read that the routing plugin is run twice.

Where did you read that? It's not accurate and I need to update the wording to avoid confusion.

It should say something like ... 

> The routing plugin is run before any plugin hook. So for example, it would be run once each before `pre_receive()` and `post_receive()` hooks. The first time, before the `pre_receive()` hook, it would only have access to attributes sent by the alert origin, the second time, prior to running the `post_receive()` hook, it would have access to all alert attributes such as `duplicate_count` or `previous_severity`.

Anyway, I've found a bug as you suggested and it looks like it was not being run before the `post_receive()` hook as was intended. So thanks for raising the issue.
