### ISSUE TITLE
API environments throwing 500 error

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#1370]
With the docker image updates from last night, our running system is now throwing a 500 error once a second with the request to https://alerta.example.com/api/environments?status=open,ack from the web ui. The request return the following stack trace:

```
Traceback (most recent call last):
  File \"/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request rv = self.dispatch_request()
  File \"/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
  File \"/venv/lib/python3.7/site-packages/flask_cors/decorator.py\", line 128, in wrapped_function resp = make_response(f(*args, **kwargs))
  File \"/venv/lib/python3.7/site-packages/alerta/auth/decorators.py\", line 89, in wrapped return f(*args, **kwargs)
  File \"/venv/lib/python3.7/site-packages/alerta/models/metrics.py\", line 258, in wrapped response = f(*args, **kwargs)
  File \"/venv/lib/python3.7/site-packages/alerta/utils/response.py\", line 18, in decorated return func(*args, **kwargs)
  File \"/venv/lib/python3.7/site-packages/alerta/views/alerts.py\", line 473, in get_environments environments = Alert.get_environments(query)
  File \"/venv/lib/python3.7/site-packages/alerta/models/alert.py\", line 516, in get_environments return db.get_environments(query)
  File \"/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py\", line 602, in get_environments for e in environments]
  File \"/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py\", line 602, in <listcomp> for e in environments]
KeyError: 'mobimo'
```

The environment `mobimo` does exist, but doesn't have an open or acknowledged item available. But I'm not sure if that's relevant. The errors always complain about `mobimo`, never about any of the other 7 available environments.

Any idea?

**Comment by satterly** [comment]
Are you suggesting this happened between version 8.0.3 and 8.1.0? You don't mention any version numbers so it makes it difficult to investigate.

**Comment by jurgenhaas** [comment]
Sorry, yes. It started to happen today after updating to the latest image.

**Comment by satterly** [comment]
And you haven't said explicitly but I assume from version 8.0.3. It really helps me a lot to know what version you upgraded from, and to, so that I can narrow down the changes that need to be investigated.

**Comment by satterly** [comment]
Or are you building your own docker images from master? Because I made a change that was needed to get Postgres backend working on Heroku last night. If you pulled master you would have got that change.

**Comment by jurgenhaas** [comment]
Sorry, not at my desk anymore, bit yes we build on top of master

**Comment by satterly** [comment]
Do you version your containers with the commit ID? If so what was the commit ID for the docker that was working and what was the commit ID you updated to?

**Comment by jurgenhaas** [comment]
We have Ansible automated all of our infrastructure and that updates every night at 3am GMT+1 the Docker containers when necessary with this Dockerfile:

```
# build stage
FROM node:lts-alpine as build-stage

RUN apk add --no-cache git
WORKDIR /app
ADD https://github.com/alerta/alerta-webui/archive/master.tar.gz /tmp/webui.tar.gz
RUN tar zxvf /tmp/webui.tar.gz -C /app --strip-components=1
RUN npm install
COPY .env .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /app
COPY config.json /app/config.json
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

The update is triggered, when the official alerta/alerta-web image got updated. So, the error happened with the update on November 6 and the previous one was from November 5. That should limit the number of commits, but if you want me to run other debugging steps, please let me know.

**Comment by satterly** [comment]
The official alerta-web image is not built from master. It is built from specific versions that are tagged in git for exactly this reason. Otherwise you can't have deterministic builds and it makes it difficult and time-consuming to reproduce errors and find and fix bugs.

Can you rebuild your image from https://github.com/alerta/alerta/releases/tag/v8.1.0 and tell me if that fixes it? Thanks.

**Comment by jurgenhaas** [comment]
That got confused now. We have 2 images involved here: the web-ui image gets build from master as mentioned in my previous post and the other one in alerta-web which is build with this Dockerfile:

```
FROM alerta/alerta-web

USER root
COPY ./plugins/*.py /tmp/plugins/
RUN /venv/bin/pip install python-gitlab && \
    cd /tmp/plugins && \
    /venv/bin/python3 setup_alerta_gitlab.py install && \
    /venv/bin/python3 setup_alerta_elastalert.py install && \
    cp alerta_gitlab.py /venv/lib/python3.7/site-packages/ && \
    cp alerta_elastalert.py /venv/lib/python3.7/site-packages/ && \
    echo "Done"

USER 1001
```

So we don't use the alerta/alerta project which you mentioned in your comment.

**Comment by satterly** [comment]
You do not pin a version here. By default this will find the "latest" image but you have no idea what "latest" is ...

```
FROM alerta/alerta-web
```

I'm pretty sure I've fixed the issue so please retry your builds. And I would strongly suggest you [don't use "latest" tag in production environments](https://www.google.com/search?q=dockerfile+never+use+latest).

**Comment by jurgenhaas** [comment]
> And I would strongly suggest you don't use "latest" tag in production environments.

Agreed, I've now pinned alerta-web to 8.1.0 and web-ui to 8.0.1 and can confirm, that the problem is gone. Thanks @satterly 

Just wondering: is there a way to automatically post new tags for all the components onto the @alertaio Twitter account? That would help to get notified if a new version was available.

**Comment by satterly** [comment]
> Just wondering: is there a way to automatically post new tags for all the components onto the @alertaio Twitter account? That would help to get notified if a new version was available.

Probably. It's a good idea. I'll look into it. 👍
