### ISSUE TITLE
Add delete alerts to scopes

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta#1371]
It would be great to have deleting alerts added as a specific scope. 

We typically want alerts only closed by a closing alert or in the event of an alert that does not have a close (log, etc) we would like them to be manually closed. If an alert gets deleted we loose visibility in to the alert.

**Comment by satterly** [comment]
So you want to prevent operators from deleting alerts? ie. a permission that permits closing but not deleting?

**Comment by wo250012** [comment]
Yep, that would be great.
