### ISSUE TITLE
[Feature request] Allow processing notes in plugins

### ISSUE THREAD

**Issue by hugoShaka** [alerta/alerta#1382]
**Is your feature request related to a problem? Please describe.**

I'd like to add some logic when users add notes, for example populate alert attributes based on the note content, triggering escalation, ...
Notes added with an action can be treated with a plugin using `take_action`, but notes added without an action cannot as they're going through a different api route: `note`.

**Describe the solution you'd like**

Would it make sense to add another plugin method to hook custom logic on notes ?
Or could notes be fed into the existing `take_action` plugin method with an action name like `_note` ?

**Describe alternatives you've considered**

I've considered using a dedicated custom action instead of relying on vanilla notes, but the UI does not offers custom actions with text (although I think hitting `/action` with `{"action":"customAction","text":"foo"}` should work).

**Additional context**

I can submit a PR if you confirm you're interested in the feature and want it implemented in the backend. If you prefer to add custom actions with text in the UI it would also totally solve my issue but I likely won't be able to help you implement it.

**Comment by satterly** [comment]
Thanks for the offer to work on this. I think the proposal for a new plugin method is a good one. I suggest something like `take_note()`. It would be triggered when someone adds or updates/edits a note so you'd need to modify two API routes. Let me know if you need any more information.
