### ISSUE TITLE
how to export/import API keys?

### ISSUE THREAD

**Issue by tessus** [alerta/alerta#1433]
I searched closed issues for an answer and I also googled, yet I couldn't find anything. There's no forum or anything else, thus I hope it is ok to ask questions here in a gh issue. If not, please point me to the correct support channel.

I am thinking of switching the backend db from Postgres to MongoDB. I can live with the fact that the current alerts in the db will be gone. However, it might be a pain to have people and teams in the company to rotate their API keys.

Is there any chance I can export the API keys from the old sytem (Postgres) and import them into the new system (MongoDB)?

**Comment by satterly** [comment]
There is nothing built-in to support this. The easiest thing to do is probably use database commands to dump and upload the data in required formats.

If you want to discuss this further probably best to join us on Slack https://slack.alerta.dev

**Comment by tessus** [comment]
Yes, I'd love to, especially since I might have a few other questions as well. ;-)

I tried the slack link before I opened the issue, but this is what I got:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/223439/102396283-3caea200-3faa-11eb-8dc5-2be280444006.png">

(Just tried again. Same message.)

**Comment by satterly** [comment]
You should have mentioned the Slack link was inactive. I would have created a new one like this https://join.slack.com/t/alerta/shared_invite/zt-jzf22ydz-zJvXfKXLZzEs1AGhH~5m3g

**Comment by tessus** [comment]
Thanks, the new link worked. Well, I thought you are no longer using Slack. Since it was acquired by Salesforce a few people left the Slack universe....
