### ISSUE TITLE
Demo sites down

### ISSUE THREAD

**Issue by franz-josef-kaiser** [alerta/alerta#1436]
**Issue Summary**
The demo sites linked at the [docs page](https://docs.alerta.io/en/latest/) are down. Might be something with the Heroku-Account.

**Comment by satterly** [comment]
Thanks yes, near the end of the month the free dynos tend to run out. Seems to happen more often these days, not sure why. Will take a look.

**Comment by satterly** [comment]
Demo site has moved from Heroku to Fly.io so this shouldn't happen any more.
