### ISSUE TITLE
Freeze dependencies

### ISSUE THREAD

**Issue by damoun** [alerta/alerta#1448]
**Is your feature request related to a problem? Please describe.**
In the last release (8.3.3), the requirements in the setup.py is not frozen. So the last version of PyJWT (2.0) can be install by pip even if alerta-server code isn't compatible with this major release.

**Describe the solution you'd like**
Freezing every dependencies of this module under the install_requires in setup.py.

**Describe alternatives you've considered**
To fix our deployment of alerta-server, we had to freeze the working dependencies in our own requirements.txt.

**Comment by satterly** [comment]
Fixed by #1441 . This will be available in a future version to be released in the next few days. Thanks.

**Comment by damoun** [comment]
It's fixed for PyJWT but it doesn't prevent this issue to appear again.
For exemple, PyYAML could be updated by a major release tomorrow and it would break alerta-server module.

**Comment by satterly** [comment]
That's what requirements.txt is for.

**Comment by damoun** [comment]
The requirements.txt is not used by using `pip install alerta-server`.

**Comment by satterly** [comment]
```
RUN pip install --no-cache-dir pip virtualenv && \
    python3 -m venv /venv && \
    /venv/bin/pip install --no-cache-dir --upgrade setuptools && \
    /venv/bin/pip install --no-cache-dir --requirement /app/requirements.txt && \
    /venv/bin/pip install --no-cache-dir --requirement /app/requirements-docker.txt
```

https://github.com/alerta/docker-alerta/blob/master/Dockerfile#L55
