### ISSUE TITLE
Reject plugin don't work with webhooks defaults values

### ISSUE THREAD

**Issue by gaetanars** [alerta/alerta#1455]
If the reject plugin is enabled then alerts must have an environment attribute that is one of either ALLOWED_ENVIRONMENTS values.

But it seems that some webhooks fix a default value for environment (like grafana webhook), that doesn't make sense when we want to reject some alerts.

Is there a guideline for this ? Maybe we can align all webhooks to have the same comportment?

**Comment by gaetanars** [comment]
When I use prometheus alert without environment label the alert is rejected, when I use grafana alert without environment label, the alert passed with Production environment. 
I will make more tests tomorow.

**Comment by satterly** [comment]
https://docs.alerta.io/en/latest/faq.html#why-do-i-need-to-set-an-environment-and-service-when-they-are-not-mandatory

**Comment by satterly** [comment]
You can now set a new configuration setting ...
```
DEFAULT_ENVIRONMENT='whatever'
```
