### ISSUE TITLE
unable to start alerta

### ISSUE THREAD

**Issue by kb70** [alerta/alerta#1457]
**Issue Summary**
When starting the alerta-server ( alertad run --port 8080), I get the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/alertad", line 6, in <module>
    from alerta.commands import cli
  File "/usr/local/lib/python3.7/dist-packages/alerta/commands.py", line 10, in <module>
    from alerta.auth.utils import generate_password_hash
  File "/usr/local/lib/python3.7/dist-packages/alerta/auth/__init__.py", line 39, in <module>
    from . import github, login, logout, oidc, userinfo   # noqa isort:skip
  File "/usr/local/lib/python3.7/dist-packages/alerta/auth/github.py", line 5, in <module>
    from alerta.auth.utils import create_token, get_customers, not_authorized
  File "/usr/local/lib/python3.7/dist-packages/alerta/auth/utils.py", line 12, in <module>
    from alerta.models.token import Jwt
  File "/usr/local/lib/python3.7/dist-packages/alerta/models/token.py", line 6, in <module>
    from jwt import DecodeError, ExpiredSignature, InvalidAudience
ImportError: cannot import name 'ExpiredSignature' from 'jwt' (/usr/local/lib/python3.7/dist-packages/jwt/__init__.py)`

Installed Python packages, see below.

**Environment**
- OS: Debian 10
- Deployment: self-hosted
- Database: MongoDB 4.4

**Additional context**
`pip3 list
Package             Version
------------------- -------------
alerta              8.3.0
alerta-server       8.3.3
asn1crypto          0.24.0
bcrypt              3.2.0
blinker             1.4
Brotli              1.0.9
certifi             2018.8.24
cffi                1.14.4
chardet             3.0.4
click               7.1.2
cryptography        2.6.1
distro-info         0.21
entrypoints         0.3
Flask               1.1.2
Flask-Compress      1.8.0
Flask-Cors          3.0.10
httplib2            0.11.3
idna                2.6
itsdangerous        1.1.0
Jinja2              2.11.3
keyring             17.1.1
keyrings.alt        3.1.1
MarkupSafe          1.1.1
mohawk              1.1.0
pip                 18.1
pycparser           2.20
pycrypto            2.6.1
pycurl              7.43.0.2
PyGObject           3.30.4
PyJWT               2.0.1
pymongo             3.11.2
pyparsing           2.4.7
PySimpleSOAP        1.16.2
python-apt          1.8.4.3
python-dateutil     2.8.1
python-debian       0.1.35
python-debianbts    2.8.2
pytz                2021.1
pyxdg               0.25
PyYAML              5.4.1
reportbug           7.5.3-deb10u1
requests            2.21.0
requests-hawk       1.1.0
SecretStorage       2.3.1
sentry-sdk          0.19.5
setuptools          40.8.0
six                 1.12.0
tabulate            0.8.7
unattended-upgrades 0.1
urllib3             1.24.1
Werkzeug            1.0.1
wheel               0.32.3`

I don't know what I'm missing or have done wrong. If you need any further information, I'll be happy to provide it.
Any help would be very much appreciated.

Thanks,
Kurt

**Comment by satterly** [comment]
Install a version of PyJwt less than 2.x.

**Comment by kb70** [comment]
Hi,

ok, I uninstalled the 'pip3 PyJWT package' and installed the debian package 'python3-jwt' instead. This is version 1.7.0-2.
Now alerta starts and works.

Thanks for your help.
