### ISSUE TITLE
Add CLUSTER column with deduplication from Alertmanager tag

### ISSUE THREAD

**Issue by anvpetrov** [alerta/alerta#1463]
**Is your feature request related to a problem? Please describe.**
We have some Openshift clusters. From all clusters we send alerts to Alerta with external tag CLUSTER.
Now we can not add cluster column with deduplication.
**Describe the solution you'd like**
Add custom columns from Alertmanager tags to Alerta with the ability to deduplicate with this tag
**Describe alternatives you've considered**
Now I add tag instance: {{ $labels.cluster }} and add instance to Event (event: Alertname:{{$labels.instance}})

**Comment by satterly** [comment]
I would add the cluster label to the resource, because that's what uniquely identifies the source of the alert. That is the designed solution.
