### ISSUE TITLE
Migrate Alerta from one server to another

### ISSUE THREAD

**Issue by raghu033** [alerta/alerta#1469]
Hi All,

Need help with steps on migrating alerta from 1server to another.
Please suggest me few steps to migrate without hurdles.

**Comment by satterly** [comment]
It all depends where you database is located. If it's on the same server as Alerta then you'll need to backup the data and reinstall using standard db tools. If the database is on dedicated infrastructure, as it should be, then it's just a matter of pointing the new Alerta server at the current database.
