### ISSUE TITLE
Enabling AzureAD - Cannot read property 'data' of undefined     at UserLogin.vue:189

### ISSUE THREAD

**Issue by cukal** [alerta/alerta#1481]
**Issue Summary**
I'm trying to setup authentication with Azure according https://docs.alerta.io/en/latest/authentication.html#azure-ad-oidc.
Tried the provider azure and openid (with OAUTH params) but I always end up with the same error in browser console: 

```
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at UserLogin.vue:189
```

**Environment**
- OS: Linux
- API version: latest
- Deployment: docker

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Azure / opened
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: latest docker

**Docker envs:**

```
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - PLUGINS=blackout,normalise,enhance,prometheus,acked_by
      - DEFAULT_EXPIRED_DELETE_HRS=48
      - DEFAULT_INFO_DELETE_HRS=24
      - AUTH_REQUIRED=True
      - AUTH_PROVIDER=azure
      - AZURE_TENANT=dd1600b0-3b29-43f4-accc-8ae523225dad
      - OAUTH2_CLIENT_ID=************
      - OAUTH2_CLIENT_SECRET='************'
      - ADMIN_USERS='********@******.com'
      - ALLOWED_EMAIL_DOMAINS='*******.com'
```

Console logging when starting shows:

```
web_1  | 2021-03-12 12:48:47,674 urllib3.connectionpool[40]: [DEBUG] Starting new HTTPS connection (1): login.microsoftonline.com:443
web_1  | 2021-03-12 12:48:47,833 DEBG 'uwsgi' stdout output:
web_1  | 2021-03-12 12:48:47,831 urllib3.connectionpool[40]: [DEBUG] https://login.microsoftonline.com:443 "GET /dd1600b0-3b29-43f4-accc-8ae523225dad/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1651
```

**Comment by satterly** [comment]
What's in the web browser developer console network tab for the auth requests and responses?

**Comment by cukal** [comment]
Thanks for your _quick_ reply!

I don't really see any auth requests/response, it's like the redirect to authenticate against Azure is not getting to my browser.

network tab screenshot: https://monosnap.com/file/XPB1vPyzpgC08AKVNtdjbOlfQAdyVc

When I check in debugger the snippet below it does get filled in with the env values but breaks on

 ```  .then(() => this.$router.push({ path: this.$route.query.redirect || '/' }))```

```
    authenticate() {
      if (this.authProvider) {
        this.message = `Authenticating with ${this.authProvider} ...`
        this.$store
          .dispatch('auth/authenticate', this.$config.provider)
          .then(() => this.$router.push({ path: this.$route.query.redirect || '/' }))
          .catch(error => this.error = error.response.data.message)
      } else {
        this.message = i18n.t('AuthNotPossible')
        this.error = `Unknown authentication provider (${this.$config.provider})`
      }
    },
```

**Comment by cukal** [comment]
Ok, watching my own screenshot I saw the red dot in the browser bar. /facepalm.

It's actually doing a popup and not a redirect in the same page and Chrome is blocking it. 
When allowing the popup the authentication page comes up!
