### ISSUE TITLE
Groups not visible in navigation bar 

### ISSUE THREAD

**Issue by devops-42** [alerta/alerta#1485]
**Issue Summary**
Hi,

I need some assistance to get permissions assignment according to LDAP groups running. 

In my `alertad.conf`(see below) I used `LDAP_GROUP_FILTER` to retrieve all group memberships for a certain account. 
When logging in to Alerta as a member of group "A" I can verify by clicking on "Profile" that group membership has been detected correctly. But when logging in with an admin account I cannot see those groups when editing the user. Moreover, I miss the "Groups" entry in the left navigation bar. Calling the /groups URL leads to an error message "Sorry, nothing to display here :("

**Environment**
- OS: Linux
- API version: [eg. 8.4.1]
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP,
  Customer views? Yes
  (or provide the `/config` endpoint output)

Snippet from alertad.conf:
```
AUTH_PROVIDER = 'ldap'
LDAP_URL = 'ldap://localhost:389'
LDAP_ALLOW_SELF_SIGNED_CERT = 'false'

LDAP_USER_BASEDN = 'ou=users,dc=example,dc=org'
LDAP_USER_NAME_ATTR = 'uid'

LDAP_GROUP_BASEDN = 'ou=groups,dc=example,dc=org'
LDAP_GROUP_FILTER = '(&(member={userdn})(objectClass=groupOfNames))'
LDAP_GROUP_NAME_ATTR = 'cn'

LDAP_DEFAULT_DOMAIN = 'example.org'
LDAP_DOMAINS = {
    'example.org': 'uid=%s,ou=users,dc=example,dc=org',
```

- web UI version: [eg. 8.4.1]
- CLI version: [eg. 8.4.0]

**To Reproduce**
1. Deploy an Alerta service using the configuration snippet for `alertad.conf` above
2. Login as regular user
3. Click on "Profile" to verify group memberships retrieved from LDAP
4. Logout and login using an admin account
5. Click on "Users", choose the regular user used in step 2 and click on the "edit" icon
6. In the appearing box click on Groups => nothing to see
7. Verify the menu list in the navigation bar, the entry "Groups" is missing

**Expected behavior**
Groups from LDAP should be visible in the "Users" section, the "Groups" section should be visible too, when group memberships are detected. 

Would  you tell me what I'm missing in my configuration?

Thanks in advance!

**Comment by satterly** [comment]
The "Groups" menu option is only active when using "BasicAuth" as the auth provider. When using LDAP the LDAP groups for a user are used. What you might be missing is that you need to assign permissions to roles and those roles can then be mapped to groups.
