### ISSUE TITLE
Timeout and Duplication Settings

### ISSUE THREAD

**Issue by ValentinPifu** [alerta/alerta#1487]
Hello,
This is just a question and maybe an feature request if it doesn't exist. (I don't find it anywhere)

I'm using praeco+elastalert ( https://github.com/johnsusek/praeco ) in docker and I installed alerta on docker too.

1. How can I extend the timeout to like 2-3 days? I didn't find where to set this.
2. I have a filter on elastalert for any **java.lang.NullPointerException** but it's not only 1 error, they are multiples. Can this errors enter on separate alert on alerta? The 15 errors (the major one) to have each individual lines.

![Screenshot from 2021-03-22 17-02-39](https://user-images.githubusercontent.com/18114871/112011029-87ebca00-8b30-11eb-8a4d-d0b070cf600d.png)

Thank you.

**Comment by satterly** [comment]
1. https://docs.alerta.io/en/latest/configuration.html#timeout-settings
2. https://docs.alerta.io/en/latest/gettingstarted/tutorial-4-alerts.html#step-2-simple-correlation

**Comment by pantelis-karamolegkos** [comment]
Is the `ALERT_TIMEOUT` the time it takes before an alert becomes expired?
