### ISSUE TITLE
Add API to manage groups for basic authentication

### ISSUE THREAD

**Issue by danielelopez1** [alerta/alerta#1491]
**Is your feature request related to a problem? Please describe.**
Is possible to create groups, and use them to associate an user to multiple client, but is not possible to manage it by API or CLI.
The goal is to associate multiple clients to single user by API

**Describe the solution you'd like**
Insert into user API the possibility to associate one (or more) group(s) to user (ex. in user update or user create API)

**Describe alternatives you've considered**
Create an API to manage groups (but i think this is too much effort if we consider the actual Alerta structure)
Or add a command to alerta CLI to link group(s) to user(s)

Thanks for your work.

**Comment by lpolone** [comment]
Same problem here, can somebody tell us if that request is possible? thanks

**Comment by satterly** [comment]
Yes, this is already possible -- just poorly documented. The API endpoints you are interested in a here ... https://github.com/alerta/alerta/blob/master/alerta/views/groups.py

In summary ...

```
create_group | POST | /group | Create a user group
get_group | GET | /group/:id | Get a user group
update_group | PUT | /group/:id | Update a user group
add_user_to_group | PUT | /group/:id/user/:userid | Add a user to a group
remove_user_from_group | DELETE | /group/:id/user/:userid | Remove a user from a group
get_group_users | GET | /group/:id/users | Get list of users assigned to a group
list_groups | GET | /groups | List all user groups
delete_group | DELETE | /group/:id | Delete a user group
```

**Comment by satterly** [comment]
There are some new options added to the `alerta` CLI to support adding and removing users to/from groups.

```
$ alerta group --name foo --text bar -h                                                             
Usage: alerta group [OPTIONS]

  Create or delete a user group, add and remove users from groups.

  EXAMPLES

      Create a group.

          $ alerta group --name <group-name> --text <description>

      Add a user to a group.

          $ alerta group -id <group-id> --user <user-id>

      List users in a group.

          $ alerta group <group-id> --users

      Delete a user from a group.

          $ alerta group -id <group-id> -D <user-id>

      Delete a group.

          $ alerta group -D <group-id>
```
