### ISSUE TITLE
Prevent the deletion of "closed" alerts

### ISSUE THREAD

**Issue by DB-CL** [alerta/alerta#1493]
**Is your feature request related to a problem? Please describe.**
During the night, I have a few events going on and then closing themself because the problematic behavior just stopped. The alerts in alerta close ... and disappear forever after a short amount of time. I can't have any details about my problem anymore.

**Describe the solution you'd like**
I would like alerta to stop deleting the closed alerts. Or even better, to delay it by the amount of time I chose in the configuration (for example a few weeks).
I tried to use the housekeeping variables (https://docs.alerta.io/en/latest/configuration.html#housekeeping-settings) but it looks like it has no effect on the closed alerts, alerta still delete these alerts very quiclky.

**Describe alternatives you've considered**
I tried to play with every variables with "timeout" in the name with no effect on closed alerts

**Additional context**
I'm using the latest docker version of Alerta

**Comment by satterly** [comment]
> I tried to use the housekeeping variables (https://docs.alerta.io/en/latest/configuration.html#housekeeping-settings) but it looks like it has no effect on the closed alerts, alerta still delete these alerts very quiclky.

Please share your config.

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).

**Comment by DB-CL** [comment]
Sure, here is my alertad.conf

```
SECRET_KEY = 'XXXXX'
HISTORY_LIMIT = 100000
DEFAULT_EXPIRED_DELETE_HRS = 8760
DEFAULT_INFO_DELETE_HRS = 8760
SITE_LOGO_URL = 'https://myurl.com/logo.png'
COLUMNS = ['severity', 'status', 'resource', 'service', 'value', 'text', 'lastReceiveTime', 'duplicateCount', 'environment', 'event', 'customer']
```

**Comment by satterly** [comment]
Instead of putting a massive number of hours you can zero it should skip deletion completely...
```
# Housekeeping settings
DEFAULT_EXPIRED_DELETE_HRS = 0  # hours (0 hours = do not delete)
DEFAULT_INFO_DELETE_HRS = 0  # hours (0 hours = do not delete)
```

**Comment by satterly** [comment]
And can you confirm your config is being read by Alerta by checking for the settings in `/management/properties` endpoint, similar to this http://alerta-api.herokuapp.com/management/properties

**Comment by DB-CL** [comment]
Yes, when I go to this endpoint I can find this :

```
'DEFAULT_EXPIRED_DELETE_HRS': 8760
...
'DEFAULT_INFO_DELETE_HRS': 8760
```

So it's well read. Also I played with the SIGNUP_ENABLED this afternoon and it worked well.

I will try with 0 now and tell you if it is working this week end, but this is not what I want because I want these alerts to eventually disappear.

I thought these two parameters were for expired alert (and info alerts) and not closed alerts, do you confirm DEFAULT_EXPIRED_DELETE_HRS should also impact closed alerts ?

Thanks !

**Comment by DB-CL** [comment]
I can confirm that putting the values to 0 did not change anything. My closed alerts are still getting deleted.

**Comment by escoand** [comment]
I experienced the same problem with the docker image. The values in the config are ignored but the values of the environment are used.

https://github.com/alerta/docker-alerta/blob/a9e3a0b8ca9303dfeded0c2ed63809e83cf6b5e3/supervisord.conf#L16

**Comment by satterly** [comment]
OK Thanks. That's a bug. 👍

**Comment by DB-CL** [comment]
Thx @escoand I will try to set these env variables. 

I find it strange that in the endpoint given by the API I can see the values in my configuration file, that would mean that endpoint is not displaying the values taken by alerta ?

**Comment by DB-CL** [comment]
Oh no I think I got it. The configuration is well read by alerta but not by the housekeeping program. My bad.

**Comment by escoand** [comment]
> Oh no I think I got it. The configuration is well read by alerta but not by the housekeeping program. My bad.

Exactly the housekeeping knowns the config values but it's called with the explicit env values.

**Comment by escoand** [comment]
@satterly Why aren't you removing the explicit values passed to the housekeeping job and instead read `DEFAULT_EXPIRED_DELETE_HRS` and `DEFAULT_INFO_DELETE_HRS` from the docker environment?

**Comment by satterly** [comment]
Good question. The reason I hadn't merged this PR yet is because I didn't think it looked right. I think I'll deprecate the `HK_` settings and just use the `DEFAULT_` ones.

**Comment by satterly** [comment]
This should be fixed. New settings ...
```
DELETE_EXPIRED_AFTER = 2 * 60 * 60  # seconds (0 = do not delete)
DELETE_INFO_AFTER = 12 * 60 * 60  # seconds (0 = do not delete)
```
