### ISSUE TITLE
Issue while loading alerta web UI

### ISSUE THREAD

**Issue by kavanat** [alerta/alerta#1502]
**Issue Summary**
When I load alerta UI, it displays a empty alerta dashboard with no data available
In console I see Typerror: r.replace is not a function

**Environment**
- OS: [Linux]
- API version: [8.5.0]
- Deployment: [Self-hosted]
- For self-hosted, WSGI environment: []

- Database: [Postgres]

- Server config:
  Auth enabled? Yes
  Auth provider? Basic Auth
  Customer views? Yes
  (or provide the `/config` endpoint output)

- web UI version: [7.4.0]
- CLI version: []

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Screenshots**
![1618930267985](https://user-images.githubusercontent.com/13285594/115417763-863c2180-a216-11eb-9491-e215a64282a3.jpg)

**Additional context**

Alerta is installed with pip

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
Is the web UI version really 7.4.0? And can you check the network tab for any http errors?

**Comment by kavanat** [comment]
Thanks @satterly 
Yes the version of Alerta API version is 7.4.0. When I downgrade alerta API version to 7.4.1, this above error I posted is not there but I get this error
`{
"code": 500,
"errors": null,
"message": "cannot cast type record to history\n LINE ......:: history]...\n DETAIL: Input has too few columns.\n",
"requestId", null,
"status", "error"
}
`

**Comment by satterly** [comment]
Why not just run the most recent versions of both the web UI and API. The reason there are new versions is because I've fixed bugs in previous versions. Don't downgrade the web UI; upgrade the API.

**Comment by kavanat** [comment]
So what are the suggested versions I should be using for web UI and API?

**Comment by satterly** [comment]
I suggest you run the latest versions of each. See https://github.com/alerta/alerta/releases and https://github.com/alerta/alerta-webui/releases

**Comment by kavanat** [comment]
Thanks @satterly

**Comment by kavanat** [comment]
Hello,
I have installed latest alerta api using python but I'm unable to update alerta web ui using pip install. Could you please help?

**Comment by kavanat** [comment]
Hello @satterly ,

When I load alerta we Ui and try to login I get this error
`Object of type bytes is not josn serializable (500)`

**Comment by satterly** [comment]
>  I'm unable to update alerta web ui using pip install.

It's not a python package, that would be why. You need to tell me exactly what command you run when you get an error, not just the error.
