### ISSUE TITLE
Blackouts based on attributes

### ISSUE THREAD

**Issue by mjtice** [alerta/alerta#1512]
**Is your feature request related to a problem? Please describe.**
No problems!

**Describe the solution you'd like**
Being able to set a blackout based on the alerts attributes would give additional fine-grained control over what gets blacked out.

**Describe alternatives you've considered**
I'm not sure there are really alternatives to this.  We can already set blackouts on a number of properties of the alert but some of them are rigidly set by the producing application (see context below).

**Additional context**
We push data into Alerta from Netdata.  Netdata statically sets some properties of the alert that aren't particularly helpful when it comes to Alerta.  However, Netdata does set some useful attributes.  See: https://github.com/netdata/netdata/blob/b053c8423e86785efa2d5c743daa331f623107c0/health/notifications/alarm-notify.sh.in#L1541

edit:
While this would be useful for Netdata I think it would be very useful in general for everyone (not just Netdata users)

**Comment by satterly** [comment]
The solution is to use tags. Create a plugin that dynamically assigns tags to alerts as they are received based on the criteria that you would use to blackout those alert groups. Then create blackout periods using those tags.
