### ISSUE TITLE
API key: Use custom value on creation

### ISSUE THREAD

**Issue by devops-42** [alerta/alerta#1517]
Hi @satterly,

it‘d would be great if the value of an API key could be predefined in the creation request, e.g.:

```
curl -XPOST http://localhost:8080/key \
-H 'Authorization: Key demo-key' \
-H 'Content-type: application/json' \
-d '{
      "user": "admin@alerta.io",
      "scopes": ["write"],
      "text": "API key for external system",
      "key“: "abcde12355“
    }'
```

This feature would facilitate automated deployments for multiple customers.

Thanks and cheers!

**Comment by satterly** [comment]
Added. It will be included in the next release.
