### ISSUE TITLE
Trigger Heartbeat alerts

### ISSUE THREAD

**Issue by momo3038** [alerta/alerta#1529]
Hello

I'm trying to setup Heartbeat alerts and I saw that we only way to trigger Heartbeat alert is to use the Alerta CLI. 

Is there another way to to it ? With the API ? I didn't see that in the documentation. (https://docs.alerta.io/en/latest/server.html#heartbeats)

If the CLI is the only way. What is the standard setup ? To install the CLI somewhere and trigger the command line each X minutes or hours like a CRON job ? 

Thanks a lot for your help.

**Comment by satterly** [comment]
You could script something yourself to use the API directly if you want. Otherwise the alerta CLI is it. And yes, use some sort of job scheduler to run it as often as you want/need.

**Comment by momo3038** [comment]
Is an option available is the API to trigger Alerts from stale Heartbeat ?

**Comment by momo3038** [comment]
OK understood. I can use the Heartbeat ALL or GET API to trigger manually new alert. Thanks
