### ISSUE TITLE
Limitation of wathcing alert

### ISSUE THREAD

**Issue by benbenai7786** [alerta/alerta#1532]
Hi guys, just curious, Does alerta support classfication of alert according to the user or user's group. For example, david just could see "event=XXX" alert in alerta. Dev group is allowed to see "environment=development" alerts. :)

**Comment by satterly** [comment]
No. If you want to partition alerts by user, you have to use "customer views". However, customer views is targeted at multi-tenancy deployments where a single Alerta installation is used by multiple different customers so I think that is not a good fit for this use-case.
