### ISSUE TITLE
Healthcheck broken as of v8.4.1 with MongoDB 5.0

### ISSUE THREAD

**Issue by creganFL** [alerta/alerta#1554]
**Issue Summary**
/api/management/healthcheck after Alerta v8.3.3 is broken

**Environment**
- OS: Ubuntu 16 LTS
- API version: 8.4.1 & 8.5.0
- Deployment: Docker

- Database: MongoDB 5.0

- Server config:
  Auth enabled? No
  Customer views? No

- web UI version: 8.4.1 & 8.5.0
- CLI version: 8.4.1 & 8.5.0

**To Reproduce**
GET /api/management/healthcheck
On v8.4.1, returns 503 STATUS with BODY: `HEALTH_CHECK_FAILED: must use a list of (key, direction) pairs, not: 'lastReceiveTime'`
On v8.5.0, returns 503 STATUS with BODY: `HEALTH_CHECK_FAILED: must use a list of (key, direction) pairs, not: '_id'`

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
`200 OK`

**Additional context**
I tried testing with MongoDB 4.x but am having issues getting that to work in our env and abandoned that testing, but MongoDB 5.0 is now the latest branch as of last week. 

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by 3IMOH** [comment]
Can you provide more information on this? I am unable to reproduce.
