### ISSUE TITLE
Event Correlation during Outages/High Priority Incidents to prevent noisy alerts.

### ISSUE THREAD

**Issue by p-24** [alerta/alerta#1560]
**Is your feature request related to a problem? Please describe.**
Can we have another kind of correlation like  "**event and environment based**" correlation( ie; irrespective of resource), considering some time period. This helps in reduction of alert volume during incidents. And all the resources which are having same issue can be caught from one alert.
Please refer to the below scenario :
Let us consider there is some application that went down due to recent deployment bug and that is impacting several zones/resources at the same time frame. So the current alerta workflow would create 4 different alerts.

-  Severity : Major, Environment: Production, Event : 5xx response High, Resource : us-west1
-  Severity : Major, Environment: Production, Event : 5xx response High, Resource : us-east2
-  Severity : Major, Environment: Production, Event : 5xx response High, Resource : ap-east-1
-  Severity : Major, Environment: Production, Event : 5xx response High, Resource : eu-north-1

It would have been good if one alert is generated.

**Describe the solution you'd like**
Can we have some queries added to the database. When any new alert comes to the alerta engine, then database should check if there is any other exisiting alert for the same _event and environment_ for last 30 minutes, without considering the other attributes. If yes, then correlate those two alerts. Add the new alert resource to the existing alert resource group and update the old alert.

Additional points :
1) We may need resource attribute to be of list type
2) Interval during which this event co-relation should happen can be provided through alerta.conf .

Please let me know if this can be implemented in Alerta and would be much helpful to me :slightly_smiling_face:

**Comment by 3IMOH** [comment]
I understand the need here but this sounds like quite a change to the way alerts are correlated...will let @satterly speak to this. One thought I had was that you could write an external script that polls alerta via the API and does this correlation for you. You could then create a new "super" alert (possibly a different color) that would have your existing alerts combined.

**Comment by satterly** [comment]
This is a significant enhancement and fundamentally changes how alerts are correlated. I suggest you either investigate the use of a pre-correlation step before passing the alerts to Alerta or try the solution proposed by @3IMOH 

https://simple-evcorr.github.io/
https://www.drools.org/
https://www.espertech.com/esper/
