### ISSUE TITLE
Alerta alert.is_blackout() is return True even when blackout rule has expired

### ISSUE THREAD

**Issue by sushovan23** [alerta/alerta#1563]
**Issue Summary**
We have custom plugin where we decide the notification state based on alerta.is_blackout().
in the `post_receive` we have following code:

```
    def post_receive(self, alert):
        is_blackout = alert.is_blackout()
        do_not_notify = app.config.get('NOTIFICATION_BLACKOUT')  #setting to true always

        if do_not_notify and is_blackout:
            LOG.info('Suppressed notifications during blackout period (id=%s)' % alert.id)
            alert.attributes['notify'] = False
        elif "shelved" in alert.status:
            LOG.info('alert is shelved in UI')
            alert.attributes['notify'] = False
        elif do_not_notify and not is_blackout:
            alert.attributes['notify'] = True

        return alert
```

**Environment**
- OS: centos7
- API version: 
alerta                8.3.0
alerta-server         8.3.3

- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi 
- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? OpenID
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: 8.4.0
- CLI version: alerta client 8.3.0

**To Reproduce**
1. Create a blackout rule which will expire within an hour. (for example 3pm - 4pm)
2. Fire an alert which matches the blackout rule condition.
3. Make sure alert is in blackout state in alerta ui.
4. Wait for blackout rule to expire.
5. Refire the same alert after rule has expired.
6. State changed from blackout to Open but `Notify` attribute is set to false because of above code in Custom plugin.
We can see following log:
alerta.plugins.routing[19236]: [INFO] Suppressed notifications during blackout period (id=ba601351-697d-4099-bde7-37f74deea08b)

**Expected behavior**
since the blackout rule has expired we expect alert.is_blackout() to return False.

**Screenshots**

**Additional context**

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by sushovan23** [comment]
Looks like https://github.com/alerta/alerta/blob/3511ec02318c93fa568e9a25a2978c9943102b59/alerta/database/backends/mongodb/base.py#L962-L965

        query = dict()
        query['startTime'] = {'$lte': alert.create_time}
        query['endTime'] = {'$gt': alert.create_time}
        
looks like endTime needs to be checked against last_receive_time . Please let us know if that looks correct?

**Comment by sushovan23** [comment]
update - I modified the `is_blackout_period` to make `query['startTime']` and `query['endTime']` both use `alert.last_receive_time` but when I add check in my `pre_receive` function in custom plugin still `alert.is_blackout` is returning False. 
but that `alert.is_blackout()` when I put in `post_receive` is returning True. Which is correct behavior.

However inorder to show the alert correctly in UI. I need to modify the `alert.status` which can only be done in `pre_receive` 
So while my fix has fixed the issue of setting customer attribute based on `is_blackout` in post_receive. I still cannot set the status to blackout as that function is not working in pre_receive. 

Let me know how this can be fixed. Thanks

**Comment by satterly** [comment]
You can't use `last_receive_time` in the `pre_receive()` hook because the alert hasn't been processed yet. So you will need to change your plugin to use `alert.is_suppressed` instead of `alert.is_blackout()`, like so...

```
    def post_receive(self, alert):
        is_blackout = alert.is_suppressed
        do_not_notify = app.config.get('NOTIFICATION_BLACKOUT')  #setting to true always

        if do_not_notify and is_blackout:
            LOG.info('Suppressed notifications during blackout period (id=%s)' % alert.id)
            alert.attributes['notify'] = False
        elif "shelved" in alert.status:
            LOG.info('alert is shelved in UI')
            alert.attributes['notify'] = False
        elif do_not_notify and not is_blackout:
            alert.attributes['notify'] = True

        return alert
```

**Comment by sushovan23** [comment]
Is is_suppressed() a new method or available always? Wanted to know to figure out if only plug-in update is needed or alerta also
