### ISSUE TITLE
docs: duplication count

### ISSUE THREAD

**Issue by mkp-gebensleben** [alerta/alerta#1568]
It is not clear to me from the documentation when exactly the duplication count of an alert is incremented/reset.

For example, [this](https://docs.alerta.io/en/latest/gettingstarted/tutorial-4-alerts.html#step-1-de-duplication) section seems to imply that duplicates are counted based on the same `event` and `resource`. 

However, I noticed that the duplication counter also resets to 0 when the `severity` changes, even if `event` and `resource` was the same as the last alert. I don't know whether there are more undocumented cases like this.

----

Context: I'm trying to figure out whether the alert I posted last led to a severity change.

**Comment by satterly** [comment]
> When an alert with the same `environment-resource-event` combination is received with the **same** `severity`, the alert is de-duplicated.

See https://docs.alerta.io/en/latest/server.html#de-duplication
