### ISSUE TITLE
remote_user authentcation via proxy

### ISSUE THREAD

**Issue by keith6014** [alerta/alerta#1578]
I am not sure if its avaliable but with a proxy server server it would be great if I can pass remote_user for authentication.

**Comment by satterly** [comment]
Can you provide a bit more information about how this works? I'm not familiar with remote_user. Do you have a web reference or can you point to another web app that does something similar to what you describe? Thanks.

**Comment by keith6014** [comment]
Yes, here is an example with Grafana.

https://community.grafana.com/t/how-to-use-auth-proxy-with-nginx/2257/6

**Comment by satterly** [comment]
Thanks for the link, I understand the issue now. You want a proxy to be able to do the authentication and just pass the authenticated user name to Alerta. I'll add this to the backlog.

**Comment by satterly** [comment]
Found another example using OpenSearch security plugin https://opensearch.org/docs/latest/security-plugin/configuration/proxy/
