### ISSUE TITLE
Customer views - can't login and see alarms - NoCustomerMatch - mongoDb

### ISSUE THREAD

**Issue by sandrorotabulo** [alerta/alerta#1584]
Issue Summary
Unable to see alerts with Customer views.

OS: Linux RedHat 8
Deployment: Normal way (not Docker)
Database: MongoDb
Server config:
Auth enabled? Yes
Auth provider? Basic
Customer views? Yes

To Reproduce
  

> user-test created via Web-Ui with Permissions : User (role)
>   created an api Key linked with this user-test
>   Login as User (Read & Write roles)

Can't Login

Expected behavior
Login AND See all alarms from all customers as User Read & Write.

Additional context
Error in alerta:

> 2021-10-06 10:55:40,752 - alerta.app[2021715]: ERROR - sequence item 0: expected str instance, NoneType found [in /home/.local/lib/python3.6/site-packages/alerta/exceptions.py:126]
Traceback (most recent call last):
  File "/home/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/.local/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/.local/lib/python3.6/site-packages/alerta/auth/login.py", line 15, in login
    return basic.login()
  File "/home/.local/lib/python3.6/site-packages/alerta/auth/basic.py", line 94, in login
    customers = get_customers(login=user.login, groups=[user.domain] + groups)
  File "/home/.local/lib/python3.6/site-packages/alerta/auth/utils.py", line 42, in get_customers
    return Customer.lookup(login, groups)
  File "/home/.local/lib/python3.6/site-packages/alerta/models/customer.py", line 86, in lookup
    customers = db.get_customers_by_match(login, matches=groups)
  File "/home/.local/lib/python3.6/site-packages/alerta/database/backends/mongodb/base.py", line 1465, in get_customers_by_match
    raise **NoCustomerMatch(f"No customer lookup configured for user '{login}' or '{','.join(matches)}'")**
TypeError: sequence item 0: expected str instance, NoneType found
2021-10-06 10:55:40,755 - alerta.app[2021715]: INFO - "POST /auth/login HTTP/1.0" 500 1646 

Thanks for your help

**Comment by sandrorotabulo** [comment]
DEBUG = True

ALERT_TIMEOUT = 43200  # 12 hours

AUTH_REQUIRED = True
CUSTOMER_VIEWS = True
SECRET_KEY = '************************'
ADMIN_USERS = ['admin@alerta.io', 'users for our group']

USER_DEFAULT_SCOPES = ['read', 'write:alerts']
GUEST_DEFAULT_SCOPES = ['read:alerts']

#BASE_URL = '/api'
BASE_URL = 'https://******************/api/'  # for SAML2 Authentication it should be HTTPS

ALERTMANAGER_API_URL='http://*********************:9093'
USE_PROXYFIX = True  # use if proxy is terminating HTTPS traffic

LOG_FILE = '/var/log/alertad.log'
LOG_HANDLERS = ['console','file']
LOG_FORMAT = 'verbose'
PLUGINS=['reject','blackout']
ALLOWED_ENVIRONMENTS=['Production', 'Development', 'Code', 'None', 'Acceptation']
COLUMNS = ['severity', 'status', 'lastReceiveTime', 'timeOut', 'duplicateCount', 'customer', 'environment', 'service', 'resource', 'event', 'value', 'ticket', 'text',      'region', 'createTime','status', 'correlate', 'id','group','origin','type', 'previousSeverity']


##BASIC AUTHENTICATION
AUTH_PROVIDER = 'basic'
SIGNUP_ENABLED = True

#SAML2 Authenication 
#AUTH_PROVIDER = 'saml2'
SAML2_CONFIG = {
    'metadata': {
        'local': ['/home/FederationMetadata.xml']
    },
    'key_file': '/home/alerta.key',
    'cert_file': '/home/alerta.cert'
}
SAML2_ENTITY_ID = 'https://***************/api'
SAML2_METADATA_URL = 'https://**************/FederationMetadata/2007-06/FederationMetadata.xml'
#SAML2_USER_NAME_FORMAT = '{first_name} {last_name}'
SAML2_EMAIL_ATTRIBUTE = 'email'
#SAML2_CONFIG = {}
#ALLOWED_SAML2_GROUPS = ['*']


SEVERITY_MAP = {
    'fatal': 0,
    'critical': 1,
    'major': 2,
    'minor': 3,
    'warning': 4,
    'indeterminate': 5,
    'ok': 5,
    'informational': 5,
    'trace': 9,
    'unknown': 9,
    'error': 9
}

DEFAULT_NORMAL_SEVERITY = 'ok'

COLOR_MAP = {
    'severity': {
        'fatal': 'blue',
        'critical': 'red',
        'major': 'orange',
        'minor': 'yellow',
        'warning': '#1E90FF',
        'indeterminate': 'lightblue',
        'ok': '#00CC00',
        'informational': '#00CC00',
        'trace': 'silver',
        'unknown': 'silver'
    }
}

**Comment by satterly** [comment]
I suspect this issue is related to missing login fixed in #1629.

**Comment by sandrorotabulo** [comment]
Sorry to reply late ... 

I will check it ... right now ... 

and I'll give you feedback.

;-)

**Comment by sandrorotabulo** [comment]
Ok, For each customer, we can setup an user with different Role (User, Guest) 
BUT
Can we have an user with User or Guest role, without Customer Lookup for a general view  ?
It means, a **_read user_** is connected to full alarms GUI only to view alarms....

Because I created an user with "USER" Role, but it's always an error message on login screen:**" NO CUSTOMER Lookup configured for this user !"** 

Thanks.

**Comment by sandrorotabulo** [comment]
I found finally the solution ...  :-) 

we need to use in the customer field value :  "*" when we add the new customer screen.
