### ISSUE TITLE
Action-set `ack` status cannot be unacked 

### ISSUE THREAD

**Issue by hugoShaka** [alerta/alerta#1587]
**Issue Summary**
An alert transitionned to the `ack` status by a custom action cannot be unacknowledged.

**Environment**
- OS: Linux
- API version: 8.6.0
- Deployment: Docker custom image
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

**To Reproduce**
1. Create a plugin with the following code
    ```
    def take_action(self, alert, action: str, text: str, **kwargs):
        if not action == "foo":
            return
        alert.status = Status.Ack
        return alert
    ```

2. Create a new alert
3. Run the `foo` action on it
4. Check the alert has correctly transitionned to the `ack` state (we can see `changeType` is `Action` in the history)
5. Try to un-acknowledge  the alert
6. You receive the error `Invalid action for current open status (409)`

**Expected behavior**
The alert transitions back to the `open` state without error (I don't really care about restoring the previous timeout or state).

**Screenshots**
![image](https://user-images.githubusercontent.com/16366487/136586119-9e2f81b3-831e-4a78-9040-a86b58e0c3f1.png)

**Additional context**
This behaviour is caused by the `Alert._get_hist_info(action)` method.

* During the `from_action()` treatment alerta retrieve the current state using `self._get_hist_info(action)`: https://github.com/alerta/alerta/blob/10db92318df25fad64c849c2f9bd93e96b0dee8f/alerta/models/alert.py#L627 
* the method looks back in the alert history to find the last known state
* but it has a special case handling for ack/unack and looks for ChangeType.ack events
* as this event never happened it returns None
* the alerta alarm_model `transition()` method then defaults to the status open, and refuses to open an already open alert, even if the alert is in the `ack` state in reality

I'm wondering if we could add a fallback if no `ChangeType.ack` event is found so it has the default behaviour of returning the last element. I think the following snippet would be backward compatible while solving this edge-case.

```
    def _get_hist_info(self, action=None):
        h_loop = self.get_alert_history(alert=self)
        if not h_loop:
            return None, None, None, None
        
        current_status = h_loop[0].status
        current_value = h_loop[0].value

        if len(h_loop) == 1:
            return current_status, current_value, None, None
        if action == ChangeType.unack:
            find = ChangeType.ack
        elif action == ChangeType.unshelve:
            find = ChangeType.shelve
        else:
            find = None

        # looking for a specific transition to undo
        if find:
            for h, h_next in zip(h_loop, h_loop[1:]):
                if h.change_type == find:
                    return status, value, h_next.status, h_next.timeout
        
        return current_status, current_value, h_loop[1].status, h_loop[1].timeout
```

I can submit a PR if you are OK with the suggested changes

**Comment by satterly** [comment]
@hugoShaka I've taken your suggested code fixes and created a PR. Thank for your input.
