### ISSUE TITLE
Extend 'openid' OAuth2 to make it more generic

### ISSUE THREAD

**Issue by michael-doubez** [alerta/alerta#1601]
### Problem
I am trying to make Alerta work with a custom OIDC which doesn't conform to the model implemented in openid:

- authentication method (with client_id/client_secret) requires a Basic auth and not passed in data
- user info fields are not those of openid (ex: `mail` instead of `email`)

### Solution
Either have a generic AUTH_PROVIDER = 'oidc' or reuse the existing 'openid' but with additional config to allow alternatives auth methods and different field mapping.

### Alternatives
Today, I have made it work by modifying the code:

- apply auth in oidc.py (option not shown):
  ```
    data = {
        'grant_type': 'authorization_code',
        'code': request.json['code'],
        'redirect_uri': request.json['redirectUri']
    }
    auth = (request.json['clientId'], current_app.config['OAUTH2_CLIENT_SECRET'])
    r = requests.post(token_endpoint, data, auth=auth)
   ```
- change the fields mapping:
   ```
   OAUTH2_INFO_FIELDS = {
      'name': ['name', 'given_name'],
      'username': ['preferred_username', 'login']
      ...
   }
   info_fields = current_app.config.get('OAUTH2_INFO ',  {}).update(info_defaults)
    name = next(userinfo.get(x) or id_token.get(x) for x in info_fields['name'] if userinfo.get(x) or id_token.get(x))
    username = ...
    ```

### Additional context

I think a different AUTH_PROVIDER would be better

- integrated it the existing oidc.py file but distinct from openid.
- triggering the alternate authentication
- the OAUTH mapping can stay generic

I am ready to contribute code if you agree with the feature.

**Comment by satterly** [comment]
I assume you realise this already but the whole point of a standard is that if all systems conform to it then you don't have to do what you are suggesting.

What custom OIDC are you referring to? Have you looked into whether they could confirm to the spec instead of everyone else having to conform to their non-standard implement?

**Comment by michael-doubez** [comment]
At a guess, they started with a simple OAuth service and then added what was needed to get something like OIDC.

I understand that this is non-standard. I could rebrand it to "Generic OAuth" and not mention OIDC but they do use a `/.well-known/openid-configuration` endpoint, which is convenient.

**Comment by michael-doubez** [comment]
Please note that the authentication part is OIDC compliant as OIDC defines multiple client authentication methods:
https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

I suppose the current implementation in alerta uses 'client_secret_post' while my clunky provider requires 'client_secret_basic'.

**Comment by satterly** [comment]
@michael-doubez I've added support for the other "client secret" token endpoint auth methods as suggested. This was a useful article that explains the differences ... https://darutk.medium.com/oauth-2-0-client-authentication-4b5f929305d4

If you are still interested in submitting a PR to support configurable JWT claim mapping please go ahead. Thanks.
