### ISSUE TITLE
Not list all environments

### ISSUE THREAD

**Issue by nilver** [alerta/alerta#1602]
**Not list all environments**
When a have more than 50 environments the /environments endpoint only returns 50 items because DEFAULT_PAGE_SIZE=50.
This affects when I need to create a blackout, then  I can`t get it all.

**Environment**
- OS: [Linux]
- API version: [eg. 6.8.1]
- Deployment: [ self-hosted]

- Database: [ Postgres]

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP, etc
  Customer views? No
  (or provide the `/config` endpoint output)

- CLI version: [eg. 8.5.0]

**To Reproduce**
1. Create more than 50 alerts with different environment
2. Consume /environments endpoint
3. See error (Only return the first 50 items)

**Comment by frasy** [comment]
@satterly I have tried to amend this issue adding test for postgres and mongodb and trying to patch webui as well. Could you please take a look and let me know if you miss anything?
* https://github.com/alerta/alerta/pull/2029
* https://github.com/alerta/alerta-webui/pull/600
