### ISSUE TITLE
Help to Setup alerta api scale up with ReplicaSet for MongoDB

### ISSUE THREAD

**Issue by sandrorotabulo** [alerta/alerta#1619]
Hi,
I installed 2 Alerta servers( with Uwsgi) with MongoDb on both Servers.
I will ask a loadbalancer for HA.
I put the DATABASE_URL And DATABASE_NAME on alertad.conf.

but for MongoDB : 
 - should It stay on Alerta servers or do we need to move it to a cluster ?
 - how do we configure replicaset and Where ?
 - do you have a guide line for that ?

Thanks.

**Comment by satterly** [comment]
I've added an example to the docker repo that demonstrates how to configure Alerta with a MongoDB replicaset.

Note the use of `replicaSet` param in the `DATABASE_URL` ... 

```
DATABASE_URL=mongodb://db0:27017,db1:27017/monitoring?replicaSet=rs0
```

**Comment by sandrorotabulo** [comment]
Thanks @satterly   :-) 

Question: 
- do we need always 3 nodes of MongoDb for replication behavior ?

**Comment by satterly** [comment]
three is the minimum number of members in a replica set. To reduce costs one of those may be an arbiter which can vote but does not sure data.

https://docs.mongodb.com/manual/core/replica-set-members/
