### ISSUE TITLE
Customer view based on github team on the same org

### ISSUE THREAD

**Issue by lotooo** [alerta/alerta#1624]
We are considering enabling CUSTOMER_VIEWS on our setup to delegate dedicated views to our developpers.

It's not technically customers, but this feature could be used for that purpose.

The missing part seems be able to assign "customerA" or "customerB"  to users  from the same github org  based on their github team.

**Comment by satterly** [comment]
The problem here is that a user from a organizationA that has access to customerA because they were in teamA could create a team called teamB and get access to customerB data. Belonging to an organization is controlled by GitHub. Creating a team name is controlled by the admins of an organization.

**Comment by satterly** [comment]
You can achieve what you want with the following setting ...

```
GITHUB_GROUP_CLAIM = 'teams'  # used in customer mapping
```
Note that team names are prefixed with the organisation name. For example a team called `justice-league` in the `github` organisation is represented as `github/justice-league`.
