### ISSUE TITLE
alerta + keycloak integration

### ISSUE THREAD

**Issue by Fran-78** [alerta/alerta#1638]
Good Day,

Having trouble with alerta - keycloak integration, 

**Created alerta keycloak client:** 

{
    "clientId": "my_alerta_clientid",
    "rootUrl": "my-alerta-url",
    "adminUrl": "my-alerta-url",
    "baseUrl": "my-alerta-url",
    "surrogateAuthRequired": false,
    "enabled": true,
    "alwaysDisplayInConsole": false,
    "clientAuthenticatorType": "client-secret",
    "redirectUris": [
        "http://*",
        "https://*"
    ],
    "webOrigins": [
        "*"
    ],
    "notBefore": 0,
    "bearerOnly": false,
    "consentRequired": false,
    "standardFlowEnabled": true,
    "implicitFlowEnabled": false,
    "directAccessGrantsEnabled": true,
    "serviceAccountsEnabled": true,
    "authorizationServicesEnabled": true,
    "publicClient": false,
    "frontchannelLogout": false,
    "protocol": "openid-connect",
    "attributes": {
        "saml.assertion.signature": "false",
        "saml.multivalued.roles": "false",
        "saml.force.post.binding": "false",
        "saml.encrypt": "false",
        "login_theme": "keycloak",
        "saml.server.signature": "false",
        "saml.server.signature.keyinfo.ext": "false",
        "exclude.session.state.from.auth.response": "true",
        "saml_force_name_id_format": "false",
        "saml.client.signature": "false",
        "tls.client.certificate.bound.access.tokens": "false",
        "saml.authnstatement": "false",
        "display.on.consent.screen": "false",
        "saml.onetimeuse.condition": "false"
    },
    "authenticationFlowBindingOverrides": {},
    "fullScopeAllowed": true,
    "nodeReRegistrationTimeout": -1,
    "protocolMappers": [
        {
            "name": "Client Host",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-usersessionmodel-note-mapper",
            "consentRequired": false,
            "config": {
                "user.session.note": "clientHost",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "clientHost",
                "jsonType.label": "String"
            }
        },
        {
            "name": "Client ID",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-usersessionmodel-note-mapper",
            "consentRequired": false,
            "config": {
                "user.session.note": "clientId",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "clientId",
                "jsonType.label": "String"
            }
        },
        {
            "name": "role memberships",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-usermodel-realm-role-mapper",
            "consentRequired": false,
            "config": {
                "multivalued": "true",
                "userinfo.token.claim": "true",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "roles",
                "jsonType.label": "String"
            }
        },
        {
            "name": "Client IP Address",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-usersessionmodel-note-mapper",
            "consentRequired": false,
            "config": {
                "user.session.note": "clientAddress",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "clientAddress",
                "jsonType.label": "String"
            }
        },
        {
            "name": "client roles",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-usermodel-client-role-mapper",
            "consentRequired": false,
            "config": {
                "user.attribute": "foo",
                "access.token.claim": "true",
                "claim.name": "resource_access.${client_id}.roles",
                "jsonType.label": "String",
                "multivalued": "true"
            }
        }
    ],
    "defaultClientScopes": [
        "web-origins",
        "role_list",
        "profile",
        "email"
    ],
    "optionalClientScopes": [
        "address",
        "phone",
        "offline_access",
        "microprofile-jwt"
    ],
    "access": {
        "view": true,
        "configure": true,
        "manage": true
    }
}

**Alerta Configmap:**

kind: ConfigMap
apiVersion: v1
metadata:
  name: alerta
  namespace: monitoring
  selfLink: /api/v1/namespaces/monitoring/configmaps/alerta
  uid: 12345678-1234-46f4-b3ca-877e7dd3a1be
  resourceVersion: '247750451'
  creationTimestamp: '2021-12-02T12:49:12Z'
  labels:
    app: alerta
    chart: alerta-0.2.1
    heritage: Helm
    release: alerta
  managedFields:
    - manager: OpenAPI-Generator
      operation: Update
      apiVersion: v1
      time: '2021-12-02T12:49:12Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:config.js': {}
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:chart': {}
            'f:heritage': {}
            'f:release': {}
    - manager: kubectl-edit
      operation: Update
      apiVersion: v1
      time: '2021-12-02T13:10:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:alertad.conf': {}
data:
  alertad.conf: >
    PLUGINS = ['normalise', 'enhance']
    AUTH_REQUIRED = True
    KEYCLOAK_URL = 'https://keycloak. #############/auth/realms/tools/protocol/openid-connect/auth'
    KEYCLOAK_REALM = 'tools'
    OAUTH2_CLIENT_ID = 'my_alerta_clientid'
    OAUTH2_CLIENT_SECRET = 'my_alerta_client_secret'  
    DATABASE_URL = "postgresql://alerta:changeme@postgresql:5432/monitoring"
    SEVERITY_MAP = {
    'S1': 1,
    'S2': 2,
    'indeterminate': 5,
    'ok': 5,
    'unknown': 9
    }
    DEFAULT_NORMAL_SEVERITY = 'ok'  # 'normal', 'ok', 'cleared'
    DEFAULT_PREVIOUS_SEVERITY = 'indeterminate'
    COLOR_MAP = {
    'severity': {
        'S1': 'red',
        'S2': '#1E90FF',
        'indeterminate': 'lightblue',
        'ok': '#00CC00',
        'unknown': 'silver'
    },
    'text': 'black',
    'highlight': 'skyblue '
    }
  config.js: |
    // contents of config.js
    'use strict';
    angular.module('config', [])
      .constant('config', {
        'endpoint'    : "/api",
        'provider'    : "basic"
      })
      .constant('colors', {});

-------------------------------------------------------------------------------

Ok, so in the configmap as you can see this: AUTH_PROVIDER = 'keycloak' is missing, as when we add this it breaks Alerta,
so currently its running but does not redirect at all. Alerta is running fine with local login. 
Current deployment version: alerta/alerta-web:8.6.4

When AUTH_PROVIDER = 'keycloak' is added to the config - i get the usual error: 
"ERROR: Failed to retrieve client config from alerta api endpoint /api/config.
This could be due to api not being available.......you know the rest.....

I did see something about self hosted & ssl certs'....not sure....

I see that alerta has 3 roles: admin, guest and user. Do these roles need to be aligned with keycloak roles. my guess would be yes, but this config i've also not added in configmap as for now.

I'm sure we are missing something here, other than from roles.

Some tips would be appreciated.

Thanks in advance.

**Comment by satterly** [comment]
Where did you get this kubernetes config from? More specifically that `config.js` is not valid for this version. It is for the old AngularJS web UI. The frontend now uses a `config.json` file. Is there one?

**Comment by Fran-78** [comment]
Hi, thanks for your response.

- api/config we receive internal server error while using auth_provider = 'keycloak'  
- if we use any other name in there eg: AUTH_PROVIDER = "keycloak1" the application runs without breaking. But obviously this is incorrect config. 
- we tried other image versions, same issue.
- keycloak is accessible from the deployment, so no issue there.

"alertad.conf": "PLUGINS = ['normalise', 'enhance']
		AUTH_REQUIRED = True
		AUTH_PROVIDER = "keycloak"
		KEYCLOAK_URL = 'https://keycloak.capsilondev.net/auth/realms/tools/protocol/openid-connect/auth'
		KEYCLOAK_REALM = 'tools'
		OAUTH2_CLIENT_ID = 'alerta-eksdevelop'
		OAUTH2_CLIENT_SECRET = '60f28f97-0760-4078-a158-e9ab05c36622'
		DATABASE_URL = \"postgresql://alerta:changeme@postgresql:5432/monitoring\"
		SEVERITY_MAP = {
		'S1': 1,
		'S2': 2,
		'indeterminate': 5,
		'ok': 5,
		'unknown': 9
		}
		DEFAULT_NORMAL_SEVERITY = 'ok'  # 'normal', 'ok', 'cleared'
		DEFAULT_PREVIOUS_SEVERITY = 'indeterminate'
		COLOR_MAP = {
		'severity': {
		    'S1': 'red',
		    'S2': '#1E90FF',
		    'indeterminate': 'lightblue',
		    'ok': '#00CC00',
		    'unknown': 'silver'
		},
		'text': 'black',
		'highlight': 'skyblue '
		}
		",
	"config.json": "{
		  \"endpoint\": \"https://k8s-alerta-eksdevelop.capsilondev.net/\"
		}
		"
}

**Comment by satterly** [comment]
I'll need to see your logs. Specifically the text of the internal server error you are seeing. And hopefully some context. ie. source code filenames and line numbers.

**Comment by Fran-78** [comment]
Hi, problem solved.

KEYCLOAK_URL = 'https://keycloak.capsilondev.net'

lol

Thanks for trying to assist!

**Comment by tbbkitty** [comment]
> Hi, problem solved.
> 
> KEYCLOAK_URL = 'https://keycloak.xxxxxxxxx.net'
> 
> and not KEYCLOAK_URL = 'https://keycloak.xxxxxxxx/auth/realms/tools/protocol/openid-connect/auth'
> 
> lol
> 
> Thanks for trying to assist!

My config is essentially a copy paste of yours, but when I try to sign in, the Keycloak pop up window shows Sorry, Page not found

Anyone have an idea?

**Comment by maehara-n** [comment]
@jrndberg
AUTH_PROVIDER: 'keycloak' does not work as expected at the moment.
Instead, you can use AUTH_PROVIDER: 'openid' to integrate with Keycloak.

For more details, please refer to the following issue:
https://github.com/alerta/alerta-webui/issues/604
