### ISSUE TITLE
400 Bad Request when deleting blackout due to audit write

### ISSUE THREAD

**Issue by moix** [alerta/alerta#1654]
**Issue Summary**
```
Trying to enable a cron job to purge periodically expired blackouts, the cmd raises the following error in debug mode:
send: b'DELETE /api/blackout/36efb467-e68a-4516-a97d-d7238f03e7a7 HTTP/1.1\r\nHost: api.alertaio.internal:5050\r\nUser-Agent: python-requests/2.25.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nX-Request-ID: a664d245-79fe-4f43-afd4-b41748c48e4b\r\nContent-Type: application/json\r\nContent-Length: 0\r\nAuthorization: Key F81G5Ea75OC1xJVUL5KURbUeiLvElzU2ajAtTygl\r\n\r\n'
reply: 'HTTP/1.1 400 BAD REQUEST\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: Access-Control-Allow-Origin header: Vary header: X-Request-ID
body: {"code":400,"errors":["The browser (or proxy) sent a request that this server could not understand."],"message":"400 Bad Request: The browser (or proxy) sent a request that this server could not understand.","requestId":"a664d245-79fe-4f43-afd4-b41748c48e4b","status":"error"}

Error: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

running a curl with exact same above headers result in the same issue. During investigation I added some additional logs to delete_blackout code (https://github.com/alerta/alerta/blob/95961df969aa803d3c08c5839178f034b5f87ebb/alerta/views/blackouts.py#L127-L144) and realized that 400 error is raised in the write_audit_trail.send call.

Removing 'write' from AUDIT_TRAIL  config works.

slack thread discussion: https://alerta.slack.com/archives/C01FJRJR2F2/p1639065817208300

**Comment by satterly** [comment]
Does it only happen for deleting blackouts?

**Comment by moix** [comment]
I have only seen with blackouts for now yes, the housekeeping job seems working fine, our alerta setup is not new and used heavily in terms of load of alerts and traffic so I think we would have seen if any other endpoint failed.
teams haven't use the blackouts historically but we are planning now that's why I checked how to keep them clean and realized about the 400
btw we have 8.5.0 version, planning upgrade now to recent 8.7.0

Is there any other endpoint you want to do a test?

**Comment by moix** [comment]
oh btw, deleting it from ui works fine

**Comment by moix** [comment]
that was fast, thanks!
