### ISSUE TITLE
Custom Webhook

### ISSUE THREAD

**Issue by pranaysahay** [alerta/alerta#1668]
Hello, I am trying to integrate Alerta to one of my applications. I have a very basic doubt. What is the difference between Plugin and Webhook? I dont need to forward these events to any other system nor I need to do any post processing of the Event. Can i go with Webhook? Secondly, my event rate is quite high, Is there a way to speed up the processing on Alerta? Currently, there is a response for each alert and so its not very efficient. Is there a way to push bulk events? Thanks

**Comment by satterly** [comment]
Firstly, you only need a webhook. Secondly, you can process multiple alerts per webhook request. See the Prometheus webhook for an example of this ... https://github.com/alerta/alerta/blob/d11866a06e4ccc832cb2b30bc70c8cea250df7f9/alerta/webhooks/prometheus.py#L108-L110
