### ISSUE TITLE
Search Alert API | OR operator not working

### ISSUE THREAD

**Issue by utsukprani** [alerta/alerta#1673]
**Issue Summary**
**OR** operator is not working consistently.
It is somehow only taking into account the first two OR conditions. It is not taking into account the third condition.
For example if we do /alerts?q=( severity:(normal OR warning) ) --> it returns results.
But if we do  /alerts?q=( severity:(normal OR warning OR critical) ) --> it does not returns any results.

**Environment**
- OS: Linux
- API version: Alerta API 8.5.0
- Deployment: Docker, self-hosted]
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
  {
    "actions": [],
    "alarm_model": {
        "colors": {
            "highlight": "skyblue",
            "severity": {
                "critical": "red",
                "normal": "green",
                "unknown": "lightblue",
                "warning": "orange"
            },
            "text": "black"
        },
        "defaults": {
            "normal_severity": "normal",
            "previous_severity": "unknown",
            "status": "open"
        },
        "name": "Alerta 8.5.0",
        "severity": {
            "critical": 1,
            "normal": 3,
            "unknown": 4,
            "warning": 2
        },
        "status": {
            "ack": "C",
            "assign": "B",
            "blackout": "E",
            "closed": "F",
            "expired": "G",
            "open": "A",
            "shelved": "D",
            "unknown": "H"
        }
    },
    "audio": {
        "new": null
    },
    "auth_required": false,
    "aws_region": "us-east-1",
    "azure_tenant": "common",
    "client_id": null,
    "cognito_domain": null,
    "colors": {
        "highlight": "skyblue",
        "severity": {
            "critical": "red",
            "normal": "green",
            "unknown": "lightblue",
            "warning": "orange"
        },
        "text": "black"
    },
    "columns": [
        "severity",
        "status",
        "lastReceiveTime",
        "timeoutLeft",
        "duplicateCount",
        "customer",
        "environment",
        "service",
        "resource",
        "event",
        "value",
        "text"
    ],
    "customer_views": false,
    "dates": {
        "longDate": "ddd D MMM, YYYY HH:mm:ss.SSS Z",
        "mediumDate": "ddd D MMM HH:mm",
        "shortTime": "HH:mm"
    },
    "debug": false,
    "email_verification": false,
    "endpoint": "http://host:port/api",
    "environments": [
        "Production",
        "Development"
    ],
    "filter": {
        "status": [
            "open",
            "ack"
        ]
    },
    "font": {
        "font-family": "\"Sintony\", Arial, sans-serif",
        "font-size": "13px",
        "font-weight": 500
    },
    "github_url": "https://github.com",
    "gitlab_url": "https://gitlab.com",
    "indicators": {
        "queries": [
            {
                "query": [
                    [
                        "environment",
                        "Production"
                    ]
                ],
                "text": "Production"
            },
            {
                "query": [
                    [
                        "environment",
                        "Development"
                    ]
                ],
                "text": "Development"
            },
            {
                "query": {
                    "q": "event:Heartbeat"
                },
                "text": "Heartbeats"
            },
            {
                "query": "group=Misc",
                "text": "Misc."
            }
        ],
        "severity": [
            "critical",
            "major",
            "minor",
            "warning",
            "indeterminate",
            "informational"
        ]
    },
    "keycloak_realm": null,
    "keycloak_url": null,
    "oidc_auth_url": null,
    "provider": "basic",
    "refresh_interval": 5000,
    "severity": {
        "critical": 1,
        "normal": 3,
        "unknown": 4,
        "warning": 2
    },
    "signup_enabled": true,
    "site_logo_url": "",
    "sort_by": [
        "severity",
        "lastReceiveTime"
    ],
    "timeouts": {
        "ack": 0,
        "alert": 31536000,
        "heartbeat": 7200,
        "shelve": 7200
    },
    "tracking_id": null
}

- web UI version: 8.5.0
- CLI version: 8.5.0

**To Reproduce**
1. Go to Postman and run the following query: /api/alerts?q=( status:(normal OR warning OR critical) )

**Expected behavior**
It should return all alerts with severity as normal or warning or critical. However it only returns for normal or warning.
If we make it /api/alerts?q=( status:(normal OR critical OR warning) ), then it is only returning for normal and critical.

**Screenshots**
N/A

**Additional context**
Looks like the OR operator is only taking into account the first two conditions.

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by utsukprani** [comment]
hi guys .. any suggestions / inputs ?

**Comment by jumtz** [comment]
Try this /alerts?q=( severity:(normal OR warning) OR severity:(critical) ) 

Every time i need a more complex query, i group the conditionals in groups of two. Ex. 

`(((A and B) and (C and D)) or (F))`

**Comment by utsukprani** [comment]
> Try this /alerts?q=( severity:(normal OR warning) OR severity:(critical) )
> 
> Every time i need a more complex query, i group the conditionals in groups of two. Ex.
> 
> `(((A and B) and (C and D)) or (F))`

This worked for me. Thanks
