### ISSUE TITLE
Regarding reported security vulnerability?

### ISSUE THREAD

**Issue by hunter123111** [alerta/alerta#1686]
Hello @satterly ,

I have found 3 critical vulnerabilities about your application Alerta and reported its on [huntr.dev](http://huntr.dev/) can you please confirm it and fix it.

Regards,
 Hunter
@hunter123111

**Comment by satterly** [comment]
Hi. I've reviewed the reports. Thanks.

**Comment by hunter123111** [comment]
@satterly I have reported another vulnerability please check it and let me know. Here is the report link: https://huntr.dev/bounties/27b57121-1142-40e2-8cdc-8faf512c34a5/
