### ISSUE TITLE
Update pip version

### ISSUE THREAD

**Issue by DB-CL** [alerta/alerta#1690]
**Is your feature request related to a problem? Please describe.**
Via pip the version is actually stuck at 8.5.1 and pip is a documented way of installing alerta

**Describe the solution you'd like**
I would like to have the pip version updated to the latest alerta version 

Thanks :)

**Comment by satterly** [comment]
Thanks for reporting this. I had no idea. I will investigate.

PyPI https://pypi.org/project/alerta/#history

**Comment by satterly** [comment]
You want "alerta-server" not "alerta" -- which is the python command-line tool.

https://pypi.org/project/alerta-server/#history
