### ISSUE TITLE
Old version of Flask in requirements.txt

### ISSUE THREAD

**Issue by sixcare** [alerta/alerta#1709]
**Issue Summary**
Flask version specified in requirements.txt is old and casues unittest to fail
https://github.com/alerta/alerta/blob/master/requirements.txt#L4

**Environment**
- OS:  Ubuntu 22.04 LTS
- Python version: Python 3.10.4
- API version: 8.7.0
- Deployment: self-hosted
- For self-hosted, WSGI environment: installed from source

- Database: Postgres

- Server config:
  Auth enabled? No
  Customer views? No

**To Reproduce**
1. Install from source as done in github actions: https://github.com/alerta/alerta/blob/master/.github/workflows/tests.yml#L46 
```
python3 -m venv venv && source venv/bin/activate
pip3 install -r requirements.txt
pip3 install -r requirements-dev.txt
pip3 install .
```
2. run test: `python3 -m unittest unittest tests/test_alerts.py`
4. See error (include command output:
```
TypeError: EnvironBuilder.__init__() got an unexpected keyword argument 'as_tuple'

----------------------------------------------------------------------
Ran 20 tests in 5.613s

FAILED (errors=19)
```

**Expected behavior**
All tests pass

**Additional context**
It's an easy fix, just update requirements.txt.
This also isn't a problem if alerta is simply installed by only running `pip3 install .`

**Comment by satterly** [comment]
Fixed by #1760
