### ISSUE TITLE
Availability of v8.7.0 in https://pypi.org/project/alerta/

### ISSUE THREAD

**Issue by Chr0my** [alerta/alerta#1751]
Hello, and thanks for this nice product. 

I'm currently trying to update alerta from 8.5.0 to 8.7.0, and discovered that the latest version available from pip is the [8.5.1](https://pypi.org/project/alerta/#history) (which seems to have disappeared from the release page).

Is there a real issue or am I doing something wrong ? 

Thanks 🙏

**Comment by mtoivo** [comment]
Hi. The `alerta` python package is just the command-line tool (and sdk) for Alerta. The actual server is in the package called `alerta-server` and that is in the version 8.7.0.

**Comment by Chr0my** [comment]
All right, thanks for your answer 🙏 
I finally managed to deploy the good version, it's OK 👍
