### ISSUE TITLE
Self signed certificates

### ISSUE THREAD

**Issue by tomasaberg** [alerta/alerta#1796]
Hi
Im using Podman to deploy a stack of tools, among them is alerta. In this setup I want to use gitlab for authentication. 

We run gitlab on-prem and also use our own certificates and root ca. When alerta starts it throws this errors in the log

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self signed certificate in certificate chain

MaxRetryError: HTTPSConnectionPool(host=<removed>, port=443) Max retries
exceeded with url: /.well-known/openid-configuration (Caused by SSLCertVerificationError)

I have built an image with root ca certificate bundled but it still gives this error.

Is it possible that this is the issue?
https://stackoverflow.com/questions/70855939/python-requests-not-looking-into-etc-ssl-certs-for-self-signed-certificates

**Comment by satterly** [comment]
What's the full log error? There should be a filename and /or line number associated with the error message.

**Comment by tomasaberg** [comment]
Hi, I got this to work with the CURL_CA_BUNDLE and REQUEST_CA_BUNDLE variable and pointing them to the correct ca. My misstake was that when i hade tried it earlier, i used the wrong filé. 

It's working now.
