### ISSUE TITLE
Integration keycloak 17 and later with alerta

### ISSUE THREAD

**Issue by CorentinH45** [alerta/alerta#1808]
**Issue Summary**
There is a problem between keycloak and alerta. Since version 17 of keycloak the following link has changed: http://ip/auth/realms/master to http://ip/realms/master
Apparently alerta does not support this. I modified the odic.py file so that alerta can be launched. Without this alerta does not run.
Except that once started, when you click on "login", the link that loads is the old one.

**Environment**
- OS: Redhat 8
- Alerta 8.6.0
- Alerta-server 8.5.0
- Deployment: self-hosted
- For self-hosted, WSGI environment: uwsgi

- Database: PostgreSQL 13

- Server config:
  Auth enabled? Yes
  Auth provider? Keycloak

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
The redirect URL used by Alerta comes from the OIDC provider. In your case keycloak. Unless I'm missing something I believe the keycloak setting needs to be changed to fix your problem.

**Comment by CorentinH45** [comment]
Hello,

Thanks for your feedback.

I'm not sure I understand. It's the conf files ported by Alerta that allow to interconnect with products like Keycloak. So it is up to Alerta to update itself to follow the evolutions of the products. 

The modification must be done in the different files of Alerta (oidc.py, probably files in the web conf for the login window).

**Comment by satterly** [comment]
Alerta config for Keycloak version < 18 ...

            'AUTH_PROVIDER': 'keycloak',
            'KEYCLOAK_URL': 'http://keycloak.local.alerta.io:9090/auth',
            'KEYCLOAK_REALM': 'master',

Alerta config for Keycloak version >= 18 ...

            'AUTH_PROVIDER': 'keycloak',
            'KEYCLOAK_URL': 'http://keycloak.local.alerta.io:9090',
            'KEYCLOAK_REALM': 'master',

Or using the generic OIDC config options...

Alerta config for Keycloak version < 18 ...

            'AUTH_PROVIDER': 'openid',
            'OIDC_ISSUER_URL': 'http://keycloak.local.alerta.io:9090/auth/realms/master',

Alerta config for Keycloak version >= 18 ...

            'AUTH_PROVIDER': 'openid',
            'OIDC_ISSUER_URL': 'http://keycloak.local.alerta.io:9090/realms/master',

**Comment by CorentinH45** [comment]
Hello,
I agree with your answer. But even if I manage to start the service by modifying the oidc.py file, I still have the problem of the uri redirection when I try to connect to Alerta. 

I did some research with a developer at my company, and it looks like there are things to modify in the /var/www ... but it also looks like it's coming from the compiled code.

At this level, there is nothing we can do ...

**Comment by CorentinH45** [comment]
_Did you try making only the configuration changes I have suggested above? Did it work? Did anything work differently?_
I can start the uwsgi service, it's just the login redirect that doesn't work 

_What changes did you need to make to oidc.py?_
In the file "/opt/alerta/lib/python3.6/site-packages/alerta/auth/oidc.py", i've deleted the /auth to the following line : 
![image](https://user-images.githubusercontent.com/86972793/223370757-c7af93f2-3632-484a-b9fe-324c512004b6.png)

_Can you list the modifications to /var/www you think you need?_
My colleague told me that there is a lot of reference to /auth from keycloak in the file : /var/www/html/js/auth.5ff10a4b.js

In my alerta confi, i have this related to keycloak : 
![image](https://user-images.githubusercontent.com/86972793/223371405-f5e4fc11-5833-42f6-bd7f-16b5ede4ea54.png)

**Comment by satterly** [comment]
This issue was raised #1680 and fixed #1683 already. It will be available in the next release.
