### ISSUE TITLE
Weak input validation

### ISSUE THREAD

**Issue by prajaktapatil60** [alerta/alerta#1888]
The application uses an input-validation scheme that may allow for attacks. 
For example - Alerta application accepts and reflects characters that are commonly used to either construct Cross-site scripting(XSS) and HTTP parameter pollution(HPP) attacks.

Can you please help us to fix this?

**Comment by satterly** [comment]
To report a vulnerability please email [admin@alerta.dev](mailto:admin@alerta.dev) and you should receive a response within 48 hours. Do not open a GitHub issue.

If you have a patch include it in the email using git format-patch.
