### ISSUE TITLE
pymongo has to be manually installed

### ISSUE THREAD

**Issue by Mapel** [alerta/alerta#1891]
I followed this manual for deployment: https://docs.alerta.io/gettingstarted/tutorial-1-deploy-alerta.html on Ubuntu 22.04, but got this error:

`Dec 19 14:03:47 alerttest alertad[6560]:   File "/opt/alerta/lib/python3.10/site-packages/alerta/database/base.py", line 43, in load_backend
Dec 19 14:03:47 alerttest alertad[6560]:     raise ImportError(f'Failed to load {backend} database backend')
Dec 19 14:03:47 alerttest alertad[6560]: ImportError: Failed to load mongodb database backend`

After some searching I found [this old issue](https://github.com/alerta/alerta/issues/1092), where the error was the missing psycopg2-binary package. 
I tried to install pymongo manually and this solved the problem.

Please add pymongo as a dependency for automatic installation or add an instruction for it to the deployment manual.

**Comment by hyberdk** [comment]
you are more than welcome to make a PR with the updated steps ;-)

**Comment by Mapel** [comment]
Added pull request for this: https://github.com/alerta/alerta-docs/pull/119
