### ISSUE TITLE
alerta.io vs keephq.dev

### ISSUE THREAD

**Issue by codesse** [alerta/alerta#1972]
Hello,

is there a relation between alerta and keep? Alerta has been around for a while, and keep and seems kind of a fork. I've looked around but there's no comments on the similarities, or even any comment about how alike keep is from alerta.

Thanks

**Comment by shahargl** [comment]
hey @codesse, maintainer of Keep here.

There is no "official" relation between the products. 
I would say we are trying to learn from other tools in our space, to build Keep to be great. 

Alerta is a great tool, and you can see Keep as "alerta for 2024" with workflow automation, noise reduction tools, a little bit of AI and lot of cool stuff we try to ship.

**Comment by michael-doubez** [comment]
People recognize a shameless marketing when they see one.

**Comment by shahargl** [comment]
What part of it is marketing?

**Comment by michael-doubez** [comment]
A new user asking a stupid question about a vaguely related product and both developers of the said product answering withing the hour.
It is not even remotely subtle. I won't say more about that as it is not a discussion forum.

**Comment by shahargl** [comment]
I’m subscribed myself to new issues on this repo. Here’s a screenshot of my friend sending it to me. Think whatever you want 🤷🏼‍♂️ 

![bd7f3a45-0aac-4415-b3cc-95893c336c0d](https://github.com/alerta/alerta/assets/12069200/e6405410-7e48-4c6a-98b0-afcf5d1c775f)

**Comment by sixcare** [comment]
Since the initial question has been answered, I'll close this issue

**Comment by codesse** [comment]
> People recognize a marketing when they see one.

I was genuinely asking this question, perhaps should have been posted on the other repository to avoid this reaction. Sorry :-(
