### ISSUE TITLE
Write alert directly to mongodb

### ISSUE THREAD

**Issue by stratanic** [alerta/alerta#2000]
Hello,

I've been using alerta for 2 years and now I'd like to push the PRTG alerts into alerta,
The PRTG api works well... and I already have a script that reads the api and writes to MONGODB.

Is it possible to push the alerts directly into mongodb, or is that not recommended? 

How can I have a system that detects new alerts and pushes only the new ones and delete the problems that have been solved?

thank you

Translated with DeepL.com (free version)

**Comment by satterly** [comment]
Not recommended. Creating a new alert is straightforward but there is quite a bit of logic when updating existing alerts.

> How can I have a system that detects new alerts and pushes only the new ones and delete the problems that have been solved?

Don't make the sending complicated. Alerta will handle repeat events for you. That's what it is for. It's better to resend active alerts and timeout old ones than only send an alert once at the very beginning.

Delete solved problems by sending a "normal" severity alert for the one you want to auto-close.
