### ISSUE TITLE
Notification plan

### ISSUE THREAD

**Issue by kjetilmjos** [alerta/alerta#415]
Hi, mentioned this before on gitter but will add it here as feature request as well just in case :)

What I would really like in alerta is notification plans. Similar to the escalation system in iris by linkedin http://iris.claims/docs/ 

It could be a new configuration page in the web UI where plans could be created. The plans would listen to a specific tag and use that to route alarms to the correct user. for example. 
All alarms with tag DEV should be sent to user(s) XXX.
 
For this to work notification methods would have to be set up on a user level. So every user decided for them self if they would like to be notified on slack, email, twilio etc.. 

The notification plans could also support escalation. ex:
If alarm with tag DEV has not been acknowledged within X number of minutes notify to user XXX.

**Comment by satterly** [comment]
Hi @kjetilmjos I think closer integration with a more fully featured notification/escalation tool is a good idea, and iris seems like a good fit. However, it's not something I will be actively working on any time soon so I've added this to the backlog. I'll close this issue for now but feel free to add to it if you have any further thoughts. We can re-open this issue if/when work commences. Thanks.

**Comment by kjetilmjos** [comment]
Sounds good. Keep up the great work @satterly
