### ISSUE TITLE
Deploying Alerta

### ISSUE THREAD

**Issue by githublemming** [alerta/alerta#417]
Hi, 

can you help me getting Alerta up and working?

I've got the dockerised version (https://github.com/alerta/docker-alerta) up and running but I'd like something a bit more production ready, so I don't loose everything if the EC2 gets restarted.

I'm running in AWS so I've tried the CloudFormation template (https://github.com/alerta/alerta-cloudformation), but this times out waiting for something to happen, installing the software I guess as I don't see anything appear on the EC2.

I've followed the instructions here http://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html#tutorial-1, but uwsgi fail to start. It's complaining about not being able to import app from alerta.app

I've spent quite some time ( a day or two) looking at getting something working, but I'm finding the inconsistency between the different 'Real World Examples' files difficult to know what if the correct answer. An example of this is the  .wsgi file

In your tutorial it is

`from alerta.app import app`

In cloudformation it is

```
#!/usr/bin/env python
from alerta.app import app as application
```

and in packer it is

```
#!/usr/bin/env python
activate_this = '/opt/alerta/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))
from alerta.app import app as application
```

If you have an upto date document for getting a system working I would be grateful.

Thanks,

Mark

**Comment by satterly** [comment]
Sorry. It shouldn't be this hard to deploy Alerta in a production environment.

I'll update the online docs and packer and fix the AWS template. 

For the latest version it should be 
`from alerta import app`

**Comment by githublemming** [comment]
I’ve managed to get something running using this in the wsgi file, though i did need to add ‘as application’ otherwise wsgi complained. I’m on Ubuntu 16.04 using apache2

#!/usr/bin/env python

try:
    from alerta import app  # alerta >= 5.0
except Exception:
    from alerta.app import app  # alerta < 5.0
