### ISSUE TITLE
oauth2 for normal login and basic auth for read-only display ?

### ISSUE THREAD

**Issue by wimfabri** [alerta/alerta#420]
Is it possible to use Oauth2 authentication for all users except for a read-only user that would use basic authentication ? Purpose is to use it on a TV that is hanging on the wall.

**Comment by satterly** [comment]
I can't think why this wouldn't work. You would need to create two different web UI `config.js` files -- one for OAuth2 and the other for basic auth -- and then associate those will different web console URLs. Does that make sense?

**Comment by wimfabri** [comment]
Yes, of course. Thanks

**Comment by satterly** [comment]
Ok, great. Let me know if this doesn't work for some reason by adding a comment below and we can reopen this issue.
