### ISSUE TITLE
python version compatability with alerta python modules

### ISSUE THREAD

**Issue by itskannanraj** [alerta/alerta#436]
Hi Satterly,

i had alerta setup and using webhook as client for sending nagios alerts to alerta. however where python 2.7 is installed i have not find any issue. 
in some hosts has been installed python 2.6, there i could not post alerts to alerta and getting error like 
"zero length field name in format"

**Comment by satterly** [comment]
Python 2.6 isn't supported. It was given "end of life" status 4 years ago.

**Comment by itskannanraj** [comment]
thank you satterly
