### ISSUE TITLE
Ack or Close from Telegram doesn't work

### ISSUE THREAD

**Issue by kattunga** [alerta/alerta#437]
Hi,
I installed Telegram Plugin, everything works fine but the Ack or Close buttons not.
If I press Ack or Close in Telegram client it keeps waiting a response.

My /etc/alertad.conf
```
AUTH_REQUIRED=True
SECRET_KEY='mykey'
ADMIN_USERS=['admin@local']
BASE_URL='/alerta_api'
PLUGINS = ['telegram']
TELEGRAM_TOKEN = '<token>'  # default="not set"
TELEGRAM_CHAT_ID = '<id>'  # default="not set"
TELEGRAM_TEMPLATE = '' # default will use hardcoded one
TELEGRAM_WEBHOOK_URL = 'https://myserver/alerta_api/webhooks/telegram'
BLACKOUT_DURATION = 86400
DEBUG=True
LOGGER_NAME = 'alerta'
LOG_FILE = '/var/log/alerta.log'
```
My debug file is attached.

[alerta.log](https://github.com/alerta/alerta/files/1568545/alerta.log)

Any idea?

**Comment by satterly** [comment]
Is this URL publicly accessible on the internet?
```
TELEGRAM_WEBHOOK_URL = 'https://myserver/alerta_api/webhooks/telegram'
```

**Comment by kattunga** [comment]
Yes it is, the url also has a comercial signed ssl certificate,

**Comment by satterly** [comment]
If it's timing out then there is clearly a connection issue. I can't help beyond what I have already.
