### ISSUE TITLE
Reset password with basic auth

### ISSUE THREAD

**Issue by kattunga** [alerta/alerta#445]
Hello,

When using basic auth, Is there any way to reset user password without delete user from database and create again?

**Comment by satterly** [comment]
Use the `alerta` command-line tool. Login as an admin user and you can reset anyone's password...

```
$ alerta login
Email: admin@alerta.io
Password:
Logged in as admin@alerta.io
$ alerta user --id 25d86c71-fcb1-47b6-8f9e-ec12da723c05 --password foo
Updated.
```

**Comment by jaylaprade** [comment]
There should be a password reset in the profile when basic auth is used.
