### ISSUE TITLE
errors on pagerduty webhook

### ISSUE THREAD

**Issue by sbds** [alerta/alerta#447]
Webhooks from PagerDuty result in either HTTP 400 or HTTP 500 responses from Alerta, depending on which version of the PagerDuty webook is used.

**Comment by satterly** [comment]
Hi @sbds like I said on Gitter, version 1 of the PagerDuty API was the only API that was available when the webhook was added. Please provide the full error response so I can try to debug, not just the HTTP status code.

**Comment by satterly** [comment]
@sbds I've added extended logging for webhooks to Alerta. The request info would really help is resolving this issue. See #469

**Comment by sbds** [comment]
Ok. Here is the logged request coming in from PagerDuty's WebHook, that results in a 500 from Alerta:
{
  "messages":[
    {
      "type":"incident.resolve",
      "data":{
        "incident":{
          "id":"PKQK8F5",
          "incident_number":25733,
          "created_on":"2018-01-29T17:59:48Z",
          "status":"resolved",
          "pending_actions":[
          ],
          "html_url":"https://blank.pagerduty.com/incidents/PKQK8F5",
          "incident_key":null,
          "service":{
            "id":"PGFUM6I",
            "name":"lurker_alerta_majors",
            "html_url":"https://blank.pagerduty.com/services/PGFUM6I",
            "deleted_at":null,
            "description":""
          },
          "escalation_policy":{
            "id":"PZQXS07",
            "name":"me",
            "deleted_at":null
          },
          "assigned_to_user":{
            "id":"PDOST60",
            "name":"me",
            "email":"me@blank.com",
            "html_url":"https://blank.pagerduty.com/users/PDOST60"
          },
          "trigger_summary_data":{
            "description":"Production: Major alert for pci web - 172.30.2.250:9091 is LowDiskSpace",
            "client_url":"https://blank.com/#/alert/ba87c613-6cac-414b-9e4b-e13e3cc140af",
            "client":"alerta"
          },
          "trigger_details_html_url":"https://blank.pagerduty.com/incidents/PKQK8F5/log_entries/ROYXKVOLU8R31S4HHCI9HGQXMZ",
          "trigger_type":"trigger_svc_event",
          "last_status_change_on":"2018-01-29T18:32:06Z",
          "last_status_change_by":{
            "id":"PDOST60",
            "name":"me",
            "email":"me@blank.com",
            "html_url":"https://blank.pagerduty.com/users/PDOST60"
          },
          "number_of_escalations":1,
          "integration_name":"lurker_alerta_eventsAPIv2",
          "resolved_by_user":{
            "id":"PDOST60",
            "name":"me",
            "email":"me@blank.com",
            "html_url":"https://blank.pagerduty.com/users/PDOST60"
          },
          "assigned_to":[
            {
              "at":"2018-01-29T17:59:49Z",
              "object":{
                "id":"PDOST60",
                "name":"me",
                "email":"me@blank.com",
                "html_url":"https://blank.pagerduty.com/users/PDOST60",
                "type":"user"
              }
            }
          ],
          "urgency":"high",
          "resolve_reason":null
        }
      },
      "id":"b662b7f0-0522-11e8-a31f-000d3a31cb72",
      "created_on":"2018-01-29T18:32:06Z"
    }
  ]
}

**Comment by satterly** [comment]
I assume you using the pagerduty plugin to generate these notifications? What I don't understand is why the `incident_key` is null in the webhook payload given that it is being set in the plugin ...
https://github.com/alerta/alerta-contrib/blob/master/plugins/pagerduty/alerta_pagerduty.py#L56
