### ISSUE TITLE
user is set to None if Authorization header is missing

### ISSUE THREAD

**Issue by ervitis** [alerta/alerta#449]
I am having some problems creating an API key using the console (using the example from [here](http://alerta.readthedocs.io/en/latest/api/reference.html#create-an-api-key)). If I set the variable AUTH_REQUIRED to False the response message is "Must set 'user' to create API key".

After I debugged, I've found that in the file keys.py when the variable key.user is set in the else condition it returns None. Is there a reason why it's returning None?

Kind regards

**Comment by satterly** [comment]
There's no need to use API keys if you have set `AUTH_REQUIRED` to `False`. And an API key must be associated with a user and so if no user has authenticated when attempting to create a new API key then "key.user" would be None.

**Comment by ervitis** [comment]
Thank you for the answer.

So I thought it too but still the error message is a little confusing in my opinion because if someone is missing the AUTH_REQUIRED value and pass in the json data in the curl request the "user" parameter the error is not very descriptive.

Regards

**Comment by satterly** [comment]
Ok. I'll make the error message more descriptive and hopefully less confusing. Thanks for the feedback.

**Comment by ervitis** [comment]
Thank you so much. And keep going, it's a great project! :)

**Comment by ervitis** [comment]
Also, I have forked alerta project and fixed the message and another things (I couldn't make pass the unit tests in my local). If you have time, take a look and we can discuss it and if it's ok I can make the pull request.

https://github.com/ervitis/alerta

Regards

**Comment by satterly** [comment]
Hi, Thanks for your efforts on this. After reviewing your PR I've decided that I think the current logic is till right however the error message could be better. The new message will be something like so...
```
{
  "code": 400,
  "errors": null,
  "message": "An API key must be associated with a 'user'. Retry with user credentials.",
  "status": "error"
}
```
See #464
