### ISSUE TITLE
New Relic webhook not working properly

### ISSUE THREAD

**Issue by jordimolesblanco** [alerta/alerta#463]
Issues:

1.  When sending a test message from New Relic ("Send a test notification" button), New Relic receives a 200 code and the following return:

```
{
response: 200,

{ "alert": { "attributes": { "ip": "XXX.XXX.XXX.xxx", "moreInfo": "Incident URL", "runBook": "Runbook URL" }, "correlate": [], "createTime": "2018-01-27T22:08:20.706Z", "customer": null, "duplicateCount": 0, "environment": "Production", "event": "New Relic Alert - Test Condition", "group": "test", "history": [ { "event": "New Relic Alert - Test Condition", "href": "https://xxxx.yyyy.com/alert/xxxxxyyyyzzzz", "id": "xxxxxyyyyzzzz", "severity": "info", "status": null, "text": "New Relic Alert - Channel Test", "type": "severity", "updateTime": "2018-01-27T22:08:20.706Z", "value": null } ], "href": "https://xxxxx.yyyy.com/alert/xxxxxyyyyzzzz", "id": "xxxxxyyyyzzzz", "lastReceiveId": "xxxxxyyyyzzzz", "lastReceiveTime": "2018-01-27T22:08:20.708Z", "origin": "New Relic/v1.0", "previousSeverity": "indeterminate", "rawData": { "account_id": xxxxyyy, "account_name": "My Account", "condition_id": 0, "condition_name": "New Relic Alert - Test Condition", "current_state": "test", "details": "New Relic Alert - Channel Test", "event_type": "NOTIFICATION", "incident_acknowledge_url": "https://alerts.newrelic.com/accounts/xxxxyyy/incidents/0/acknowledge", "incident_id": 0, "incident_url": "https://alerts.newrelic.com/accounts/xxxxyyyy/incidents/0", "owner": "Myself", "policy_name": "New Relic Alert - Test Policy", "policy_url": "https://alerts.newrelic.com/accounts/xxxxyyy/policies/0", "runbook_url": "http://localhost/runbook/url", "severity": "INFO", "targets": [ { "id": "12345", "labels": { "label": "value" }, "link": "http://localhost/sample/callback/link/12345", "name": "Test Target", "product": "TESTING", "type": "test" } ], "timestamp": 1517090900223, "version": "1.0" }, "receiveTime": "2018-01-27T22:08:20.708Z", "repeat": false, "resource": "Test Target", "service": [ "Myself" ], "severity": "info", "status": "test", "tags": [ "label:value" ], "text": "New Relic Alert - Channel Test", "timeout": 86400, "trendIndication": "lessSevere", "type": "notification", "value": null }, "id": "xxxxxyyyyzzzz", "status": "ok" }

}
```

The alert is visible via /api/alerts endpoint, but it doesn't show in the webUI. This is the alert as seen in the API.

```
{
      "attributes": {
        "ip": "XXX.XXX.XXX.xxx", 
        "moreInfo": "<a href=\"https://alerts.newrelic.com/accounts/XXXXX/incidents/0\" target=\"_blank\">Incident URL</a>", 
        "runBook": "<a href=\"http://localhost/runbook/url\" target=\"_blank\">Runbook URL</a>"
      }, 
      "correlate": [], 
      "createTime": "2018-01-27T22:08:20.706Z", 
      "customer": null, 
      "duplicateCount": 0, 
      "environment": "Production", 
      "event": "New Relic Alert - Test Condition", 
      "group": "test", 
      "history": [
        {
          "event": "New Relic Alert - Test Condition", 
          "href": "https://xxxxx.yyyyy.com/alert/xxxxxyyyyzzzz", 
          "id": "xxxxxyyyyzzzz", 
          "severity": "info", 
          "status": null, 
          "text": "New Relic Alert - Channel Test", 
          "type": "severity", 
          "updateTime": "2018-01-27T22:08:20.706Z", 
          "value": null
        }
      ], 
      "href": "https://xxxx.yyyy.com/alert/xxxxxyyyyzzzz", 
      "id": "xxxxxyyyyzzzz", 
      "lastReceiveId": "xxxxxyyyyzzzz", 
      "lastReceiveTime": "2018-01-27T22:08:20.708Z", 
      "origin": "New Relic/v1.0", 
      "previousSeverity": "indeterminate", 
      "rawData": {
        "account_id": xxxxxyyyy, 
        "account_name": "My Account", 
        "condition_id": 0, 
        "condition_name": "New Relic Alert - Test Condition", 
        "current_state": "test", 
        "details": "New Relic Alert - Channel Test", 
        "event_type": "NOTIFICATION", 
        "incident_acknowledge_url": "https://alerts.newrelic.com/accounts/xxxyyyy/incidents/0/acknowledge", 
        "incident_id": 0, 
        "incident_url": "https://alerts.newrelic.com/accounts/xxxyyyy/incidents/0", 
        "owner": "Myself", 
        "policy_name": "New Relic Alert - Test Policy", 
        "policy_url": "https://alerts.newrelic.com/accounts/xxxyyyy/policies/0", 
        "runbook_url": "http://localhost/runbook/url", 
        "severity": "INFO", 
        "targets": [
          {
            "id": "12345", 
            "labels": {
              "label": "value"
            }, 
            "link": "http://localhost/sample/callback/link/12345", 
            "name": "Test Target", 
            "product": "TESTING", 
            "type": "test"
          }
        ], 
        "timestamp": 1517090900223, 
        "version": "1.0"
      }, 
      "receiveTime": "2018-01-27T22:08:20.708Z", 
      "repeat": false, 
      "resource": "Test Target", 
      "service": [
        "Third Bridge"
      ], 
      "severity": "info", 
      "status": "test", 
      "tags": [
        "label:value"
      ], 
      "text": "New Relic Alert - Channel Test", 
      "timeout": 86400, 
      "trendIndication": "lessSevere", 
      "type": "notification", 
      "value": null
    }
```
How to reproduce: Simply create a Notification Channel from New Relic panel and add the endpoint for your installation, for example:

```
https://xxxx.yyyyy.com/api/webhooks/newrelic
```
And you'll see that the test alert doesn't show in webUI.

2. "Normal" alerts from New Relic (not testing alerts as point 1) receive a 500.
It happens every time, very easy to reproduce.
I've been trying to make changes to the file
```
/usr/local/lib/python2.7/dist-packages/alerta/webhooks/newrelic.py
```
but I haven't got very far. I tried to change the 500 return code in that file, but it doesn't seem to get to that file, the lines I add there don't get executed.
I also tried to enable DEBUG flag in alertad.conf file, but I can't see anything, it doesn't log anything.

My setup:
Ubuntu 16.04
alerta 5.0.5
alerta client 5.0.10
requests 2.18.4
mongodb 3.6

I don't know to debug this further, but happy to add some information if required and instructed how.

**Comment by satterly** [comment]
I fixed the test notification. I also tested an alert acknowledgement from New Relic to Alerta successfully. I've recently improved server logging of 500 errors which will be available in the next release (v5.0.6) very soon. If you could deploy that and include the exception traceback that would be helpful.

**Comment by jordimolesblanco** [comment]
@satterly 
thanks for looking into this so quickly!

what do you mean by an 'alert acknowledgement'?

I pulled the new code and managed to get the traceback.

I created 2 different alerts and I seem to get exactly the same error:

Infrastructure alert (this is about memory, but i also tried cpu and other values):
https://gist.github.com/jordimolesblanco/e549b2e07d852c34ff3ffa13f6c338ca

APM Apdex:
https://gist.github.com/jordimolesblanco/5a55dd69392402ff0404ac5fcbb6617c

**Comment by satterly** [comment]
Thanks for the extra info. I've got a fix for it. Perhaps there are other problems though so if you could run master again that would be useful. Alternatively, provide the raw json data of the New Relic HTTP POST and I can update the test case.

**Comment by jordimolesblanco** [comment]
@satterly 

that's fixed, but unfortunately there's another error. Here's the traceback:
https://gist.github.com/jordimolesblanco/171e348a1c2cd8f46bc65bdda2ae5590
I've tried several alerts, and they all produce the same output.

if it helps... i'm using New Relic "default" alert. It can be configured to create a custom payload, but I haven't done so.
However, I can't see in New Relic the payload that is sent to Alerta. Do you have an easy way to print the payload that Alerta receives?

**Comment by satterly** [comment]
I've added some better logging for webhooks and merged with master branch. If you could try again and grab the output that would be great.

**Comment by jordimolesblanco** [comment]
ok, very strange.....
now it's working. I've tried several alerts, and they all work. This is an example of an alert working:
https://gist.github.com/jordimolesblanco/bf4494d0ebef2e7b487cf3381b6eefa2

As i understand, the changes in the file
https://github.com/alerta/alerta/blob/master/alerta/webhooks/__init__.py
are only about logging, right?

well... at least in my case.... these changes actually "fix" the issue.
I tried to rollback to the previous version, and it triggers an exception again.

**Comment by satterly** [comment]
Yes, the change was only to add logging. Glad it works, though. I'll close this issue again. Let me know if you get errors again.

**Comment by jordimolesblanco** [comment]
@satterly , it's been working great since the last change.

I forgot to say that I also removed the *.pyc together with applying the latest "logging-only" changes, cause i was doing the changes manually rather than pulling the whole repo.
I usually have "caching" problems with pyc files, so I tried that.

Anyway.... the issue seems more than solved for me.

Thanks for this great project!

**Comment by satterly** [comment]
That's good to hear. And thanks for the positive feedback. :smile:
