### ISSUE TITLE
No effect when using BASE_URL

### ISSUE THREAD

**Issue by matthenning** [alerta/alerta#473]
I'm running alerta as a docker container behind an nginx reverse proxy under the path /alerta.
The site loads fine, the api calls fail though.

The BASE_URL environment variable doesn't seem to have an effect in my environment,
I've created the docker container like this:
```
docker run --name alerta-web -e MONGO_URI=mongodb://db:27017/monitoring -e BASE_URL=/alerta/api --link alerta-db:db -d -p 127.0.0.1:27018:80 alerta/alerta-web
```

The API requests still point to the wrong endpoint though:
```
https://<mydomain>/api/alerts/count?status=open&status=unknown
```

I would have expected this url:
```
https://<mydomain>/alerta/api/alerts/count?status=open&status=unknown
```

Config:
```
$ cat /etc/alertad.conf
DEBUG = True
BASE_URL = '/alerta/api'
SECRET_KEY = '****'
OAUTH2_CLIENT_ID = 'not-set'
OAUTH2_CLIENT_SECRET = 'not-set'
PLUGINS = []
```

Version:
```
$ alerta version
alerta 5.0.5
alerta client 5.0.10
requests 2.18.4
```

NGINX config:
```
...
location ^~ /alerta {
    index               index.html;
    rewrite             ^/alerta/(.*) /$1 break;
    proxy_pass          http://127.0.0.1:27018;
}
...
```

**Comment by satterly** [comment]
This should now be fixed in the latest version of the Docker container available now.
