### ISSUE TITLE
[question] When does alert.repeat get populated

### ISSUE THREAD

**Issue by sushovan23** [alerta/alerta#474]
I have following plugins configured: 

PLUGINS=['blackout', 'enrich', 'email', 'slack', 'customtimeout']
In my enrich plugin I have implemented a logic based on repeat plus some other custom attributes where I decide where or not to send notification.

I notice that in enrich plugin alert.repeat is always False. When I look up the alert in alerta UI and see JSON it says repeat = true. Also in my slack plugin I see that alert.repeat is true.

So I wonder that repeat attribute is set later on? Could you let me know where this repeat attribute is set? So I don't have to duplicate the logic on each of the plugin which I have?

EDIT:
I see that in plugins `post_receive` it comes as repeat. In my enrich plugin I was using the `pre_receive` method to implement that logic. Is that correct understanding?

**Comment by satterly** [comment]
The `repeat` attribute is set when the alert is processed. ie. after the `pre_receive` and before the `post_receive` plugin methods. So as you say in your EDIT, your logic should check `repeat` in the `post_receive` hook.
