### ISSUE TITLE
Error while setting up SAML2 authentication

### ISSUE THREAD

**Issue by sushovan23** [alerta/alerta#477]
I was looking to enable saml2 authentication. I made the changes to config.js. 
Made changes to alerta.conf accordingly. 
However getting this error:
{
  "code": 500, 
  "errors": [
    "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1598, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/lib/python2.7/site-packages/alerta/auth/saml2.py\", line 47, in saml_redirect_to_idp\n    (session_id, result) = saml_client().prepare_for_authenticate(relay_state=relay_state)\n  File \"/usr/lib/python2.7/site-packages/alerta/auth/saml2.py\", line 34, in saml_client\n    (absolute_url('/auth/saml'), saml2.BINDING_HTTP_POST)\nAttributeError: 'module' object has no attribute 'BINDING_HTTP_POST'\n"
  ], 
  "message": "'module' object has no attribute 'BINDING_HTTP_POST'", 
  "status": "error"
}

Where should BINDING_HTTP_POST be defined?

**Comment by satterly** [comment]
Did you follow the docs when setting this up? http://docs.alerta.io/en/latest/authentication.html#saml-2-0

**Comment by sushovan23** [comment]
Yes we followed but looks like saml2 module is not able to read the IDP-metadata.xml provided by the team. Does it need to be in specific localtion? I have given it read permissions.

**Comment by satterly** [comment]
I have no idea. I've never used SAML and don't know anything about how it works. Sorry.

**Comment by sushovan23** [comment]
We can close this topic. I switched towards developing my own provider based on your inputs and some trial and error. Very soon I will share my changes for openid support.
