### ISSUE TITLE
End support for Python 2.7

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#480]
Python 2.7 is [EOL in 2020](http://legacy.python.org/dev/peps/pep-0373/) and many python projects have decided to stop supporting Python 2.7 already.

The benefits of a Python 3 only codebase means that Alerta projects can take advantage of new features such as [type hints](https://docs.python.org/3/library/typing.html).

It is proposed to make Alerta Release 5.2 and all dependent projects the last release to support Python 2.7. **The proposal is that Python 2.7 support should be dropped 6 months from now. ie. 31 August 2018.**

From this date, all future Alerta releases (ie. 6.x etc) will only support Python 3 with the last Python 2 release (5.2.x) only getting critical bug fixes.

**Comment by mmulqueen** [comment]
Fully agree with this proposal. We've been running Alerta with Python 3 since we've started using it, no issues. I've proposed some related changes to the documentation.

**Comment by satterly** [comment]
Release 5.1.0 is [now out](https://github.com/alerta/alerta/releases/tag/v5.1.0) and will only officially support Python 3.

**Comment by satterly** [comment]
Worryingly, I've just learned that `click` is recommending Python 2 for production environments due to  unresolved Python 3 limitations. See http://click.pocoo.org/5/python3/

**Comment by d-ganchar** [comment]
Not sure that Python 2.7 support [makes sense](https://pythonclock.org/). 
Better to use [typing](https://docs.python.org/3/library/typing.html)

**Comment by satterly** [comment]
@d-ganchar Exactly. That's why python 2.7 support will be withdrawn in less than 4 months now.

**Comment by satterly** [comment]
**IMPORTANT** Support for Alerta on Python 2.7 will end in **one month**!!!

**Comment by satterly** [comment]
❗️ Note: An example of what needs to change in the deployment for an Apache/WSGI virtualenv environment on  Debian/Ubuntu can be found here https://github.com/alerta/vagrant-try-alerta/pull/13

**Comment by satterly** [comment]
Alerta server version 5.2.9 has just been published to Pypy and it is proposed that **this is the last release to support Python 2.7.** Only critical application bug fixes and security fixes will be applied to [this branch](https://github.com/alerta/alerta/tree/release/5.2) in future.

**Alerta server 6.0 will only support Python 3.5+ and will require Postgres 9.6+ or MongoDB 3.x.**

**Comment by satterly** [comment]
Alerta client version 5.2.1 has just been published to [Pypy](https://pypi.org/project/alerta/) and it will be the last release to support Python 2.7. Only critical application bug fixes and security fixes will be applied to [this branch](https://github.com/alerta/python-alerta-client/tree/release/5.2) in future.

**Comment by satterly** [comment]
Limited support for Alerta on Python 2.7 will continue until support for Python 2.7 has officially ceased. 

<img width="783" alt="screen shot 2018-09-04 at 10 24 58" src="https://user-images.githubusercontent.com/615057/45019537-e0b7ed80-b02c-11e8-9976-d4b4b6271d2f.png">

https://pythonclock.org/
