### ISSUE TITLE
Get History of "value" and "text" even no status/severity/event changes

### ISSUE THREAD

**Issue by bennneuh** [alerta/alerta#483]
Hi,

I need to have an history of value/text for duplicated alerts to have an history of value/text  over the time even no changes on the status/severity or event.

I'm not sure it's possible now but it could be interesting.

Regards

**Comment by satterly** [comment]
You can log every event as it happens to another tool like elasticsearch Kibana. And then query it from a plugin to de-duplicate alerts based on any criteria you like.

**Comment by bennneuh** [comment]
Yes we can do that with elastic but it will not answer with the elarta principle and WebUI who match perfectly my needs.

Let me clarify, the deduplication works perfectly with static alerts (up or down for example with change on the 'Event"), but it could be frustrated when we have alerts with dynamic values like latency or score because we loose the information, and we just see the counter of deduplucation.

I my case i use the machine learning of elastic with an anomaly score matched by elastalert. I send an alert when the score is high. But if it was possible to have the deduplication of alerts and when i click on the alert in alerta, i can see the score over the time with the value and text columns in the history (i don't talk about 1000 alerts in the history but just 10 or 20 for exemple) it will be perfect. All informations in the same place with the possibility to manage the alert.

I imagine, it could be possible to add a boolean option push with the alert to alerta. If it's true, we keep value/text in the history of the deduplicated alert  (like when "event" change) without necessary a change on the status/severity change. If the boolean is to false (default config) then it works like now.

I hop i'm clear... :)

**Comment by bennneuh** [comment]
Just to add even for Static alerts (i mean with fix informations like up or down) it's interesting to have a visibility when the "flood" has generated deduplication.

**Comment by satterly** [comment]
If I understand you correctly, you would like the option to push alerts to history for every change in text or value. Is that right? If so, my initial reaction is that this would be a significant behaviour change and could dramatically affect performance. Let me think about this a bit more and get back to you.

**Comment by bennneuh** [comment]
Not exactly, i imagine, when duplicate is matched (+1 in duplicate) at the same time we push the alert in the history to have the history of "value", "text" and the timestamp when the alert has been de-duplicated. We keep the same principle like before by correlating "event" by ressource etc... we just add a push in history in parallel of the "+1" for the de-duplication.

For the impact, i imagine (again sorry) it could be limited if:

* it's an option disabled by default
* The alert where the option is enable don't flood too much (but in any cases the alert is analyzed for the deduplication entry)

It could have also an impact on the size of the DB also if the alert flood

Stupidly i imagine that it's just to play the function used when you detect a change on "event" but each times the deduplication is matched and modifying the action when the event has change to avoid multi similar entry in the history (action already played during deduplication). But i'm not a dev so i suspect it more complex :)

Thanks for your answers

**Comment by bennneuh** [comment]
Hi,

Did you have time to think about this question?

Thanks,

**Comment by satterly** [comment]
Yes, it is not complicated if you only wanted the history of value changes for duplicate alerts.

However, to add every alert text change may require an additional attribute or overloading an existing attribute (both of which I'm reluctant to do).

Would you be happy to go ahead with just value changes for now and see if that's enough or are you set on having text changes?

**Comment by bennneuh** [comment]
Yes for the moment with just the value and the timestamp of the deduplication matching the value it's enough.

I imagine in the futur i could have the need of text detail (to be sure i don't miss an evolution) but not for the moment.

Are you able to create the feature ? unfortunately i'm not a developper, but if it's not complex, i can check or i can ask to a friend who work with me on the project.

Thx

**Comment by bennneuh** [comment]
Thx for the feature!!!

I have one last question, i have seen that you have pushed the change in the master branch, but when i get the image from docker hub, i don't see the change. i have miss something ?

**Comment by bennneuh** [comment]
Ok understood the docker hub release is 5.0.8 and you have created the release 5.0.9 since 3 or 4 hours now so i wait :)

**Comment by satterly** [comment]
Docker container is building now.

**Comment by bennneuh** [comment]
Thx for the container! 👍 

Unfortunatly, I suspect a bug in the "add alert value to history", i have some tests rules who generate deduplicates during this after-noon. i see lot's of alerts with 1 to 10 deduplicates but the value of the history of "duplicate alert with value change" is just one entry or zero (never more). I'm totally sure the "value" has changed over the time. The machine learning score is very sensible.

i'm not sure how i can help to debug.

**Comment by satterly** [comment]
@bennneuh I think I've fixed this but are you able to test this on master to verify for me?

**Comment by satterly** [comment]
@bennneuh I've kicked off a docker container build for version 5.1.0. Please test and let me know if the issue is fixed. Thanks.

**Comment by bennneuh** [comment]
It seems working now! thanks a lot!
