### ISSUE TITLE
Feature: change status of one or many alerts by checkbox

### ISSUE THREAD

**Issue by bennneuh** [alerta/alerta#484]
Hi,

Just one proposal of feature:

Edit the status of one or many alerts from Web interface who list alerts by selecting it with checkbox and by selecting the status to apply.

I imagine it could be useful when we have many alerts to close or ack at the same time.

**Comment by satterly** [comment]
This is already possible, though poorly documented. See http://docs.alerta.io/en/latest/webui.html#view-recent-alerts

**Comment by bennneuh** [comment]
Cool Feature! Thanks and sorry to have asked the question
