### ISSUE TITLE
'utf-8' codec can't decode byte error while acking an alert using postgres backend

### ISSUE THREAD

**Issue by arindamchoudhury** [alerta/alerta#492]
When user has accent in their username like "Roberto Fernández", acking an alert throws exception:

Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py\", line 1612, in full_dispatch_request\n    rv = self.dispatch_request()\n  

File \"/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py\", line 1598, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python3.6/site-packages/Flask_Cors-3.0.3-py3.6.egg/flask_cors/decorator.py\", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/auth/utils.py\", line 115, in wrapped\n    return f(*args, **kwargs)\n  

File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/models/metrics.py\", line 259, in wrapped\n    response = f(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/utils/api.py\", line 30, in decorated\n    return func(*args, **kwargs)\n  

File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/views/alerts.py\", line 101, in set_status\n    if alert.set_status(status, text):\n  File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/models/alert.py\", line 348, in set_status\n    return db.set_status(self.id, status, history)\n  

File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/database/backends/postgres/base.py\", line 241, in set_status\n    return self._update(update, {'id': id, 'like_id': id + '%', 'status': status, 'change': history}, returning=True)\n  

File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/database/backends/postgres/base.py\", line 855, in _update\n    self._log(cursor, query, vars)\n  

File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/database/backends/postgres/base.py\", line 878, in _log\n    LOG.debug('{stars}\\n{query}\\n{stars}'.format(stars='*'*40, query=cursor.mogrify(query, vars).decode('utf-8')))\n  

File \"/usr/local/lib/python3.6/site-packages/alerta_server-5.0.8-py3.6.egg/alerta/database/backends/postgres/base.py\", line 26, in adapt_history\n    adapt(h.text).getquoted().decode('utf-8'),\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 42: invalid continuation byte\n

**Comment by willhope** [comment]
i think text of the alert should encode utf-8, like this
self.text = kwargs.get('text', "").encode('utf-8')

**Comment by willhope** [comment]
i think text of the alert should be encode by utf-8, like this
self.text = kwargs.get('text', "").encode('utf-8')

**Comment by satterly** [comment]
It looks like the History adapter needs to be "prepared". See https://github.com/psycopg/psycopg2/issues/331
