### ISSUE TITLE
Users belong to multiple customers

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#499]
Is there a way that a user belongs to multiple but not all customers? My auth provider is gitlab and I have users that belong to multiple groups in GitLab and should therefore see multiple customers in Alerta as well. Currently only the first found group from GitLab is being used to find exactly one customer per user.

**Comment by satterly** [comment]
Support for multiple customers has been added in Release 5.1.0 which is available for download. Please test and re-open this issue if you find any problems. Thanks for the suggestion.

**Comment by jurgenhaas** [comment]
Thanks a lot @satterly for that quick response to this. My problem is that I don't have permission to re-open the issue and I can't test the functionality because the web UI doesn't seem to work with this new functionality.

As for the admin role I had to log out and login again before the UI showed any customers.

For regular users, even after a new login, now customers are being displayed. When going to the profile of a regular user, it shows an array of customers which is expected. But no alerts, not even closed ones, will be displayed for any of those customers.

I also tried for a regular user that only belongs to a single customer but that shows as an array too in their profile and therefore they don't see any alerts from any customer either.

**Comment by satterly** [comment]
It's going to easier to trouble shoot this on Gitter https://gitter.im/alerta/chat If we could continue this there that would be helpful. In the meantime, can you tell me if you are deploying via Docker (if so, there are problems with Docker not building at the moment)?

**Comment by satterly** [comment]
@jurgenhaas I can't reproduce your error.  Can you ping me on gitter chat when you get a chance. Thanks.

**Comment by satterly** [comment]
All issues related to multiple customers should be resolved now. Please test and let me know if you think otherwise.
