### ISSUE TITLE
Building RPM

### ISSUE THREAD

**Issue by hkhail** [alerta/alerta#515]
Hello,
In the alerta-webui, there is a file "alerta-webui.spec" to build a RPM. 
However, it requires a dependency : "alerta-server". 
Where to find this package ?

Thanks
H.

**Comment by satterly** [comment]
Sorry but I removed that a while ago because I didn't use it and didn't think anyone else was. It would still be in the commit history if you really needed it.

**Comment by hkhail** [comment]
Yes, I need it. I would also like to build the alerta-server RPM.

**Comment by hkhail** [comment]
I found the file. I wanted to build alerta-server-5.1.1 but I got the following error :
`
Compiling 
/root/rpmbuild/BUILDROOT/alerta-server-5.1.1-1.x86_64/opt/alerta/lib/python2.7/site-packages/jinja2/asyncfilters.py 
...
   File 
"/opt/alerta/lib/python2.7/site-packages/jinja2/asyncfilters.py", line 7
     async def auto_to_seq(value):
             ^
SyntaxError: invalid syntax

Compiling 
/root/rpmbuild/BUILDROOT/alerta-server-5.1.1-1.x86_64/opt/alerta/lib/python2.7/site-packages/jinja2/asyncsupport.py 
...
   File 
"/opt/alerta/lib/python2.7/site-packages/jinja2/asyncsupport.py", line 22
     async def concat_async(async_gen):
             ^
SyntaxError: invalid syntax
`

**Comment by satterly** [comment]
Use Python 3.5 or above. https://github.com/pallets/jinja/issues/643
