### ISSUE TITLE
Question: Is there existing 'generic' outgoing webhook for alert status / changes.

### ISSUE THREAD

**Issue by savpek** [alerta/alerta#523]
I looked through current plugins however i cannot find documented 'generic' outgoing webhook. Is this currently possible? Only solution i have figured this far is to use existing (like slack integration) and document that end user should implement api looking like slack message api to receive notifications via webhooks.

**Comment by satterly** [comment]
Just in the last few days a "forwarder" plugin has been added. See https://github.com/alerta/alerta-contrib/tree/master/plugins/forward and let us know if it works for you.
