### ISSUE TITLE
/api/auth/signup allows users to specify their own roles

### ISSUE THREAD

**Issue by Anderen2** [alerta/alerta#525]
This is something I noticed in alerta/auth/base.py and alerta/models/user.py when implementing #524.

It seems like users can define their own roles (and other metadata, such as mail verification) when signing up as the client provided JSON input (in https://github.com/alerta/alerta/blob/master/alerta/auth/basic.py#L19 ) is taken directly to https://github.com/alerta/alerta/blob/master/alerta/models/user.py#L42
```
anderen2@TCC:~$ curl -XPOST -H "Content-Type: application/json" -d '{"email": "me@example.com", "name": "me", "password": "me", "text": "", "roles": ["admin"]}' http://localhost:8000/api/auth/signup
{
  "token": "[snip]"
}
```

I am unsure if this is an issue or by design, but it made me curious enough to create this issue.

**Comment by satterly** [comment]
Thanks for raising this as an issue. I have a potential fix #526 that I'll merge when I get a chance.
