### ISSUE TITLE
Raven dependency version constraint

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#531]
Currently, Alerta requires `raven[flask]==6.1.0` and I wonder if there is a reason to not allow `>=6.1.0` because I do have other packages that require version 6.7

**Comment by satterly** [comment]
Looks like I tried that but there was a bug if I recall correctly. See https://github.com/alerta/alerta/commit/23c08cf0fe8d2324fcba7071d2ef5dde14611092

I'll see if I can work out if that is still an issue.

**Comment by jurgenhaas** [comment]
Thanks @satterly
