### ISSUE TITLE
improvement: Requirements modifications

### ISSUE THREAD

**Issue by d-ganchar** [alerta/alerta#534]
At the moment requirements in [setup.py](https://github.com/alerta/alerta/blob/master/setup.py#L39) and in [requirements.txt](https://github.com/alerta/alerta/blob/master/requirements.txt) are different.
Need to add parsing of **requirements.txt** in **setup.py** and use 1 list for installing dependencies.
Also need to freeze versions of packages(such as Flask, requests, PyJWT etc.).
What do you think?

**Comment by d-ganchar** [comment]
I propose to parse **requirements.txt** in **setup.py**. What is benefits:

- We will have 1 file with dependencies(requirements.txt)
- Less opportunity for error

**About freezing**. I propose set min versions of support. For example, at now we have:

```
pytz
PyJWT
bcrypt
```

But what is the version? We should to set available range of versions like **package>=0.2,<0.3**.

**Comment by satterly** [comment]
When you said "freeze versions" I thought you meant only support one version of a library. I would agree setting a minimum version or a range would be useful.

**Comment by satterly** [comment]
Looks like the recommended approach is to not ship a `requirements.txt` at all, but if you really need to then it should literally just be a full stop `.`. See https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py
