### ISSUE TITLE
username when login

### ISSUE THREAD

**Issue by d-ganchar** [alerta/alerta#539]
I found some strange behavior. How to reproduce:

1) We need to create a user. Send POST request to `auth/signup`. Example of data:

```
name: test
email: test@test.tt
password: test
```

Response 200 with token. 

2) Now logout and try to login. Try to send wrong(or empty) password. POST request to `/auth/login`. Backend will return the response(401):

```
{
  "code": 401,
  "errors": null,
  "message": "must supply 'username' and 'password'",
  "status": "error"
}
```

3) Now try to login with correct _username_ and _password_(test/test). Backend will return the next result:

```
{
  "code": 401,
  "errors": null,
  "message": "invalid username or password",
  "status": "error"
}
```

Looks like [frontend](https://github.com/alerta/angular-alerta-webui/blob/master/app/partials/login.html#L11) works only with `email`, but [backend](https://github.com/alerta/alerta/blob/master/alerta/auth/basic.py#L63) works with username + email. By the way db search works only by [email](https://github.com/alerta/alerta/blob/master/alerta/auth/basic.py#L68).
Also I found that only [email](https://github.com/alerta/alerta/blob/master/alerta/sql/schema.sql#L121) column has UNIQUE index, but name no and can be empty. As I understood `/auth/login` should works only with `email` and return correct messages to client. What do you think?

**Comment by satterly** [comment]
This is for backward compatibility. Previous versions of the web UI used `email/password` combination but this was changed to `username/password` a while back even though email is what is used as the password.

Confusing, I know, but considering all the different type of authentication providers I have to support it was the most consistent approach I could come up with. See https://github.com/alerta/angular-alerta-webui/commit/dcb46dd2a8064dca2b8c9af0bdd624ac1bef0405

**Comment by d-ganchar** [comment]
@satterly I understood. Thanks.
