### ISSUE TITLE
Is there way to force settings reload without full restart

### ISSUE THREAD

**Issue by savpek** [alerta/alerta#543]
Is there way to signal alerta to reload configuration without full restart? 

Basically i need to dynamically configure alerta based on end user settings (specifically smtp server and http callbacks), i think i extend image with agent that pulls new configurations and updates them to filesystem -> reload alerta. Killing process is probably fine and wait kubernetes to respawn it, but it feels litle harsh for this specific purpose.

**Comment by savpek** [comment]
Started to think that have i understood term 'integration' incorrectly, are they standalone applications that integrates alerta to other systems? 

If so i can start 'mailer' integration in different container and execute it there as long as it can reach same mq topic? That makes dynamic configuration part easier.

**Comment by satterly** [comment]
Yes, an integration is a stand-alone application or service. Running it in a separate container with access to a message queue is exactly the kind of architecture this was meant to support.

**Comment by satterly** [comment]
I'll close this for now. Just add a comment to this issue if you need more help on this topic.

**Comment by savpek** [comment]
https://github.com/alerta/docker-alerta/issues/67 releated
