### ISSUE TITLE
Cannot login with GitHub Enterprise

### ISSUE THREAD

**Issue by j-sokol** [alerta/alerta#544]
Hi,

When I add Github Oauth2 integration, I cannot finish authentication and it goes back to login window.
In the Web UI, I can click on login, which will create pop-up github window, where I can enter GitHub login name with password. Then it redirects back to AlertaUI, with this pop-up window error:
```
{"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"withCredentials":false,"url":"https://alerta-api.domain.io/auth/github","data":{"code":"79b5ac7defa2bc373524","clientId":"idhere","redirectUri":"https://alerta.domain.io"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":""}
```

This error is not telling me much. I've tried to debug this but I'm stuck at this point for a while. Do you know what could cause this?

I've configured GitHub Enterprise in the following way:

`Web UI conf`:
```
'use strict';

angular.module('config', [])
  .constant('config', {
    'endpoint'    : "https://alerta-api.domain.io",
    'provider'    : "github",
    'client_id'   : "idhere",
    'github_url'  : "https://github.domain.io",
    'colors'      : {
      'severity': {
        'critical'     : '#D8122A',
...
      },
      'text': 'white',
      'highlight': 'lightgray'
    }
  });
```
and `alertad.conf` containing:
```
# Github login
OAUTH2_CLIENT_ID = 'idhere'
OAUTH2_CLIENT_SECRET = 'secrethere'

ALLOWED_GITHUB_ORGS = ['*']

GITHUB_URL = 'https://github.domain.de'
CORS_ORIGINS = ['https://alerta.domain.io']
```
With Github Oauth2 app created with callback to `https://alerta.domain.io`.

**Comment by satterly** [comment]
`github_url` in the web UI `config.js` and `GITHUB_URL` in the `alertad.conf` file should be the same.

And are there any errors in the server log file? If not, set `DEBUG = True` and try again.

**Comment by j-sokol** [comment]
I have both `github_url` and `GITHUB_URL` set up to the same value (just forgot to write it here when I was replacing it with placeholder).

In configuration I have debug enabled, and I see some DEBUG and INFO level loglines, i.e.
```
May 15 13:44:09 ip-10-112-20-169.eu-central-1.compute.internal gunicorn[18527]: 2018-05-15 13:44:09,591 - alerta.plugins[18531]: DEBUG - Server plugin 'reject' installed. [in /opt/alerta/env/lib64/python3.4/site-packages/alerta/utils/plugi
May 15 13:44:09 ip-10-112-20-169.eu-central-1.compute.internal gunicorn[18527]: 2018-05-15 13:44:09,591 - alerta.plugins[18531]: DEBUG - Server plugin 'blackout' installed. [in /opt/alerta/env/lib64/python3.4/site-packages/alerta/utils/plu
May 15 13:44:09 ip-10-112-20-169.eu-central-1.compute.internal gunicorn[18527]: 2018-05-15 13:44:09,753 - alerta.plugins[18531]: INFO - Server plugin 'reject' enabled. [in /opt/alerta/env/lib64/python3.4/site-packages/alerta/utils/plugin.p
```
 but nothing occurs about this login. 

I've also found this issue, but the solution didn't help me much: https://github.com/alerta/angular-alerta-webui/issues/18

I tried both havind domain in `CORS_ORIGINS` and a `*`, but nothing changed it. 

Is there way to make logging even more verbose? Maybe add some debug marks to the code?

**Comment by satterly** [comment]
I get the same error when I run the alerta web UI configured to use github OAuth but the alerta API isn't available so the callback fails.

<img width="564" alt="screen shot 2018-05-15 at 17 11 44" src="https://user-images.githubusercontent.com/615057/40065860-138c4d90-5863-11e8-8f6a-bbfa724b55e2.png">

Can you set `AUTH_REQUIRED=False` and check that you can use the web UI when authentication isn't required?

**Comment by j-sokol** [comment]
So I changed `AUTH_REQUIRED` to `False` and suddenly I was able to login (Alerta backend became available?) Then I set up `AUTH_REQUIRED=True` and logging in still works.

I'll try one more redeploy if everything works fine.

Thank you!

**Comment by satterly** [comment]
Let me know if this still isn't working. I'll close this issue for now.

**Comment by fhightower** [comment]
I recently setup alerta using the instructions here: https://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html#tutorial-1 and I ran into almost the same problem. With `AUTH_REQUIRED=True`, logging in with github will not work (it gives the alert posted in the comment here: https://github.com/alerta/alerta/issues/544#issuecomment-389203978). With `AUTH_REQUIRED=False`, I am able to login, but when I change the configuration back to `AUTH_REQUIRED=True`, I am no longer able to login.

**Comment by satterly** [comment]
Please paste the `alertad.conf` and `config.js` file below (suitably redacted). Thanks.

**Comment by satterly** [comment]
@fhightower Do the OAuth App configured for Alerta have the following permissions...

<img width="778" alt="screen shot 2018-09-11 at 14 33 09" src="https://user-images.githubusercontent.com/615057/45360367-a1ab0e80-b5cf-11e8-9b0f-b687b7cd68eb.png">

**Comment by fhightower** [comment]
@satterly : Sorry it has taken me so long to get back to you. I'm not sure how to view that page you took a screenshot of.

I created my oauth token by going to *settings* > *developer settings* > *new oauth app* (https://github.com/settings/applications/new) . Is this the correct place?

Or should it be  *settings* > *developer settings* > *github apps* > *new github app* (https://github.com/settings/apps/new)

**Comment by satterly** [comment]
Ignore that. I was wrong. You are right. It is at *Settings > Developer Settings > OAuth Apps* and should look something like this ...

<img width="686" alt="screen shot 2018-09-20 at 13 33 03" src="https://user-images.githubusercontent.com/615057/45815703-baa37600-bcd9-11e8-9de7-a080557c15a7.png">

What do you see in the web browser javascript console? Any errors? And what about the network tab? Are there any 4xx or 5xx error responses?

**Comment by fhightower** [comment]
Strange, I tried it again today and it worked perfectly.

I did have `ADMIN_USERS = ['fhightower']` in the `/etc/alertad.conf`... not sure if that made the difference or not. Thanks for the help @satterly and thanks for making this great project!
