### ISSUE TITLE
[Feature Request/Idea] Mobile clients

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#553]
Mobile clients for Android and iOS would be great. Features should be:

- Persistent session
- Same features as the Alerta web UI but with a mobile UX
- Configurable notifications with and without sound

All of that should be possible by utilizing the Alerta API and I wonder if anyone has already thought about this or even got started somewhere.

**Comment by satterly** [comment]
Thanks for the feature request. I have considered something like this in the past but have not wanted to commit to having to support a UI across multiple platforms (web, Android and iOS). When I had some time I was going to look at refreshing the web UI but if a mobile client was more popular maybe I would consider that instead. However, I have no mobile experience so it would be great if a mobile dev wanted to get involved with this.

**Comment by satterly** [comment]
It would be great if this happened but unfortunately I can't see this happening any time soon. I'll reopen this issue if/when there is any change in status or a renewed interest from other parties. Thanks.
