### ISSUE TITLE
[Feature Request/Idea] Create issue in configurable systems

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#554]
There has been some work to create issues in Jira from the web UI. Not sure about the status of that feature but I'd really like to see a more comprehensive solution for this:

- Should be supported by the API and on top of that by all clients (CLI, web, mobile)
- The backend should allow plugins for various systems like Jira, GitLab, BitBucket, YouTrack and others
- Maybe the information about the created ticket should be linked to the alert so that we could update the issue when new related alerts arise

Is that something you would consider for a future Alerta version?

**Comment by satterly** [comment]
Yes, I would definitely consider something like this. It should be "plugin" based so that it could be easily extended. I assume it would rely on a notification plugin to trigger the ticket and then a webhook to handle any updates. Is that about right?

**Comment by jurgenhaas** [comment]
> It should be "plugin" based so that it could be easily extended. I assume it would rely on a notification plugin to trigger the ticket and then a webhook to handle any updates. Is that about right?

Something along those lines. Let me try explaining it in my own words in more detail:

- **Backend configuration**: there should be a default - and optionally a separate definition for each customer - which specifies the plugin and plugin dependant extra parameters
- **New API endpoint**: I guess there should be an endpoint (let's call it `createIssue`) that can be triggered with an alert as the only parameter. This API endpoint then determines the correct plugin and its configuration and passes the alert over to that plugin. This plugin does its internal stuff (e.g. creating an issue with Jira, Gitlab, or else) and returns an ID for the newly created issue. This ID is stored by the API endpoint somewhere with the meta data of the given alert.
- **Updates**: If an alert gets an update in the future, the backend verifies if the original alert has an issue ID and if so, triggers the associated plugin again to let that update the external issue again.

With this architecture the process can then be triggered automatically (following certain rules) or manually from a button in either of the clients (web UI or mobile or else).

Does that make sense?

**Comment by tester22** [comment]
I have built an JIRA integration using an plugin and an extension in the web ui.

In my use case there is an additional 5 fields that the user need to enter before the issue actually can be created. This is also something that need to be considered so maybe the createIssue endpoint should support adding for manipulating attributes in the alert.

**Comment by iDemonix** [comment]
Is this still a goer? I'm testing implementing Alerta to replace an in-house legacy overview that fronts Icinga2/Nagios boxes, but we use a ticket system and currently we can have ticket details built-in to our overview/dashboard.

It'd be great to be able to trigger a notification script and have an API endpoint that could work with something like Request Tracker. Storing a ticket ID against the alert as metadata would be very useful, a future improvement could be configurable URLs (i.e. 'http://ticket.internal/?ticket=') so they're clickable from Alerta.

**Comment by tester22** [comment]
I think it looks good.
From my perspective I would have prefered that there is some kind of popup where the user can enter defined values (eg queue) based on values in the alerts. But this is an good start!

**Comment by satterly** [comment]
@tester22 Yes, that should be possible and it makes sense to support something like that, though I'm not sure how. Anyway, once the basics are sorted out this can be iterated on in future releases.

**Comment by iDemonix** [comment]
@satterly Looks good! I agree some configurability would be nice, but that can wait, and might require that it's treated similar to a plugin for different onward systems/APIs.

**Comment by satterly** [comment]
Thanks for your feedback. This is now available as Alerta Release 6.2.0.
