### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by middelthun** [alerta/alerta#558]
Hi!

Would it be possible to have a release bump? I've been waiting for the newly merged pull requests, and it would be nice with a fresh version from pip.

**Comment by satterly** [comment]
Released 5.2.4 a few minutes ago. Should be PyPI about now ... https://pypi.org/project/alerta-server/5.2.4/ 

Please test and let me know if there's any issues. Thanks!

**Comment by middelthun** [comment]
Ah, that was quick! :) Tested, it works. Thank you very much!
