### ISSUE TITLE
Alarm Status after Blackout Period with NOTIFICATION_BLACKOUT=True

### ISSUE THREAD

**Issue by zachmoody** [alerta/alerta#559]
Noticed that when we have `NOTIFICATION_BLACKOUT=True` that the alert fails to go back to an `Open` state after the blackout has expired. Not sure if this is configuration error on our part or something else. Running alerta-server==5.2.3.

**Comment by satterly** [comment]
If an alarm condition still exists after the blackout period has expired **and the alert is resent at regular intervals** then the alert status will change to `open` from `blackout` the next time the alert is sent. If the alert is not resent after the blackout period expires then Alerta can not know that the alarm condition is still active and has no reason to update the alert status.

**Comment by zachmoody** [comment]
I figured as much, but I'm not seeing that behavior. If I delete a blackout, or let it expire, the status stays in `blackout` despite the `Last Receive Time` being current and `duplicates` incrementing. Would it make a difference if the alert was coming in via a webhook? These alerts are coming in from the prometheus webhook.

**Comment by zachmoody** [comment]
Fwiw, I tested from the CLI client and updated to 5.2.4, but to no avail.

**Comment by satterly** [comment]
After merging this fix I re-ran your test and it resulted in the alert status being `open` once the blackout period had been deleted, as it should.
```
$ alerta --profile gitlab query -i 6ea9260d
 ID       | LAST RECEIVED       | SEVERITY   | STATUS   |   DUPL | CUSTOMER   | ENVIRONMENT   | SERVICE   | RESOURCE   | GROUP   | EVENT   | VALUE   | TEXT
----------+---------------------+------------+----------+--------+------------+---------------+-----------+------------+---------+---------+---------+--------
 6ea9260d | 2018/07/04 20:19:43 | critical   | open     |      2 |            | Production    | Foo       | TEST::TEST | Misc    | TEST    |         |
```
