### ISSUE TITLE
Alerts sent in with severity OK/cleared/normal gets status open

### ISSUE THREAD

**Issue by Anderen2** [alerta/alerta#560]
Hi!

It seems like alerts raised to Alerta with the status OK/cleared/normal becomes regular alerts with the open status. Then when this alert gets cleared again it goes to closed. 

Is this intended behavior, or would you accept a pull request which discards alarms in a normal/clear/ok severity with no matching alert which already exists? 

Thanks!

**Comment by Anderen2** [comment]
Hi!

I'm sorry, you are correct. When I dived deeper into this I discovered that the system that had this issue explicitly sent the alarm with a status of "Open" and a cleared severity. In that situation Alerta creates Open alarms with a cleared status, and they get closed on the next iteration. I consider Alerta to work as intended in that scenario. 

However, since we are already discussing this. Is there any reason for accepting cleared alarms with no previous severity at all? 

For some background, we have some legacy systems using a wrapper to communicate with Alerta. These systems send alerts in intervals even if the status is all good or not. 
To avoid cluttering the "closed" view with alarms that have been OK since forever we've created a plugin to disregard all cleared alarms that has no previous alarm to clear. (returns BlackoutPeriod with a custom message).

Would it be an idea to do this internally in Alerta? Or should we just keep it as a plugin?

**Comment by satterly** [comment]
This sounds like an edge case that I couldn't be sure everyone would want to handle the same way so I think making use of a plugin to do exactly what you want is the correct approach. It might be good to publish your plugin as a github gist or some other way as it might be useful to others. As you wish.
