### ISSUE TITLE
Login with GitLab no longer working

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#562]
This morning I started to get the following stacktrace when trying to login to Alerta 5.2.4 with GitLab auth:

```
Traceback (most recent call last):
  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File \"/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py\", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File \"/usr/local/lib/python2.7/dist-packages/alerta/auth/gitlab.py\", line 36, in gitlab
    groups = [g['path'] for g in r.json()]
TypeError: string indices must be integers
```

Any idea what could be causing this?

**Comment by satterly** [comment]
Are you saying this stopped working when you upgraded to 5.2.4? Are you using gitlab.com or a self-hosted solution? Has the gitlab side been updated recently?

**Comment by jurgenhaas** [comment]
> Are you saying this stopped working when you upgraded to 5.2.4?

Sorry, no. I had upgraded the day after 5.2.4 came out. I just wanted to report the current version.

> Are you using gitlab.com or a self-hosted solution?

I'm using a self-hosted solution.

> Has the gitlab side been updated recently?

The last update was on June 28 to 11.0.2 and it may well be that this is when things changed. I can't tell for sure because I don't have to login each and every day as the cookie lifetime is a couple of days.

The error seems to be Python 2 specific so I may go ahead and switch to Python 3. What is the recommended way of doing this for alerta when run with uwsgi?

**Comment by satterly** [comment]
It's not related to python 2 or python 3. Looks like the Gitlab API has changed...
```
{'error': 'API V3 is no longer supported. Use API V4 instead.'}
```

**Comment by jurgenhaas** [comment]
Yes, that's true. They have deprecated API V3 a long time ago. Does this mean that this needs to be fixed in Alerta?

**Comment by satterly** [comment]
Since GitLab 9.0, API V4 is the preferred version to be used.

API V3 was unsupported from GitLab 9.5, released on August 22, 2017. API v3 was removed in GitLab 11.0.

See https://docs.gitlab.com/ee/api/v3_to_v4.html

**Comment by jurgenhaas** [comment]
Maybe using this [library](https://github.com/python-gitlab/python-gitlab) is an option? They handle both versions of the API and provide your own application with an abstraction layer which makes integration much easier. I've used their library for a couple of years already in an Ansible plugin and been very happy with it.

**Comment by satterly** [comment]
Thanks for the suggestion but it was a simple matter of bumping the version number in the API base URL.
