### ISSUE TITLE
Workflow for normal/ok alerts

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#567]
Hi.

I have many checks which are running every hour and sending a major/minor/warning on failures or normal/ok if everything is fine. So the alerts never get deleted because they are constantly received (with ok status).
What is the designed solution for this use case?

My first impression would be that the lastReceived time is not updated for already closed alerts and not existing alerts will not be created when receiving normal/ok. Do I need to created a plugin for this by myself?

Thanks

**Comment by satterly** [comment]
I would suggest you write a plugin that rejects OK alerts that aren't currently active and that also sets the timeout to less than 1 hour (as that is your resend interval) for OK alerts. That way, alerts that go into an OK state are deleted within the hour and are not accepted again until they become active. This is similar to what I suggested in #560 but in that case they were only concerned about not receiving OK alerts for alerts that weren't already active. This is a more comprehensive solution and something I would consider including as an out-of-the-box plugin, though perhaps not enabled by default.

**Comment by escoand** [comment]
Thanks for your answer. I've already created a plugin for that which could be included in the release if you want.

´´´
try:
    from alerta.plugins import app  # alerta >= 5.0
except ImportError:
    from alerta.app import app  # alerta < 5.0

from alerta.exceptions import BlackoutPeriod
from alerta.models import severity_code
from alerta.plugins import PluginBase


class UninterestingNormalAlert(BlackoutPeriod):
    """Alert was not processed because it was normal and uninteresting."""
    pass


class IgnoreUninterestingNormal(PluginBase):

    def pre_receive(self, alert):

        if severity_code.Severity.name_to_code(alert.severity) == severity_code.Severity.name_to_code(severity_code.NORMAL):
            if alert.is_duplicate():
                raise UninterestingNormalAlert("Ignore, alert already on severity normal")
            elif not alert.is_correlated():
                raise UninterestingNormalAlert("Ignore, new alert with severity normal")

        return alert

    def post_receive(self, alert):
        return

    def status_change(self, alert, status, text):
        return
´´´

**Comment by satterly** [comment]
Thanks a lot. I'll use this as a starting point. 👍
