### ISSUE TITLE
New Feature - Add comments in alerts

### ISSUE THREAD

**Issue by francopeapea** [alerta/alerta#572]
As described in the tittle, it would be good to be able to add comment if the alert get shelved or closed so if someone goes and see why it's in that state you can check there faster than ask everyone in your team.
Also would be good to add simple comment in open alerts so if the alert still there and someone is working on it you can know that way

**Comment by satterly** [comment]
Reasonable request. There have been similar suggestions before. See alerta/angular-alerta-webui#130 I'll add this to the backlog. Thanks for the feedback.

**Comment by jeremystretch** [comment]
Hey @satterly, did you ever start down this road? We keep running into a workflow issue:

1. Get alert for something that's not an immediate fix (e.g. dead PDU)
2. Ack the alert and open a ticket
3. New person comes on shift and sees the acked alert, has to go look for a relevant ticket

**Comment by satterly** [comment]
Yes. This will be available in the next major release of the web console which is currently in development. I'll keep you posted on progress and perhaps you could help by beta testing it.

**Comment by pad92** [comment]
I would also be interested in this feature in order to link an Alerta alert to a ticketing toolI would also be interested in this feature in order to link an Alerta alert to a ticketing tool

**Comment by satterly** [comment]
A beta version of the full rewrite of the Alerta web console is available at https://beta.alerta.io

The repo is at https://github.com/alerta/beta.alerta.io however issues are currently closed. Issues will be open once the project moves from "beta" to "release candidate" stage.

Feedback is very welcome but please direct **questions, comments and feedback** to the [Gitter chat room](https://gitter.im/alerta/chat) for the time being. I will collate what I get and track it separately on a development Trello board.

There is no timeline for delivery of this new release of the web UI but it would be nice to have it finished before the current version's 5th birthday in April this year.

**Comment by satterly** [comment]
See alerta/beta.alerta.io#73
