### ISSUE TITLE
Feature Request - Add all status filter

### ISSUE THREAD

**Issue by francopeapea** [alerta/alerta#577]
In the status filter it should be a * (All) status filter, so you can filter both by specific service and see all closed, shelved, open, active and closed at the same time. And you can check if there are coming all the checks and alerts from a specific server or service

![screen shot 2018-07-18 at 12 31 20 pm](https://user-images.githubusercontent.com/16282981/42903423-a102dc66-8a86-11e8-83a4-356b7704d8e2.png)

**Comment by satterly** [comment]
I'll add this to the UI backlog and close this issue. Thanks for the feedback.
