### ISSUE TITLE
[Feature Request] MySQL support for backend

### ISSUE THREAD

**Issue by francopeapea** [alerta/alerta#579]
Hello Nick, are you working in any other DB support for the backend? I was thinking about starting some MySQL support for this but in case you have something done I could contribute to it.

The reason here is. PostgreSQL has no master-master replication support. And MongoDB has special license that not every cloud provider accept MongoDB in their policies. So the third option with good backend and good replication methods it's MySQL

**Comment by PMDubuc** [comment]
Just wondering if this would also support [MariaDB](https://mariadb.org/) since [MySQL is now owned by Oracle](http://www.oracle.com/technetwork/database/mysql/index.html).

**Comment by francopeapea** [comment]
It should, the only modification needed its change the cursor, the rest are only queries into the database

**Comment by satterly** [comment]
Adding additional backends is not on the roadmap but if you want to add support for mysql/mariadb k would be happy to accept it -- as long as all the tests pass, of course.

Let me know if I can be of any assistance.

**Comment by francopeapea** [comment]
I have already adapt the code to accept mysql backend, there is another step, change the schema so it can be used by it

**Comment by francopeapea** [comment]
I will commit the code in case anyone can help me adapting the schema

**Comment by francopeapea** [comment]
This issue refers to #580

**Comment by satterly** [comment]
Closing as no progress for a month. I will reopen the issue if work restarts. Thanks.

**Comment by jet-go** [comment]
Hi @satterly 
Is there any plan to provide mysql backend?
If not, I would like to pick this up & create PR for this.

I've been using alerta for some time now, it's really cool with so many integrations/plugins. 
It would be nice to have mysql/mariadb as backend. 

Let me know, if it's okay to go ahead with this.

Thanks,

**Comment by satterly** [comment]
Thanks for the offer. You are welcome to give it a go. It is a lot of work though. Let me know if you need any pointers.

**Comment by jet-go** [comment]
Cool, let me give a try. If I need any help will reach out on slack.

**Comment by rickmce** [comment]
Good afternoon.
Does the current version already support MySQL or only in the branch you developed?  I saw that the main branch has been unchanged for some time
