### ISSUE TITLE
Sign up does not work

### ISSUE THREAD

**Issue by banzayats** [alerta/alerta#584]
Hello

I've installed Alerta with uWSGI/Nginx. 
Now I'm trying to create new user but it shows me the error:
![image](https://user-images.githubusercontent.com/477161/43319936-40717468-91af-11e8-95f4-1f7790f63958.png)

Here is output from alert-cli:

```
# alerta user --name vadim --email vadim@example.com --password test --status active
ERROR: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
```

Here is the output from /api/:
`
...{"href":"http://alerta-host/alerts/top10/standing","method":"GET","rel":"api.get_top10_standing"},{"href":"http://alerta-host/auth/github","method":"POST","rel":"auth.github"},{"href":"http://alerta-host/auth/gitlab","method":"POST","rel":"auth.gitlab"},{"href":"http://alerta-host/auth/google","method":"POST","rel":"auth.google"},{"href":"http://alerta-host/auth/keycloak","method":"POST","rel":"auth.keycloak"},{"href":"http://alerta-host/auth/login","method":"POST","rel":"auth.login"},{"href":"http://alerta-host/auth/pingfederate","method":"POST","rel":"auth.pingfederate"},{"href":"http://alerta-host/auth/saml","method":"GET","rel":"auth.saml_redirect_to_idp"},{"href":"http://alerta-host/auth/saml","method":"POST","rel":"auth.saml_response_from_idp"},{"href":"http://alerta-host/auth/saml/metadata.xml","method":"GET","rel":"auth.saml_metadata"},{"href":"http://alerta-host/blackout","method":"POST","rel":"api.create_blackout"},...`

I cannot see _/auth/signup_ in the list. What could be the problem?

**Comment by satterly** [comment]
What happens if you try to create a user from the `alerta` CLI? 

For example (note: use `--debug` to show debug output) ...
```
$ alerta --debug user --name foo --email foobar@example.com --password foo
send: 'POST /auth/signup HTTP/1.1\r\nHost: localhost:8080\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.19.1\r\nContent-Type: application/json\r\nContent-Length: 151\r\nAuthorization: Key \r\n\r\n{"status": null, "email_verified": false, "name": "foo", "roles": [], "text": null, "attributes": {}, "password": "foo", "email": "foobar@example.com"}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 01 Aug 2018 08:28:37 GMT
header: Server: Apache/2.4.18 (Ubuntu)
header: Access-Control-Allow-Origin: http://localhost
header: Vary: Origin,Accept-Encoding
header: Access-Control-Allow-Credentials: true
header: Content-Encoding: gzip
header: Content-Length: 427
header: Keep-Alive: timeout=5, max=100
header: Connection: Keep-Alive
header: Content-Type: application/json

body: {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OWQ5OTZjYi1iMjhiLTRlNmEtODhmMi0yZWFiNzZhY2I4MTUiLCJyb2xlcyI6WyJ1c2VyIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC8iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJmb29iYXJAZXhhbXBsZS5jb20iLCJuYW1lIjoiZm9vIiwiZW1haWwiOiJmb29iYXJAZXhhbXBsZS5jb20iLCJzY29wZSI6InJlYWQgd3JpdGUiLCJqdGkiOiJjNWEwYTU2Mi1hMjFkLTRiNmEtODE4NS0zNmJmOTAwYjFiM2EiLCJleHAiOjE1MzQzMjE3MTcsInByb3ZpZGVyIjoiYmFzaWMiLCJpYXQiOjE1MzMxMTIxMTcsIm5iZiI6MTUzMzExMjExNywiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwLyJ9.lWN-Ejmoic6kdEpfQXREPYtRQfpLJiYriN3zNpfVccU"}

Created.
```

**Comment by banzayats** [comment]
As was previously mentioned, here is output from alert-cli:

```
# alerta user --name vadim --email vadim@example.com --password test --status active
ERROR: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
```

With debug:
```
# alerta --debug user --name foo --email foobar@example.com --password foo
send: 'POST /api//auth/signup HTTP/1.1\r\nHost: alerta.server\r\nContent-Length: 151\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-862.9.1.el7.x86_64\r\nConnection: keep-alive\r\nContent-Type: application/json\r\nAuthorization: Key \r\n\r\n{"status": null, "email_verified": false, "name": "foo", "roles": [], "text": null, "attributes": {}, "password": "foo", "email": "foobar@example.com"}'
reply: 'HTTP/1.1 404 NOT FOUND\r\n'
header: Server: nginx/1.12.2
header: Date: Wed, 01 Aug 2018 11:27:19 GMT
header: Content-Type: application/json
header: Content-Length: 314
header: Connection: keep-alive
header: Access-Control-Allow-Origin: http://localhost
header: Vary: Origin

body: {"code":404,"errors":["The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."],"message":"404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.","status":"error"}

ERROR: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
```

And here is another query:
```
# alerta --debug query
send: 'GET /api//alerts HTTP/1.1\r\nHost: alerta.server\r\nConnection: keep-alive\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nAuthorization: Key \r\nUser-Agent: python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-862.9.1.el7.x86_64\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx/1.12.2
header: Date: Wed, 01 Aug 2018 11:31:55 GMT
header: Content-Type: application/json
header: Content-Length: 1979
header: Connection: keep-alive
header: Access-Control-Allow-Origin: http://localhost
header: Vary: Origin, Accept-Encoding
header: Content-Encoding: gzip

body: {"alerts":[{"attributes":...
```
Alerta version: **alerta (5.2.0)**

**Comment by banzayats** [comment]
alerta (5.2.0)
alerta-server (5.2.6)
argcomplete (1.7.0)
backports.ssl-match-hostname (3.5.0.1)
bcrypt (3.1.4)
beautifulsoup4 (4.3.2)
blinker (1.4)
cffi (1.6.0)
chardet (2.2.1)
click (6.7)
configobj (4.7.2)
contextlib2 (0.5.5)
cryptography (1.7.2)
decorator (3.4.0)
dnspython (1.12.0)
enum34 (1.0.4)
ethtool (0.8)
Flask (1.0.2)
Flask-Compress (1.4.0)
Flask-Cors (3.0.6)
future (0.16.0)
gssapi (1.2.0)
html5lib (0.999)
idna (2.4)
iniparse (0.4)
ipaclient (4.5.4)
ipaddress (1.0.16)
ipalib (4.5.4)
ipaplatform (4.5.4)
ipapython (4.5.4)
isodate (0.5.4)
itsdangerous (0.24)
Jinja2 (2.10)
jwcrypto (0.4.2)
kitchen (1.1.1)
langtable (0.0.31)
lxml (3.2.1)
MarkupSafe (1.0)
netaddr (0.7.5)
netifaces (0.10.4)
perf (0.1)
pip (8.1.2)
ply (3.4)
psutil (2.2.1)
psycopg2 (2.7.5)
pulp-agent (2.10.3)
pulp-common (2.10.3)
pulp-rpm-common (2.10.3)
pulp-rpm-handlers (2.10.3)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.14)
pycurl (7.19.0)
pygobject (3.22.0)
pygpgme (0.3)
pyinotify (0.9.4)
PyJWT (1.6.4)
pyliblzma (0.5.3)
pymongo (3.7.1)
pyOpenSSL (0.13.1)
python-augeas (0.5.0)
python-dateutil (1.5)
python-dmidecode (3.10.13)
python-ldap (2.4.15)
python-linux-procfs (0.4.9)
python-nss (0.16.0)
python-yubico (1.2.3)
pytz (2016.10)
pyudev (0.15)
pyusb (1.0.0b1)
pyxattr (0.5.1)
qrcode (5.0.1)
raven (6.9.0)
requests (2.6.0)
schedutils (0.4)
setuptools (0.9.8)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
SSSDConfig (1.16.0)
subscription-manager (1.20.11)
tabulate (0.8.2)
urlgrabber (3.10)
urllib3 (1.10.2)
uWSGI (2.0.17.1)
Werkzeug (0.14.1)
yum-langpacks (0.4.2)
yum-metadata-parser (1.1.4)

**Comment by satterly** [comment]
I see `python-ldap` in that output. Are you using LDAP Basic Auth? If not, uninstall it using ...
```
pip uninstall python-ldap
```
If you don't uninstall it then Alerta will assume you are using LDAP and not let you create users. You must manage users in LDAP instead.

**Comment by banzayats** [comment]
The problem is:
```
$ rpm -q --whatrequires python-ldap
python2-ipalib-4.5.4-10.el7.centos.3.noarch
ipa-client-4.5.4-10.el7.centos.3.x86_64
```
If I remove python-ldap I will loose IPA...

OK. I will try to run alerta in virtualenv

**Comment by banzayats** [comment]
Created virtualenv:
`virtualenv /opt/virtualenvs/alerta`

Changed /etc/uwsgi.ini
```
[uwsgi]
virtualenv = /opt/virtualenvs/alerta
...
```

Changed alerta-app.service:
```
...
[Service]
ExecStart=/usr/bin/bash -c 'source /opt/virtualenvs/alerta/bin/activate; uwsgi --ini /etc/uwsgi.ini'
...
```

Now it works!

**Comment by cukal** [comment]
Same problem. Removing ldap didn't do the trick. virtualenv did.
