### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by y-mori0110** [alerta/alerta#586]
I tried the [tutorial-2-housekeeping,](http://docs.alerta.io/en/latest/gettingstarted/tutorial-2-housekeeping.html#tutorial-2) except for housekeeping, the timeout value of duplicate alerts did not change.

This  is the procedure.

1-1. Send new alert with timeout 20
```
#alerta send -r user01 -e fail -s major -E Code -S Security -t 'user01 login failled.' --timeout 20
```
From alerta UI, I checked the status was “open” and the timeout value was  “20”. 

1-2. After 20 seconds, perform the housekeeping
```
#alerta housekeeping
```
I checked the status was “Expired” and the timeout value was “86400”

1-3. Resend same alert with timeout 20
```
#alerta send -r user01 -e fail -s major -E Code -S Security -t 'user01 login failled.' --timeout 20
```
I checked the status was “Open” and the timeout value keep “86400” 
I expected  the timeout value changes to 20.

Next delete the before alerts, I  send alerts with changing the timeout value. 

2-1. Send new alert with timeout 20
```
#alerta send -r user01 -e fail -s major -E Code -S Security -t 'user01 login failled.' --timeout 20
```
From the alerta UI, I checked the status was “open” and the timeout value was  “20”. 

2-2. Resend same alert with timeout 30
```
#alerta send -r user01 -e fail -s major -E Code -S Security -t 'user01 login failled.' --timeout 30
```
From the alerta UI, I checked the status was “open” and the timeout value was  “20”. 
I expected  the timeout value changes to 30.

Is this normal ?

My env is
- Alerta server 5.2.6
- PostgreSQL 9.6
- Python 3.6

**Comment by satterly** [comment]
No, it's not how it should work. Thanks for the fix. Merging now...
