### ISSUE TITLE
[Question] about scaling and high availability

### ISSUE THREAD

**Issue by PMDubuc** [alerta/alerta#591]
I have a questions regarding this topic:

>Scalability
>
> Alerta can scale horizontally, in the same way any other web application scales horizontally – a load balancer handles the HTTP requests and distributes those requests between all available application servers.
> 
> >Note:
> >
>> If using multiple API servers ensure the same SECRET_KEY is used across all servers otherwise there will be problems with web UI user logins.
>
> High Availability
> 
> To achieve high system availability the Alerta API should be deployed to scale out horizontally and the MongoDB database should be deployed as a replica set.

I have the MongoDB deployed as a 3 node replica set and I've deployed an instance of Alerta as a uwsgi app on each of the nodes.  I haven't put the load balancer (HAProxy) in yet, but I've noticed that t the Alerta web console on two of the nodes do not seem able to connect to MongoDB.  I can see alerts only on the web console of only one of the nodes.  Does Alerta need to be configured differently in this arrangement other than all instances having the same SECRET_KEY?

Help from anyone who has tried this HA configuration, would be very much appreciated.  Thanks!

**Comment by satterly** [comment]
The load balancer sits in front of the Alerta API (web tier) and all API's should connect to the primary database in the replica set. See the diagram below which is a typical example of this setup...

![blank-network-diagram-page-1-2](https://user-images.githubusercontent.com/615057/43657921-764093be-9757-11e8-96e9-dabed7c2feb5.png)

Does your architecture look like this diagram? (Ignore the fact that it says RDS and assume that it is any database that supports master-slave replication).

**Comment by PMDubuc** [comment]
The load balancer directs requests to available Alerta instances, but what happens when a new MongoDB primary is elected (when the old one is unavailable). How does the Alerta web app know how to access the new primary?

**Comment by satterly** [comment]
Does your mongodb connection string look like this ...

mongodb://db1.example.net:27017,db2.example.net:2500/?replicaSet=test

See https://docs.mongodb.com/manual/reference/connection-string/#replica-set-option

**Comment by PMDubuc** [comment]
No.  I don't have DATABASE_URL set at all.  So, it must default to localhost.  When I set DATABASE_URL, I get a syntax error in the syslog pointing to the first : after "mongodb".

```
Aug  3 15:42:15 pmd-alerta alertad:     DATABASE_URL = mongodb://XX.XXX.XX.XXX:27017,XX.XXX.XX.X:27017,XX.XXX.XX.XX:27017/?replicaSet=alerta
Aug  3 15:42:15 pmd-alerta alertad:                           ^
Aug  3 15:42:15 pmd-alerta alertad: SyntaxError: invalid syntax
```

**Comment by satterly** [comment]
Ah. Sorry. Forgot the single quotes. 

`DATABASE_URL='mongodb://db1.example.net:27017,db2.example.net:2500/?replicaSet=test'`

**Comment by PMDubuc** [comment]
Got that.  Now I'm seeing errors like:

```
2018-08-03 15:56:37,495 - flask.app[25686]: ERROR - No default database def
                                             Traceback (most recent call last):
                                               File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1811, in
                                                 rv = self.preprocess_request()
                                               File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2087, in
                                                 rv = func()
                                               File "/usr/local/lib/python3.5/dist-packages/alerta/database/base.py", li
                                                 g.db = self.connect()
                                               File "/usr/local/lib/python3.5/dist-packages/alerta/database/backends/mon
                                                 db = self.client.get_default_database()
                                               File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", li
                                                 raise ConfigurationError('No default database defined')
                                             pymongo.errors.ConfigurationError: No default database defined

```

When I restart the uwsgi service.  Do I need to set DATABASE_NAME?

**Comment by satterly** [comment]
The full format is `mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]`

So you need to add your database name before the question mark. 

`DATABASE_URL='mongodb://db1.example.net:27017,db2.example.net:2500/mydb?replicaSet=test'`

**Comment by PMDubuc** [comment]
Where is the database name defined?

**Comment by PMDubuc** [comment]
Found it: "monitoring"

**Comment by PMDubuc** [comment]
It seems to be working now.  Thanks again for you're help!
