### ISSUE TITLE
Password tab doesn't work on Developer Console

### ISSUE THREAD

**Issue by DeathlyChicken1** [alerta/alerta#599]
I recently downloaded Ubuntu on my Acer Chromebook 14. I had some time exploring around the operating system then I went to log off. Once I hit the button, it took me straight back to Chrome OS. That's what I expected. Then, I pressed the shortcut key ctrl alt forward to get to Linux. It then took me to some Developer Console and It told me 'localhost login'. Is localhost login the Username I put when downloading on the developer shell? Anyway, I entered it in and then pressed enter and took me to the password. I entered it in but, as I typed, nothing showed or even moved. I need help

**Comment by satterly** [comment]
This is not an issues list for Ubuntu or Chrome. I think you've come to the wrong place.

**Comment by DeathlyChicken1** [comment]
Sorry man, I'm new to Github and I don't know how it works.

Can you tell me where the issues list for Ubuntu/Chrome is?

Many thanks
