### ISSUE TITLE
Email as an Alert Source into Alerta

### ISSUE THREAD

**Issue by danfoxley** [alerta/alerta#612]
Is there support to alert FROM email into Alerta. I have several systems that only have the ability to source alerts via email. If no, what would that look like to get email into Alerta?

Thanks,
Dan

**Comment by satterly** [comment]
Check out https://github.com/alerta/alerta-contrib/blob/master/webhooks/mailgun/README.md

**Comment by burakksglu** [comment]
Sorry to bump this up @danfoxley. How did you manage to do this if you did it? I am looking for best practices Email-to-Alerta :)

**Comment by danfoxley** [comment]
@burakksglu hope this points you in the right direction.
Required installing plugin and signing up for Mailgun service, I didn't mess with Postfix.

Install Plugin to Alerta:
![GitHub-Email](https://user-images.githubusercontent.com/2074038/81074289-a952b180-8e9d-11ea-99b0-e944f3d8e22f.png)

Go to your alerta instance URL http://alerta.mydomain.com/api  and search for "mailgun" in the output to see if mailgun is now installed.

- Create Mailgun account
- Add **public Internet** DNS records.  In my case I created a new subdomain just for Alerta. Following Mailgun installation guide created required DNS records (TXT, MX, CNAME) for alerta.mydomain.com, so email to somealertdestination@alerta.mydomain.com will be received by Mailgun.

Then allow Mailgun to post to Alerta from the Internet (open your firewall).

**Comment by burakksglu** [comment]
Thank you for detailed explanation. One more question tho, did you buy the mailgun or did you already have it? Cause we don't have that service right now and looking for a free/opensource alternative. Maybe even I'll parse and send to webhook via script.

**Comment by danfoxley** [comment]
Got freemium account, and what looked to be my volume would be quite low.
