### ISSUE TITLE
Alerta de-duplication

### ISSUE THREAD

**Issue by amohit1315** [alerta/alerta#615]
Hi,

After going through the documentation and implementing alerta. I see that alerta de-duplicates based on (Environment, Resource, Event). But my data set has say suppose (Environment, resource, event) same but one property as device-id different.

[Environment: production, Resource: Alarmset, Event: nod1, device-id: R1]
[Environment: production, Resource: Alarmset, Event: nod1, device-id: R2]

Now alerta combines these two as one unit and increase the duplicate count. Is there a way to add some extra attribute to prevent this de-duplication as I am trying get these both data unit separately.

Also I don't want to combine Event and device-id as node1_R1, node1_R2.

Is it possible?

**Comment by satterly** [comment]
What is "Alarmset"? It doesn't sound like it should be the "resource under alarm". I suggest you use "device-id" for `resource` and "Alarmset" should be the `group`. Alternatively, the `resource` could be combined "Alarmset:device-id" if that makes more sense.

Either way, you need to find a combination of `event` and `resource` that is unique and that is meaningful to you.

**Comment by kvaps** [comment]
@satterly how resource field is measured?

I tried to assign label `resource` in my alerts but it's not working for some reason.
