### ISSUE TITLE
Unable to create API key from UI

### ISSUE THREAD

**Issue by heydonovan** [alerta/alerta#620]
I'm here: http://127.0.0.1:8080/#/keys - Filling in the form does nothing, tried all browsers.

**Comment by satterly** [comment]
Open the browser developer console and see what the HTTP response is in the network tab or if there are any javascript console errors.

**Comment by heydonovan** [comment]
It's running in a docker container, so it can't be a misconfiguration:

![image](https://user-images.githubusercontent.com/918946/44788357-6e906600-ab5f-11e8-980c-0956ae1fa580.png)

**Comment by satterly** [comment]
What's the actual http response body for that 400 error? you can get it from the network tab. the response body can be found as in the image below ...
<img width="1024" alt="screen shot 2018-08-29 at 14 47 58" src="https://user-images.githubusercontent.com/615057/44788515-8afdc400-ab9a-11e8-9477-66f2d1188a02.png">

**Comment by heydonovan** [comment]
The response is:

```
{"code":400,"errors":null,"message":"not allowed to set customer to 'my_customer'","status":"error"}`
```

**Comment by heydonovan** [comment]
Maybe it's because I'm using a local version? I'm trying to deploy it on a production instance, cause I'm ready to use it, and start hacking at it, but Heroku looks to only be a demo:

https://github.com/alerta/heroku-api-alerta

**Comment by satterly** [comment]
Does the customer lookup for "my_customer" exist? Are you an admin?

**Comment by satterly** [comment]
If this is still a problem let me know and we can reopen this issue.
