### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by cukal** [alerta/alerta#624]
When using the SMTP verification email the mail contains a link with ip. 
How can I change that to a link with the full dns name?

**Comment by kjetilmjos** [comment]
try setting base url in settings: BASE_URL = ''

**Comment by cukal** [comment]
@kjetilmjos thanks for your reply! 
You mean /etc/alertad.conf ? It's currently set to ```BASE_URL='/api'```.
Changing that seems to only impact the URL after the http://<hostname/ part. 
Setting to empty breaks the link, it goes to /auth instead of /api/auth.

**Comment by satterly** [comment]
Does the Alerta docker container have a DNS resolvable hostname associated with it? What's the URL of the Alerta web UI? It is a FQDN or IP addresses?

**Comment by cukal** [comment]
No docker but using the DNS name generates a mail with the right hostname. Extremely logical but it totally escaped me. Thanks!
