### ISSUE TITLE
Shelve

### ISSUE THREAD

**Issue by cukal** [alerta/alerta#625]
When running with ```AUTH_REQUIRED = False``` (5.2.9) it seems possible for anyone to shelve an alert. Is that maybe deliberately done? I would think that would be only possible when being logged in?

**Comment by satterly** [comment]
This is a bug. It seems the button isn't being correctly disabled because it's a drop-down. See https://github.com/alerta/angular-alerta-webui/blob/master/app/partials/alert-details.html#L16
