### ISSUE TITLE
Webhook 500 Traceback

### ISSUE THREAD

**Issue by iDemonix** [alerta/alerta#628]
I'm running alerta in a container, and the container was launched with the `PLUGINS` and `INSTALL_PLUGINS` set appropriately to use `prometheus`. 

Whenever I GET/POST the endpoint, I'm receiving:

http://ip.ip.ip.ip/api/webhooks/prometheus:

```
{
"code": 500,
"errors": [
"Traceback (most recent call last):\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/venv/lib/python3.6/site-packages/flask_cors/decorator.py\", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File \"/venv/lib/python3.6/site-packages/alerta/auth/decorators.py\", line 94, in wrapped\n    return f(*args, **kwargs)\n  File \"/venv/lib/python3.6/site-packages/alerta/webhooks/custom.py\", line 17, in custom\n    incomingAlert = custom_webhooks.webhooks[webhook].incoming(\nKeyError: 'prometheus'\n"
],
"message": "'prometheus'",
"status": "error"
}
```

Am I doing something wrong? I jumped in to the Docker container and installed the plugin from github manually, but still seem to be missing something.

**Comment by satterly** [comment]
Can you paste the output of a POST to `http://ip.ip.ip.ip/api/webhooks/prometheus` ? You should get back something like this...
```
$ curl -XPOST https://alerta-api.herokuapp.com/webhooks/prometheus?api-key=demo-key
{
  "code": 400,
  "errors": null,
  "message": "no alerts in Prometheus notification payload",
  "status": "error"
}
```

**Comment by iDemonix** [comment]
Hi Satterly,

Here's a POST:

```
[root@prometheus ~]$curl -XPOST http://1.2.3.4/api/webhooks/prometheus?api-key=453pxVOPDVcq4K5stXM9Ss9rTXNvQx6Z0zgHz
{"code":400,"errors":null,"message":"no alerts in Prometheus notification payload","status":"error"}
```

This is correct as I didn't send a notification in my curl, but I have several alerts in AlertManager (I set a low threshold alert for testing which is constantly going off for different instances) and I'm not receiving anything in to Alerta?

Here's config from my `alertmanager.yml`:

```
receivers:
- name: "alerta"
  webhook_configs:
  - url: 'http://1.2.3.4/api/webhooks/prometheus?api-key=453pxVOPDVcq4K5stXM9Ss9rTXNvQx6Z0zgH'
    send_resolved: true
```

**Comment by satterly** [comment]
Are you still getting that error in the issue description? Or is that fixed?

**Comment by iDemonix** [comment]
I'm still receiving that output (Traceback) if I send a GET request. What would the expected output be of the following endpoint?

http://1.2.3.4/api/webhooks/prometheus?api-key=453pxVOPDVcq4K5stXM9Ss9rTXNvQx6Z0zgHz

If I change the API key to be incorrect I get the proper response about the key being wrong, but when they key is correct, I get the Traceback with the KeyError of 'prometheus'.

**Comment by iDemonix** [comment]
I've got this working now, I was being stupid and I hadn't send a default receiver in my AlertManager config! My apologies!

Before I close this, as it all seems to be working, should that Traceback happen at a GET of that endpoint, or is that a bug?

**Comment by satterly** [comment]
I would expect to get an error if I did a GET to this endpoint because it only accepts POST. I've modified this error for the next release to make it a bit more "user friendly". See https://github.com/alerta/alerta/pull/618

**Comment by iDemonix** [comment]
Thanks, very much appreciated!
