### ISSUE TITLE
get_history() does not show most recent history events

### ISSUE THREAD

**Issue by infernix** [alerta/alerta#637]
With a HISTORY_LIMIT of 100, a `get_history()` in alerta client returns results in ascending order. The problem is that this causes the most recent events to get cut off if there are more than 100, because in mongodb/base.py the sort filter is:
```
        pipeline = [
            {'$unwind': '$history'},
            {'$match': query.where},
            {'$project': fields},
            {'$limit': current_app.config['HISTORY_LIMIT']},
            {'$sort': {'history.updateTime': 1}}
        ]
```

So if there are more than 100 history events (let's say there's 150), only the oldest 100 are shown.

I suggest to order descending, e.g. `-1`, so as to avoid being unable to fetch the most recent events unless HISTORY_LIMIT is bigger than what is being queried for.

**Comment by satterly** [comment]
The use of `HISTORY_LIMIT` in this query is wrong. I've removed it and reversed the sort order as suggested. Thanks.
