### ISSUE TITLE
One user on multiple Customer Views Error

### ISSUE THREAD

**Issue by SteffenWG** [alerta/alerta#666]
Trying to create one user with multiple Customer Views.
The way I am trying to do it is:
- Assigning the same user twice in the customer's table with different customer name.

I'm getting av 500 INTERNAL SERVER ERROR.

Am I doing it wrong or is there a bug?

**Comment by SteffenWG** [comment]
Looking for clues and got this, I assume then that it is not meant for one user to view multiple customer views then:

duplicate key value violates unique constraint "customers_match_key"↵DETAIL:  Key (match)=(someUser@someEmail.com) already exists.

**Comment by satterly** [comment]
This is not possible at present. What happens with other auth strategies is that you can belong to multiple groups (gitlab, saml2) or organisations (github) or roles (keycloak) and then those groups/orgs/roles are used to lookup customers so a user can view multiple customers.

I assume you are using either BasicAuth or Google. If so then you only have two options for assigning customers.

1) assign a customer directly to an email address.
2) assign a customer based on the email domain

Let me know if you need any more help.
