### ISSUE TITLE
[Feature Request] Allow customisable or hide-able columns on the main dashboard

### ISSUE THREAD

**Issue by iDemonix** [alerta/alerta#706]
We use Prometheus/Alertmanager and an in-house written Icinga2 script that sends alerts to Alerta, we pass through different fields from both, but we don't make use of all the available columns on the front dashboard of alerta, which wastes a lot of visual space.

It'd be ideal if the view was more flexible, i.e. the ability to hide specific columns, all columns, or write a custom ordered list of fields. Could be a global setting to get a pull request in easily, then consideration could be given to allowing for different settings for multitenancies or users.

**Comment by satterly** [comment]
Duplicate of https://github.com/alerta/angular-alerta-webui/issues/142

Will be available as Release 6.1.1 shortly.
