### ISSUE TITLE
HTTP/S of Endpoint Overwritten by Server Config

### ISSUE THREAD

**Issue by danudell-trustnetworks** [alerta/alerta#715]
My UI deployment has the config.json of `{"endpoint":"https://my_server/alerta/api"}` 

This works, and when i go to the UI i can see it makes an initial request to `https://my_server/alerta/api/config` however that call overwrites the `endpoint` to be `http://my_server/alerta/api`

This leads to a "http called from https context" error and all subsequent requests fail. Not quite managed to track-down where/why the endpoint is getting overwritten by the server - hoping someone may be able to spot it.

**Comment by danudell-trustnetworks** [comment]
It'll take me a little while to test this out - I left BASE_URL relative as we have it behind a proxy and are using the docker containers - BASE_URL is used in `uswgi.ini` as the mount path which means it bombs out with the full address

Is there likely be other places that base_url is used like that?

**Comment by satterly** [comment]
Ah, ok. So the docker container needs to be fixed to just use the path if the BASE_URL is a fully qualified URL. Let me fix that and get back to you.

**Comment by danudell-trustnetworks** [comment]
Yeah - I think this part of the entrypoint.sh will also fail is the BASE_URL is fully qualified:

```
[DEFAULT]
endpoint = http://localhost:8080${BASE_URL}
key = ${API_KEY}
EOF
  else
    cat >${ALERTA_CONF_FILE} << EOF
[DEFAULT]
endpoint = http://localhost:8080${BASE_URL}
```

**Comment by satterly** [comment]
It gets it from the server. You set it locally and then the server overwrites it while loading in all the other config.

I could make it so that local config isn't overwritten if in an exclusion list. Something like this...
```
[profile local]
endpoint = http://localhost:8080/api
use_local = ['endpoint']
```
Thoughts?

**Comment by danudell-trustnetworks** [comment]
Yeah that could work - we use local for liveness/readiness hooks in the containers lifecycle - we don't want to have to embed client certs into the containers in order to just query locally.

So if we can override that that would be great. And we can use a another variable like MOUNT_PATH or something similar in the docker-entrypoint.sh and the containers uswgi.ini.

**Comment by danudell-trustnetworks** [comment]
Just a side note - if we do make the base_url relative then it sets the endpoint to http://PROXY_SERVER_NAME/alerta/api - even though its proxied on https - why the protocol change?

**Comment by satterly** [comment]
Ok. I'll merge the `use_local` option.

The protocol change is a curious one. I just did a quick google and found this flask issue ... https://github.com/pallets/flask/issues/773

**Comment by satterly** [comment]
Still need to fix docker container...

**Comment by satterly** [comment]
See https://stackoverflow.com/questions/23347387/x-forwarded-proto-and-flask
