### ISSUE TITLE
ERROR: 'normal'

### ISSUE THREAD

**Issue by jaylaprade** [alerta/alerta#716]
I followed this guide:
http://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html

and just can't seem to get by this one error when running the command line alerta:

 #server:~# $ /opt/alerta/bin/alerta send -r net01 -e down -s fatal -E Code -S Network -t 'net01 is down.'
ERROR: 'normal'

With debug on in the ~/.alerta.conf:

/opt/alerta/bin/alerta send -r net01 -e down -s fatal -E Code -S Network -t 'net01 is down.'
send: b'POST /api/alert HTTP/1.1\r\nHost: 10.101.20.223\r\nConnection: keep-alive\r\nUser-Agent: python-requests/2.20.0\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nContent-Type: application/json\r\nContent-Length: 333\r\n\r\n'
send: b'{"group": null, "value": null, "environment": "Code", "text": "net01 is down.", "origin": null, "tags": [], "service": ["Network"], "customer": null, "severity": "fatal", "createTime": "2018-10-19T17:07:41.174Z", "timeout": null, "attributes": {}, "resource": "net01", "correlate": [], "event": "down", "rawData": null, "type": null}'
reply: 'HTTP/1.1 500 INTERNAL SERVER ERROR\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: Vary header: Access-Control-Allow-Origin
body: {"code":500,"errors":null,"message":"'normal'","status":"error"}

ERROR: 'normal'

and the error in syslog:

MY_SERVER alertad: 2018-10-19 12:46:14,542 - flask.app[649]: ERROR - 'normal' [in /opt/alerta/lib/python3.5/site-packages/alerta/exceptions.py:78]#012Traceback (most recent call last):#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/utils/api.py", line 62, in process_alert#012    alert = alert.create()#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/models/alert.py", line 319, in create#012    current_severity=self.severity#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/models/alarms/alerta.py", line 104, in transition#012    if StateMachine.Severity[current_severity] == StateMachine.Severity['normal']:#012KeyError: 'normal'#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/views/alerts.py", line 47, in receive#012    alert = process_alert(incomingAlert)#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/utils/api.py", line 64, in process_alert#012    raise ApiError(str(e))#012alerta.exceptions.ApiError: 'normal'#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/opt/alerta/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/opt/alerta/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/opt/alerta/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function#012    resp = make_response(f(*args, **kwargs))#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/auth/decorators.py", line 103, in wrapped#012    return f(*args, **kwargs)#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/models/metrics.py", line 259, in wrapped#012    response = f(*args, **kwargs)#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/utils/response.py", line 19, in decorated#012    return func(*args, **kwargs)#012  File "/opt/alerta/lib/python3.5/site-packages/alerta/views/alerts.py", line 55, in receive#012    raise ApiError(str(e), 500)#012alerta.exceptions.ApiError: 'normal'
Oct 19 12:46:14 MY_SERVER alertad: [pid: 649|app: 0|req: 36/214] 10.101.20.223 () {42 vars in 520 bytes} [Fri Oct 19 12:46:14 2018] POST /api/alert => generated 65 bytes in 14 msecs (HTTP/1.1 500) 4 headers in 151 bytes (1 switches on core 0)

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

Any idea what I am missing?

**Comment by satterly** [comment]
It's not you. This is a bug introduced a few weeks ago. Sorry about that. I'm working on a fix and will let you know when it's sorted. Thanks for reporting the issue.
