### ISSUE TITLE
alerta will be automatically deleted

### ISSUE THREAD

**Issue by chgxtony** [alerta/alerta#729]
alerta will be automatically deleted. I want to forbid the schedule delete action. how to configure? 
Thank you

**Comment by satterly** [comment]
Alerts with a `timeout` of `0` will never be deleted. Is that what you want?

**Comment by chgxtony** [comment]
how to config timeout in restful api?

**Comment by satterly** [comment]
I just tried this using the `alerta` CLI and it seems to use the default timeout value if "0" is supplied. Is this what you have discovered?

**Comment by chgxtony** [comment]
I found `timeout` can not work. I set the timeout = 0, but still be deleted

**Comment by satterly** [comment]
I haven't released the latest version that contains the fix yet. Are you using Docker?
