### ISSUE TITLE
I found timeout can not work. I set the timeout = 0, but still be deleted

### ISSUE THREAD

**Issue by chgxtony** [alerta/alerta#734]
sorry, the last issue had been closed. 
I found `timeout` can not work. I set the `timeout` = 0, but still be deleted

**Comment by satterly** [comment]
The way github works is if you put "Fixes #Issue" in the description of a PR then it auto-closes the issue when you merge the PR. Understandably this can cause confusion if actually making the fix available to end-users (like uploading the python package to PyPI or building a Docker image) has still yet to be done.

So, yes, the issue should be fixed but as I haven't actually released a new version of Alerta yet you would need to run the "master" branch by downloading from github directly.

I'll make the new release available as soon as possible but I was going to review other fixes and enhancements for inclusion in the new release first.

**Comment by chgxtony** [comment]
thank you , I know the reason that still be deleted. there is a celery task `housekeeping`.  `DELETE FROM alerts WHERE (status IN ('closed', 'expired')......`, when the alert is set to be closed, it will be de
deleted . Thank you for your explanation

**Comment by satterly** [comment]
👍
