### ISSUE TITLE
can not login with gitlab as the OAuth2 provider for Alerta

### ISSUE THREAD

**Issue by sashasokolova** [alerta/alerta#736]
I use nginx/uwgsi configuration. We use LDAP auth on gitlab.
there is alertad.conf
DEBUG = True
AUTH_REQUIRED = True
SECRET_KEY = 'key'
BASE_URL = '/api'

AUTH_PROVIDER = 'gitlab'
GITLAB_URL = 'https://gitlab.example'
OAUTH2_CLIENT_ID = 'ID_FROM_GITLAB'
OAUTH2_CLIENT_SECRET = 'SECRET_FROM_GITLAB'
ALLOWED_GITLAB_GROUPS = ['*']

When I try to login it opens a new window I am able to login into gitlab. I don't get any errors. It just keeps asking to login into alerta. In Gitlab user section I can see: "Anonymous:  Authorization was granted by entering your username and password in the application"
If I try to login again(and I haven't logged out from gitlab)I get this error in gitlab: "The requested scope is invalid, unknown, or malformed."
Did i miss something in configuration?

**Comment by satterly** [comment]
LDAP or OAuth?

**Comment by sashasokolova** [comment]
LDAP auth - it what we use on our gitlab
For alerta i am trying OAuth with gitlab

**Comment by sashasokolova** [comment]
Forgot to tell i use alerta for Prometheus. If it helps

**Comment by satterly** [comment]
It's not made clear in the online docs but you need to assign the `openid` scope to the application. Click on the "Edit" button for the application in Gitlab user settings and you should see the below...

<img width="458" alt="screenshot 2018-10-31 at 16 27 41" src="https://user-images.githubusercontent.com/615057/47799105-e890c700-dd29-11e8-8b0c-e4a7d6024572.png">

Save the change and you should be able to login. Let me know if that works.

**Comment by sashasokolova** [comment]
Thank you so much. That it. i used api and read_user.
