### ISSUE TITLE
Add LDAP authentification

### ISSUE THREAD

**Issue by rpelissi** [alerta/alerta#737]
Hi!
You solution is almost perfect! But it could be even more cool to have an ldap authentification backend since all the tools we use already use LDAP as the authentification backend.
Is it possible to have it in a future version?

Thanks.

**Comment by satterly** [comment]
Alerta already supports LDAP authentication! What was lacking was the documentation. 😉 I've addressed that now. See http://docs.alerta.io/en/latest/authentication.html#basic-auth-using-ldap

Feedback on the docs welcome. Let me know if you need any more information.

**Comment by rpelissi** [comment]
Thanks!
So impatient to test that :)
