### ISSUE TITLE
Customer based routing plugins' configuration

### ISSUE THREAD

**Issue by skbly7** [alerta/alerta#746]
**Is your feature request related to a problem? Please describe.**
Currently all the plugins in Alerta run with same configuration. Due to which different customers having same routing plugin but different configuration can't be boarded. An example might be:

1. If `customer=='A'` route to slack with API key `123456` on slack channel `#alerts`
2. If `customer=='B'` route to slack with API key `789012` on slack channel `#infra-alerts`

(minor discussion on the same can be found in Gitter [here](https://gitter.im/alerta/chat?at=5be940ad4e7ca14520920647))

**Describe the solution you'd like**
The routing should be based on alerts (which already happen in Alerta) but at the same time, plugins can dynamically change their configuration. For ex: if the `alert.owner` is `customerA` then plugin should be running with tokens and other configurations defined for `customerA` and so on. (default config for configs not provided/overridden)

I am willing to know views/alternative solution design, but my initial thoughts are as follows which I believe to be backward compactible (taking `opsgenie` plugin as example):

1. `settings.py`
```
OPSGENIE_SERVICE_KEY = 'abcdefghijkl'
SERVICE_KEY_MATCHERS = []
CUSTOMER_CONFIG_OVERRIDES = {
    'customerA': {
        'opsgenie': {
            'OPSGENIE_SERVICE_KEY': '1234567890'
        }
    },
}
```

2. `alerta_opsgenie.py`

Currently, variables are defined as module globals and used in class directly (`OPSGENIE_SERVICE_KEY`, etc). This can be updated in plugins to `self.get_config('OPSGENIE_SERVICE_KEY', alert.owner)`, while `PluginBase` can have `get_config` function which return default or overridden config based on `alert.owner` value.

**Describe alternatives you've considered**
One alternative can be initializing plugins multiple times i.e. one for all customers in `utils/plugin.py` and directly use that instance based on `alert.owner` or default if `alert.owner is None`.

**Comment by satterly** [comment]
Ok. Thanks for the write up. It's important to get real use cases for these sorts of issues. I'll need to take time to consider this, or alternative, approaches. I'll let you know either way in the next few weeks.

**Comment by geekhead** [comment]
This is a pretty significant feature lacking that prohibits a lot of companies with multiple TechOps teams and multiple alerting sources from adopting Alerta. The ability for Alerta to be one source that all other alerting sources (alertmanager, grafana, netdata, etc) can use to aggregate alerts to before being shipped out to PagerDuty, HipChat, etc is a big win. However, not having the ability for multiple teams/customers to define their own PagerDuty Service key, or HipChat/Slack chat API, etc is a huge miss and defeats the whole purpose of having multitenancy and aggregating alerts from different teams and services in the first place. Most companies have multiple PagerDuty on-call rotation groups and services they own. Sure, seeing all alerts in one place is nice but no one is going to be watching the UI at 2am in the morning and is relying on their multiple PagerDuty service setups to notify the appropriate team that owns a service of an issue.

Will there be any more attention given to this missing feature or is the statement that every single alert that comes into Alerta will need to go to only one PagerDuty service defined or HipChat/Slack room?

**Comment by satterly** [comment]
@geekhead Thanks for your feedback. I've taken onboard your feedback and the other feedback above and have the following proposed enhancement...

1. server configuration can now include plugin configuration organised in any way that suits the user
2. configuration is passed to a "routing rule" and can be used to lookup required config on a "per-alert" basis. eg. can lookup API keys for external notification using alert customer
3. configuration can then be optionally passed from a "routing rule" to all plugins as they are invoked

**Example Server Configuration**
```
PD_API_KEYS = {
    'Tyrell Corporation': 'tc-key',
    'Cyberdyne Systems': 'cs-key',
    'Weyland-Yutani': 'wy-key',
    'Zorin Enterprises': 'ze-key'
}
SLACK_API_KEYS = {
    'Soylent Corporation': 'sc-key',
    'Omni Consumer Products': 'ocp-key',
    # 'Dolmansaxlil Shoe Corporation': 'dsc-key'  # use default key
}
API_KEY = 'default-key'
```
**Example Routing Rule**
```
def rules(alert, plugins, **kwargs):

    TIER_ONE_CUSTOMERS = [
        'Tyrell Corporation',
        'Cyberdyne Systems',
        'Weyland-Yutani',
        'Zorin Enterprises'
    ]

    TIER_TWO_CUSTOMERS = [
        'Soylent Corporation',
        'Omni Consumer Products',
        'Dolmansaxlil Shoe Corporation'
    ]

    config = kwargs['config']
    if alert.customer in TIER_ONE_CUSTOMERS:
        # Tier 1 customer SLA needs PagerDuty to manage escalation
        return [
            plugins['remote_ip'],
            plugins['reject'],
            plugins['blackout'],
            plugins['pagerduty']
        ], dict(PAGERDUTY_SERVICE_KEY=config['PD_API_KEYS'][alert.customer])

    elif alert.customer in TIER_TWO_CUSTOMERS:
        # Tier 2 customers handled via Slack
        return [
            plugins['remote_ip'],
            plugins['reject'],
            plugins['blackout'],
            plugins['slack']
        ], dict(SLACK_API_TOKEN=config['SLACK_API_KEYS'][alert.customer])

    else:
        # Tier 3 customers get "best effort"
        return [
            plugins['remote_ip'],
            plugins['reject'],
            plugins['blackout']
        ]
```

**Example Slack Plugin ()**
```
class TriggerEvent(PluginBase):

    def pre_receive(self, alert, **kwargs):
        return alert

    def post_receive(self, alert, **kwargs):
        config = kwargs['config']
        PAGERDUTY_SERVICE_KEY = config['PAGERDUTY_SERVICE_KEY']

        payload = {
            "service_key": PAGERDUTY_SERVICE_KEY,
            "incident_key": alert.id,
            "event_type": event_type,
            "description": message,
            "client": "alerta",
            "client_url": '%s/#/alert/%s' % (DASHBOARD_URL, alert.id),
            "details": alert.get_body(history=False)
        }
...
```

Comments and feedback on the above and/or PR #944 welcome.

**Comment by satterly** [comment]
@skbly7 @Anderen2 @geekhead I'll merge this by the end of the day unless I hear otherwise. Thanks.

**Comment by geekhead** [comment]
Hey @satterly, what would this look like if we wanted to filter based on a specific alert attribute or a custom key/value pair that we are sending? For example, if we are sending the key:value pairs:
service:mysql
service:dbproxy
service:globaldb

And we wanted to route alerts to the database teams pagerduty service if any alerts matched these three alert attributes, would that be possible with your changes?

Also, I'm assuming we'd be able to override Hipchat/Slack room ID's as well? Thanks

**Comment by satterly** [comment]
Is this what you want?
```
PAGERDUTY_LOOKUP = {
    'devops': 'random-key-1',
    'dba': 'random-key-2'
}

if bool(set(alert.service) & set('mysql', 'dbproxy', 'globaldb')):
    TEAM = 'dba'
else:
    TEAM = 'devops'

return ['reject', 'pagerduty'], dict(PAGERDUTY_API_KEY=PAGERDUTY_LOOKUP[TEAM])
```
And yes, it's just python code, so you can do whatever you want.

However, note that none of the contributed plugins have been rewritten to take advantage of this yet.

**Comment by geekhead** [comment]
Yup, that would be perfect and meet our needs. Thanks!
