### ISSUE TITLE
Allowing lookup to refer multiple customers

### ISSUE THREAD

**Issue by skbly7** [alerta/alerta#748]
**Is your feature request related to a problem? Please describe.**
I have a scenario in which `user` need to be linked to multiple `customer` based on same lookup value.

Example mapping (lookup -> customers):
1. `groupAB`: `["customerABC", "customerXYZ"]`
2. `groupA`: `["customerABC"]`
3. `groupB`: `["customerXYZ"]`

**Describe the solution you'd like**
One user can be part of multiple customers after #499, but one look up can fetch one customer only. Hence, above scenario can't work directly.

I am uncertain why `unique index` is present on `customer.lookup`. But getting rid of this index above scenario is possible. The changes needed were (tested with mongodb only right now):

1. Replacing `find_one` -> `find` [here](https://github.com/alerta/alerta/blob/master/alerta/database/backends/mongodb/base.py#L1254)
2. Remove `unique` constraint on `customer.match` [here](https://github.com/alerta/alerta/blob/master/alerta/database/backends/mongodb/base.py#L41)

If the feature and solution looks good shall I raise a PR for the same?

**Comment by satterly** [comment]
Yes, I think this should work. We need to make sure we write a few tests to cover the different scenarios but I can help with that if needed. Go for it! Thanks.

**Comment by satterly** [comment]
Looking at this again, the way I see it working is you define a lookup multiple times in order to assign more than one customer. Is that what you are suggesting?

That is, using your example above, it would actually be represented as follows  ...
```
+---------+-------------+
| Lookup  |   Customer  |
+---------+-------------+
| groupAB | customerABC |
| groupAB | customerXYZ |
| groupA  | customerABC |
| groupB  | customerXYZ |
+---------+-------------+
```

Then, when a user in group `groupAB` signs in they get assigned customers `customerABC` and `customerXYZ`. Is that right?

**Comment by skbly7** [comment]
Yes, the above is right. 😃
