### ISSUE TITLE
Adding support for LDAP groups in LDAP authentication

### ISSUE THREAD

**Issue by skbly7** [alerta/alerta#749]
**Is your feature request related to a problem? Please describe.**
The universal method for getting groups a member is part of is done via LDAP. Right now, Alerta's LDAP authentication don't fetch those groups. These groups can be useful to automatically assign users as different customer.

**Describe the solution you'd like**
Appending groups a user is part of in [LDAP authentication](https://github.com/alerta/alerta/blob/master/alerta/auth/basic_ldap.py#L55).

This change might need adding a new settings variable `LDAP_GROUP_FILTER` or refactoring of `LDAP_DOMAINS` variable. Example group filter is `(&(memberUid=%s)(objectClass=group))`.

The final code will look something like this:

```
    groups = [user.domain]
    groups_filter = current_app.config['LDAP_DOMAINS_GROUP'][domain] % username
    resultID = ldap_connection.search(basedn, ldap.SCOPE_SUBTREE, groups_filter)
    resultTypes, results = ldap_connection.result(resultID)
    for result in results:
        groups.append(user.domain + ':' + result[1]['cn'][0].decode("utf-8"))

    customers = get_customers(user.email, groups=groups)
```
NOTE: To not break multi-tenancy `user.domain:` has been appended to group names. This is due to the fact that different clients/domains can have repetitive group names.

If the feature and solution looks good shall I raise a PR for the same?

**Comment by satterly** [comment]
Sounds great, thanks. Not sure I follow exactly why you need to add the `user.domain` to the LDAP group name but we can discuss that in more detail when you have a working PR. Thanks again.

**Comment by satterly** [comment]
@Anderen2 Any chance you could review and/or test this? Thanks.
