### ISSUE TITLE
Problems with Keycloak server without role mapping

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#754]
**Describe the bug**
Using Keycloak as AUTH_PROVIDER but just for authentication (no roles management) is not possible. The Keycloak server I have to use at work does not give a list of roles - so I got an error at keycloak.py line 43.
Furthermore when the Keycloak server redirects to Alerta the error message is shown within a message box. This does also happen when no customer mapping is existing. Really hard to read for an unexperienced user.

**To Reproduce**
Use a keycloak server without role mapping.

**Expected behavior**
Not existing role mapping should be handled like empty list. Additionally should it be possible to set roles for Keycloak users.

**Comment by satterly** [comment]
Three things...
1) this should not just throw an error -> this can be fixed
2) the error should be more obvious -> this can also be fixed
3) no ability to set roles for Keycloak users -> this is as designed

Further to point 3, the way most of the auth providers work is that the user management is undertaken by that system. ie. assignment to roles, groups or organisations. Where this hasn't been possible in the past those auth providers have been removed (eg. Twitter OAuth).

Requiring Alerta to manage users but offloading the auth to different providers is going to cause confusion and make the auth logic (even more) complex so I would be against adding this feature.

Instead, I would find out if your Keycloak server could be extended to add support for roles.

**Comment by escoand** [comment]
OK, thanks for point 1 and 2. But for point 3. I think there will be no chance that the server will provide any role mapping. My departement is just a small group and the keycloak organizes tens of thousands of users.

I can see in the keycloak web ui that my account has full access to every client but no role at all. So this is obviously by design.

**Comment by satterly** [comment]
You should still be able to use `admin` and `user` roles. Would that be enough?

**Comment by escoand** [comment]
Maybe but I wanted to split into write and read-only users.

**Comment by satterly** [comment]
Are you able to test this PR #755 ?

**Comment by escoand** [comment]
Yes off course, but earliest next Monday.

**Comment by satterly** [comment]
After considering this I have decided that it's not appropriate to modify the Keycloak auth integration to include support for customising roles for several reasons...

1/ it would cause confusion about where the responsibility for role assignment lay
2/ it would make Keycloak inconsistent with every other oauth provider
3/ it would require significant (and potentially confusing and bug ridden) changes to both the web UI and `alerta` CLI
4/ ongoing support for this special case would be an additional burden on limited resources that would take away from new features
5/ there is already a solution for this, namely to use keycloak roles
6/ there is already a work-around, namely to use basic auth instead

Apologies if this isn't the answer you were hoping for but I need to balance the needs of individuals with those of the wider project. Let me know what you think.

**Comment by escoand** [comment]
I understand your decision but this was not my desired answer. ;-)
The keycloak server admins have some descriptions how to use a proxy infront of it.
So I have to fight with this implementation as well, maybe...
Anyway, thanks.
