### ISSUE TITLE
Custom Run Book URL

### ISSUE THREAD

**Issue by mridude23** [alerta/alerta#778]
Hi,
I'm running Alerta on a docker and it's hooked up with webhooks to a Grafana instance. Is it possible to change the Run Book URL which I can see when clicking on a firing alert? Also can this be made clickable? Can seem to find any info on this issue. Also can we customize the links we see when clicking on the alert? (something like External URL)

![image](https://user-images.githubusercontent.com/35563212/49938005-2ebc7700-fee1-11e8-92bd-094a384e0951.png)

On a Prometheus instance that is hooked to Alerta I can see another External URL for example.

**Comment by satterly** [comment]
There's some info on the docs website about how to make links clickable [here](https://docs.alerta.io/en/latest/integrations.html#bi-directional).
