### ISSUE TITLE
Alerta Monitoring keep flapping alerts from some network devices 

### ISSUE THREAD

**Issue by talenmhm** [alerta/alerta#779]
Hi Alerta Team,

I have an Alerta system to monitor IEC Sessions for a Scada Master system.
However, Alerta was showing a false alarm for multiple sessions for period around 5 hours.
I checked the logs in Alerta and Syslog servers to check the IEC session status and the logs was correct.
But Alerta still gaving the false alarm.

Please advise

**Comment by satterly** [comment]
Are you forwarding the Scada alarms to Alerta using Syslog? If so, sometimes syslog can drop messages if it is configured to use UDP.

The standard recommendation is to resend alerts at regular intervals to lessen the impact of dropped alerts.

>Alerts are cheap
Alerts should be resent at regular intervals if they are still active which means that if all data is lost after a certain amount of time (eg. 2 hours?) you are back to where you were. This will be generally true though, for some alert sources this isn’t possible eg. SNMP traps, log errors. Alerts in a normal state can be resent at a longer interval.

See https://docs.alerta.io/en/latest/design.html#alerts-are-cheap

**Comment by satterly** [comment]
Closing this for now. Let me know if you need more info. Thanks.
