### ISSUE TITLE
Making log formatter configurable

### ISSUE THREAD

**Issue by skbly7** [alerta/alerta#780]
**Is your feature request related to a problem? Please describe.**
The logs from application aren't that digestible by ELK when pushed via filebeat, etc.

**Describe the solution you'd like**
Allow the logging in JSON and in face leave it configurable so users can select log formatter not just the log format.

**Describe alternatives you've considered**
Parser at filebeat/logstash level which understand every column and mark accordingly. But this don't seem to be permanent/good solution.

**Comment by skbly7** [comment]
Although one of possible way is by above closed branch, but it will need `settings.py` edit. Hence, discarding it.

Do you think having a flag like `LOGGING_TYPE` which can have one of value `[Normal, JSON, etc...]` good to add in Alerta or any other suggestion to get logs in json?

**Comment by satterly** [comment]
Do you want every request? Or do you just want to know when things have changed? If you're only interested in changed then the audit log should work for you. You can log in JSON or have the message POSTed to a URL using audit logging.

**Comment by skbly7** [comment]
I wanted to log all the loggers, especially what `logstash` plugin do. 

Exact flow in mind:
Given alerta logs are getting printed on console (as I am running it via docker-alerta method, I was doing filebeat to ES. This way seemed much more reliable to me than sending each alert over network to logstash (+1 tcp connection) and then to ES.

**Comment by satterly** [comment]
Using [`dictConfig`](https://docs.python.org/3/library/logging.config.html#logging-config-api) available in the standing `logging` library seems to be the recommended approach these days. This should make it configurable enough to easily define additional loggers of which a JSON logger could be one.

Do you want to try give this a go or should I put it on the backlog?

**Comment by satterly** [comment]
See https://www.techatbloomberg.com/blog/guide-logging-python/

**Comment by satterly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JSON logging](https://trello.com/c/HdU9Js4c/527-json-logging)
