### ISSUE TITLE
Possible vulnerability: anonymous user can obtain all keys via API

### ISSUE THREAD

**Issue by ossjet** [alerta/alerta#784]
**Describe the bug**
An unauthorized user can obtain all API keys via API. (alerta 5 and 6)

**To Reproduce**

Using alerta-cli:
1. Set up the config like this:
```
$ cat .alerta.conf
[DEFAULT]
timezone = Europe/Moscow
profile = production

[profile production]
endpoint = https://url.to-our.alerta
```
2. Type `alerta keys` in a terminal
3. All API keys will be shown

Using curl:

1. Type in a terminal: `curl https://url.to-our.alerta/keys`
2. Then JSON with all keys will be shown.

**Expected behavior**
API supposed to return an error like "Authorization failed, no key provided" or something.

---

Any ideas? Maybe I missed something?

**Comment by n0guest** [comment]
> Please share your server configuration alertad.conf file. Do you have AUTH_REQUIRED=True set?

As I wrote in gitter chat, we've tested both 5.x and 6.x. For now we can't enable AUTH_REQUIRED on our 5.2.x installation. But we tried enabling auth_required with "basic auth" on 6.x - this bug is still reproducible. Here is our conf from 6.x:

```
$ grep -vE '^#' /etc/alertad.conf
SECRET_KEY='DELETED'

DEBUG = True
BASE_URL = 'https://sub.somedomain.tld'
CORS_ORIGINS = [ 'https://sub.somedomain.tld' ]

LOGGER_NAME = 'alerta'
DATABASE_URL = 'mongodb://DELETED:DELETED@mongors1,mongors2,mongors3/DELETED?replicaSet=DELETED'
DATABASE_NAME='DELETED'

DEFAULT_PAGE_SIZE = 500
HISTORY_LIMIT = 100

ADMIN_USERS = ['username@somedomain.tld']
CUSTOMER_VIEWS = False
ALLOWED_EMAIL_DOMAINS = ['somedomain.tld']
TOKEN_EXPIRE_DAYS = 14
API_KEY_EXPIRE_DAYS = 3650

SIGNUP_ENABLED = True
AUTH_REQUIRED = True
AUTH_PROVIDER = 'basic'
OAUTH2_CLIENT_ID = 'DELETED'
OAUTH2_CLIENT_SECRET = 'DELETED'

USER_DEFAULT_SCOPES = [ 'read:alerts', 'read:blackouts' ]

AUTO_REFRESH_ALLOW = 'ON'
SENDER_API_ALLOW = 'ON'

BLACKOUT_DURATION = 3600

EMAIL_VERIFICATION = True
SMTP_STARTTLS = False
SMTP_HOST = 'relay'
SMTP_PORT = 25
MAIL_FROM = 'username@somedomain.tld'

PLUGINS = [ ]
PAGERDUTY_SERVICE_KEY = ''  # default="not set"
SERVICE_KEY_MATCHERS = []  # default="not set"
DASHBOARD_URL = 'https://sub.somedomain.tld'

SEVERITY_MAP = {
    'security': 0,
    'critical': 1,
    'major': 2,
    'minor': 3,
    'warning': 4,
    'indeterminate': 5,
    'cleared': 5,
    'normal': 5,
    'ok': 5,
    'informational': 6,
    'debug': 7,
    'trace': 8,
    'unknown': 9
}
DEFAULT_SEVERITY = 'indeterminate'
```

Are we missing something? Or it's a real bug?

**Comment by satterly** [comment]
Thanks, any help with the documentation would be appreciated. 👍

**Comment by ossjet** [comment]
> @ossjet, please, close this issue.
Okay
