### ISSUE TITLE
Keycloak TypeError: must be str, not list

### ISSUE THREAD

**Issue by judexzhu** [alerta/alerta#785]
**Describe the bug**
Can not use keycloak as the authentication. show Error:

```
File \"/venv/lib/python3.6/site-packages/alerta/auth/utils.py\", line 53, in create_token\n    scopes = Permission.lookup(login, groups=(roles or []) + (groups or []) + (orgs or []))\nTypeError: must be str, not list\n
```

**To Reproduce**
1. Use helm chart to install alerta in Kubernetes
2. change the alertaConfig as:
```
alertaConfig:
  AUTH_PROVIDER: "'keycloak'"
  KEYCLOAK_URL: "'https://keycloak.xxxxxxxx.com'"
  KEYCLOAK_REALM: "'Login'"
  OAUTH2_CLIENT_ID: "'alerta-ui'"
  OAUTH2_CLIENT_SECRET: "'86501715-2591-4b8c-b756-axxxxxx97c7f'"
  ALLOWED_KEYCLOAK_ROLES: "'*'"
```
3.docker image: alerta/alerta-web:6.5.0
4.helm install
5. See error

```
{  
   "data":{  
      "code":500,
      "errors":[  
         "Traceback (most recent call last):\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/venv/lib/python3.6/site-packages/flask_cors/decorator.py\", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File \"/venv/lib/python3.6/site-packages/alerta/auth/keycloak.py\", line 56, in keycloak\n    customers=customers, roles=roles)\n  File \"/venv/lib/python3.6/site-packages/alerta/auth/utils.py\", line 53, in create_token\n    scopes = Permission.lookup(login, groups=(roles or []) + (groups or []) + (orgs or []))\nTypeError: must be str, not list\n"
      ],
      "message":"must be str, not list",
      "status":"error"
   },
   "status":500,
   "config":{  
      "method":"POST",
      "transformRequest":[  
         null
      ],
      "transformResponse":[  
         null
      ],
      "withCredentials":false,
      "url":"/api/auth/keycloak",
      "data":{  
         "code":"eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..AeO6NpFB00ZLvmjdB_103Q.uKX1g3w_xE56u33LKi-rrTjRdAyeHlF2IrLMYwAGkox0alYCaZYIHjrioTGcW0gLibWDHqoIRJBMVBRq3mrTj1KD31sH9v_ogVeQJV9uKLXt14aA3vqA4Gr3nX9HUCfC_96fjCZzuJMSMjMNxGuXTIGAbeQjKBVCMYbD06p-ngh1eVsHQXOWgT3cJZqeGPgUCPICGSHmMX1LYVDwPJKWomrMLFlnH3xaNXKdL-LSHHM7nzjE7YNLIRbhijGWXuZ6.t-V2LPZqczuxfUaADoU2Eg",
         "clientId":"alerta-ui",
         "redirectUri":"https://alerta.xxxxxxxx.com"
      },
      "headers":{  
         "Accept":"application/json, text/plain, */*",
         "Content-Type":"application/json;charset=utf-8"
      }
   },
   "statusText":"INTERNAL SERVER ERROR"
}
```

**Expected behavior**
should be able to login

**Screenshots**

![image](https://user-images.githubusercontent.com/17834225/50070270-59237280-0208-11e9-8ce8-762deef22f48.png)

**Additional context**
I already created two roles in the keycloak

![image](https://user-images.githubusercontent.com/17834225/50070356-94be3c80-0208-11e9-80a0-a912acfc106a.png)

I also create two roles "admin" and "user" under the client：

![image](https://user-images.githubusercontent.com/17834225/50070401-bae3dc80-0208-11e9-9649-a53cd4ee352c.png)

Set the token mappers as document described：

![image](https://user-images.githubusercontent.com/17834225/50070428-dcdd5f00-0208-11e9-96f0-189006862f94.png)

also try the 6.0.0 images, same Error

also tried to composite roles

![image](https://user-images.githubusercontent.com/17834225/50070793-6e010580-020a-11e9-999b-ba6e4379aa87.png)

add one user in roles and use this account to login 

![image](https://user-images.githubusercontent.com/17834225/50070832-9b4db380-020a-11e9-9f8a-2ea8e7ebf3b3.png)

![image](https://user-images.githubusercontent.com/17834225/50070887-ccc67f00-020a-11e9-894c-d13443769281.png)

Same error

![image](https://user-images.githubusercontent.com/17834225/50070907-dfd94f00-020a-11e9-8787-ec435eb86b8d.png)

**Comment by satterly** [comment]
The documentation has been updated to mention that `Multivalued` needs to set `ON` for "role memberships". See https://github.com/alerta/alerta-docs/pull/89
