### ISSUE TITLE
Google+ API being sunset by March 2019 ()

### ISSUE THREAD

**Issue by madankumarj** [alerta/alerta#786]
**Describe the bug**
Google is expediting the process of sunsetting the Google+ APIs and targeted to sunset on March 7 2019, Alerta is currently using Google+ APIs to authenticate using google Id. Need to document a diferent way to use Google ID before google sunnsets the APIs 

**To Reproduce**
https://www.blog.google/technology/safety-security/expediting-changes-google-plus/

**Additional context**
https://www.blog.google/technology/safety-security/expediting-changes-google-plus/

**Comment by satterly** [comment]
From https://developers.google.com/+/api-shutdown
> The Google+ Sign-in feature has been fully deprecated and will also be shut down on March 7, 2019. Developers should migrate to the more comprehensive [Google Sign-in](https://developers.google.com/identity/) authentication system.

**Comment by madankumarj** [comment]
Documentation still speak about Google+
http://docs.alerta.io/en/latest/authentication.html#google-oauth2

**Comment by satterly** [comment]
Fixed https://github.com/alerta/alerta-docs/pull/88
