### ISSUE TITLE
[question] Alerta not picking up the latest alert

### ISSUE THREAD

**Issue by Orjanp** [alerta/alerta#822]
I have an alert that is not shown with correct severity. For some reason the newest alert is not the one displayed as "Last Received Alert ID". The "Last Receive Time" however is correct. Have tried wiping the postgres database, but that didn't help. In Prometheus and Alert Manager, everything looks right. And the alert is sent to and displayed in Alerta. It's just not picking out the latest one.

Have you seen this kind of behavior before? I suspects it's on our end since I haven't been able to find anyone with the same problem, but was hoping you maybe had seen it during testing or something. How does Alerta decide which alert is the latest?

We are running Alerta 6.6.1. with a Postgres 10.5 database. Alerts are provided by Prometheus 2.4.3.

![alerta_issue](https://user-images.githubusercontent.com/489760/51172444-8b7dc980-18b3-11e9-8e90-bc8e6777a3d0.png)

The rule that creates the alarm looks like this:

``` perl
# vim: set filetype=perl:
groups:
- name: Device_last_seen_status
  rules:
  - alert: Last_Seen_Fault
    expr: rate(last_seen[2m]) == 0
    for: 1m
    labels:
      severity: critical
      correlate: Last_Seen_OK
      instance: "{{ $labels.service }}-{{ $labels.system_device }}"
    annotations:
      value: "{{ $value }}"
      device: "{{ $labels.system_device }}"
      system: "{{ $labels.service }}"
      summary: "Device: {{ $labels.system_device }} on {{ $labels.service }} has not been seen in a while"
      description: "Device: {{ $labels.system_device }} on {{ $labels.service }} was not seen in the 2 minute time frame."
  - alert: Last_Seen_OK
    expr: rate(last_seen[2m]) > 0
    for: 1m
    labels:
      severity: normal
      correlate: Last_Seen_Fault
      instance: "{{ $labels.service }}-{{ $labels.system_device }}"
    annotations:
      value: "{{ $value }}"
      device: "{{ $labels.system_device }}"
      system: "{{ $labels.service }}"
      summary: "Device: {{ $labels.system_device }} on {{ $labels.service }} was recently seen"
      description: "Device: {{ $labels.system_device }} on {{ $labels.service }} was seen in the 2 minute time frame."
```

**Comment by satterly** [comment]
No I haven't seen this specifically but there could be many different reasons why a particular alert doesn't get processed. Try disabling all plugins and see if that makes a difference. ie. set `PLUGINS=[]` and I'll see if I can reproduce the issue.

**Comment by Orjanp** [comment]
Not sure what fixed it, but I upgraded Prometheus and Alert Manager to latest version, and removed all but one plugin. This seems like it fixed it. I will at a later stage try to backtrack to see if I can find what caused the problem so that I don't run into it again. Thanks for help.
