### ISSUE TITLE
GitLab auth and group association

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#828]
An issue with Gitlab authentication and group assiciation just came to my attention. It worked in a past release but must have changed. Unfortunately I can't tell when it worked last as my clients only reported that a couple of days ago. Now we're running Alerta 6.7.1

The problem is that our users are member of the following GitLab groups:

```
ansible-inventories/hosts/company1
ansible-inventories/hosts/company2
company3
```

In the past it worked that Alerta recognized the membershhip for all 3 companies in Alerta but that doesn't work anymore. It only recognizes company3.

Our customer lookup rules in Alerta are just using the company names but not the namespaces as seen for company1 and company2 above. So, either GitLab has changed and now reports the fully qualified name with their namespace or Alerta has changed the interpretation of the names.

**Comment by jurgenhaas** [comment]
I have tried adding additional customer lookups in Alerta but that doesn't solve the problem, unfortunately.

**Comment by jurgenhaas** [comment]
What's interesting, if a user is member of company3 (i.e. without namespace) and to a couple of groups with the namespace, they can login and see all the customers they are member of. But in order to login they have to be meber of a group without a namespace, otherwise they get declined.

**Comment by jurgenhaas** [comment]
They are subgroups.

**Comment by satterly** [comment]
If you're sure this used to work then something might have changed here https://github.com/alerta/alerta/pull/808

**Comment by jurgenhaas** [comment]
Yes I'm sure it used to work as our authentication scheme has been based on this right from the beginning.

**Comment by jurgenhaas** [comment]
Well, that user is member of groups without a namespace. The login problem persists when in the above example the user were only member of `team-alerta/core` and maybe a couple more namespaced groups.

**Comment by satterly** [comment]
I see. I'll take another look. Thanks.

**Comment by satterly** [comment]
Are you using "api" scope or "openid" scope on the GitLab application setting? 

<img width="479" alt="screenshot 2019-01-29 at 10 21 33" src="https://user-images.githubusercontent.com/615057/51897723-acfcac00-23af-11e9-8def-4d6329a51fe7.png">

**Comment by jurgenhaas** [comment]
I'm using both, API and OpenID for the Alerta application in GitLab. But I see you have committed a fix in the meantime, so you seem to have found something that fixes it. Great, thanks. I'll give it a try when the next release is available.

**Comment by satterly** [comment]
OK. I'll merge and close this issue. Once you've tested the new release please confirm if it works. Thanks.
