### ISSUE TITLE
Customer blackouts not supported without customer view

### ISSUE THREAD

**Issue by tjongerius** [alerta/alerta#873]
**Describe the bug**
When customer view is disabled, customer blackouts cause entire environment to be blacked out.

**To Reproduce**
1. Enable customer view
2. Schedule blackout for specific customer in specific environment
3. See result.

**Expected behavior**
Only blackout customer specified.

**Comment by satterly** [comment]
What version of Alerta is this? And is the backend Postgres or MongoDB?

**Comment by satterly** [comment]
And just to clarify, are you enabling customer view, creating a blackout, and then disabling customer view and seeing that the blackout created when customer views was enabled now suppresses all alerts with that environment, with or without the previously defined customer?

**Comment by tjongerius** [comment]
@satterly the full reproduction including config output might help:
alerta@2650a14871af:/app$ alerta config
actions             :
alarm_model         : {'name': 'Alerta 6.7.3'}
audio               : {'new': None}
auth_required       : True
client_id           : None
colors              : {'highlight': 'black', 'severity': {'minor': 'lightblue', 'warning': 'yellow'}}
columns             : severity, status, createTime, lastReceiveTime, customer, service, resource, event, value, text
customer_views      : False
dates               : {'longDate': 'd/M/yyyy h:mm:ss.sss a', 'mediumDate': 'EEE d MMM HH:mm', 'shortTime': 'HH:mm'}
email_verification  : False
endpoint            : http://localhost:8080/api
github_url          : https://github.com
gitlab_url          : https://gitlab.com
keycloak_realm      : None
keycloak_url        : None
pingfederate_url    : None
provider            : google
refresh_interval    : 5000
severity            : {'cleared': 5, 'critical': 1, 'debug': 7, 'indeterminate': 5, 'informational': 6, 'major': 2, 'minor': 3, 'normal': 5, 'ok': 5, 'security': 0, 'trace': 8, 'unknown': 9, 'warning': 4}
signup_enabled      : True
site_logo_url       : https://www.videns-it.com/wp-content/uploads/2018/08/Videns-IT-logo-195wide.png
sort_by             : lastReceiveTime
tracking_id         : None
config_file         : ~/.alerta.conf
profile             : None
key                 : m0atmDfR-6PEYBof351sp84906KxZV84vWv7qY1b
username            : None
password            : None
timezone            : Europe/London
timeout             : 5.0
sslverify           : True
output              : simple
color               : True
debug               : False
client              : <alertaclient.api.Client object at 0x7f6d1cb0d3c8>

alerta@2650a14871af:/app$ alerta blackout -E Development --customer test1 --text test_blackout
5ca11a46-ce1f-48cb-ad17-0baed022a522
alerta@2650a14871af:/app$ alerta blackouts
ID                                      P  ENVIRONMENT    SERVICE    RESOURCE                   EVENT        GROUP    TAGS    CUSTOMER    START                END                  DURATION    STATUS    REMAINING    USER                       CREATED              COMMENT
------------------------------------  ---  -------------  ---------  -------------------------  -----------  -------  ------  ----------  -------------------  -------------------  ----------  --------  -----------  -------------------------  -------------------  ------------------------------------------------
5ca11a46-ce1f-48cb-ad17-0baed022a522    1  Development                                                                        test1       2019/03/11 07:44:39  2019/03/11 11:44:39  14400s      active    14395s       support@videns-it.com      2019/03/11 07:44:39  test_blackout

alerta@2650a14871af:/app$ alerta send --customer test1 -r web01 -e NodeDown -E Development -S Website -s major -t "Web server is down." -v ERROR
90ec629d-a4d5-488c-9cbc-c8895ec124b8 (indeterminate -> major)
alerta@2650a14871af:/app$ alerta send --customer test2 -r web01 -e NodeDown -E Development -S Website -s major -t "Web server is down." -v ERROR
05871d21-a0f8-4dab-94fb-3d60c91eba04 (indeterminate -> major)
alerta@2650a14871af:/app$ alerta query --filter environment=Development
ID        LAST RECEIVED        SEVERITY    STATUS      DUPL  CUSTOMER    ENVIRONMENT    SERVICE    RESOURCE    GROUP    EVENT     VALUE    TEXT
--------  -------------------  ----------  --------  ------  ----------  -------------  ---------  ----------  -------  --------  -------  -------------------
05871d21  2019/03/11 07:46:43  major       blackout       0  test2       Development    Website    web01       Misc     NodeDown  ERROR    Web server is down.
90ec629d  2019/03/11 07:46:43  major       blackout       0  test1       Development    Website    web01       Misc     NodeDown  ERROR    Web server is down.

**Comment by satterly** [comment]
Thanks for the extra info. And now I'm really confused ;) Why are you creating blackouts and sending alerts using the `customer` option when you have Customer Views disabled?

**Comment by tjongerius** [comment]
problem we have, when enabling customer views and the extended team wants to review the alarm it forces us to make them all "admin" while they only have "user" rights.  If this is by design, we can close the bug, we can work around this by creating the customers from our own domain for all customers. (feature request: * wildcard support for single organisation to allow to all customers).

**Comment by satterly** [comment]
What authentication provider are you using?

**Comment by satterly** [comment]
Does your company have G-Suite ie. Google groups for Business?

**Comment by tjongerius** [comment]
Yes, we use G Suite business.

**Comment by satterly** [comment]
So, it would be possible to map google groups (available only with G-suite) to different customer domains wit a little development work. Would that work for you?

**Comment by tjongerius** [comment]
I had similar workarround in mind looping periodically over alerts and add
customer to generic customer (internal users). In that case we can close
the request. Wildcard for the future would be best. Thanks for the effort.

-- 

Met vriendelijke groet / Kind regards,

Thomas Jongerius

- Send via a mobile device

Videns IT Services BV

Orteliuslaan 850

3528 BB Utrecht

The Netherlands

T: +31 30 767 1067

M: +31 6 3456 3990


t.jongerius@videns-it.com

www.videns-it.com



Videns wins FD Gazellen Award being one of the fastest growing companies in
the Nederlands.



Op ma 11 mrt. 2019 16:03 schreef Nick Satterly <notifications@github.com>:

**Comment by satterly** [comment]
Is this what you mean? https://github.com/alerta/alerta/pull/548

**Comment by tjongerius** [comment]
@satterly thanks for the reference, if you give me contributor access to the doc repo I am happy to push the update for the documentation.

diff --git a/customer-views.rst b/customer-views.rst
index 607df85..1c6476f 100644
--- a/customer-views.rst
+++ b/customer-views.rst
@@ -46,6 +46,8 @@ Web Console for Users

 Users that have a `customer view` are limited to what they can do in the web console (and via the API). They cannot create other users, configure blackout periods or modify the customer lookup table.

+.. note:: When a specific customer requires to view all customers. The "*" customer reference can be used.
+

 Web Console for Administrators
 ------------------------------

**Comment by tjongerius** [comment]
Thanks for the support, you can close the issue.
