### ISSUE TITLE
alerta Jwt doesn't have mechanism to pass parameters to JWT.parse token

### ISSUE THREAD

**Issue by ashwinbasavaraja** [alerta/alerta#875]
**Describe the bug**

Issue 1 -  Defaulting algorithm to HS256 & verify = True
Currently looking for mechanism to integrate third party Auth provider like Okta. By default, algorithm used is RS256, But the code which referred   https://github.com/alerta/alerta/blob/master/alerta/models/token.py#L39 defaults it to 'HS256' & verify = True. So it doesn't allow to change the algorithm or turn off validation without modifying the code. Need to externalise these options, so that it can be modified without changing the main code.

Issue 2- Default permission scope
In case of 3rd party (like Okta) authentication integration, after validating JWT token successfully, it throws scope is empty. So we need option's like defaulting scope if it is not mapped in the Identity provider, something like https://github.com/alerta/alerta/blob/master/alerta/auth/utils.py#L53

**Expected behavior**
Need flexibility to externalise the configuration parameters to plug-in custom Identity provider integration

**Screenshots**

**Desktop (please complete the following information):**
Any

**Additional context**

**Comment by satterly** [comment]
Sorry but I don't understand why these changes are necessary to support an additional authentication provider. Are you confusing the identity provider JWTs with Alerta API web application JWTs? They are two separate things.

The web application JWTs are created and used by the Alerta API solely for the purpose of authenticating web app requests between the web app and the API once the user has logged in and authenticated with whatever authentication provider has been configured - whether that is internally provided basic auth or some external auth provider like Google or Github.

**Comment by ashwinbasavaraja** [comment]
If Identity provider JWTs with Alerta API web application JWTs, will lead to  showing of double login screen i.e., One with identity provider login page ( like Okta) & followed by alerta login page. 

Is there any way to avoid double login.  Typically I want to disable the user management of Alerta as it is taken care by external identity provider mainly on authentication front. Let the API level RBAC handled by Alerta itself ( as handled in google auth provider)

**Comment by satterly** [comment]
Yes, that's what I'm suggesting. Either there is a specific okta auth provider added to Alerta (as for Google, Github etc) or a generic OpenID/OAuth2 provider that okta Identity provider can work with.

**Comment by satterly** [comment]
Just found out that Id Providers can get "OpenID certification". A registry of certified OpenID Id providers is maintained by OIXnet https://www.oixnet.org/openid-certifications/ okta are in that list. So if a generic OpenID provider was added to Alerta then okta should be able to work with it.

**Comment by satterly** [comment]
I've got all of it working with okta except for getting the custom claim "group" to appear in the userinfo response. I can only get it to appear in the Access or ID token. Do you know if it's possible to add custom claims to the userinfo response?

**Comment by satterly** [comment]
<img width="1034" alt="screenshot 2019-03-08 at 00 50 20" src="https://user-images.githubusercontent.com/615057/53997373-35533700-413c-11e9-8119-ad4e3bae9030.png">

**Comment by satterly** [comment]
`/userinfo` response ...
```
{
  "sub": "00uc5sopceb89h5Sk356",
  "name": "Nick Satterly",
  "locale": "en-US",
  "email": "nfs@alerta.dev",
  "preferred_username": "nfs@alerta.dev",
  "given_name": "Nick",
  "family_name": "Satterly",
  "zoneinfo": "America/Los_Angeles",
  "updated_at": 1551995091,
  "email_verified": true
}
```

**Comment by satterly** [comment]
<img width="618" alt="screenshot 2019-03-08 at 07 47 03" src="https://user-images.githubusercontent.com/615057/54012516-9bf54680-4176-11e9-98dc-942fd41be914.png">

**Comment by satterly** [comment]
<img width="343" alt="screenshot 2019-03-08 at 07 47 52" src="https://user-images.githubusercontent.com/615057/54012535-ae6f8000-4176-11e9-9b6d-ee194a7bf66a.png">

**Comment by ashwinbasavaraja** [comment]
Thanks for the changes. I will test & get back to you on this
