### ISSUE TITLE
ERROR: type object 'StateMachine' has no attribute 'NORMAL_SEVERITY_LEVEL'

### ISSUE THREAD

**Issue by kaustubhd93** [alerta/alerta#884]
# Steps to reproduce 

I followed the steps given in the official tutorial : https://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html 
and I was running this command from the same server where alerta is set up: 
```
alerta send -r web01 -e NodeDown -E Production -S Website -s critical -t "Web server is down." -v ERROR
```
This gives an error : 
```
ERROR: type object 'StateMachine' has no attribute 'NORMAL_SEVERITY_LEVEL'
```

# Versions 

alerta : 6.8.1
alerta-server : 6.8.1
mongo : v3.2.22
uwsgi : 2.0.18
nginx : nginx/1.10.3
ubuntu : 16.04

Am I doing something wrong here ?

**Comment by satterly** [comment]
Almost certainly a bug. I'll take a look. Thanks for reporting the issue.
