### ISSUE TITLE
REST api for customers, not just customer lookup

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#885]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to request a new REST interface for a list of all existing customers within the alert data with the corresponding count - similar to the `/environments` interface. The current implementation is just a list of the customer lookup table.

**Describe alternatives you've considered**
A workaround would be to request all alerts, iterate over the result and count the customers. But this is a large overhead on the database, the network and the client.

**Additional context**
My initial goal was to use customer as the first layer and environment as the second. And i tried to adapt this also to the tab line in the web gui which is currently hard to implement without this api.

**Comment by satterly** [comment]
So you want to add an extra layer of tabs for customers above the row of environment tabs?

**Comment by escoand** [comment]
Not extra but instead.

**Comment by satterly** [comment]
Do you use environment in this scenario?

**Comment by escoand** [comment]
Yes, 1. customer, 2. environment=server or database, 3. resource=process or table. It's maybe not like intentionally design but we need the customer as the most upper layer.

**Comment by satterly** [comment]
The recommended approach is to combine "server" or "database" into the "process" or "table" so you have "server:process" or "database:table" ie. "myweb01:apached" or "MYDB:table3".

"environment" is meant to allow you to namespace your resources. "customer" is meant to allow you to partition alerts so some users only see alerts intended for them. Using environment and customer in the way you describe is not supported. And if I made this change it would only encourage more people to wrongly assign what I consider the resource to the environment.

So unless you have some overwhelmingly good reason, I think I'm going to have to reject this request.

**Comment by escoand** [comment]
I understand your point but this would double the information of customer and environment in our case.
We are a support unit for multiple manufacturing plants. Every plant is some kind of standalone so they are different customers (to not see the alerts of the other plants). If we try to namespace the alerts for our support users as well we need to use the same information as environment. Not really nice but doable with your recommendation.
