### ISSUE TITLE
Wrong response when using api key and customer view

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#886]
**Issue Summary**
Wrong response when using api key and customer view.

```
$ curl '.../keys'
{"keys": [
	{"customer": null, "key": "A-o2AKuJ1lm_IdO5TfyZ77dwgLgrQT5pzB0vhfBS", "scopes": ["admin"], ...},
	{"customer": "*",  "key": "BoQFb-rqGaihPK_Y_J9ZTjNk8C-tLjd5_ttjd3yb", "scopes": ["admin"], ...}
]}

$ curl '.../alerts/count' -H 'Authorization: Key A-o2AKuJ1lm_IdO5TfyZ77dwgLgrQT5pzB0vhfBS'
{"autoRefresh":true,"severityCounts":{"major":83,"normal":950,"warning":100},"status":"ok","statusCounts":{"closed":950,"open":183},"total":1133}

$ curl '.../alerts/count' -H 'Authorization: Key BoQFb-rqGaihPK_Y_J9ZTjNk8C-tLjd5_ttjd3yb'
{"autoRefresh":true,"severityCounts":{},"status":"ok","statusCounts":{},"total":0}
```

**Environment**
- OS: Linux
- API version: 6.8.1
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx
- Database: MongoDB
- Server config:
  Auth enabled? Yes
  Auth provider? OpenID
  Customer views? Yes
- web UI version: 6.8.1
- CLI version: 6.8.1

**To Reproduce**
1. Create api key with role `admin` and empty customer.
2. Create api key with role `admin` and `*` customer.
3. Request the `/alerts/count` endpoint with first api key - full result.
4. Request the `/alerts/count` endpoint with second api key - empty result.

**Expected behavior**
The second api key should respond with the same result.

**Comment by satterly** [comment]
Why would `null` and `*` produce the same result? Is your expectation that the customer names should actually be regular expressions? I'm not sure why you would assume that or how it would work in practice. Did you find a reference to that behaviour in documentation somewhere?

**Comment by escoand** [comment]
No, it was the analogy to the customer lookup table. So it isn't?

**Comment by satterly** [comment]
No, the asterisk (*) will be treated as a literal string. ie. a customer called "*".
