### ISSUE TITLE
Allow housekeeping to close but not delete stale alerts

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#887]
> I use Alerta to display alerts from Prometheus/AlertManager. It works fine, but there are some cases when AlertManager does not send OK event. For instance, when we create a silence period for alerts and then these alerts are closing or when there are inhibit rules and there are inhibited alerts which are closing in that state. So I usually have some stale alerts in Alerta which I should close manually.
I have tried to use the housekeeping feature but it just removes stale alerts. It is not so good because of alerts history - I still want to see the stale alerts (which are closed/deleted now) in the history.
Is there any way to close the stale alerts instead of deleting them during housekeeping?
@vykulakov

**Comment by satterly** [comment]
To run housekeeping but **not delete** alerts just set the thresholds to zero ...

```
DEFAULT_EXPIRED_DELETE_HRS = 0 # do not delete
DEFAULT_INFO_DELETE_HRS = 0 # do not delete
```

**Comment by dreweastep** [comment]
@satterly Where do you set these values? In the alertad.conf?

**Comment by satterly** [comment]
Yes.
