### ISSUE TITLE
Counts per service

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#888]
I try to create some kind of status page of all the open alerts per environment and service. This will be displayed in a matrix as HTML table. This is already working quiet well but I need to do a `/alerts/count?environment=...&service=...&status=open` for every existing combination. This results already in my test deployment in over 100 HTTP requests. Could this be done without such a mess?

Ideal would be a combination of `/services` with the counts from `/alerts/count`.

PS: Sorry for the many issues. We're currently try to evaluate and rollout alerta into our default workflow. So we are investigating what could be done...

**Comment by satterly** [comment]
Doesn't the "services" endpoint already give you want you want?
```
$ http ':8080/services?status=closed'
HTTP/1.0 200 OK
Access-Control-Allow-Origin: http://localhost
Content-Length: 150
Content-Type: application/json
Date: Thu, 21 Mar 2019 13:34:13 GMT
Server: Werkzeug/0.14.1 Python/3.6.5
Vary: Origin

{
    "services": [
        {
            "count": 1,
            "environment": "Development",
            "service": "Test"
        }
    ],
    "status": "ok",
    "total": 1
}
``

**Comment by escoand** [comment]
Thanks for the fast feedback. But sadly not exactly. I wanted the count status and severity based. Like this:

```json
{
    "services": [
        {
            "count": 524,
            "environment": "Development",
            "service": "Test",
            "severityCounts":{"major":21,"normal":484,"warning":19},
            "statusCounts":{"closed":484,"open":40}
        }
    ],
    "status": "ok",
    "total": 1
}
```

**Comment by net592** [comment]
I have a problem.
the first time i post alert
"event": "system.cpu.load[percpu,avg1]",
"resource": "zbx124.se.net",
"environment": "Production",
"service": ["service_name1", "service_name2"]

When my service changes  i post alert,
"event": "system.cpu.load[percpu,avg1]",
"resource": "zbx124.se.net",
"environment": "Production",
"service": ["service_name3", "service_name4"]

i get this alert  Response  is still.
 "service": ["service_name1", "service_name2"]  
I understand
 "service": ["service_name3", "service_name4"]

May be mischaracterized. thank you.

**Comment by escoand** [comment]
@net592 Sorry, but how is this connected to the initial question?

**Comment by satterly** [comment]
Example ...
```
$ http :8080/services?api-key=Xm6X2leGzaMOuUXUeB25AGVu-NVGbjcfyddyFnpd
HTTP/1.0 200 OK
Access-Control-Allow-Origin: http://localhost
Content-Encoding: gzip
Content-Length: 248
Content-Type: application/json
Date: Sat, 23 Mar 2019 18:50:09 GMT
Server: Werkzeug/0.14.1 Python/3.6.5
Vary: Origin, Accept-Encoding

{
    "services": [
        {
            "count": 2,
            "environment": "Production",
            "service": "MySvc",
            "severityCounts": {
                "High": 1,
                "OK": 1
            },
            "statusCounts": {
                "closed": 1,
                "open": 1
            }
        },
        {
            "count": 1,
            "environment": "Production",
            "service": "Svc3",
            "severityCounts": {
                "Disaster": 1
            },
            "statusCounts": {
                "open": 1
            }
        },
        {
            "count": 1,
            "environment": "Production",
            "service": "Svc2",
            "severityCounts": {
                "Disaster": 1
            },
            "statusCounts": {
                "open": 1
            }
        },
        {
            "count": 2,
            "environment": "Production",
            "service": "Svc",
            "severityCounts": {
                "Disaster": 2
            },
            "statusCounts": {
                "open": 2
            }
        },
        {
            "count": 3,
            "environment": "Development",
            "service": "GitHub",
            "severityCounts": {
                "major": 3
            },
            "statusCounts": {
                "open": 3
            }
        }
    ],
    "status": "ok",
    "total": 5
}
```

**Comment by escoand** [comment]
Fantastic, thank you.

**Comment by escoand** [comment]
Should we have an extra scope for this? Maybe `read:counts`?

**Comment by satterly** [comment]
Why?

**Comment by escoand** [comment]
Yes, I have a static HTML page with a JavaScript snippet doing the AJAX call and adding the counts into the table. I could do it in a background job and create a "static" json file but this would be an other point of failure.
