### ISSUE TITLE
Ability to create backdated alerts matching expired blackouts

### ISSUE THREAD

**Issue by Anderen2** [alerta/alerta#891]
**Is your feature request related to a problem? Please describe.**
We sometimes experience some race-conditions with our alerting and blackouts. 
This happens when events generated by downstream systems (eg. Telegraf/Kapactor, etc) get delayed to Alerta, and is raised after a blackout has automatically expired or been deleted. 

**Describe the solution you'd like**
The ability to create back-dated alerts that matches expired blackouts. 
Likely requires change in https://github.com/alerta/alerta/blob/master/alerta/database/backends/postgres/base.py#L643 to take into account that createTime may be in the past. 

**Describe alternatives you've considered**
A temporary workaround for this is to create blackouts with a longer expiry that takes the delay into account.

**Comment by satterly** [comment]
So are you suggesting instead of this...
```
WHERE start_time <= NOW() at time zone 'utc' AND end_time > NOW() at time zone 'utc'
```
it should be something like this ...
```
WHERE start_time <= alert.createTime AND end_time > alert.createTime
```

Have you tried/tested this?
