### ISSUE TITLE
I have a problem.

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#892]
I have a problem.
the first time i post alert
```
"event": "system.cpu.load[percpu,avg1]",
"resource": "zbx124.se.net",
"environment": "Production",
"service": ["service_name1", "service_name2"]

```
When my service changes  i post alert,
```
"event": "system.cpu.load[percpu,avg1]",
"resource": "zbx124.se.net",
"environment": "Production",
"service": ["service_name3", "service_name4"]

```
i get this alert  Response  is still.
` "service": ["service_name1", "service_name2"] ` 
I understand
` "service": ["service_name3", "service_name4"]`

May be mischaracterized. thank you.

_Originally posted by @net592 in https://github.com/alerta/alerta/issues/888#issuecomment-475589473_

**Comment by satterly** [comment]
@net592 Not all attributes of duplicate alerts are updated. See ...

>When an alert with the same environment-resource-event combination is received with the same severity, the alert is de-duplicated.
This means that information from the de-duplicated alert is used to update key attributes of the existing alert (like duplicateCount, repeat flag, value, text and lastReceiveTime) and the new alert is not shown.

https://docs.alerta.io/en/latest/server.html?highlight=duplicate#de-duplication

In future, please don't ask unrelated questions in an existing issue. It's confusing for everyone and mean your issue isn't actually addressed.

**Comment by net592** [comment]
Thank!!!

**Comment by satterly** [comment]
See #953

**Comment by net592** [comment]
Nice 
Thank you very much
