### ISSUE TITLE
The duplicate events  "service" does not update the question to consult

### ISSUE THREAD

**Issue by net592** [alerta/alerta#896]
**Issue Summary**
The service does not update the question to consult。

the first time i post alert

```
"event": "system.cpu.load[percpu,avg1]",
"resource": "zbx124.se.net",
"environment": "Production",
"service": ["service_name_group1", "service_name_group2"]
```

When my service changes i post alert,

```
"event": "system.cpu.load[percpu,avg1]",
"resource": "zbx124.se.net",
"environment": "Production",
"service": ["service_name_group1", "service_name_group2", "service_name_group3"]
```

i get this alert Response is still.
`"service": ["service_name_group1", "service_name_group2"]`
I hope it's
`"service":  ["service_name_group1", "service_name_group2", "service_name_group3"]`

Because I am converting to service with zabbix hostgroup 
When my hostgroup changes or adjusts, I expect the alerta service field to update,
This will cause inconvenience,  duplicate events How to update fields
Maybe not. Thank you

**Comment by satterly** [comment]
This is a duplicate of #892 which you posted 3 days ago. The answer is the same.

https://github.com/alerta/alerta/issues/892#issuecomment-475678738

**Comment by satterly** [comment]
See #953

**Comment by net592** [comment]
Nice
Thank you very much
