### ISSUE TITLE
Feature Request: Use SAML groups assertion for customer lookup instead of e-mail domain

### ISSUE THREAD

**Issue by jcmcken** [alerta/alerta#898]
Currently, the SAML auth plugin [takes the user's e-mail domain](https://github.com/alerta/alerta/blob/4adf73437bc78cdde72542bb9852f9f40a6405f9/alerta/auth/saml2.py#L105) as the group when performing customer lookup instead of using the 'groups' assertion returned from the SAML IdP.

This seems to differ from the OIDC, GitLab, and other auth plugins that have role/group support.

To maintain backwards compatibility, maybe there should be a boolean option such as ``SAML_MAP_GROUPS_TO_CUSTOMERS`` that defaults to ``False``.

**Comment by satterly** [comment]
Yes, I agree. Can you provide an example SAML response that includes role and group assertions?

**Comment by jcmcken** [comment]
We use the groups claim with Jenkins -- there's a sample response [here](https://support.cloudbees.com/hc/en-us/articles/227202668-SAML-Plugin-Basics)

I'm not certain how standard that response is. Our Jenkins encrypts the payload response, so I'll need to dig into it to get the key and decrypt to get the actual details for you.

I believe [this line](https://github.com/alerta/alerta/blob/4adf73437bc78cdde72542bb9852f9f40a6405f9/alerta/auth/saml2.py#L101) already references the groups claim though. So that part might already be solved.

**Comment by jcmcken** [comment]
Here's the attribute statement from one of our services (values replaced) that includes groups:

```xml
    <AttributeStatement>
      <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
        <AttributeValue>foo@example.com</AttributeValue>
      </Attribute>
      <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name">
        <AttributeValue>JOHN DOE</AttributeValue>
      </Attribute>
      <Attribute Name="memberOf">
        <AttributeValue>GROUP1</AttributeValue>
        <AttributeValue>GROUP2</AttributeValue>
        <AttributeValue>GROUP3</AttributeValue>
      </Attribute>
    </AttributeStatement>

```

**Comment by satterly** [comment]
Thanks for the extra info. Are you saying you use Jenkins as the SAML2 identity provider or is Jenkins integrating with an external SAML2 idp?

**Comment by satterly** [comment]
The fix simply adds "groups" to the list of things to do a customer match against. ie. in addition to email and domain.

**Comment by jcmcken** [comment]
We're using Microsoft ADFS as the IDP. Jenkins was just an example where we use the groups claim for role/group assignment.

Your change looks like it will solve our issue. Thanks!
