### ISSUE TITLE
Deploying alerta with apache on centos7

### ISSUE THREAD

**Issue by Promzor** [alerta/alerta#899]
Hello, 

when trying the test alert 

> /opt/alerta/bin/alerta send -r net01 -e down -s fatal -E Code -S Network -t 'net01 is down.'

Console responds with:

>
 Error: Failed to get config from http://localhost/api/config. Reason: 500 Server Error: Internal Server Error for url: http://localhost/api/config
> 

when I look into /var/log/httpd/error_log I see : 

> [Thu Mar 28 11:58:34.322562 2019] [mpm_prefork:notice] [pid 23527] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/4.6.2 Python/3.6 configured -- resuming normal operations
> [Thu Mar 28 11:58:34.322614 2019] [core:notice] [pid 23527] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
> [Thu Mar 28 11:58:47.831155 2019] [wsgi:error] [pid 23532] [remote ::1:45332] mod_wsgi (pid=23532): Failed to exec Python script file '/var/www/wsgi.py'.
> [Thu Mar 28 11:58:47.831239 2019] [wsgi:error] [pid 23532] [remote ::1:45332] mod_wsgi (pid=23532): Exception occurred processing WSGI script '/var/www/wsgi.py'.
> [Thu Mar 28 11:58:47.831560 2019] [wsgi:error] [pid 23532] [remote ::1:45332] Traceback (most recent call last):
> [Thu Mar 28 11:58:47.831594 2019] [wsgi:error] [pid 23532] [remote ::1:45332]   File "/var/www/wsgi.py", line 1, in <module>
> [Thu Mar 28 11:58:47.831603 2019] [wsgi:error] [pid 23532] [remote ::1:45332]     from alerta import app
> [Thu Mar 28 11:58:47.831628 2019] [wsgi:error] [pid 23532] [remote ::1:45332] ModuleNotFoundError: No module named 'alerta'
> [root@localhost www]# 

And when I check that file in /var/www/wsgi.py only the following line is present

> from alerta import app

Since it was working under Nginx, however the entire cluster here is Apache so it must run under apache. 
If any other conf files are needed I can provide ofc.

-Cheers Promzor

**Comment by satterly** [comment]
Have you seen this https://github.com/alerta/vagrant-try-alerta/blob/master/scripts/centos/apache.sh ?

**Comment by Promzor** [comment]
Thanks for the fast reply, 

when running the script the UWSGI wont start. 

when checking in journalctl -xe

> Mar 28 13:04:21 localhost.localdomain alertad[20144]: unable to find "application" callable in file wsgi.py
> Mar 28 13:04:21 localhost.localdomain alertad[20144]: VACUUM: unix socket /var/run/uwsgi.sock removed.



The uwsgi.ini file 

> [uwsgi]
> chdir = /var/www/
> mount = /api=wsgi.py
> callable = app
> manage-script-name = true
> env = BASE_URL=/api
> 
> master = true
> processes = 5
> logger = syslog:alertad
> 
> socket = /var/run/uwsgi.sock
> chmod-socket = 777
> uid = root
> gid = root
> vacuum = true
> 
> die-on-term = true

Currently running as root , and max permissions, once it works I will tweak on that.

**Comment by satterly** [comment]
I'm confused. Are you using Apache mod_wsgi or uwsgi? If using Apache then uwsgi config is irrelevant. Please share Apache config instead.

**Comment by Promzor** [comment]
This is the config from apache default.conf

> Listen 8080
> 
> <VirtualHost *:8080>
>   ServerName localhost
>   WSGIDaemonProcess alerta processes=5 threads=5 python-home=/opt/alerta
>   WSGIProcessGroup alerta
>   # WSGIApplicationGroup %{GLOBAL}
>   WSGIScriptAlias / /var/www/wsgi.py
>   WSGIPassAuthorization On
>   SetEnv BASE_URL /api
> </VirtualHost>
> <VirtualHost *:80>
>   ProxyPass /api http://localhost:8080
>   ProxyPassReverse /api http://localhost:8080
>   DocumentRoot /var/www/html
> </VirtualHost>


 /etc/httpd/conf/httpd.conf


> >ServerRoot "/etc/httpd"
> Listen 80
> Include conf.modules.d/*.conf
> User apache
> Group apache
> ServerAdmin root@localhost
> <Directory />
>     AllowOverride none
>     Require all denied
> </Directory>
> DocumentRoot "/var/www/html"
> <Directory "/var/www">
>     AllowOverride None
>     Require all granted
> </Directory>
> <Directory "/var/www/html">
>     Options Indexes FollowSymLinks
>     AllowOverride None
>     Require all granted
> </Directory>
> <IfModule dir_module>
>     DirectoryIndex index.html
> </IfModule>
> <Files ".ht*">
>     Require all denied
> </Files>
> ErrorLog "logs/error_log"
> LogLevel warn
> <IfModule log_config_module>
>     LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
>     LogFormat "%h %l %u %t \"%r\" %>s %b" common
>     <IfModule logio_module>
>       LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
>     </IfModule>
>     CustomLog "logs/access_log" combined
> </IfModule>
> <IfModule alias_module>
>     ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
> </IfModule>
> <Directory "/var/www/cgi-bin">
>     AllowOverride None
>     Options None
>     Require all granted
> </Directory>
> <IfModule mime_module>
>     TypesConfig /etc/mime.types
>     AddType application/x-compress .Z
>     AddType application/x-gzip .gz .tgz
>     AddType text/html .shtml
>     AddOutputFilter INCLUDES .shtml
> </IfModule>
> AddDefaultCharset UTF-8
> <IfModule mime_magic_module>
>     MIMEMagicFile conf/magic
> </IfModule>
> EnableSendfile on
> IncludeOptional conf.d/*.conf



Cheers
