### ISSUE TITLE
Basic auth cannot be used when python-ldap is installed

### ISSUE THREAD

**Issue by Albibek** [alerta/alerta#900]
Since LDAP is automatically detected, one cannot use basic auth even with AUTH_TYPE='basic' when python-ldap is installed on host for some other reasons. 

Authenticating becomes very frustrating. User expects the basic auth to happen, but ldap auth is tried instead giving "unauthorized domain" even when ALLOWED_EMAIL_DOMAINS match with domain in username (but LDAP_DOMAINS is empty while ldap is autodetected). 

Proposal: change the AUTH_TYPE for ldap more explicit with 'ldap' type.

Also LDAP auth doesn't give any chance to have authorization by group membership. So it's either any user from LDAP catalog can authenticate or no one at all.

**Comment by satterly** [comment]
Sure this is possible and I'll probably do it but why not install Alerta in a python virtual environment.

**Comment by Albibek** [comment]
I did, but I've also installed python-ldap to test LDAP auth. My concern is mostly about configuration and error message being a kind of misleading.

**Comment by satterly** [comment]
So why install python ldap in the virtual environment if you wanted to use basic authentication? And you mention a misleading error message but don't tell me what is was so very difficult for me to improve it.

**Comment by satterly** [comment]
> Also LDAP auth doesn't give any chance to have authorization by group membership. So it's either any user from LDAP catalog can authenticate or no one at all.

I've addressed the other issues. Is this LDAP group issue something you think you could fix yourself?
