### ISSUE TITLE
Cloudwatch alerts are not displayed

### ISSUE THREAD

**Issue by gregoryb** [alerta/alerta#905]
**Describe the bug**
Alerts from Cloudwatch are not processed. **I received the confirmation from SNS on Alerta and i confirmed** but alerts are not displayed.

When i post the attached JSON - [SNS.txt](https://github.com/alerta/alerta/files/3028555/SNS.txt) - to Alerta cloudwatch endpoint i got:

```
{
  "code": 400,
  "errors": null,
  "message": "the JSON object must be str, bytes or bytearray, not 'dict'",
  "status": "error"
}
```

**To Reproduce**

1. Steps to reproduce the behavior:
2. Setup Cloudwatch plugin into SNS.
3. Confirm on Alerta
4. There is no alerts.

**Expected behavior**
Alerts from Clouwatch should be displayed.

**Additional context**
Ubuntu 18.04
alerta 6.8.1
alerta client 6.8.1
requests 2.21.0
click 7.0

**Comment by satterly** [comment]
Can you provide an example JSON payload?

**Comment by gregoryb** [comment]
There is one attached in the description SNS.txt

**Comment by gregoryb** [comment]
I understand what happen. My "Alert" come from an "INSUFFICIENT_DATA" state. There is not "Type" key in the message.
It's not really managed in the plugin. I think an Alert should be raised instead of an exception.

**Comment by satterly** [comment]
Testing by me confirms that this works already. I've added a unit test to confirm that this is the case (see #971). I'm not sure why it's not working for you. If you could supply the entire payload sent by AWS instead of just the `Message` payload that would be useful.
