### ISSUE TITLE
Feature Request: Allow 'customer admins' (specifically for allowing customer-managed blackout periods)

### ISSUE THREAD

**Issue by jcmcken** [alerta/alerta#907]
**Is your feature request related to a problem? Please describe.**

Currently, it seems that customer views only allow a 'read only' access to a filtered list of alerts. We plan on using alerta in a highly multi-tenant fashion, and would like a subset of each customer group (the 'customer admins') to be able to manage the blackout periods for that customer view. This way they don't have to contact the main team to request blackout period changes. 

**Describe the solution you'd like**

Add a new type of role to alerta, "customer admin", that has standard customer view permissions plus the ability to manage blackout periods for that customer view. This role would not have any other permissions (e.g. customer lookup table, etc.).

**Describe alternatives you've considered**

We've considered providing some kind of API proxy that performs the blackout update after making an authorization decision, but this seems like overkill for something that could be baked straight into alerta itself.

**Comment by satterly** [comment]
>Currently, it seems that customer views only allow a 'read only' access to a filtered list of alerts. 

What gives you the impression a user assigned to a customer can only have `read` scopes?

**Comment by jcmcken** [comment]
Maybe I'm not using the right terminology. The [documentation](https://docs.alerta.io/en/latest/customer-views.html?highlight=customer%20admin) states:

> Users that have a customer view are limited to what they can do in the web console (and via the API). They cannot create other users, configure blackout periods or modify the customer lookup table.

**Comment by satterly** [comment]
Sorry, but it looks like that documentation is out-of-date. Users with a customer view login that have "write" permission can create blackouts for any customer that they can view. See example screenshot below.

<img width="1077" alt="Screenshot 2019-04-03 at 10 19 05" src="https://user-images.githubusercontent.com/615057/55465880-56555d80-55fe-11e9-80ff-9f2e530e5840.png">

I will update the docs to reflect this. Let me know if you have any more questions.

**Comment by jcmcken** [comment]
Great! Thanks for the help
