### ISSUE TITLE
Grafana Webhook accepting timeout string breaking Python SDK

### ISSUE THREAD

**Issue by tjongerius** [alerta/alerta#911]
**Issue Summary**
By example:
https://<>/api/webhooks/grafana?api-key=<key>&environment=<env>&service=<service>&timeout=1200

timeout=1200 > converted into string

curl -k -XPOST "https://<>/api/webhooks/grafana?api-key=<key>&environment=Development&service=Web&timeout=1200" \
> -H 'Content-type: application/json' \
> -d '{
>   "title": "My alert",
>   "ruleId": 1,
>   "ruleName": "Load peaking!",
>   "ruleUrl": "http://url.to.grafana/db/dashboard/my_dashboard?panelId=2",
>   "state": "alerting",
>   "imageUrl": "http://s3.image.url",
>   "message": "Load is peaking. Make sure the traffic is real and spin up more webfronts",
>   "evalMatches": [
>     {
>       "metric": "requests",
>       "tags": {},
>       "value": 122
>     }
>   ]
> }'
{"alert":{"attributes":{"imageUrl":"<a href=\"http://s3.image.url\" target=\"_blank\">Image</a>","ip":"77.164.139.59:52469","ruleId":"1","ruleUrl":"<a href=\"http://url.to.grafana/db/dashboard/my_dashboard?panelId=2\" target=\"_blank\">Rule</a>"},"correlate":[],"createTime":"2019-04-02T19:09:14.243Z","customer":null,"duplicateCount":0,"environment":"Development","event":"Load peaking!","group":"Performance","history":[{"event":"Load peaking!","href":"https://<>/api/alert/5645884f-f486-4db3-8058-46e17260fb95","id":"5645884f-f486-4db3-8058-46e17260fb95","severity":"major","status":"open","text":"new alert","type":"new","updateTime":"2019-04-02T19:09:14.243Z","value":"122"}],"href":"https://<>api/alert/5645884f-f486-4db3-8058-46e17260fb95","id":"5645884f-f486-4db3-8058-46e17260fb95","lastReceiveId":"5645884f-f486-4db3-8058-46e17260fb95","lastReceiveTime":"2019-04-02T19:09:14.251Z","origin":"Grafana","previousSeverity":"indeterminate","rawData":"{\"title\": \"My alert\", \"ruleId\": 1, \"ruleName\": \"Load peaking!\", \"ruleUrl\": \"http://url.to.grafana/db/dashboard/my_dashboard?panelId=2\", \"state\": \"alerting\", \"imageUrl\": \"http://s3.image.url\", \"message\": \"Load is peaking. Make sure the traffic is real and spin up more webfronts\", \"evalMatches\": [{\"metric\": \"requests\", \"tags\": {}, \"value\": 122}]}","receiveTime":"2019-04-02T19:09:14.251Z","repeat":false,"resource":"requests","service":["Web"],"severity":"major","status":"open","tags":[],"text":"Load is peaking. Make sure the traffic is real and spin up more webfronts",**"timeout":"1200"**,"trendIndication":"moreSevere","type":"performanceAlert","value":"122"},"id":"5645884f-f486-4db3-8058-46e17260fb95","status":"ok"}

curl -k -XGET https://<>/api/alert/5645884f-f486-4db3-8058-46e17260fb95 \
> -H 'Authorization: Key <>' \
> -H 'Content-type: application/json'
{"alert":{"attributes":{"imageUrl":"<a href=\"http://s3.image.url\" target=\"_blank\">Image</a>","ip":"77.164.139.59:52469","ruleId":"1","ruleUrl":"<a href=\"http://url.to.grafana/db/dashboard/my_dashboard?panelId=2\" target=\"_blank\">Rule</a>"},"correlate":[],"createTime":"2019-04-02T19:09:14.243Z","customer":null,"duplicateCount":0,"environment":"Development","event":"Load peaking!","group":"Performance","history":[{"event":"Load peaking!","href":"https://<>/api/alert/5645884f-f486-4db3-8058-46e17260fb95","id":"5645884f-f486-4db3-8058-46e17260fb95","severity":"major","status":"open","text":"new alert","type":"new","updateTime":"2019-04-02T19:09:14.243Z","value":"122"}],"href":"https://<>/api/alert/5645884f-f486-4db3-8058-46e17260fb95","id":"5645884f-f486-4db3-8058-46e17260fb95","lastReceiveId":"5645884f-f486-4db3-8058-46e17260fb95","lastReceiveTime":"2019-04-02T19:09:14.251Z","origin":"Grafana","previousSeverity":"indeterminate","rawData":"{\"title\": \"My alert\", \"ruleId\": 1, \"ruleName\": \"Load peaking!\", \"ruleUrl\": \"http://url.to.grafana/db/dashboard/my_dashboard?panelId=2\", \"state\": \"alerting\", \"imageUrl\": \"http://s3.image.url\", \"message\": \"Load is peaking. Make sure the traffic is real and spin up more webfronts\", \"evalMatches\": [{\"metric\": \"requests\", \"tags\": {}, \"value\": 122}]}","receiveTime":"2019-04-02T19:09:14.251Z","repeat":false,"resource":"requests","service":["Web"],"severity":"major","status":"open","tags":[],"text":"Load is peaking. Make sure the traffic is real and spin up more webfronts"**,"timeout":"1200"**,"trendIndication":"moreSevere","type":"performanceAlert","value":"122"},"status":"ok","total":1}

```python
result = aclient.get_alert("5645884f-f486-4db3-8058-46e17260fb95")
Traceback (most recent call last):
  File "/Users/thomasjongerius/Library/Preferences/PyCharmCE2017.3/scratches/scratch_36.py", line 13, in <module>
    result = aclient.get_alert("5645884f-f486-4db3-8058-46e17260fb95")
  File "/Users/thomasjongerius/PycharmProjects/videns/venv37/lib/python3.7/site-packages/alertaclient/api.py", line 65, in get_alert
    return Alert.parse(self.http.get('/alert/%s' % id)['alert'])
  File "/Users/thomasjongerius/PycharmProjects/videns/venv37/lib/python3.7/site-packages/alertaclient/models/alert.py", line 64, in parse
    raise ValueError('timeout must be an integer')
ValueError: timeout must be an integer

```
**Environment**
alarm_model         : {'name': 'Alerta 6.7.3'}
- Deployment: Docker

- Database:  MongoDB,

- Server config:
actions             :
alarm_model         : {'name': 'Alerta 6.7.3'}
audio               : {'new': None}
auth_required       : True
client_id           : None
colors              : {'highlight': 'black', 'severity': {'emergency': 'red', 'minor': 'lightblue', 'notice': 'yellow', 'warning': 'yellow'}}
columns             : severity, status, createTime, lastReceiveTime, customer, service, resource, event, value, text
customer_views      : True
dates               : {'longDate': 'd/M/yyyy h:mm:ss.sss a', 'mediumDate': 'EEE d MMM HH:mm', 'shortTime': 'HH:mm'}
email_verification  : False
endpoint            : http://localhost:8080/api
github_url          : https://github.com
gitlab_url          : https://gitlab.com
keycloak_realm      : None
keycloak_url        : None
pingfederate_url    : None
provider            : google
refresh_interval    : 5000
severity            : {'critical': 1, 'emergency': 1, 'indeterminate': 5, 'major': 2, 'minor': 4, 'normal': 5, 'notice': 3, 'ok': 5, 'unknown': 9, 'warning': 3}
signup_enabled      : True
site_logo_url       :  <>
sort_by             : lastReceiveTime
tracking_id         : None
config_file         : ~/.alerta.conf
profile             : None
key                 :<>
username            : None
password            : None
timezone            : Europe/London
timeout             : 5.0
sslverify           : True
output              : simple
color               : True
debug               : False
client              : <alertaclient.api.Client object at 0x7fcae06ff390>

**To Reproduce**
See above

**Expected behavior**
Convert to int()

**Comment by satterly** [comment]
Thanks for raising the issue. Seems it was only a problem if using MongoDB as Postgres cast the string to an integer before updating the database. I've fixed the grafana webhook to only send integers and the alert model to only accept values that can be cast to integers.
