### ISSUE TITLE
Unack doesn't work if alert has been acked twice

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#914]
If state doesn't change following an action then ignore the action. This should prevent "double acks" breaking the "unack" to previous status.

**Comment by infernix** [comment]
Example:

![image](https://user-images.githubusercontent.com/162537/55463582-ac73d200-55f9-11e9-9a28-b010ebe11f9b.png)

**Comment by satterly** [comment]
Adding "debounce" to action buttons would also help here. It would disable the button for 200ms or so which would prevent accidental double-clicking.

**Comment by infernix** [comment]
AFAIK the issue also happens on CLI. I think it's better to solve it on the API side.

Either way, I don't think it's good enough to only fix accidental double clicks. Can be the case that it gets set to the same state any time after, and can't see a valid reason why it should be possible to set the same state more than once?

**Comment by satterly** [comment]
I was proposing to do both things. Not one or the other.
