### ISSUE TITLE
Performance issues with version 6.8.4

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#927]
**Issue Summary**
I upgraded to 6.8.4 and then ran the query above before starting and Its still filling up the connection limit with a large alert volume

**Environment**
- OS: Ubuntu
- API version: 6.8.4
- Deployment: Docker
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

**To Reproduce**
1. Deploy docker image 6.8.4
2. Send alerts
3. Watch number of Pg connections increase

**Additional Context**
Grayson Head @graysonhead 22:52
There didn't seem to be anything interesting in the logs in debug mode, I wound up starting from a fresh database on 6.8.4 and didn't encounter the same regression
I went from using 405 sessions (my postgres limit is 400) to about ~145 on average when running the full battery of testing without changing anything else
And of course right when I say that, it jumped to 405 again after about 10 minutes of behaving correctly. Let me look at these logs and see what happened around the time it occured

I downgraded to 6.8.0 and blew away the database again, now instead of 145 pgsql sessions I have 7 during the same battery of tests. I'm going to let it run for a bit and see if the issue re-occurs

Yeah, one thing to mention is that I am sending a fairly high volume of alerts. Every time one of my monitoring jobs run, it sends a status update (A "normal" status if nothing is wrong) that way things can auto-clear in Alerta/PagerDuty if they fix themselves as they often do. Right now I'm pushing about 100,000 alerts per hour and I expect that to accelerate as we test more things with Alerta. Given that I'm intentionally sending a lot of duplicate alerts with identical statuses to let Alerta handle the state changes (so my monitoring jobs can stay stupid and be easier to maintain), I was eyeing this commit with a bit of suspicion: alerta/alerta@625fc77 since it seems to change the behavior of duplicate alerts. That is just a wild guess on my part though.

**Comment by satterly** [comment]
For future reference, the following are Python package versions for v6.8.3 and v6.8.4 ...

version 6.8.3
```
$ /venv/bin/pip freeze
alerta==6.8.1
alerta-server==6.8.3
bcrypt==3.1.6
blinker==1.4
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
Flask==1.0.2
Flask-Compress==1.4.0
Flask-Cors==3.0.7
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.1
psycopg2==2.7.7
pycparser==2.19
PyJWT==1.7.1
pymongo==3.7.2
pyparsing==2.3.1
python-dateutil==2.8.0
pytz==2018.9
PyYAML==5.1
raven==6.10.0
requests==2.21.0
six==1.12.0
tabulate==0.8.3
urllib3==1.24.1
uWSGI==2.0.18
Werkzeug==0.15.1
```
version 6.8.4
```
$ /venv/bin/pip freeze
alerta==6.8.1
alerta-server==6.8.4
bcrypt==3.1.6
blinker==1.4
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
Flask==1.0.2
Flask-Compress==1.4.0
Flask-Cors==3.0.7
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
psycopg2==2.8.1
pycparser==2.19
PyJWT==1.7.1
pymongo==3.7.2
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2018.9
PyYAML==5.1
raven==6.10.0
requests==2.21.0
six==1.12.0
tabulate==0.8.3
urllib3==1.24.1
uWSGI==2.0.18
Werkzeug==0.15.2
```

**Comment by satterly** [comment]
The issue seems to be with psycopg2 version 2.8 onwards. I noticed this during testing, which is why I locked the python package version to 2.7.7 but then neglected to insure that the same packages tested against were actually used when building the docker image. 🤦‍♂️

**Comment by satterly** [comment]
Example server log with errors ...
```
db_1   | 2019-04-09 22:16:07.464 UTC [1599] FATAL:  sorry, too many clients already
web_1  | 2019-04-09 22:16:07,466 DEBG 'uwsgi' stdout output:
web_1  | FATAL:  sorry, too many clients already
web_1  |
web_1  | Retry attempt 4/5 (wait=16s)...
web_1  |
web_1  | 2019-04-09 22:16:08,745 DEBG 'nginx' stdout output:
web_1  | 2019/04/09 22:16:08 [info] 14#14: *415 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 172.18.0.1, server: , request: "POST /api/alert HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "localhost:8082"
web_1  | ip=\- [\09/Apr/2019:22:16:08 +0000] "\POST /api/alert HTTP/1.1" \499 \0 "\-" "\python-requests/2.19.1"
web_1  |
web_1  | 2019-04-09 22:16:09,757 DEBG 'uwsgi' stdout output:
web_1  | FATAL:  sorry, too many clients already
web_1  |
web_1  | 2019-04-09 22:16:09,757 DEBG 'uwsgi' stdout output:
web_1  |
web_1  |
web_1  | 2019-04-09 22:16:09,758 DEBG 'uwsgi' stdout output:
web_1  | Retry attempt 3/5 (wait=8s)...
web_1  |
db_1   | 2019-04-09 22:16:09.756 UTC [1600] FATAL:  sorry, too many clients already
web_1  | 2019-04-09 22:16:12,319 DEBG 'uwsgi' stdout output:
web_1  | FATAL:  sorry, too many clients already
web_1  |
web_1  | Retry attempt 4/5 (wait=16s)...
web_1  |
db_1   | 2019-04-09 22:16:12.316 UTC [1601] FATAL:  sorry, too many clients already
db_1   | 2019-04-09 22:16:12.705 UTC [1602] FATAL:  sorry, too many clients already
web_1  | 2019-04-09 22:16:12,708 DEBG 'uwsgi' stdout output:
web_1  | FATAL:  sorry, too many clients already
web_1  |
web_1  | Retry attempt 4/5 (wait=16s)...
web_1  |
db_1   | 2019-04-09 22:16:17.764 UTC [1603] FATAL:  sorry, too many clients already
web_1  | 2019-04-09 22:16:17,768 DEBG 'uwsgi' stdout output:
web_1  | FATAL:  sorry, too many clients already
web_1  |
web_1  | Retry attempt 4/5 (wait=16s)...
web_1  |
```

**Comment by satterly** [comment]
The root cause of the issue is definitely psycopg2 2.8+. This package is now locked to version 2.7.7 in the `requirements.txt` for both this repo and the docker repo.

**Comment by satterly** [comment]
A new docker image for version 6.8.4 is now available. Let me know if there are any problems.

**Comment by graysonhead** [comment]
I've been running 6.4.8 for about 4 hours with no issues now, seems to have fixed my issue.
