### ISSUE TITLE
Add attributes of an origin alert to a correlated alert

### ISSUE THREAD

**Issue by vykulakov** [alerta/alerta#939]
**Is your feature request related to a problem? Please describe.**

I'm trying to modify the standard alerta-prometheus plugin to remove a silence period in AlertManager when Alerta receives a corresponding normal (or cleared) alert. Now it is not possible because the normal alert in the `status_change` handler (https://github.com/alerta/alerta-contrib/blob/master/plugins/prometheus/alerta_prometheus.py#L37) does not contain attributes from an original alert. The attributes are added to this alert right after `status_change_hook` is completed (https://github.com/alerta/alerta/blob/master/alerta/models/alert.py#L350).

**Describe the solution you'd like**
Is it possible to execute the status changed hook after getting the correlated alert with filled attributes from DB?

**Describe alternatives you've considered**
(don't know)

**Additional context**

slava @vykulakov Apr 15 11:29
@satterly I've tried to describe my problem here: alerta/python-alerta-client#182
The problem is that a corresponding normal or cleared alert which closes an original alert does not contain attributes from the original alert.
So I cannot get silenceId in the status_change handler.

slava @vykulakov Apr 15 11:38
There is the code:
        if new_status != status:
            status_change_hook.send(self, status=new_status, text=self.text)
            self.update_time = now

        self.status = new_status
        return Alert.from_db(db.correlate_alert(self, history))
If I understood correctly, the last line loads the original and updated alert from DB with attributes and it will be great if we invoke status_change_hook.send() after this line with the loaded and updated alert.

slava @vykulakov Apr 15 12:04
Hm... But in this case, we won't store silenceId to attributes without additional updating.

slava @vykulakov Apr 15 12:17
Oh, I see. I can use the post_receive handler to remove the silence period on receiving the normal alert... But it is not so convenient. And anyway, I must invoke additional updating to remove silenceId from attributes in DB.

Nick Satterly @satterly Apr 15 13:53
I don't understand why you are updating silences on closed. Surely that is managed by Alertmanager before it is received by Alerta. If anything the problem exists in reverse. Where Alertmanager fails to update subscribers when a silenced alert clears.
alerta/alerta#278
But.you know about this already so I'm confused

slava @vykulakov Apr 15 14:00
Yes, I understand why you are confused now. I must give you some details again. I have two AlertManager instances now. One to send notification via email and slack and one to send alerts to Alerta. So with this configuration Alerta can silence alerts and nobody will receive them but Alerta will continue receiving alerts from the second instance.

slava @vykulakov Apr 15 14:09
This configuration solves the problem, described in alerta/alerta#278. It is not so beautiful but it works and I have actual data in Alerta without any timeouts, housekeeping and so on.
But the problem described above should be actual not only for Prometheus and AlertManager because handlers don't have all the information about alerts. It is quite general.

**Comment by satterly** [comment]
Can you take a look at this fix #940 and let me know if this is what you want? Thanks.

**Comment by vykulakov** [comment]
Thank you for your fix. I've made a review and left a couple of comments.
