### ISSUE TITLE
NotNullViolation error on login after upgrading

### ISSUE THREAD

**Issue by vykulakov** [alerta/alerta#942]
After upgrading alerta webui and server to the last versions I always get the error `null value in column "email" violates not-null constraint` right after login through GitLab.

**Environment**
- OS: Debian
- API version: 7.0.1
- Deployment: self-hosted
- WSGI environment: gunicorn

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitLab

- web UI version: 7.0.1
- CLI version: 6.8.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the login page
2. Click on `Login` to log in with GitLab
3. See the alert popup with a long error

**Expected behavior**
Success login

**Additional context**
Alerta server logs:
```
apr 17 09:45:14 example.com gunicorn[19834]: ERROR:flask.app:null value in column "email" violates not-null constraint
apr 17 09:45:14 example.com gunicorn[19834]: DETAIL:  Failing row contains (87, Vyacheslav Kulakov, null, , active, {user}, {}, 2019-04-17 09:45:14.3, null, , 2019-04-17 09:45:14.3, f, null, vkulakov).
apr 17 09:45:14 example.com gunicorn[19834]: Traceback (most recent call last):
apr 17 09:45:14 example.com gunicorn[19834]:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
apr 17 09:45:14 example.com gunicorn[19834]:     rv = self.dispatch_request()
apr 17 09:45:14 example.com gunicorn[19834]:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
apr 17 09:45:14 example.com gunicorn[19834]:     return self.view_functions[rule.endpoint](**req.view_args)
apr 17 09:45:14 example.com gunicorn[19834]:   File "/usr/local/lib/python3.5/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
apr 17 09:45:14 example.com gunicorn[19834]:     resp = make_response(f(*args, **kwargs))
apr 17 09:45:14 example.com gunicorn[19834]:   File "/usr/local/lib/python3.5/dist-packages/alerta/auth/oidc.py", line 115, in openid
apr 17 09:45:14 example.com gunicorn[19834]:     user.create()
apr 17 09:45:14 example.com gunicorn[19834]:   File "/usr/local/lib/python3.5/dist-packages/alerta/models/user.py", line 137, in create
apr 17 09:45:14 example.com gunicorn[19834]:     return User.from_db(db.create_user(self))
apr 17 09:45:14 example.com gunicorn[19834]:   File "/usr/local/lib/python3.5/dist-packages/alerta/database/backends/postgres/base.py", line 880, in create_user
apr 17 09:45:14 example.com gunicorn[19834]:     return self._insert(insert, vars(user))
apr 17 09:45:14 example.com gunicorn[19834]:   File "/usr/local/lib/python3.5/dist-packages/alerta/database/backends/postgres/base.py", line 1263, in _insert
apr 17 09:45:14 example.com gunicorn[19834]:     cursor.execute(query, vars)
apr 17 09:45:14 example.com gunicorn[19834]:   File "/usr/local/lib/python3.5/dist-packages/psycopg2/extras.py", line 319, in execute
apr 17 09:45:14 example.com gunicorn[19834]:     return super(NamedTupleCursor, self).execute(query, vars)
apr 17 09:45:14 example.com gunicorn[19834]: psycopg2.errors.NotNullViolation: null value in column "email" violates not-null constraint
apr 17 09:45:14 example.com gunicorn[19834]: DETAIL:  Failing row contains (87, Vyacheslav Kulakov, null, , active, {user}, {}, 2019-04-17 09:45:14.3, null, , 2019-04-17 09:45:14.3, f, null, vkulakov).
```

**Comment by satterly** [comment]
I assume you don't have an email address associated with your GitLab account. Not even the "no reply" one gitlab creates for you.

**Comment by vykulakov** [comment]
My GitLab account has the email address.

**Comment by satterly** [comment]
Do you have `profile`, `email` and `openid` scopes enabled for the auth provider application?

<img width="554" alt="Screenshot 2019-04-17 at 12 05 37" src="https://user-images.githubusercontent.com/615057/56279845-3008e500-6109-11e9-90c9-b84967535a6f.png">

**Comment by vykulakov** [comment]
I've added `email` and `profile` scopes but I still get the error.

**Comment by vykulakov** [comment]
Maybe I should recreate my user in Alerta or fill an email manually?

**Comment by satterly** [comment]
It should fix the email problem if you log out and log back in ...
https://github.com/alerta/alerta/blob/293e2b3baa27195bef2f331b8ac62b1f92a8c8fe/alerta/auth/oidc.py#L112-L117

Can you check to see what you get back from gitlab in the id_token?

**Comment by vykulakov** [comment]
How can I do it?

**Comment by vykulakov** [comment]
After restarting I see another problem:
```
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
```

**Comment by satterly** [comment]
So now it looks like you are getting an email back from gitlab but that there is already a user with that email that exists in the user table. Is that possible?

**Comment by vykulakov** [comment]
Hm... Looks like there is a mistake in my configuration. I should check something.

**Comment by vykulakov** [comment]
Yes, there was a mistake. Now it works fine. Sorry.
