### ISSUE TITLE
Why is it that when I set shelved, the alarm doesn't timeout

### ISSUE THREAD

**Issue by net592** [alerta/alerta#957]
**Issue Summary**
When I set shelved, I notice that when I get to shelved timout, the alarm is still in shelved state.
I understand that shelve is sort of like a suppressed 1 hour alarm,
When shelved 1 hour is set, the alarm status should become open or timeout clearr if it exceeds 1 hour.
But no matter how long the alarm goes, it's still in shelved,   
alerta housekeeping  #502 #504
,
![image](https://user-images.githubusercontent.com/11604938/56786277-0c414f80-682b-11e9-946c-fecc2bf2db3a.png)

**Environment**
- Alerta  alerta 7.1.0
- Database: [MongoDB]

So here I'm setting set shelve timou 1s
One second later, I understand the alarm state should be open,
May I ask if my understanding is wrong
![image](https://user-images.githubusercontent.com/11604938/56786133-6e4d8500-682a-11e9-9006-405fee3339fc.png)

Now there are a lot of alarms set to shelve,
But the timeout alarm state cannot be automatically opened
![image](https://user-images.githubusercontent.com/11604938/56786191-a8b72200-682a-11e9-84ee-75f20022379e.png)

**Comment by satterly** [comment]
Did you see the docs explaining [housekeeping](https://docs.alerta.io/en/latest/deployment.html?highlight=housekeeping#house-keeping)? Or work through the timeout, heartbeats and housekeeping [tutorial](https://docs.alerta.io/en/latest/gettingstarted/tutorial-2-housekeeping.html#tutorial-2)?

Housekeeping is setup automatically if you use the Docker container. But you didn't fill in the issue template fully so I don't know whether you are using the "official" docker container or not, and whether or not there is an issue with the docker container.

```
**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: [eg. 6.8.1]
- Deployment: [eg. Docker, Heroku, AWS, GCloud, self-hosted]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]
```

**Comment by net592** [comment]
Environment
- API version:  alerta 7.1.0
- Database: [MongoDB]
- Deployment:[self-hosted]
- For self-hosted, WSGI environment: uwsgi

I also encountered this problem while testing shelved at the site
set shelve 1 hour
https://try.alerta.io/#/alerts?status=shelved
https://try.alerta.io/#/alert/25744e52-7838-4423-9e37-b96f4cd5d075
![image](https://user-images.githubusercontent.com/11604938/56787661-d2267c80-682f-11e9-994c-4eab1d16b69b.png)

**Comment by satterly** [comment]
You didn't reply when I asked you if you had read this documentation...

>Did you see the docs explaining [housekeeping](https://docs.alerta.io/en/latest/deployment.html?highlight=housekeeping#house-keeping)? Or work through the timeout, heartbeats and housekeeping [tutorial](https://docs.alerta.io/en/latest/gettingstarted/tutorial-2-housekeeping.html#tutorial-2)?

It is explained there in step-by-step detail that you need to setup a schedule to run the housekeeping command at regular intervals.
