### ISSUE TITLE
Error: update only works with $ operators

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#959]
**Issue Summary**

When trying to close an alert, either through the UI or with the alerta cli, I'm getting the error message `Error: update only works with $ operators`.

```
{"code":500,"errors":null,"message":"update only works with $ operators","status":"error"}
```

That started a couple of days ago and wasn't the case before I went to 7.0 - any idea what could be causing this?

**Environment**
- OS: Linux
- API version: 7.1.0 for the server and 6.8.1 for the CLI
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: MongoDB v4.0.9

- Server config:
  Auth enabled? Yes/No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**

Tried 3 different ways:

1. in the UI opening an alert and then clicking the x-symbol to close that alert. Shows the error message as a red fly-in at the bottom of the page for a second
2. in the UI in the alert list selecting multiple alerts and clicking the x-symbol as well, gettting the same error message for a little while at the bottom of the page
3. in the console using `alerta close --all` responds with the error message from the subject line just once and stoping the alerta client.

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Web console errors**

```
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:14
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:27
    p https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:37
chunk-vendors.6ebc8b01.js:27:72900
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:14
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:27
    p https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:37
chunk-vendors.6ebc8b01.js:27:72900
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:14
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:27
    p https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:37
chunk-vendors.6ebc8b01.js:27:72900
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:14
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:27
    p https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:37
chunk-vendors.6ebc8b01.js:27:72900
```

**Additional context**

I currently have 10 open alerts and none of them can be closed (or used any other action). But I also just had one which I was able to close. It happens with close, ack and shelve, but the watch action does work.

**Comment by satterly** [comment]
You don't say whether the attempt to close succeeds or not. 

And can you describe exactly what commands you ran...
```
To Reproduce Steps to reproduce the behavior:

Go to '...'
Click on '....' or Run '...'
Scroll down to '....'
See error (include command output)
```

**Comment by jurgenhaas** [comment]
Tried 3 different ways:

1. in the UI opening an alert and then clicking the x-symbol to close that alert. Shows the error message as a red fly-in at the bottom of the page for a second
2. in the UI in the alert list selecting multiple alerts and clicking the x-symbol as well, gettting the same error message for a little while at the bottom of the page
3. in the console using `alerta close --all` responds with the error message from the subject line just once and stoping the alerta client.

**Comment by satterly** [comment]
Can you get the full error from the network tab of the web browser JavaScript console?

**Comment by jurgenhaas** [comment]
The PUT request there gets this response:

```
{"code":500,"errors":null,"message":"update only works with $ operators","status":"error"}
```

Any thing else from the console?

**Comment by jurgenhaas** [comment]
Ah wait, here is more in the console tab:

```
Request to access cookie or storage on “https://www.googletagmanager.com/gtag/js?id=null” was blocked because it came from a tracker and content blocking is enabled. alerts
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:14
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:27
    p https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:37
chunk-vendors.6ebc8b01.js:27:72900
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:14
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:27
    p https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:37
chunk-vendors.6ebc8b01.js:27:72900
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:14
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:27
    p https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:37
chunk-vendors.6ebc8b01.js:27:72900
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:14
    exports https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:27
    p https://alerta.lakedrops.com/js/chunk-vendors.6ebc8b01.js:37
chunk-vendors.6ebc8b01.js:27:72900
```

**Comment by satterly** [comment]
Is it failing for all alerts or just some?

**Comment by jurgenhaas** [comment]
It's some. I currently have 10 open alerts and none of them can be closed (or used any other action). But I also just had one which I was able to close.

**Comment by jurgenhaas** [comment]
Sounds like similar error messages are known in the mongodb world. I'm using Mongo 3.4.20 if that matters

**Comment by satterly** [comment]
So are you saying it isn't just close but all actions? That is an important difference.

**Comment by satterly** [comment]
FYI, I develop against MongoDB 4.0.2 and the CI tests run against 4.0.7.

**Comment by jurgenhaas** [comment]
> So are you saying it isn't just close but all actions? That is an important difference.

It happens with close, ack and shelve, but the watch action does work.

**Comment by jurgenhaas** [comment]
I have also updated mongodb to 4.0.9, the error remains the same.

**Comment by satterly** [comment]
I've filled in the issue template as best I could from all the information above and realised that I still don't know whether you are using Customer Views, and what auth provider you are using, if any.

It would have been better if you had supplied all the information in the template right from the start, to be honest, as it makes it sooo much harder to reproduce a problem like this when I don't have all the information. It has been 2 days and a dozen comments back and forth and a lot of time wasted on both sides. In future, if you could fill in the issue template with as much detail as possible when you log an issue that would be greatly appreciated.

Please let me know the auth provider and whether customer views is enabled. Thanks.

**Comment by satterly** [comment]
Also, I might have missed it but did you say what web UI you were using? Or are you using both v6 and v7 at the moment? If so, do they both show the same error?

**Comment by jurgenhaas** [comment]
Sorry for causing this trouble. I thought the UI details shouldn't be essential because the same problem occurs when using the API directly, u.e. with the alerta cli client.

Nevertheless, I'm using the v7 ui only and GitLab as the auth provider.

**Comment by satterly** [comment]
Customer views?

**Comment by jurgenhaas** [comment]
Sorry, yes I use customer views too.

**Comment by satterly** [comment]
Ok. Thanks. I've finally managed to reproduce the error...

```
2019-04-28 17:42:53,875 - flask.app[36226]: ERROR - update only works with $ operators [in /Users/nsatterl/Projects/alerta/alerta/exceptions.py:89]
Traceback (most recent call last):
  File "/Users/nsatterl/Projects/alerta/alerta/views/alerts.py", line 153, in action_alert
    alert = alert.from_action(action, text, timeout)
  File "/Users/nsatterl/Projects/alerta/alerta/models/alert.py", line 617, in from_action
    r = status_change_hook.send(self, status=new_status, text=text)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/Users/nsatterl/Projects/alerta/alerta/utils/hooks.py", line 45, in process_status_change
    alert.update_attributes(alert.attributes)
  File "/Users/nsatterl/Projects/alerta/alerta/models/alert.py", line 441, in update_attributes
    return db.update_attributes(self.id, self.attributes, attributes)
  File "/Users/nsatterl/Projects/alerta/alerta/database/backends/mongodb/base.py", line 402, in update_attributes
    response = self.get_db().alerts.update_one({'_id': {'$regex': '^' + id}}, update=update)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/pymongo/collection.py", line 985, in update_one
    common.validate_ok_for_update(update)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/pymongo/common.py", line 491, in validate_ok_for_update
    raise ValueError('update only works with $ operators')
ValueError: update only works with $ operators

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/nsatterl/Projects/alerta/alerta/auth/decorators.py", line 74, in wrapped
    return f(*args, **kwargs)
  File "/Users/nsatterl/Projects/alerta/alerta/models/metrics.py", line 259, in wrapped
    response = f(*args, **kwargs)
  File "/Users/nsatterl/Projects/alerta/alerta/utils/response.py", line 19, in decorated
    return func(*args, **kwargs)
  File "/Users/nsatterl/Projects/alerta/alerta/views/alerts.py", line 162, in action_alert
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: update only works with $ operators
2019-04-28 17:42:53,880 - werkzeug[36226]: INFO - 127.0.0.1 - - [28/Apr/2019 17:42:53] "PUT /alert/a75b33aa-f9b2-4cdf-8c45-905068b3b923/action HTTP/1.1" 500 - [in /Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/werkzeug/_internal.py:88]
```

**Comment by jurgenhaas** [comment]
Thank you so much for your patience and support.
