### ISSUE TITLE
blackouts period each days in a rule

### ISSUE THREAD

**Issue by w-HA** [alerta/alerta#960]
Dears,

is it possible to create a blackout rule for a time period each day

For example all days between 02:00am and 08:00am in one rule

presently , it seems i need to create one rule per day 

Thanks a lot

**Comment by satterly** [comment]
It's possible but it's not "built in" to Alerta. Job scheduling is actually incredibly complex and not the core focus of this project. You can achieve what you what by using pretty much any job scheduler whether self-hosted (eg. cron or [quartz](http://www.quartz-scheduler.org/)) or in the cloud (eg. [Google Cloud Scheduler](https://cloud.google.com/scheduler/)). All they need to be able to do is hit an [HTTP endpoint with POST data](http://docs.alerta.io/en/latest/api/reference.html#create-a-blackout) and you can create/delete blackout periods at will.

**Comment by w-HA** [comment]
ok thanks for your answer . i think i'll use cron to do that

very good job
