### ISSUE TITLE
question： Set Shelve 1 hour, alarm does not automatically timeout open

### ISSUE THREAD

**Issue by net592** [alerta/alerta#961]
I'm testing at https://try.alerta.io/
Put some alarms on shelve
But the alarm is still not open after timeout is found
https://try.alerta.io/#/alert/1c178ccc-8343-40bb-a3ba-d997372fe183
![image](https://user-images.githubusercontent.com/11604938/56858345-01152d80-69ab-11e9-8d95-cd2ea8c7943a.png)

![image](https://user-images.githubusercontent.com/11604938/56858338-f490d500-69aa-11e9-9e57-eda8de27454f.png)
I understand from the documentation that Shelve is suspended and suppressed for a period of time without warning
Thank you for

**Comment by net592** [comment]
https://beta.alerta.io  web-ui 7.0
![image](https://user-images.githubusercontent.com/11604938/56859699-39276b00-69c1-11e9-9863-7c2df8d63c97.png)

**Comment by satterly** [comment]
Housekeeping schedules aren't configured on these test / demo sites.

**Comment by satterly** [comment]
See #985
