### ISSUE TITLE
Add your company logo to https://alerta.io website

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#965]
In an effort to raise the profile of Alerta so that we all benefit from more users/reviewers/testers/contributors I would like to list company logos of those using Alerta on the “landing page” (https://alerta.io).

If your company uses Alerta, and you are happy for your logo to appear on this page in a list of “who’s using Alerta” or even better, a “case study” (similar to https://kubernetes.io/case-studies/) then either send me an email at nfsatterly@gmail.com or add a comment below.

Thanks for your support.

**Comment by satterly** [comment]
Kjetil @kjetilmjos May 27 20:29
Hi @satterly you asked earlier for some use cases of alerta to put on alerta.io. We made a video to show how we use alerta at my company: Incredibly proud of what the team at Gapit have a achieved. Combining 3D scanning with the latest open source technology. https://www.youtube.com/watch?v=tbWn41yRK8A

**Comment by judexzhu** [comment]
Alerta is a really great product. We really love it. 

![Newegg-Logo-1](https://user-images.githubusercontent.com/17834225/59475366-a746c500-8e7d-11e9-89f9-8451d278f8f1.png)
