### ISSUE TITLE
Logging in with Keycloak fails

### ISSUE THREAD

**Issue by Promzor** [alerta/alerta#966]
**Issue Summary**
After upgrade of alerta logging in with keycloak  fails. 

**Environment**
- OS: [eg. Linux]
- API version: [7.2] 
- Deployment: [self-hosted]
- For self-hosted, WSGI environment: [apache/mod_wsgi]

- Database: [eg. MongoDB]

- Server config:
  Auth enabled? Yes
  Auth provider? Keycloack
  Customer views? Yes/No

- web UI version: [7.2]
- CLI version: [eg. 6.8.1] => latest 

**To Reproduce**
1. Go to login
2. Login into Keycloack with credentials
3. get redirected and get error 404

For web app issues, include any web browser JavaScript console errors.

Tested webbrowser firefox / google chrome

**Expected behavior**
Logging in 

**Screenshots**
![image](https://user-images.githubusercontent.com/24809938/57066930-e1914400-6ccd-11e9-868c-9fa5eff65291.png)

**Additional context**
Was working with previous version 

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
Can you share you `/config` output?

**Comment by Promzor** [comment]
alertad.conf ? that one ?

**Comment by Promzor** [comment]
`AUTH_REQUIRED = True
SECRET_KEY='my_secret_key'

SEVERITY_MAP = {
    'fatal': 0,
    'critical': 1,
    'warning': 4,
    'indeterminate': 5,
    'ok': 5,
    'page':5,
    'normal':5,
    'unknown': 9,
    'up': 5,
    'down': 0
}

COLOR_MAP = {
    'severity': {
        'fatal': 'orange',
        'critical': 'red',
        'warning': '#1E90FF',
        'indeterminate': 'lightblue',
        'ok': '#00CC00',
        'ok': '#00CC00',
        'unknown': 'silver',
        'page': ' #f8e900',
        'up' : '#00CC00',
        'down' : 'red'
    }
}

COLUMNS = ['severity', 'status', 'lastReceiveTime', 'duplicateCount',
        'customer', 'environment', 'service', 'resource', 'event', 'value', 'text']

PLUGINS=['Prometheus']
ALLOWED_ENVIRONMENTS=['Production', 'Development', 'Code']






AUTH_PROVIDER = 'keycloak'
KEYCLOAK_URL = 'https://keycloakhere.com'
KEYCLOAK_REALM = 'myrealm'
OAUTH2_CLIENT_ID = 'alerta-ui'
OAUTH2_CLIENT_SECRET = 'my-secret'

ALLOWED_KEYCLOAK_ROLES = ['my roles']`

**Comment by satterly** [comment]
What is your keycloak config look like?  What is your redirect URL? This is the one that 404'ing, right?

**Comment by Promzor** [comment]
It opens a keycloack page where I can login, after I login with my credentials that pop up closes and the 404 is on the alerta page. 



`actions             : 
alarm_model         : {'colors': {'severity': {'critical': 'red', 'down': 'red', 'fatal': 'orange', 'indeterminate': 'lightblue', 'ok': '#00CC00', 'page': ' #f8e900', 'unknown': 'silver', 'up': '#00CC00', 'warning': '#1E90FF'}}, 'name': 'Alerta 7.2.0', 'severity': {'critical': 1, 'down': 0, 'fatal': 0, 'indeterminate': 5, 'normal': 5, 'ok': 5, 'page': 5, 'unknown': 9, 'up': 5, 'warning': 4}, 'status': {'ack': 'C', 'assign': 'B', 'blackout': 'E', 'closed': 'F', 'expired': 'G', 'open': 'A', 'shelved': 'D', 'unknown': 'H'}}
audio               : {'new': None}
auth_required       : True
azure_tenant        : None
client_id           : alerta-ui
colors              : {'severity': {'critical': 'red', 'down': 'red', 'fatal': 'orange', 'indeterminate': 'lightblue', 'ok': '#00CC00', 'page': ' #f8e900', 'unknown': 'silver', 'up': '#00CC00', 'warning': '#1E90FF'}}
columns             : severity, status, lastReceiveTime, duplicateCount, customer, environment, service, resource, event, value, text
customer_views      : False
dates               : {'longDate': 'd/M/yyyy h:mm:ss.sss a', 'mediumDate': 'EEE d MMM HH:mm', 'shortTime': 'HH:mm'}
debug               : False
email_verification  : False
endpoint            : http://localhost:8080
github_url          : https://github.com
gitlab_url          : https://gitlab.com
keycloak_realm      : inuits
keycloak_url        : https://idp-dev.inuits.io
oidc_auth_url       : None
pingfederate_url    : None
provider            : keycloak
refresh_interval    : 5000
severity            : {'critical': 1, 'down': 0, 'fatal': 0, 'indeterminate': 5, 'normal': 5, 'ok': 5, 'page': 5, 'unknown': 9, 'up': 5, 'warning': 4}
signup_enabled      : False
site_logo_url       : 
sort_by             : lastReceiveTime
tracking_id         : None
config_file         : ~/.alerta.conf
profile             : None
key                 : 
username            : None
password            : None
timezone            : Europe/London
timeout             : 5.0
sslverify           : True
output              : simple
color               : True
client              : <alertaclient.api.Client object at 0x7fceeb581780>
`

**Comment by satterly** [comment]
Check your redirect URL is pointing to the right place ...

<img width="653" alt="Screenshot 2019-05-02 at 12 15 46" src="https://user-images.githubusercontent.com/615057/57069153-13a5a480-6cd4-11e9-9beb-0e6766af15a6.png">

**Comment by Promzor** [comment]
it is, however I redirect to port 80 this is where the webUI is served, 8080 is the API

**Comment by satterly** [comment]
Sure, that was just an example. I can't know how you have set up your self-hosted environment unless you tell me.

You say you get a 404 but you don't say what URL you actually get a 404 for. It will either be in the API server logs or the web UI javascript console, or both.

**Comment by Promzor** [comment]
Hmm, its fixed but honestly I don't know how or why ...

Bassicly I deleted and reinstalled alerta-server alerta again

Sorry for taking up your time

**Comment by satterly** [comment]
OK. Glad it's sorted. 👍
