### ISSUE TITLE
Request to include wheel in setup.py

### ISSUE THREAD

**Issue by jgoff** [alerta/alerta#969]
**Is your feature request related to a problem? Please describe.**
On the back of alerta#967, it's also found for a fresh python3.7 venv needs wheel to be installed due to bdist_wheel in Makefile

```
Building wheels for collected packages: alerta-server, blinker
  Running setup.py bdist_wheel for alerta-server ... error
  Complete output from command /home/nd/latest/p3env/test/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-c75egr1f/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ycntixt4 --python-tag cp37:
  fatal: not a git repository (or any of the parent directories): .git
  /home/nd/latest/p3env/test/lib/python3.7/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '7.2.1
  ' to '7.2.1'
    normalized_version,
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for alerta-server
  Running setup.py clean for alerta-server
```
this means one cannot simply `pip3 install <alerta-tarball>` without error

**Describe the solution you'd like**
Add wheel into `setup.py`

**Describe alternatives you've considered**
Ignore the error ?

**Additional context**
Found on kali (2019.2) on x86_64 with python 3.7.3rc1 venv

**Comment by satterly** [comment]
Sorry but I don't understand what you're trying to do. Please include the exact command you ran to generate the output above.

And why are you trying to do this? I'm not familiar with kali. Are you supposed to build everything from sources???

**Comment by jgoff** [comment]
Sorry for not supplying enough info; Kali is some sort of Debian distribution, the base python3.7 install on this system comes from the kali repository. I mention this only to frame where the python came from - wasn't built, rather installed with apt. 

Really not urgent (doesn't warrant a 7.2.2 for example), just for your consideration to add it to the setup requirements in the interest of an error free install experience without having to add dependencies manually.

steps to recreate
-----------------
1. create a venv
    _python3.7 -mvenv alerta-test_

2. activate it 
    _cd alerta-test; source bin/activate_

3. try to pip3 install alerta-7.2.1.tar.gz
    _pip3 install /tmp/somewhere/alerta-7.2.1.tar.gz_

4. errors seen relating to lack of "wheel"

Workaround
-------------
before running step 3 above, use _pip3 install wheel_

Attached example of the issue
-------------------------------
[alerta_wheel.txt](https://github.com/alerta/alerta/files/3151840/alerta_wheel.txt)

**Comment by satterly** [comment]
I'm not sure this is an Alerta install issue. What happens if you run `pip3 install --upgrade pip` before you run `pip3 install tarball`?

**Comment by jgoff** [comment]
gave it a go, it's the same problem - wheel is not present by default, but Alerta's setup.py requires it.

**Comment by satterly** [comment]
You need to install the `wheel` package yourself in your python environment before installing Alerta. It's not the distributed packages responsibility to include `wheel` as a dependency [[SO]](https://stackoverflow.com/a/42369296). You should ensure your python environment has correct versions of `setuptools`, `pip` or `wheel` installed.

> # Generating distribution archives
>The next step is to generate distribution packages for the package. These are archives that are uploaded to the Package Index and can be installed by pip.
Make sure you have the latest versions of setuptools and wheel installed:
`python3 -m pip install --user --upgrade setuptools wheel`
Tip IF you have trouble installing these, see the Installing Packages tutorial.

https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives
