### ISSUE TITLE
Alerta Docker with No IPv6

### ISSUE THREAD

**Issue by BenB196** [alerta/alerta#979]
**Issue Summary**
Trying to start the Alerta Docker container on a system which does not support IPv6, causes nginx to fail to start, thus making Alerta unusable.

**Environment**
- OS: Linux (Photon OS)
- API version: latest
- Deployment: Docker (Docker Compose)
- For self-hosted, WSGI environment: N/A

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No

- web UI version: latest
- CLI version: latest

**To Reproduce**
1. Run the Alerta docker container on a system which does not support IPv6
2. Look at container logs; Alerta will be in an infinite loop saying nginx failed to start
3. The Alerta container will stay active, so much check logs for the error.

**Expected behavior**
I would expect that the Alerta container should be able to work correctly whether IPv6 is supported or not.

**Additional context**
Removing the following line from nginx.conf fixes the issue, I don't know what the optimal way would be to go about solving it in a more permanent way.

`                listen [::]:8080 default_server;`

URL of line: https://github.com/alerta/docker-alerta/blob/470a447a3573f8b505d53a0109fec3cd8c2e4658/nginx.conf#L34

**Comment by satterly** [comment]
I can't get this to fail. How are you running docker-compose on a system which does not support IPv6? Please describe your environment in as much detail as possible. Thanks.

**Comment by BenB196** [comment]
Hi, docker/docker-compose does not require IPv6 to work.

A more detailed description of environment:

I am running VMwares Photon OS, I have explicitly disabled IPv6 on the host so that IPv6 cannot be used at all. The reason behind disabling IPv6 is that it can cause some weird issues when running on a strict IPv4 network. 

Docker-compose for Alerta

`
  alertadb01:
    image: postgres:latest
    container_name: alertadb01
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: alertaUser
      POSTGRES_PASSWORD: superStrongPassword
    volumes:
      - /alertadb/data:/var/lib/postgresql/data:rw
    networks:
      - alerta
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
  alerta01:
    depends_on:
      - alertadb01
    image: alerta/alerta-web:latest
    container_name: alerta01
    ports:
      - "8083:8080"
    volumes:
      - /alertadb/conf/nginx.conf:/app/nginx.conf:ro
      - /alertadb/conf/alertad.conf:/app/alertad.conf
      - /alertadb/conf/config.json:/web/config.json
    environment:
      - ADMIN_PASSWORD=changeme
      - BASE_URL=http://photon.domain.com:8083/api
      - DATABASE_URL=postgres://alertaUser:superStrongPassword@alertadb01:5432/monitoring
      - DATABASE_NAME=monitoring
    networks:
      - alerta
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
networks:
  alerta:
    driver: bridge #This is probably what causes it to break when IPv6 is disabled on the host OS
`

Here is alertad.conf

`DEBUG = True
SECRET = "^Bpa%i8_nCAc8fI4l9)nhn2EG2!@Gdwad"
AUTH_REQUIRED = True

SEVERITY_MAP = {
    'fatal': 0,
    'critical': 1,
    'major': 2,
    'minor': 3,
    'warning': 4,
    'indeterminate': 5,
    'cleared': 5,
    'normal': 5,
    'ok': 5,
    'informational': 6,
    'debug': 7,
    'trace': 8,
    'unknown': 9
}
DEFAULT_NORMAL_SEVERITY = 'normal', 'ok', 'cleared'
DEFAULT_PREVIOUS_SEVERITY = 'indeterminate'

PLUGINS = ['reject', 'blackout', 'prometheus', 'normalise']
`

Here is config.json

`{"endpoint": "https://localhost:8080"}`

Please let me know if any other information is needed.

**Comment by satterly** [comment]
I think the permanent fix here is for you to build your own custom Alerta image. This seems to me like a very specific problem that would unnecessarily complicate an already complex entry point script for very little benefit to the vast majority of users.
