### ISSUE TITLE
Error: duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by judexzhu** [alerta/alerta#981]
**Issue Summary**
After upgrading to 7.2.7 from 6.7.3 via docker on kubernetes.

```
Cannot log in with Keycloak anymore.
Error: duplicate key value violates unique constraint "users_login_key" DETAIL: Key (login)=(jude.x.zhu@newegg.com) already exists.
```

**Environment**
- OS: MAC
- API version: 7.2.7
- Deployment: Docker on Kubernetes
- For self-hosted, WSGI environment:nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Keycloak
  Customer views? Yes
  (or provide the `/config` endpoint output)

- Web UI version: 7.2.7
- CLI version: 7.2.7

**To Reproduce**
1. deploy alerta 6.7.3 and PostgreSQL with Keycloak auth
2. Change alerta image tag to 7.2.7
3. login in

![image](https://user-images.githubusercontent.com/17834225/58601006-7e3d0680-82b9-11e9-9df2-7590a1a18f21.png)

I'm using the email from LDAP attribute as the username 

Here is the user attributes mappers look like on Keycloak 

![image](https://user-images.githubusercontent.com/17834225/58601077-d116be00-82b9-11e9-927a-022971598591.png)

Both username and email mappers to the LDAP attribute "mail"

Here is what the client scope looks like.

![image](https://user-images.githubusercontent.com/17834225/58601117-0d4a1e80-82ba-11e9-9119-d0dfacff3683.png)

Client Mappers

![image](https://user-images.githubusercontent.com/17834225/58601176-45e9f800-82ba-11e9-8365-5a2f8c82a0e6.png)

If I remove the email from the client scope as below images shows 

![image](https://user-images.githubusercontent.com/17834225/58601218-76319680-82ba-11e9-811f-d798bca8af51.png)

the error message will change from 

![image](https://user-images.githubusercontent.com/17834225/58601237-8e091a80-82ba-11e9-9851-60177ef9e3e1.png)

to

![image](https://user-images.githubusercontent.com/17834225/58601397-2e5f3f00-82bb-11e9-9363-b76d49784205.png)

How can I troubleshoot and fix this issue?

Here is the logs from the alerta pod.

```
2019/05/30 02:32:48 [info] 41#41: *2408 client 127.0.0.1 closed keepalive connection

2019-05-30 02:32:48,147 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 139665528789112 for <Subprocess at 139665528749232 with name housekeeping in state RUNNING> (stdout)>
2019-05-30 02:32:48,147 INFO exited: housekeeping (exit status 1; not expected)
2019-05-30 02:32:48,148 DEBG received SIGCLD indicating a child quit
2019-05-30 02:32:48,172 DEBG 'nginx' stdout output:
ip=\- [\30/May/2019:02:32:48 +0000] "\GET / HTTP/1.1" \200 \879 "\-" "\kube-probe/1.11"
/web/ | /index.html | > GET / HTTP/1.1

2019-05-30 02:32:48,178 INFO spawned: 'housekeeping' with pid 857
2019-05-30 02:32:48,842 DEBG 'uwsgi' stdout output:
{"name": "flask.app", "levelno": 40, "levelname": "ERROR", "pathname": "/venv/lib/python3.6/site-packages/alerta/exceptions.py", "filename": "exceptions.py", "module": "exceptions", "lineno": 116, "funcName": "handle_exception", "created": 1559183568.8403566, "thread": 140401390969216, "threadName": "uWSGIWorker1Core0", "process": 49, "endpoint": "auth.openid", "method": "POST", "url": "https://e9k8s-alerta.newegg.org/api/auth/keycloak", "reqargs": {}, "data": "{\"code\":\"0fcc6974-78b2-4a84-a81e-30a8d71bb4cd.be928f5e-3155-4ae9-a17e-2218c528dc09.96f49409-ff9a-48cf-90c5-3f3e6feb1b42\",\"clientId\":\"e9k8s-alerta-ui\",\"redirectUri\":\"https://e9k8s-alerta.newegg.org\",\"state\":\"91c9i902i9a\"}", "remote_addr": "10.20.17.0", "user": null, "message": "duplicate key value violates unique constraint \"users_login_key\"\nDETAIL:  Key (login)=(jude.x.zhu@newegg.com) already exists.\n"}

2019-05-30 02:32:48,847 DEBG 'nginx' stdout output:
ip=\172.20.171.120 [\30/May/2019:02:32:48 +0000] "\POST /api/auth/keycloak HTTP/1.1" \500 \1515 "\https://e9k8s-alerta.newegg.org/login" "\Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
/web | /api/auth/keycloak | > POST /api/auth/keycloak HTTP/1.1

2019-05-30 02:32:48,848 DEBG 'uwsgi' stdout output:
[pid: 49|app: 0|req: 56/490] 10.20.17.0 () {64 vars in 1219 bytes} [Thu May 30 02:32:46 2019] POST /api/auth/keycloak => generated 1515 bytes in 1876 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)

2019-05-30 02:32:49,850 INFO success: housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-05-30 02:32:54,756 DEBG 'nginx' stdout output:
```

**Comment by satterly** [comment]
Check your database for duplicate entries in either the email or login columns? And what is the value for `subject` in the JWT token returned by keycloak after succesful authentication?

**Comment by judexzhu** [comment]
@satterly 
Thank you for your reply.

Here is the JWT token payload 

```json
{
  "jti": "a2e598a7-3541-4b70-8897-de151e8e468f",
  "exp": 1559265346,
  "nbf": 0,
  "iat": 1559265046,
  "iss": "https://keycloak.newegg.org/auth/realms/Newegg",
  "sub": "53c7e798-5256-410a-a843-369df151f38e",
  "typ": "Bearer",
  "azp": "e9k8s-alerta-ui",
  "auth_time": 0,
  "session_state": "660853a2-29a6-476c-8f59-48129cf67a56",
  "acr": "1",
  "allowed-origins": [
    "https://e9k8s-alerta.newegg.org"
  ],
  "scope": "openid profile",
  "name": "Jude Zhu",
  "preferred_username": "jude.x.zhu@newegg.com",
  "given_name": "Jude",
  "family_name": "Zhu"
}
```

Here is the database user table looks like 

![image](https://user-images.githubusercontent.com/17834225/58680312-e19e6580-8399-11e9-9222-673425260caa.png)

![image](https://user-images.githubusercontent.com/17834225/58680332-f4189f00-8399-11e9-80f7-4fe9f80c0761.png)


Did you mean the username value cannot be the same with email and login?

but this works in 6.7.3

**Comment by satterly** [comment]
email and login must be unique.

Version 7 requires users to be created so user preferences can be saved.

**Comment by judexzhu** [comment]
@satterly 

Thank you, this was resolved by clearing the user table.

I'm going to close this case
