### ISSUE TITLE
ALERT_TIMEOUT not working

### ISSUE THREAD

**Issue by martinboller** [alerta/alerta#984]
**Issue Summary**
Changing ALERT_TIMEOUT doesn't work, whereas HEARTBEAT_TIMEOUT does.

**Environment**
- OS: Debian 9
Versions: 
    alerta 7.2.7
    alerta client 7.2.1
    requests 2.9.1
    click 7.0
- Deployment: self-hosted
- WSGI environment: nginx/uwsgi

- Database: MongoDB
- Server config:
  Auth enabled: Yes
  Auth provider: Basic
  Customer views: No
  
- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
change ALERT_TIMEOUT to any issue, however timeout doesn't change from default 24 hours. 

**Expected behavior**
Timeout change to 12 hours.
Heartbeat did change to 2 hours (see below) 
Tried other values for both, but same behaviour.

**Additional context**
alertad.conf:
```
DEBUG=False
TESTING=False
SECRET_KEY='this field intentionally changed'
PLUGINS=['reject', 'blackout', 'slack']
DATABASE_URL='mongodb://localhost:27017/monitoring'
JSON_AS_ASCII=False
JSON_SORT_KEYS=True
JSONIFY_PRETTYPRINT_REGULAR=True
AUTH_REQUIRED = True
AUTH_PROVIDER = 'basic'
ADMIN_USERS = ['admin', 'John]
USER_DEFAULT_SCOPES = ['read', 'write:alerts']
ALLOWED_ENVIRONMENTS=['Production', 'Development', 'Testing']
LOG_HANDLERS = ['file']
LOG_FILE = '/var/log/alertad.log'
LOG_MAX_BYTES = 5*1024*1024 
LOG_BACKUP_COUNT = 2
LOG_FORMAT = 'json'
SITE_LOGO_URL = 'changed URL'
ALERTA_TIMEOUT = 43200  # 12 hours
HEARTBEAT_TIMEOUT = 7200  # 2 hours
```
________________________________________________________

A search of all issues didn't get me anything, so sincerely hope this is not a duplicate.
Thanks

**Comment by satterly** [comment]
It's not `ALERTA_TIMEOUT` it's `ALERT_TIMEOUT`.

**Comment by martinboller** [comment]
> It's not `ALERTA_TIMEOUT` it's `ALERT_TIMEOUT`.
That's also what i use in the alertad.conf - I tested with ALERTA_TIMEOUT just to verify and, by mistake, copied that example here. So not working for me :(

**Comment by satterly** [comment]
Ok well I can only go on what you supply in the issue description.

Can you document the exact steps you took so I can reproduce the problem? Include the `alerta` commands you ran if that's what you used.

**Comment by martinboller** [comment]
Apologies, the issue is with elastalert:

Using elastalert, and wanted the default timeout to be several days (not 24x7, long weekends etc).
All alerts triggered use the default instead of ALERT_TIMEOUT.

Using Alerta, e.g. alerta send -r test_time -e timeout_1 -E Production -s critical -S alerta -t "This is a test" works correctly, so just realized that I'm a massive fool and the issue is with elastalert. (always specified --timeout when using alerta.

Thanks for replying & a super awesome project.

**Comment by martinboller** [comment]
For anyone else making the same mistake, the setting in Elastalerts config.yaml is alerta_timeout: example: alerta_timeout: 432000 #5 days
