### ISSUE TITLE
housekeeping will always timeout when the alerts volume goes high

### ISSUE THREAD

**Issue by Ehekatl** [alerta/alerta#993]
**Issue Summary**
the default http timeout (20s) is too low for housekeeping, in our environment, sometimes we have 10k alerts within oneday, and the housekeeping will never able to finish within 20s

**To Reproduce**
- inject large mount of alerts, and try housekeeping, it will timeout
- adjust timeout value and retry, problem fixed

**Expected behavior**

longer timeout value for housekeeping

**Comment by satterly** [comment]
Set your own value for timeout. See http://docs.alerta.io/en/latest/cli.html#configuration

**Comment by Ehekatl** [comment]
@satterly surely I can, but that's a global timeout. I think housekeeping should have a longer timeout value by default, separate from the global one

**Comment by satterly** [comment]
Then create a profile just for housekeeping.

**Comment by Ehekatl** [comment]
alright
