### ISSUE TITLE
Unable to support multi tenancy with single API key

### ISSUE THREAD

**Issue by Edke** [alerta/alerta#996]
As I'm not sure if this is a bug of feature, opening custom issue. 

Looks like currently key needs to be defined as without customer or for single customer. This breaks for me integration i.e. with InfluxDB's Kapacitor, where alerts created can be fine tuned to land for certain customer. But when key is without customer, it can't create alerts with customer specified.

Is this behavior by some reason ? I think it would be good to have opportunity to create key which can create alerts to any existing customers.

**Comment by Edke** [comment]
Addional note .. when having multiple heatbeats for multiple customers, looks like this breaks also to have single job to create alerts from all stalled heatbeads nevertheless which customer they are belong to. As there can't be single key that can create alerts from heatbeat either with or without customer defined.

**Comment by satterly** [comment]
Create an API key with "admin:heartbeat" and/or "admin:alerts" scopes. See https://docs.alerta.io/en/latest/authorization.html#scopes-and-permissions

In future, if you could fill out the template with as much information as possible, that helps a lot in understanding your environment and requirements -- whether it is a bug or an enhancement. Thanks.

**Comment by Edke** [comment]
We evaluate and integrate Alerta in our monitoring stream for three weeks, Docs study constantly .. and I missed this page which I was going though like 4 times :( 

Really sorry for such a bad intro issue :) Will try to behave from now on, just as mentioned earlier, was not sure if this is a bug or feature, there is a reason why no proper template was used. 

Is there another channel like Slack for these kinds of questions to be asked and not spam with issues ?

**Comment by satterly** [comment]
You can use Gitter https://gitter.im/alerta/chat
